Move pleroma frontend to backend directory

diff --git a/src/freedombone-app-pleroma b/src/freedombone-app-pleroma
--- a/src/freedombone-app-pleroma
+++ b/src/freedombone-app-pleroma
@@ -238,7 +238,7 @@ function pleroma_set_background_image {
             if [ ${#temp_background} -gt 0 ]; then
                 PLEROMA_BACKGROUND_IMAGE_URL="$temp_background"
                 write_config_param "PLEROMA_BACKGROUND_IMAGE_URL" "$PLEROMA_BACKGROUND_IMAGE_URL"
-                if [[ $(pleroma_set_background_image_from_url "$PLEROMA_DOMAIN_NAME" "$PLEROMA_BACKGROUND_IMAGE_URL" "$PLEROMA_TITLE" | tail -n 1) == "0" ]]; then
+                if [[ $(pleroma_set_background_image_from_url $PLEROMA_DIR "$PLEROMA_DOMAIN_NAME" "$PLEROMA_BACKGROUND_IMAGE_URL" "$PLEROMA_TITLE" | tail -n 1) == "0" ]]; then
                     dialog --title $"Set Pleroma login background" \
                            --msgbox $"The background image has been set" 6 60
                 fi
@@ -262,8 +262,7 @@ function pleroma_set_title {
                 PLEROMA_TITLE="$new_title"
                 PLEROMA_DOMAIN_NAME=$(get_completion_param "pleroma domain")
                 write_config_param "PLEROMA_TITLE" "$PLEROMA_TITLE"
-                cd /var/www/$PLEROMA_DOMAIN_NAME/htdocs/static
-                sed -i "s|\"name\":.*|\"name\": \"${PLEROMA_TITLE}\",|g" config.json
+                sed -i "s|\"name\":.*|\"name\": \"${PLEROMA_TITLE}\",|g" $PLEROMA_DIR/static/config.json
                 sed -i "s|name: .*|name: \"${PLEROMA_TITLE}\",|g" $PLEROMA_DIR/config/config.exs
                 systemctl restart pleroma
                 dialog --title $"Set Pleroma title" \
@@ -527,8 +526,8 @@ function install_pleroma {
     install_nodejs pleroma-backend
     install_postgresql
 
-    if [ ! -d /var/www/$PLEROMA_DOMAIN_NAME ]; then
-        mkdir /var/www/$PLEROMA_DOMAIN_NAME
+    if [ ! -d /var/www/${PLEROMA_DOMAIN_NAME}/htdocs ]; then
+        mkdir -p /var/www/${PLEROMA_DOMAIN_NAME}/htdocs
     fi
     if [ -d $PLEROMA_DIR ]; then
         rm -rf $PLEROMA_DIR
@@ -635,17 +634,6 @@ function install_pleroma {
     echo '  # include snippets/well-known.conf;' >> $pleroma_nginx_site
     echo '}' >> $pleroma_nginx_site
 
-    function_check create_site_certificate
-    create_site_certificate $PLEROMA_DOMAIN_NAME 'yes'
-
-    function_check nginx_ensite
-    nginx_ensite $PLEROMA_DOMAIN_NAME
-
-    systemctl restart postgresql
-    systemctl restart nginx
-
-    set_completion_param "pleroma domain" "$PLEROMA_DOMAIN_NAME"
-
 
     # back end
     cd $PLEROMA_DIR
@@ -668,11 +656,33 @@ function install_pleroma {
     # front end
     install_pleroma_front_end "pleroma" "$PLEROMA_DOMAIN_NAME" "$PLEROMA_BACKGROUND_IMAGE_URL" "$PLEROMA_TITLE"
     install_gnusocial_default_background "gnusocial" "$PLEROMA_DOMAIN_NAME"
-    sed -i 's|"theme":.*|"theme": "base16-apathy.css",|g' /var/www/${PLEROMA_DOMAIN_NAME}/htdocs/static/config.json
+    if [ ! -f $PLEROMA_DIR/static/config.json ]; then
+        echo $"$PLEROMA_DIR/static/config.json file missing"
+        exit 323689
+    fi
+    sed -i 's|"theme":.*|"theme": "base16-apathy.css",|g' $PLEROMA_DIR/static/config.json
 
     if [ $PLEROMA_BACKGROUND_IMAGE_URL ]; then
-        pleroma_set_background_image_from_url "$PLEROMA_DOMAIN_NAME" "$PLEROMA_BACKGROUND_IMAGE_URL" "$PLEROMA_TITLE"
+        pleroma_set_background_image_from_url $PLEROMA_DIR "$PLEROMA_DOMAIN_NAME" "$PLEROMA_BACKGROUND_IMAGE_URL" "$PLEROMA_TITLE"
     fi
+
+    if [ ! -f $PLEROMA_DIR/index.html ]; then
+        echo $'Pleroma index file missing'
+        exit 7825393
+    fi
+
+
+    # Get certificate
+    function_check create_site_certificate
+    create_site_certificate $PLEROMA_DOMAIN_NAME 'yes'
+
+    function_check nginx_ensite
+    nginx_ensite $PLEROMA_DOMAIN_NAME
+
+    systemctl restart postgresql
+    systemctl restart nginx
+
+    set_completion_param "pleroma domain" "$PLEROMA_DOMAIN_NAME"
 
 
     # daemon
