Bring server zeronet install into line with the client

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -1648,6 +1648,20 @@ function install_zeronet_blog {
   ZERONET_BLOG_ADDRESS=${blog_address//[[:blank:]]/}
   ZERONET_BLOG_PRIVATE_KEY=${blog_private_key//[[:blank:]]/}
 
+  if [ ${#ZERONET_BLOG_ADDRESS} -lt 20 ]; then
+      echo "Address:    $ZERONET_BLOG_ADDRESS"
+      echo "Public key: $ZERONET_BLOG_PRIVATE_KEY"
+      echo 'Unable to create zeronet blog address'
+      exit 7358
+  fi
+
+  if [ ${#ZERONET_BLOG_PRIVATE_KEY} -lt 20 ]; then
+      echo "Address:    $ZERONET_BLOG_ADDRESS"
+      echo "Public key: $ZERONET_BLOG_PRIVATE_KEY"
+      echo 'Unable to create zeronet blog private key'
+      exit 1639
+  fi
+
   if [ ! -d "/opt/zeronet/data/$ZERONET_BLOG_ADDRESS" ]; then
       echo "Unable to find site directory: /opt/zeronet/data/$ZERONET_BLOG_ADDRESS"
       exit 7638
@@ -1658,9 +1672,19 @@ function install_zeronet_blog {
       echo 'ZeroBlog repo could not be cloned'
       exit 6739
   fi
-  echo "Blog address:     $ZERONET_BLOG_ADDRESS"
-  echo "Blog private key: $ZERONET_BLOG_PRIVATE_KEY"
+  echo "ZeroNet Blog address:     $ZERONET_BLOG_ADDRESS"
+  echo "ZeroNet Blog private key: $ZERONET_BLOG_PRIVATE_KEY"
   cp -r /opt/zeronet/ZeroBlog/* /opt/zeronet/data/$ZERONET_BLOG_ADDRESS
+
+  if [ ! -d /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/data ]; then
+      mkdir /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/data
+  fi
+  cp /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/data-default/data.json /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/data
+  sed -i "s/MyZeroBlog/$ZERONET_DEFAULT_BLOG_TITLE/g" /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/data/data.json
+  sed -i "s/My ZeroBlog./$ZERONET_DEFAULT_BLOG_TAGLINE/g" /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/data/data.json
+  sed -i "s/ZeroBlog Demo/$ZERONET_DEFAULT_BLOG_TITLE/g" /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/index.html
+  sed -i "s|<h3 class=\"description\">.*|<h3 class=\"description\">$ZERONET_DEFAULT_BLOG_TAGLINE</h3>|g" /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/index.html
+  sed -i "s/Blogging platform Demo/Blogging platform/g" /opt/zeronet/data/$ZERONET_BLOG_ADDRESS/content.json
   python zeronet.py siteSign $ZERONET_BLOG_ADDRESS $ZERONET_BLOG_PRIVATE_KEY
 
   # Add an avahi service
@@ -1675,6 +1699,11 @@ function install_zeronet_blog {
   echo '  </service>' >> /tmp/zeronet-blog.service
   echo '</service-group>' >> /tmp/zeronet-blog.service
   sudo cp /tmp/zeronet-blog.service /etc/avahi/services/zeronet-blog.service
+
+  if [ ! -d /home/$MY_USERNAME/.config/zeronet ]; then
+      mkdir -p /home/$MY_USERNAME/.config/zeronet
+  fi
+  echo "$ZERONET_URL/$ZERONET_BLOG_ADDRESS" > /home/$MY_USERNAME/.config/zeronet/myblog
 
   if ! grep -q "ZeroNet Blog address" /home/$MY_USERNAME/README; then
       echo '' >> /home/$MY_USERNAME/README
@@ -1718,6 +1747,20 @@ function install_zeronet_forum {
   ZERONET_FORUM_ADDRESS=${forum_address//[[:blank:]]/}
   ZERONET_FORUM_PRIVATE_KEY=${forum_private_key//[[:blank:]]/}
 
+  if [ ${#ZERONET_FORUM_ADDRESS} -lt 20 ]; then
+      echo "Address:    $ZERONET_FORUM_ADDRESS"
+      echo "Public key: $ZERONET_FORUM_PRIVATE_KEY"
+      echo 'Unable to create zeronet forum address'
+      exit 76352
+  fi
+
+  if [ ${#ZERONET_FORUM_PRIVATE_KEY} -lt 20 ]; then
+      echo "Address:    $ZERONET_FORUM_ADDRESS"
+      echo "Public key: $ZERONET_FORUM_PRIVATE_KEY"
+      echo 'Unable to create zeronet forum private key'
+      exit 87356
+  fi
+
   if [ ! -d "/opt/zeronet/data/$ZERONET_FORUM_ADDRESS" ]; then
       echo "Unable to find site directory: /opt/zeronet/data/$ZERONET_FORUM_ADDRESS"
       exit 7638
@@ -1731,6 +1774,11 @@ function install_zeronet_forum {
   echo "Forum address:     $ZERONET_FORUM_ADDRESS"
   echo "Forum private key: $ZERONET_FORUM_PRIVATE_KEY"
   cp -r /opt/zeronet/ZeroTalk/* /opt/zeronet/data/$ZERONET_FORUM_ADDRESS
+  sed -i "s/ZeroBoard/$ZERONET_DEFAULT_FORUM_TITLE/g" /opt/zeronet/data/$ZERONET_FORUM_ADDRESS/index.html
+  sed -i "s/ZeroTalk/$ZERONET_DEFAULT_FORUM_TITLE/g" /opt/zeronet/data/$ZERONET_FORUM_ADDRESS/index.html
+  sed -i "s|Demo for dynamic, decentralized content publishing.|$ZERONET_DEFAULT_FORUM_TAGLINE|g" /opt/zeronet/data/$ZERONET_FORUM_ADDRESS/index.html
+  sed -i 's/Messaging Board Demo/Messaging Board/g' /opt/zeronet/data/$ZERONET_FORUM_ADDRESS/content.json
+  sed -i "s/ZeroBoard/$ZERONET_DEFAULT_FORUM_TITLE/g" /opt/zeronet/data/$ZERONET_FORUM_ADDRESS/content.json
   python zeronet.py siteSign $ZERONET_FORUM_ADDRESS $ZERONET_FORUM_PRIVATE_KEY
 
   # Add an avahi service
@@ -1745,6 +1793,11 @@ function install_zeronet_forum {
   echo '  </service>' >> /tmp/zeronet-forum.service
   echo '</service-group>' >> /tmp/zeronet-forum.service
   sudo cp /tmp/zeronet-forum.service /etc/avahi/services/zeronet-forum.service
+
+  if [ ! -d /home/$MY_USERNAME/.config/zeronet ]; then
+      mkdir -p /home/$MY_USERNAME/.config/zeronet
+  fi
+  echo "$ZERONET_URL/$ZERONET_FORUM_ADDRESS" > /home/$MY_USERNAME/.config/zeronet/myforum
 
   if ! grep -q "ZeroNet Forum address" /home/$MY_USERNAME/README; then
       echo '' >> /home/$MY_USERNAME/README
