Default to no static local IP address, but have the option to set one

diff --git a/src/freedombone-config b/src/freedombone-config
--- a/src/freedombone-config
+++ b/src/freedombone-config
@@ -180,8 +180,10 @@ function save_configuration_file {
         echo "MY_NAME=$MY_NAME" >> $CONFIGURATION_FILE
     fi
     echo "MY_EMAIL_ADDRESS=$MY_EMAIL_ADDRESS" >> $CONFIGURATION_FILE
-    echo "LOCAL_NETWORK_STATIC_IP_ADDRESS=$LOCAL_NETWORK_STATIC_IP_ADDRESS" >> $CONFIGURATION_FILE
-    echo "ROUTER_IP_ADDRESS=$ROUTER_IP_ADDRESS" >> $CONFIGURATION_FILE
+    if [ $LOCAL_NETWORK_STATIC_IP_ADDRESS ]; then
+        echo "LOCAL_NETWORK_STATIC_IP_ADDRESS=$LOCAL_NETWORK_STATIC_IP_ADDRESS" >> $CONFIGURATION_FILE
+        echo "ROUTER_IP_ADDRESS=$ROUTER_IP_ADDRESS" >> $CONFIGURATION_FILE
+    fi
     if [ $ENABLE_CJDNS ]; then
         echo "ENABLE_CJDNS=$ENABLE_CJDNS" >> $CONFIGURATION_FILE
     fi
@@ -657,10 +659,10 @@ function interactive_configuration {
     fi
 
     if [ -d /home/$GENERIC_IMAGE_USERNAME ]; then
-		if [ ! -f $IMAGE_PASSWORD_FILE ]; then
-			echo 'Cannot find the password file for the admin user'
-			exit 62753
-		fi
+        if [ ! -f $IMAGE_PASSWORD_FILE ]; then
+            echo 'Cannot find the password file for the admin user'
+            exit 62753
+        fi
         # when installing from an image which comes with a known default user account
         selected_username=
         while [ ! $selected_username ]
@@ -1091,34 +1093,47 @@ function interactive_configuration {
         save_configuration_file
     fi
 
-    if [ ! $LOCAL_NETWORK_STATIC_IP_ADDRESS ]; then
-        LOCAL_NETWORK_STATIC_IP_ADDRESS=$(grep 'LOCAL_NETWORK_STATIC_IP_ADDRESS' temp.cfg | awk -F '=' '{print $2}')
-        if [ ! $LOCAL_NETWORK_STATIC_IP_ADDRESS ]; then
-            LOCAL_NETWORK_STATIC_IP_ADDRESS='192.168..'
-        fi
-    fi
-    if [ ! $ROUTER_IP_ADDRESS ]; then
-        ROUTER_IP_ADDRESS=$(grep 'ROUTER_IP_ADDRESS' temp.cfg | awk -F '=' '{print $2}')
-        if [ ! $ROUTER_IP_ADDRESS ]; then
-            ROUTER_IP_ADDRESS='192.168..'
-        fi
-    fi
-    data=$(tempfile 2>/dev/null)
-    trap "rm -f $data" 0 1 2 5 15
-    dialog --backtitle $"Freedombone Configuration" \
-           --title $"Local Network Configuration" \
-           --form $"\nPlease enter the IP addresses:" 11 55 3 \
-           $"This system:" 1 1 "$LOCAL_NETWORK_STATIC_IP_ADDRESS" 1 16 16 15 \
-           $"Internet router:" 2 1 "$ROUTER_IP_ADDRESS" 2 16 16 15 \
-           2> $data
+    SET_STATIC_IP="no"
+    dialog --title $"Static local IP address" \
+           --backtitle $"Freedombone Configuration" \
+           --defaultno \
+           --yesno $"\nDo you want to set a static local IP address for this system?\n\nFor example, 192.168.1.10" 10 60
     sel=$?
     case $sel in
-        1) exit 1;;
+        0) SET_STATIC_IP="yes";;
         255) exit 1;;
     esac
-    LOCAL_NETWORK_STATIC_IP_ADDRESS=$(cat $data | sed -n 1p)
-    ROUTER_IP_ADDRESS=$(cat $data | sed -n 2p)
-    save_configuration_file
+
+    if [[ $SET_STATIC_IP == "yes" ]]; then
+        if [ ! $LOCAL_NETWORK_STATIC_IP_ADDRESS ]; then
+            LOCAL_NETWORK_STATIC_IP_ADDRESS=$(grep 'LOCAL_NETWORK_STATIC_IP_ADDRESS' temp.cfg | awk -F '=' '{print $2}')
+            if [ ! $LOCAL_NETWORK_STATIC_IP_ADDRESS ]; then
+                LOCAL_NETWORK_STATIC_IP_ADDRESS='192.168..'
+            fi
+        fi
+        if [ ! $ROUTER_IP_ADDRESS ]; then
+            ROUTER_IP_ADDRESS=$(grep 'ROUTER_IP_ADDRESS' temp.cfg | awk -F '=' '{print $2}')
+            if [ ! $ROUTER_IP_ADDRESS ]; then
+                ROUTER_IP_ADDRESS='192.168..'
+            fi
+        fi
+        data=$(tempfile 2>/dev/null)
+        trap "rm -f $data" 0 1 2 5 15
+        dialog --backtitle $"Freedombone Configuration" \
+               --title $"Local Network Configuration" \
+               --form $"\nPlease enter the IP addresses:" 11 55 3 \
+               $"This system:" 1 1 "$LOCAL_NETWORK_STATIC_IP_ADDRESS" 1 16 16 15 \
+               $"Internet router:" 2 1 "$ROUTER_IP_ADDRESS" 2 16 16 15 \
+               2> $data
+        sel=$?
+        case $sel in
+            1) exit 1;;
+            255) exit 1;;
+        esac
+        LOCAL_NETWORK_STATIC_IP_ADDRESS=$(cat $data | sed -n 1p)
+        ROUTER_IP_ADDRESS=$(cat $data | sed -n 2p)
+        save_configuration_file
+    fi
 
     if [[ $SYSTEM_TYPE == "$VARIANT_WRITER" || $SYSTEM_TYPE == "$VARIANT_FULL" ]]; then
         WIKI_DETAILS_COMPLETE=
