Fixing mariadb

diff --git a/src/freedombone-utils-database b/src/freedombone-utils-database
--- a/src/freedombone-utils-database
+++ b/src/freedombone-utils-database
@@ -162,11 +162,10 @@ function install_mariadb {
         exit 34672
     fi
 
-    if [ ! -f /etc/mysql/conf.d/my.cnf ]; then
-        echo $'/etc/mysql/conf.d/my.cnf not found'
-        exit 6376245
-    fi
-    echo 'socket = /var/run/mysqld/mysqld.sock' >> /etc/mysql/conf.d/my.cnf
+    #if [ ! -f /etc/mysql/conf.d/my.cnf ]; then
+    #    echo $'/etc/mysql/conf.d/my.cnf not found'
+    #    exit 6376245
+    #fi
     systemctl restart mysql
 
     mysqladmin -u root password "$MARIADB_PASSWORD"
