Fixing ttrss backup and restore

diff --git a/src/freedombone-app-rss b/src/freedombone-app-rss
--- a/src/freedombone-app-rss
+++ b/src/freedombone-app-rss
@@ -149,8 +149,6 @@ function upgrade_rss {
 
 function backup_local_rss {
     if [ -d /etc/share/tt-rss ]; then
-        RSS_READER_DOMAIN_NAME=$(get_completion_param "rss reader domain")
-
         echo $"Backing up ttrss"
 
         function_check backup_database_to_usb
@@ -168,7 +166,7 @@ function restore_local_rss {
     function_check rss_create_database
     rss_create_database
 
-    restore_database ttrss ${RSS_READER_DOMAIN_NAME}
+    restore_database ttrss
 
     if [ -d /etc/share/tt-rss ]; then
         if [ -d $temp_restore_dir/etc/share/tt-rss ]; then
@@ -219,7 +217,7 @@ function restore_local_rss {
 function backup_remote_rss {
     if [ -d /etc/share/tt-rss ]; then
         function_check suspend_site
-        suspend_site ${RSS_READER_DOMAIN_NAME}
+        suspend_site ttrss
 
         function_check backup_database_to_friend
         backup_database_to_friend ttrss
@@ -232,7 +230,8 @@ function backup_remote_rss {
         function_check restart_site
         restart_site
     else
-        echo $"RSS reader domain specified but not found in /etc/share/ttrss}"
+        echo $"/etc/share/tt-rss directory not found}"
+        exit 783532
     fi
 }
 
@@ -245,7 +244,7 @@ function restore_remote_rss {
         function_check rss_create_database
         rss_create_database
 
-        restore_database_from_friend ttrss ${RSS_READER_DOMAIN_NAME}
+        restore_database_from_friend ttrss
 
         if [ -d /etc/share/tt-rss ]; then
             if [ -d $temp_restore_dir/etc/share/tt-rss ]; then
