Populate upgrade functions for apps

diff --git a/src/freedombone-app-gnusocial b/src/freedombone-app-gnusocial
--- a/src/freedombone-app-gnusocial
+++ b/src/freedombone-app-gnusocial
@@ -47,9 +47,38 @@ SHARINGS_COMMIT='d5c6c7f855d9afff9086c09ea706f38c859bc0d4'
 SHARINGS_THEME_REPO="http://git.lasindias.club/manuel/SharingsTheme"
 SHARINGS_THEME_COMMIT='7106c7ef03'
 
-function upgrade_gnusocial {
-    echo ''
+function gnusocial_running_script {
+	if ! grep -Fxq "install_gnusocial" $COMPLETION_FILE; then
+		return
+	fi
+
+	# check that the daemon is running
+	echo '#!/bin/bash' > /etc/cron.hourly/gnusocial-daemons
+	echo 'daemon_lines=$(ps aux | grep "scripts/queuedaemon.php" | grep "/var/www")' >> /etc/cron.hourly/gnusocial-daemons
+	echo 'if [[ $daemon_lines != *"/var/www/"* ]]; then' >> /etc/cron.hourly/gnusocial-daemons
+
+	echo "    ADMIN_USER=\$(cat $COMPLETION_FILE | grep 'Admin user' | awk -F ':' '{print \$2}')" >> /etc/cron.hourly/gnusocial-daemons
+	echo '    MY_EMAIL_ADDRESS=$ADMIN_USER@$HOSTNAME' >> /etc/cron.hourly/gnusocial-daemons
+	echo '    echo "Restarting GNU Social daemons" | mail -s "GNU Social daemons not found" $MY_EMAIL_ADDRESS' >> /etc/cron.hourly/gnusocial-daemons
+	echo "    cd /var/www/${MICROBLOG_DOMAIN_NAME}/htdocs" >> /etc/cron.hourly/gnusocial-daemons
+	echo '    scripts/startdaemons.sh' >> /etc/cron.hourly/gnusocial-daemons
+	echo 'fi' >> /etc/cron.hourly/gnusocial-daemons
+	chmod +x /etc/cron.hourly/gnusocial-daemons
 }
+
+function upgrade_gnusocial {
+	if ! grep -Fxq "install_gnusocial_main" $COMPLETION_FILE; then
+		return
+	fi
+
+	# update to the next commit
+	function_check set_repo_commit
+	set_repo_commit /var/www/$MICROBLOG_DOMAIN_NAME/htdocs "GNU Social commit" "$MICROBLOG_COMMIT" $MICROBLOG_REPO
+
+	function_check gnusocial_running_script
+	gnusocial_running_script
+}
+
 
 function backup_local_gnusocial {
 	echo ''
@@ -87,26 +116,12 @@ function install_gnusocial_main {
 		exit 7359
 	fi
 
-	# update to the next commit
-	function_check set_repo_commit
-	set_repo_commit /var/www/$MICROBLOG_DOMAIN_NAME/htdocs "GNU Social commit" "$MICROBLOG_COMMIT" $MICROBLOG_REPO
-
-	# add a script to check that the daemon is running
-	echo '#!/bin/bash' > /etc/cron.hourly/gnusocial-daemons
-	echo 'daemon_lines=$(ps aux | grep "scripts/queuedaemon.php" | grep "/var/www")' >> /etc/cron.hourly/gnusocial-daemons
-	echo 'if [[ $daemon_lines != *"/var/www/"* ]]; then' >> /etc/cron.hourly/gnusocial-daemons
-
-	echo "    ADMIN_USER=\$(cat $COMPLETION_FILE | grep 'Admin user' | awk -F ':' '{print \$2}')" >> /etc/cron.hourly/gnusocial-daemons
-	echo '    MY_EMAIL_ADDRESS=$ADMIN_USER@$HOSTNAME' >> /etc/cron.hourly/gnusocial-daemons
-	echo '    echo "Restarting GNU Social daemons" | mail -s "GNU Social daemons not found" $MY_EMAIL_ADDRESS' >> /etc/cron.hourly/gnusocial-daemons
-	echo "    cd /var/www/${MICROBLOG_DOMAIN_NAME}/htdocs" >> /etc/cron.hourly/gnusocial-daemons
-	echo '    scripts/startdaemons.sh' >> /etc/cron.hourly/gnusocial-daemons
-	echo 'fi' >> /etc/cron.hourly/gnusocial-daemons
-	chmod +x /etc/cron.hourly/gnusocial-daemons
-
 	if grep -Fxq "install_gnusocial_main" $COMPLETION_FILE; then
 		return
 	fi
+
+	function_check gnusocial_running_script
+	gnusocial_running_script
 
 	function_check install_mariadb
 	install_mariadb
diff --git a/src/freedombone-app-rss b/src/freedombone-app-rss
--- a/src/freedombone-app-rss
+++ b/src/freedombone-app-rss
@@ -41,7 +41,36 @@ RSS_READER_GNUSOCIAL_REPO="https://github.com/bashrc/ttrss-gnusocial"
 RSS_READER_GNUSOCIAL_COMMIT='8b92b8f5db7b0d12459c7bd86a50f48815efe642'
 
 function upgrade_rss {
-    echo ''
+	if grep -Fxq "install_rss" $COMPLETION_FILE; then
+		function_check set_repo_commit
+		set_repo_commit $RSS_READER_PATH "RSS reader commit" "$RSS_READER_COMMIT" $RSS_READER_REPO
+	fi
+
+	if grep -Fxq "install_rss_mobile_reader" $COMPLETION_FILE; then
+		if [ ! $RSS_READER_PATH ]; then
+			RSS_READER_PATH=/etc/share/tt-rss
+		fi
+
+		if [ ! -d $RSS_READER_PATH ]; then
+			echo $'tt-rss is not installed, so the mobile version cannot be installed'
+			exit 63452
+		fi
+
+		RSS_MOBILE_READER_PATH=/etc/share/ttrss-mobile
+
+		# remove any previous install
+		if [ -d $RSS_READER_PATH/g2ttree-mobile ]; then
+			if grep -Fxq "install_rss_mobile_reader" $COMPLETION_FILE; then
+				sed -i '/install_rss_mobile_reader/d' $COMPLETION_FILE
+				sed -i '/RSS mobile reader commit/d' $COMPLETION_FILE
+				rm -rf $RSS_READER_PATH/g2ttree-mobile
+			fi
+		fi
+
+		# update to the next commit
+		function_check set_repo_commit
+		set_repo_commit $RSS_MOBILE_READER_PATH "RSS mobile reader commit" "$RSS_MOBILE_READER_COMMIT" $RSS_MOBILE_READER_REPO
+	fi
 }
 
 function backup_local_rss {
@@ -92,10 +121,6 @@ function install_rss_main {
 	if [[ $SYSTEM_TYPE == "$VARIANT_MAILBOX" || $SYSTEM_TYPE == "$VARIANT_CHAT" || $SYSTEM_TYPE == "$VARIANT_MEDIA" || $SYSTEM_TYPE == "$VARIANT_DEVELOPER" || $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
 		return
 	fi
-
-	# update to the next commit
-	function_check set_repo_commit
-	set_repo_commit $RSS_READER_PATH "RSS reader commit" "$RSS_READER_COMMIT" $RSS_READER_REPO
 
 	if grep -Fxq "install_rss_main" $COMPLETION_FILE; then
 		return
@@ -414,10 +439,6 @@ function install_rss_mobile_reader {
 			rm -rf $RSS_READER_PATH/g2ttree-mobile
 		fi
 	fi
-
-	# update to the next commit
-	function_check set_repo_commit
-	set_repo_commit $RSS_MOBILE_READER_PATH "RSS mobile reader commit" "$RSS_MOBILE_READER_COMMIT" $RSS_MOBILE_READER_REPO
 
 	if grep -Fxq "install_rss_mobile_reader" $COMPLETION_FILE; then
 		return
