Install scuttlebot on mesh
This should better enable nat traversal between the internet and the mesh

diff --git a/src/freedombone-image-mesh b/src/freedombone-image-mesh
--- a/src/freedombone-image-mesh
+++ b/src/freedombone-image-mesh
@@ -756,6 +756,41 @@ function mesh_setup_vpn {
     systemctl restart openvpn
 }
 
+function initialise_scuttlebot_pub {
+    chown -R scuttlebot:scuttlebot /etc/scuttlebot
+
+    systemctl enable scuttlebot.service
+    systemctl daemon-reload
+    systemctl start scuttlebot.service
+
+    sleep 3
+
+    if [ ! -d /etc/scuttlebot/.ssb ]; then
+        echo $'Scuttlebot config not generated' >> /var/log/${PROJECT_NAME}.log
+        exit 73528
+    fi
+
+    echo '{' > /etc/scuttlebot/.ssb/config
+    echo "  \"host\": \"${HOSTNAME}\"," >> /etc/scuttlebot/.ssb/config
+    echo "  \"port\": 8008," >> /etc/scuttlebot/.ssb/config
+    echo '  "timeout": 30000,' >> /etc/scuttlebot/.ssb/config
+    echo '  "pub": true,' >> /etc/scuttlebot/.ssb/config
+    echo '  "local": true,' >> /etc/scuttlebot/.ssb/config
+    echo '  "friends": {' >> /etc/scuttlebot/.ssb/config
+    echo '    "dunbar": 150,' >> /etc/scuttlebot/.ssb/config
+    echo '    "hops": 3' >> /etc/scuttlebot/.ssb/config
+    echo '  },' >> /etc/scuttlebot/.ssb/config
+    echo '  "gossip": {' >> /etc/scuttlebot/.ssb/config
+    echo '    "connections": 2' >> /etc/scuttlebot/.ssb/config
+    echo '  },' >> /etc/scuttlebot/.ssb/config
+    echo '  "master": [],' >> /etc/scuttlebot/.ssb/config
+    echo '  "logging": {' >> /etc/scuttlebot/.ssb/config
+    echo '    "level": "error"' >> /etc/scuttlebot/.ssb/config
+    echo '  }' >> /etc/scuttlebot/.ssb/config
+    echo '}' >> /etc/scuttlebot/.ssb/config
+    chown scuttlebot:scuttlebot /etc/scuttlebot/.ssb/config
+    systemctl restart scuttlebot.service
+}
 
 # whether to reset the identity
 set_new_identity=
@@ -819,6 +854,7 @@ if [ -f $MESH_INSTALL_SETUP ]; then
     create_tox_user
     #setup_tahoelafs
     mesh_setup_vpn
+    initialise_scuttlebot_pub
     setup_ipfs
     mesh_amnesic
     make_root_read_only
