Renew letsencrypt certs by default

diff --git a/src/freedombone-renew-cert b/src/freedombone-renew-cert
--- a/src/freedombone-renew-cert
+++ b/src/freedombone-renew-cert
@@ -37,6 +37,7 @@ HOSTNAME=
 PROVIDER='startssl'
 DH_KEYLENGTH=2048
 LETSENCRYPT_SERVER='https://acme-v01.api.letsencrypt.org/directory'
+INSTALL_DIR=/root/build
 
 function show_help {
     echo ''
@@ -54,20 +55,14 @@ function show_help {
 function renew_letsencrypt {
     if [ ! -f /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem ]; then
         echo $"Adding Let's Encrypt certificate"
-        ${PROJECT_NAME}-addcert -e $HOSTNAME -s $LETSENCRYPT_SERVER --dhkey $DH_KEYLENGTH
-        if [ ! "$?" = "0" ]; then
-            echo $"Unable to add Let's encrypt certificate"
-            exit 6328
-        fi
     else
         echo $"Renewing Let's Encrypt certificate"
-        letsencrypt renew \
-                    --cert-path /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem \
-                    --key-path /etc/letsencrypt/live/${HOSTNAME}/privkey.pem
-        if [ ! "$?" = "0" ]; then
-            echo $"Unable to renew Let's encrypt certificate"
-            exit 2624
-        fi
+    fi
+
+    ${PROJECT_NAME}-addcert -e $HOSTNAME -s $LETSENCRYPT_SERVER --dhkey $DH_KEYLENGTH
+    if [ ! "$?" = "0" ]; then
+        echo $"Unable to add Let's encrypt certificate"
+        exit 6328
     fi
 
     # Ensure that links are in place
