Install npm in mesh image

diff --git a/src/freedombone-image-customise b/src/freedombone-image-customise
--- a/src/freedombone-image-customise
+++ b/src/freedombone-image-customise
@@ -564,6 +564,15 @@ INSTALLING_MESH=
 install_patchwork() {
     chroot "$rootdir" apt-get -yq install g++ m4 libtool automake nodejs
     chroot "$rootdir" apt-get -yq install libxext-dev libxtst-dev libxkbfile-dev
+
+    wget https://www.npmjs.com/install.sh -O $rootdir/root/npm_install.sh
+    if [ ! -f $rootdir/root/npm_install.sh ]; then
+        echo $'Unable to download npm installer'
+        exit 8793636
+    fi
+    chroot "$rootdir" chmod +x /root/npm_install.sh
+    chroot "$rootdir" /root/npm_install.sh
+
     git clone https://github.com/ssbc/patchwork $rootdir/etc/patchwork
 
     cat <<EOF > $rootdir/usr/bin/install_patchwork
