Install a web server on mesh clients for the zeronet tracker

diff --git a/src/freedombone-meshweb b/src/freedombone-meshweb
--- a/src/freedombone-meshweb
+++ b/src/freedombone-meshweb
@@ -13,6 +13,24 @@ ZERONET_DIR=~/zeronet
 ZERONET_URL=http://127.0.0.1:43110
 TRACKER_PORT=6969
 
+function install_web_server {
+    if [ -d /etc/nginx ]; then
+        return
+    fi
+
+    sudo apt-get -y remove --purge apache2
+    if [ -d /etc/apache2 ]; then
+        sudo rm -rf /etc/apache2
+    fi
+    # install nginx
+    sudo apt-get -y install nginx
+
+    if [ ! -d /etc/nginx ]; then
+        echo 'Unable to install web server'
+        exit 51
+    fi
+}
+
 function install_zeronet {
   if [ -d $ZERONET_DIR ]; then
       return
@@ -42,6 +60,7 @@ fi
 
 if [[ $SERVER_INSTALLATION == "no" ]]; then
     if [ ! -f /tmp/meshtype ]; then
+        install_web_server
         install_zeronet
         sudo batman start
         if [ ! "$?" = "0" ]; then
@@ -78,9 +97,9 @@ cd $ZERONET_DIR
 
 existing_bttrack=$(ps aux | grep bttrack | wc -l)
 if [ $existing_bttrack -lt "2" ]; then
-	if [ ! -d ~/.bttrack ]; then
-		mkdir ~/.bttrack
-	fi
+    if [ ! -d ~/.bttrack ]; then
+        mkdir ~/.bttrack
+    fi
     bttrack --port ${TRACKER_PORT} --dfile ~/.bttrack/dstate --logfile ~/.bttrack/tracker.log --nat_check 0 --scrape_allowed full --ipv6_enabled 0 &
 fi
 
