Check last line

diff --git a/src/freedombone-app-matrix b/src/freedombone-app-matrix
--- a/src/freedombone-app-matrix
+++ b/src/freedombone-app-matrix
@@ -506,7 +506,10 @@ function install_matrix {
 
     matrix_nginx
 
-    add_user_matrix "${MY_USERNAME}" "${MATRIX_PASSWORD}"
+    if [[ $(add_user_matrix "${MY_USERNAME}" "${MATRIX_PASSWORD}" | tail -n 1) != "0" ]]; then
+        echo $'Failed to add matrix admin user';
+        exit 879352
+    fi
 
     APP_INSTALLED=1
 }
