Additional waits

diff --git a/src/freedombone-app-bdsmail b/src/freedombone-app-bdsmail
--- a/src/freedombone-app-bdsmail
+++ b/src/freedombone-app-bdsmail
@@ -253,12 +253,16 @@ function install_bdsmail {
     chmod +x /usr/bin/bdsmail_domain
 
     # wait for domain to be generated by the daemon
-    sleep 10
-
+    echo $'Waiting for i2p domain to be generated...'
+    sleep 15
     bds_domain=$(bdsmail_domain)
     if [ ! $bds_domain ]; then
-        echo $'Failed to get the bdsmail domain'
-        exit 8934638
+        sleep 15
+        bds_domain=$(bdsmail_domain)
+        if [ ! $bds_domain ]; then
+            echo $'Failed to get the bdsmail domain'
+            exit 8934638
+        fi
     fi
 
     # Create mutt configuration
