Indentation

diff --git a/src/freedombone-template b/src/freedombone-template
--- a/src/freedombone-template
+++ b/src/freedombone-template
@@ -715,34 +715,34 @@ if [ $app_webui ]; then
     echo '    fi'
 fi
 
-echo "      if [ -d /repos/${app_name} ]; then"
+echo "    if [ -d /repos/${app_name} ]; then"
 if [ $app_webui ]; then
-    echo "          mkdir \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\""
+    echo "        mkdir \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\""
 fi
 if [ ! "$app_dir" ]; then
-    echo "          cp -r -p /repos/${app_name}/. \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\""
-    echo "          cd \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\" || exit 324687356"
+    echo "        cp -r -p /repos/${app_name}/. \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\""
+    echo "        cd \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\" || exit 324687356"
 else
-    echo "          cp -r -p /repos/${app_name}/. \"${app_dir}\""
-    echo "          cd \"${app_dir}\" || exit 36487365"
+    echo "        cp -r -p /repos/${app_name}/. \"${app_dir}\""
+    echo "        cd \"${app_dir}\" || exit 36487365"
 fi
-echo '          git pull'
-echo '      else'
+echo '        git pull'
+echo '    else'
 if [ ! "$app_dir" ]; then
-    echo "          git_clone \"\$${app_name_upper}_REPO\" \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\""
+    echo "        git_clone \"\$${app_name_upper}_REPO\" \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\""
 else
-    echo "          git_clone \"\$${app_name_upper}_REPO\" \"${app_dir}\""
+    echo "        git_clone \"\$${app_name_upper}_REPO\" \"${app_dir}\""
 fi
-echo '      fi'
+echo '    fi'
 echo ''
 if [ ! "$app_dir" ]; then
-    echo "        if [ ! -d \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\" ]; then"
+    echo "    if [ ! -d \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\" ]; then"
 else
-    echo "        if [ ! -d \"${app_dir}\" ]; then"
+    echo "    if [ ! -d \"${app_dir}\" ]; then"
 fi
-echo "            echo \$'Unable to clone ${app_name} repo'"
-echo '            exit 87525'
-echo '        fi'
+echo "        echo \$'Unable to clone ${app_name} repo'"
+echo '        exit 87525'
+echo '    fi'
 echo ''
 if [ ! "$app_dir" ]; then
     echo "    cd \"/var/www/\$${app_name_upper}_DOMAIN_NAME/htdocs\" || exit 36587356"
