Check return status when enabling hotspot

diff --git a/src/freedombone-controlpanel b/src/freedombone-controlpanel
--- a/src/freedombone-controlpanel
+++ b/src/freedombone-controlpanel
@@ -1668,6 +1668,10 @@ function hotspot_settings {
         WIFI_PASSPHRASE=$TEMP_WIFI_PASSPHRASE
 
         ${PROJECT_NAME}-wifi -i $WIFI_INTERFACE -s $WIFI_SSID -t $WIFI_TYPE -p $WIFI_PASSPHRASE --hotspot $WIFI_HOTSPOT $WIFI_EXTRA
+        if [ ! "$?" = "0" ]; then
+            echo $"Can't enable wifi hotspot"
+            any_key
+        fi
     else
         WIFI_HOTSPOT=$TEMP_WIFI_HOTSPOT
         WIFI_SSID=$TEMP_WIFI_SSID
