Compile toxcore and toxic on mesh nodes
This does result in a delay before fully operational but avoids needing to cross compile while building the image, which adds complexity

diff --git a/src/freedombone-image-customise b/src/freedombone-image-customise
--- a/src/freedombone-image-customise
+++ b/src/freedombone-image-customise
@@ -640,35 +640,43 @@ function mesh_tox_node {
 	chroot "$rootdir" apt-get -y install libsodium13 libsodium-dev libcap2-bin
 	chroot "$rootdir" apt-get -y install libconfig9 libconfig-dev
 
-	chroot "$rootdir" git clone $TOXCORE_REPO $INSTALL_DIR/toxcore
-	chroot "$rootdir" cd $INSTALL_DIR/toxcore; git checkout $TOXCORE_COMMIT -b $TOXCORE_COMMIT
+	if [ ! -d $rootdir$INSTALL_DIR ]; then
+		mkdir -p $rootdir$INSTALL_DIR
+	fi
+	git clone $TOXCORE_REPO $rootdir$INSTALL_DIR/toxcore
+	if [ ! -d $rootdir$INSTALL_DIR/toxcore ]; then
+		echo $'Unable to clone toxcore'
+		exit 543335
+	fi
+	cd $rootdir$INSTALL_DIR/toxcore
+	git checkout $TOXCORE_COMMIT -b $TOXCORE_COMMIT
 
-	chroot "$rootdir" cd $INSTALL_DIR/toxcore; autoreconf -i
-	chroot "$rootdir" cd $INSTALL_DIR/toxcore; ./configure --enable-daemon --disable-av
-	if [ ! "$?" = "0" ]; then
-		return
-	fi
-	chroot "$rootdir" cd $INSTALL_DIR/toxcore; make
-	if [ ! "$?" = "0" ]; then
-		return
-	fi
-	chroot "$rootdir" cd $INSTALL_DIR/toxcore; make install
-	chroot "$rootdir" cp /usr/local/lib/libtoxcore* /usr/lib/
+	#chroot "$rootdir" cd $INSTALL_DIR/toxcore; autoreconf -i
+	#chroot "$rootdir" cd $INSTALL_DIR/toxcore; ./configure --enable-daemon --disable-av
+	#if [ ! "$?" = "0" ]; then
+		#return
+	#fi
+	#chroot "$rootdir" cd $INSTALL_DIR/toxcore; make
+	#if [ ! "$?" = "0" ]; then
+		#return
+	#fi
+	#chroot "$rootdir" cd $INSTALL_DIR/toxcore; make install
+	#chroot "$rootdir" cp /usr/local/lib/libtoxcore* /usr/lib/
 
-	if [ ! -f $rootdir/usr/local/bin/tox-bootstrapd ]; then
-		echo $"File not found /usr/local/bin/tox-bootstrapd"
-		return
-	fi
+	#if [ ! -f $rootdir/usr/local/bin/tox-bootstrapd ]; then
+		#echo $"File not found /usr/local/bin/tox-bootstrapd"
+		#return
+	#fi
 
-	chroot "$rootdir" useradd --home-dir /var/lib/tox-bootstrapd --create-home --system --shell /sbin/nologin --comment $"Account to run Tox's DHT bootstrap daemon" --user-group tox-bootstrapd
-	chroot "$rootdir" chmod 700 /var/lib/tox-bootstrapd
-	if [ ! -f $rootdir/$INSTALL_DIR/toxcore/other/bootstrap_daemon/tox-bootstrapd.conf ]; then
-		echo $"File not found $INSTALL_DIR/toxcore/other/bootstrap_daemon/tox-bootstrapd.conf"
-	fi
+	#chroot "$rootdir" useradd --home-dir /var/lib/tox-bootstrapd --create-home --system --shell /sbin/nologin --comment $"Account to run Tox's DHT bootstrap daemon" --user-group tox-bootstrapd
+	#chroot "$rootdir" chmod 700 /var/lib/tox-bootstrapd
+	#if [ ! -f $rootdir/$INSTALL_DIR/toxcore/other/bootstrap_daemon/tox-bootstrapd.conf ]; then
+		#echo $"File not found $INSTALL_DIR/toxcore/other/bootstrap_daemon/tox-bootstrapd.conf"
+	#fi
 	# remove Maildir
-	if [ -d $rootdir/var/lib/tox-bootstrapd/Maildir ]; then
-		rm -rf $rootdir/var/lib/tox-bootstrapd/Maildir
-	fi
+	#if [ -d $rootdir/var/lib/tox-bootstrapd/Maildir ]; then
+		#rm -rf $rootdir/var/lib/tox-bootstrapd/Maildir
+	#fi
 
 	# create configuration file
 	TOX_BOOTSTRAP_CONFIG=${rootdir}/etc/tox-bootstrapd.conf
@@ -751,25 +759,17 @@ function mesh_tox_client {
 	chroot "$rootdir" apt-get -y install libncursesw5-dev libconfig-dev libqrencode-dev
 	chroot "$rootdir" apt-get -y install libcurl4-openssl-dev libvpx-dev libopenal-dev
 
-	if [ ! -f $rootdir$INSTALL_DIR ]; then
+	if [ ! -d $rootdir$INSTALL_DIR ]; then
 		mkdir -p $rootdir$INSTALL_DIR
 	fi
-	chroot "$rootdir" git clone $TOXIC_REPO $INSTALL_DIR/toxic
-	chroot "$rootdir" cd $INSTALL_DIR/toxic; git checkout $TOXIC_COMMIT -b $TOXIC_COMMIT
+	git clone $TOXIC_REPO $rootdir$INSTALL_DIR/toxic
+	cd $rootdir$INSTALL_DIR/toxic
+	git checkout $TOXIC_COMMIT -b $TOXIC_COMMIT
+
 	if ! grep -q "Toxic commit" $rootdir$COMPLETION_FILE; then
 		echo "Toxic commit:$TOXIC_COMMIT" >> $rootdir$COMPLETION_FILE
 	else
 		sed -i "s|Toxic commit.*|Toxic commit:$TOXIC_COMMIT|g" $rootdir$COMPLETION_FILE
-	fi
-
-	chroot "$rootdir" cd $INSTALL_DIR/toxic; make
-	if [ ! -f $INSTALL_DIR/toxic/build/toxic ]; then
-		exit 74872
-	fi
-	chroot "$rootdir" cd $INSTALL_DIR/toxic; make install
-	if [ ! -f $TOXIC_FILE ]; then
-		echo $'Tox client was not installed'
-		exit 63278
 	fi
 }
 
