Check directories

diff --git a/src/freedombone-app-keyserver b/src/freedombone-app-keyserver
--- a/src/freedombone-app-keyserver
+++ b/src/freedombone-app-keyserver
@@ -243,12 +243,11 @@ function install_keyserver {
         cd $INSTALL_DIR/keyserver
         git pull
     else
-        if [ -d $INSTALL_DIR/keyserver ]; then
-            cd $INSTALL_DIR/keyserver
-            pull
-        else
-            git_clone $KEYSERVER_SKS_REPO $INSTALL_DIR/keyserver
-        fi
+        git_clone $KEYSERVER_SKS_REPO keyserver
+    fi
+    if [ ! -d $INSTALL_DIR/keyserver ]; then
+        echo $"$INSTALL_DIR/keyserver not found"
+        exit 835274
     fi
 
     cd $INSTALL_DIR/keyserver
@@ -267,6 +266,10 @@ function install_keyserver {
         git pull
     else
         git_clone $KEYSERVER_WEB_REPO htdocs
+    fi
+    if [ ! -d /var/www/$KEYSERVER_DOMAIN_NAME/htdocs ]; then
+        echo $"/var/www/$KEYSERVER_DOMAIN_NAME/htdocs not found"
+        exit 6539230
     fi
 
     cd /var/www/$KEYSERVER_DOMAIN_NAME/htdocs
