Blog app tidying

diff --git a/src/freedombone-app-blog b/src/freedombone-app-blog
--- a/src/freedombone-app-blog
+++ b/src/freedombone-app-blog
@@ -257,122 +257,101 @@ function install_blog_user {
     echo 'role = admin' >> /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/users/$MY_USERNAME.ini
 }
 
-function install_blog {
-    if [ ! $FULLBLOG_DOMAIN_NAME ]; then
-	echo $'The blog domain name was not specified'
-	exit 5062
-    fi
+function install_blog_settings {
+    cp /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini.example /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
+    sed -i "s|site.url.*|site.url = '/'|g" /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
+    sed -i "s|blog.title.*|blog.title = '$MY_BLOG_TITLE'|g" /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
+    sed -i "s|blog.tagline.*|blog.tagline = '$MY_BLOG_SUBTITLE'|g" /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
+    sed -i 's|timezone.*|timezone = "Europe/London"|g' /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
+    sed -i "s|Your name|$MY_NAME|g" /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
+}
 
-    if grep -Fxq "install_blog" $COMPLETION_FILE; then
-	return
-    fi
+function install_blog_website {
+    function_check nginx_http_redirect
+    nginx_http_redirect $FULLBLOG_DOMAIN_NAME
+    echo 'server {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    listen 443 ssl;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo "    root /var/www/$FULLBLOG_DOMAIN_NAME/htdocs;" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo "    server_name $FULLBLOG_DOMAIN_NAME;" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    access_log off;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo "    error_log /var/log/nginx/${FULLBLOG_DOMAIN_NAME}_error_ssl.log $WEBSERVER_LOG_LEVEL;" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    index index.php;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    charset utf-8;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    proxy_read_timeout 86400s;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    function_check nginx_limits
+    nginx_limits $FULLBLOG_DOMAIN_NAME
+    function_check nginx_ssl
+    nginx_ssl $FULLBLOG_DOMAIN_NAME
+    function_check nginx_disable_sniffing
+    nginx_disable_sniffing $FULLBLOG_DOMAIN_NAME
+    echo '    add_header Strict-Transport-Security "max-age=0;";' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # rewrite to front controller as default rule' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location / {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        rewrite ^/(.*) /index.php?q=$uri&$args last;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo "    # make sure webfinger and other well known services aren't blocked" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # by denying dot files and rewrite request to the front controller' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location ^~ /.well-known/ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        allow all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # statically serve these file types when possible' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # otherwise fall back to front controller' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # allow browser to cache them' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # added .htm for advanced source code editor library' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location ~* \.(jpg|jpeg|gif|png|ico|css|js|htm|html|ttf|woff|svg)$ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        expires 30d;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        try_files $uri /index.php?q=$uri&$args;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # block these file types' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location ~* \.(tpl|md|tgz|log|out)$ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        deny all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # or a unix socket' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location ~* \.php$ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        # Zero-day exploit defense.' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        # http://forum.nginx.org/read.php?2,88845,page=3' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo "        # Won't work properly (404 error) if the file is not stored on this" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo "        # server, which is entirely possible with php-fpm/php-fcgi." >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo "        # Comment the 'try_files' line out if you set up php-fpm/php-fcgi on" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo "        # another machine. And then cross your fingers that you won't get hacked." >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        try_files $uri $uri/ /index.php;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        fastcgi_split_path_info ^(.+\.php)(/.+)$;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        # With php5-cgi alone:' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        # fastcgi_pass 127.0.0.1:9000;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        # With php5-fpm:' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        fastcgi_pass unix:/var/run/php5-fpm.sock;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        include fastcgi_params;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        fastcgi_index index.php;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    # deny access to all dot files' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location ~ /\. {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        deny all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    #deny access to store' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location ~ /store {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '        deny all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location ~ /(data|conf|bin|inc)/ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '      deny all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    location ~ /\.ht {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '      deny  all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '}' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+}
 
-    # for the avatar changing command
-    apt-get -y install imagemagick
-
-    if [ ! -d /var/www/$FULLBLOG_DOMAIN_NAME ]; then
-	mkdir /var/www/$FULLBLOG_DOMAIN_NAME
-    fi
-
-    cd /var/www/$FULLBLOG_DOMAIN_NAME
-    git_clone $FULLBLOG_REPO htdocs
-    cd htdocs
-    git checkout $FULLBLOG_COMMIT -b $FULLBLOG_COMMIT
-    if ! grep -q "Blog commit" $COMPLETION_FILE; then
-	echo "Blog commit:$FULLBLOG_COMMIT" >> $COMPLETION_FILE
-    else
-	sed -i "s/Blog commit.*/Blog commit:$FULLBLOG_COMMIT/g" $COMPLETION_FILE
-    fi
-    cd /var/www/$FULLBLOG_DOMAIN_NAME
-
-    chown -R www-data:www-data /var/www/$FULLBLOG_DOMAIN_NAME/htdocs
-
-    if [[ $ONION_ONLY == "no" ]]; then
-	function_check nginx_http_redirect
-	nginx_http_redirect $FULLBLOG_DOMAIN_NAME
-	echo 'server {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    listen 443 ssl;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo "    root /var/www/$FULLBLOG_DOMAIN_NAME/htdocs;" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo "    server_name $FULLBLOG_DOMAIN_NAME;" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    access_log off;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo "    error_log /var/log/nginx/${FULLBLOG_DOMAIN_NAME}_error_ssl.log $WEBSERVER_LOG_LEVEL;" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    index index.php;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    charset utf-8;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    proxy_read_timeout 86400s;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	function_check nginx_limits
-	nginx_limits $FULLBLOG_DOMAIN_NAME
-	function_check nginx_ssl
-	nginx_ssl $FULLBLOG_DOMAIN_NAME
-	function_check nginx_disable_sniffing
-	nginx_disable_sniffing $FULLBLOG_DOMAIN_NAME
-	echo '    add_header Strict-Transport-Security "max-age=0;";' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # rewrite to front controller as default rule' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location / {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        rewrite ^/(.*) /index.php?q=$uri&$args last;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo "    # make sure webfinger and other well known services aren't blocked" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # by denying dot files and rewrite request to the front controller' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location ^~ /.well-known/ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        allow all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # statically serve these file types when possible' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # otherwise fall back to front controller' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # allow browser to cache them' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # added .htm for advanced source code editor library' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location ~* \.(jpg|jpeg|gif|png|ico|css|js|htm|html|ttf|woff|svg)$ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        expires 30d;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        try_files $uri /index.php?q=$uri&$args;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # block these file types' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location ~* \.(tpl|md|tgz|log|out)$ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        deny all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # or a unix socket' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location ~* \.php$ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        # Zero-day exploit defense.' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        # http://forum.nginx.org/read.php?2,88845,page=3' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo "        # Won't work properly (404 error) if the file is not stored on this" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo "        # server, which is entirely possible with php-fpm/php-fcgi." >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo "        # Comment the 'try_files' line out if you set up php-fpm/php-fcgi on" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo "        # another machine. And then cross your fingers that you won't get hacked." >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        try_files $uri $uri/ /index.php;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        fastcgi_split_path_info ^(.+\.php)(/.+)$;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        # With php5-cgi alone:' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        # fastcgi_pass 127.0.0.1:9000;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        # With php5-fpm:' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        fastcgi_pass unix:/var/run/php5-fpm.sock;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        include fastcgi_params;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        fastcgi_index index.php;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    # deny access to all dot files' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location ~ /\. {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        deny all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    #deny access to store' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location ~ /store {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '        deny all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location ~ /(data|conf|bin|inc)/ {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '      deny all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    location ~ /\.ht {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '      deny  all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '}' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-	echo '' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-    else
-	echo -n '' > /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
-    fi
+function install_blog_website_onion {
     echo 'server {' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
     echo "    listen 127.0.0.1:${FULLBLOG_ONION_PORT} default_server;" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
     echo "    root /var/www/$FULLBLOG_DOMAIN_NAME/htdocs;" >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
@@ -450,6 +429,48 @@ function install_blog {
     echo '      deny  all;' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
     echo '    }' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
     echo '}' >> /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+}
+
+function install_blog_from_repo {
+    if [ ! -d /var/www/$FULLBLOG_DOMAIN_NAME ]; then
+	mkdir /var/www/$FULLBLOG_DOMAIN_NAME
+    fi
+
+    cd /var/www/$FULLBLOG_DOMAIN_NAME
+    git_clone $FULLBLOG_REPO htdocs
+    cd htdocs
+    git checkout $FULLBLOG_COMMIT -b $FULLBLOG_COMMIT
+    if ! grep -q "Blog commit" $COMPLETION_FILE; then
+	echo "Blog commit:$FULLBLOG_COMMIT" >> $COMPLETION_FILE
+    else
+	sed -i "s/Blog commit.*/Blog commit:$FULLBLOG_COMMIT/g" $COMPLETION_FILE
+    fi
+}
+
+function install_blog {
+    if [ ! $FULLBLOG_DOMAIN_NAME ]; then
+	echo $'The blog domain name was not specified'
+	exit 5062
+    fi
+
+    if grep -Fxq "install_blog" $COMPLETION_FILE; then
+	return
+    fi
+
+    # for the avatar changing command
+    apt-get -y install imagemagick
+
+    function_check install_blog_from_repo
+    install_blog_from_repo
+
+    if [[ $ONION_ONLY == "no" ]]; then
+	function_check install_blog_website
+	install_blog_website
+    else
+	echo -n '' > /etc/nginx/sites-available/$FULLBLOG_DOMAIN_NAME
+    fi
+    function_check install_blog_website_onion
+    install_blog_website_onion
 
     function_check create_site_certificate
     create_site_certificate $FULLBLOG_DOMAIN_NAME 'yes'
@@ -457,22 +478,21 @@ function install_blog {
     function_check configure_php
     configure_php
 
-    # blog settings
-    cp /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini.example /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
-    sed -i "s|site.url.*|site.url = '/'|g" /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
-    sed -i "s|blog.title.*|blog.title = '$MY_BLOG_TITLE'|g" /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
-    sed -i "s|blog.tagline.*|blog.tagline = '$MY_BLOG_SUBTITLE'|g" /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
-    sed -i 's|timezone.*|timezone = "Europe/London"|g' /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
-    sed -i "s|Your name|$MY_NAME|g" /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/config.ini
+    function_check install_blog_settings
+    install_blog_settings
 
+    function_check install_blog_social_networks
     install_blog_social_networks
 
+    function_check install_blog_user
     install_blog_user
+
+    chown -R www-data:www-data /var/www/$FULLBLOG_DOMAIN_NAME/htdocs
+
+    FULLBLOG_ONION_HOSTNAME=$(add_onion_service blog 80 ${FULLBLOG_ONION_PORT})
 
     function_check nginx_ensite
     nginx_ensite $FULLBLOG_DOMAIN_NAME
-
-    FULLBLOG_ONION_HOSTNAME=$(add_onion_service blog 80 ${FULLBLOG_ONION_PORT})
 
     systemctl restart php5-fpm
     systemctl restart nginx
