Move remote mediagoblin backup to app script

diff --git a/src/freedombone-app-hubzilla b/src/freedombone-app-hubzilla
--- a/src/freedombone-app-hubzilla
+++ b/src/freedombone-app-hubzilla
@@ -41,7 +41,7 @@ HUBZILLA_COMMIT='2d79e75788aa71664a379c4cea0b6bfe3ab87ad0'
 HUBZILLA_ADDONS_COMMIT='67b40c7a40f328a93ee030eb15e9e1261f3cba64'
 
 function reconfigure_hubzilla {
-    echo -n ''
+	echo -n ''
 }
 
 function upgrade_hubzilla {
@@ -105,7 +105,20 @@ function restore_local_hubzilla {
 }
 
 function backup_remote_hubzilla {
-	echo -n ''
+	if grep -q "Hubzilla domain" $COMPLETION_FILE; then
+		HUBZILLA_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Hubzilla domain" | awk -F ':' '{print $2}')
+		temp_backup_dir=/var/www/${HUBZILLA_DOMAIN_NAME}/htdocs
+		if [ -d $temp_backup_dir ]; then
+			suspend_site ${HUBZILLA_DOMAIN_NAME}
+			backup_database_to_friend hubzilla
+			echo "Backing up Hubzilla installation"
+			backup_directory_to_friend $temp_backup_dir hubzilla
+			restart_site
+		else
+			echo $"Hubzilla domain specified but not found in /var/www/${HUBZILLA_DOMAIN_NAME}"
+			exit 2578
+		fi
+	fi
 }
 
 function restore_remote_hubzilla {
