functions to remove batman

diff --git a/src/freedombone-app-batman b/src/freedombone-app-batman
--- a/src/freedombone-app-batman
+++ b/src/freedombone-app-batman
@@ -45,6 +45,20 @@ function configure_firewall_for_batman {
 	echo 'configure_firewall_for_batman' >> $COMPLETION_FILE
 }
 
+function remove_batman {
+	if ! grep -Fxq "mesh_batman" $COMPLETION_FILE; then
+		return
+	fi
+
+	${PROJECT_NAME}-mesh-install -f batman --remove yes
+	if [ ! "$?" = "0" ]; then
+		echo $'Failed to remove batman'
+		exit 79353
+	fi
+	sed -i '/mesh_batman/d' $COMPLETION_FILE
+	sed -i '/configure_firewall_for_batman/d' $COMPLETION_FILE
+}
+
 function mesh_batman {
 	if grep -Fxq "mesh_batman" $COMPLETION_FILE; then
 		return
