Error if getting mariadb password fails

diff --git a/src/freedombone-utils-database b/src/freedombone-utils-database
--- a/src/freedombone-utils-database
+++ b/src/freedombone-utils-database
@@ -138,6 +138,10 @@ function get_mariadb_password {
         fi
     fi
     MARIADB_PASSWORD=$(${PROJECT_NAME}-pass -u root -a mariadb)
+    if [[ "$MARIADB_PASSWORD" == *'failed'* ]]; then
+        echo $'Could not obtain mariadb password'
+        exit 835225
+    fi
 }
 
 function install_mariadb {
