Check that the gogs database template exists

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -6553,6 +6553,10 @@ function install_gogs {
 	fi
 
 	create_database gogs "$GOGS_ADMIN_PASSWORD"
+	if [ ! -f $GOPATH/src/github.com/gogits/gogs/scripts/mysql.sql ]; then
+		echo $'MySql template for Gogs was not found'
+		exit 72528
+	fi
 	mysql -u root --password="$MARIADB_PASSWORD" -D gogs < $GOPATH/src/github.com/gogits/gogs/scripts/mysql.sql
 
 	chmod 600 $GOPATH/src/github.com/gogits/gogs/custom/conf/app.ini
