Tidying

diff --git a/src/freedombone-utils-turn b/src/freedombone-utils-turn
--- a/src/freedombone-utils-turn
+++ b/src/freedombone-utils-turn
@@ -36,10 +36,10 @@ function generate_turn_key {
     local turnkey="${1}"
     local filepath="${2}"
 
-    echo "lt-cred-mech" > "${filepath}"
-    echo "use-auth-secret" >> "${filepath}"
-    echo "static-auth-secret=${turnkey}" >> "${filepath}"
-    echo "realm=turn.${DEFAULT_DOMAIN_NAME}" >> "${filepath}"
+    { echo "lt-cred-mech";
+      echo "use-auth-secret";
+      echo "static-auth-secret=${turnkey}";
+      echo "realm=turn.${DEFAULT_DOMAIN_NAME}"; } > "${filepath}"
     if [[ $ONION_ONLY == 'no' ]]; then
         echo "cert=$MATRIX_DATA_DIR/${DEFAULT_DOMAIN_NAME}.tls.crt" >> "${filepath}"
         echo "pkey=$MATRIX_DATA_DIR/${DEFAULT_DOMAIN_NAME}.tls.key" >> "${filepath}"
@@ -58,7 +58,7 @@ function remove_turn {
 
     apt-get -y remove coturn
     rm -rf /var/lib/turn
-    sed -i "/# TURN Server/,/# End of TURN Server/d" /etc/nginx/sites-available/${DEFAULT_DOMAIN_NAME}
+    sed -i "/# TURN Server/,/# End of TURN Server/d" "/etc/nginx/sites-available/${DEFAULT_DOMAIN_NAME}"
     remove_onion_service turn ${TURN_ONION_PORT}
     rm /etc/avahi/services/turn.service
     systemctl restart nginx
@@ -69,62 +69,62 @@ function install_turn {
 
     # append the matrix server to the web site config
     turn_nginx_site=/etc/nginx/sites-available/$DEFAULT_DOMAIN_NAME
-    if ! grep -q '# End of TURN Server' $turn_nginx_site; then
-        if [[ $ONION_ONLY == "no" ]]; then
-            echo '# TURN Server' >> $turn_nginx_site
-            echo 'server {' >> $turn_nginx_site
-            echo "  listen ${TURN_HTTP_PORT} ssl;" >> $turn_nginx_site
-            echo "  listen [::]:${TURN_HTTP_PORT} ssl;" >> $turn_nginx_site
-            echo "  server_name ${DEFAULT_DOMAIN_NAME};" >> $turn_nginx_site
-            echo '' >> $turn_nginx_site
-            echo '  # Security' >> $turn_nginx_site
+    if ! grep -q '# End of TURN Server' "$turn_nginx_site"; then
+        if [[ "$ONION_ONLY" == "no" ]]; then
+            { echo '# TURN Server';
+              echo 'server {';
+              echo "  listen ${TURN_HTTP_PORT} ssl;";
+              echo "  listen [::]:${TURN_HTTP_PORT} ssl;";
+              echo "  server_name ${DEFAULT_DOMAIN_NAME};";
+              echo '';
+              echo '  # Security'; } >> "$turn_nginx_site"
             function_check nginx_ssl
-            nginx_ssl ${DEFAULT_DOMAIN_NAME}
+            nginx_ssl "${DEFAULT_DOMAIN_NAME}"
 
             function_check nginx_disable_sniffing
-            nginx_disable_sniffing ${DEFAULT_DOMAIN_NAME}
+            nginx_disable_sniffing "${DEFAULT_DOMAIN_NAME}"
 
-            echo '  add_header Strict-Transport-Security max-age=15768000;' >> $turn_nginx_site
-            echo '' >> $turn_nginx_site
-            echo '  # Logs' >> $turn_nginx_site
-            echo '  access_log /dev/null;' >> $turn_nginx_site
-            echo '  error_log /dev/null;' >> $turn_nginx_site
-            echo '' >> $turn_nginx_site
-            echo '  # Index' >> $turn_nginx_site
-            echo '  index index.html;' >> $turn_nginx_site
-            echo '' >> $turn_nginx_site
-            echo '  # Location' >> $turn_nginx_site
-            echo '  location / {' >> $turn_nginx_site
+            { echo '  add_header Strict-Transport-Security max-age=15768000;';
+              echo '';
+              echo '  # Logs';
+              echo '  access_log /dev/null;';
+              echo '  error_log /dev/null;';
+              echo '';
+              echo '  # Index';
+              echo '  index index.html;';
+              echo '';
+              echo '  # Location';
+              echo '  location / {'; } >> "$turn_nginx_site"
             function_check nginx_limits
-            nginx_limits ${DEFAULT_DOMAIN_NAME} '15m'
-            echo "      proxy_pass http://localhost:${TURN_PORT};" >> $turn_nginx_site
-            echo '      proxy_set_header X-Forwarded-For $remote_addr;' >> $turn_nginx_site
-            echo '  }' >> $turn_nginx_site
-            echo '}' >> $turn_nginx_site
-            echo '' >> $turn_nginx_site
+            nginx_limits "${DEFAULT_DOMAIN_NAME}" '15m'
+            { echo "      proxy_pass http://localhost:${TURN_PORT};";
+              echo "      proxy_set_header X-Forwarded-For \$remote_addr;";
+              echo '  }';
+              echo '}';
+              echo ''; } >> "$turn_nginx_site"
         else
-            echo '# TURN Server' >> $turn_nginx_site
+            echo '# TURN Server' >> "$turn_nginx_site"
         fi
-        echo 'server {' >> $turn_nginx_site
-        echo "    listen 127.0.0.1:$TURN_ONION_PORT default_server;" >> $turn_nginx_site
-        echo "    server_name $DEFAULT_DOMAIN_NAME;" >> $turn_nginx_site
-        echo '' >> $turn_nginx_site
+        { echo 'server {';
+          echo "    listen 127.0.0.1:$TURN_ONION_PORT default_server;";
+          echo "    server_name $DEFAULT_DOMAIN_NAME;";
+          echo ''; } >> "$turn_nginx_site"
         function_check nginx_disable_sniffing
-        nginx_disable_sniffing $DEFAULT_DOMAIN_NAME
-        echo '' >> $turn_nginx_site
-        echo '  # Logs' >> $turn_nginx_site
-        echo '  access_log /dev/null;' >> $turn_nginx_site
-        echo '  error_log /dev/null;' >> $turn_nginx_site
-        echo '' >> $turn_nginx_site
-        echo '  # Location' >> $turn_nginx_site
-        echo '  location / {' >> $turn_nginx_site
+        nginx_disable_sniffing "$DEFAULT_DOMAIN_NAME"
+        { echo '';
+          echo '  # Logs';
+          echo '  access_log /dev/null;';
+          echo '  error_log /dev/null;';
+          echo '';
+          echo '  # Location';
+          echo '  location / {'; } >> "$turn_nginx_site"
         function_check nginx_limits
-        nginx_limits $DEFAULT_DOMAIN_NAME '15m'
-        echo "      proxy_pass http://localhost:${TURN_PORT};" >> $turn_nginx_site
-        echo '      proxy_set_header X-Forwarded-For $remote_addr;' >> $turn_nginx_site
-        echo '  }' >> $turn_nginx_site
-        echo '}' >> $turn_nginx_site
-        echo '# End of TURN Server' >> $turn_nginx_site
+        nginx_limits "$DEFAULT_DOMAIN_NAME" '15m'
+        { echo "      proxy_pass http://localhost:${TURN_PORT};";
+          echo "      proxy_set_header X-Forwarded-For \$remote_addr;";
+          echo '  }';
+          echo '}';
+          echo '# End of TURN Server'; } >> "$turn_nginx_site"
     fi
 
     export DEBIAN_FRONTEND=noninteractive
@@ -151,26 +151,26 @@ function install_turn {
     fi
 
     turnkey="$(create_password 30)"
-    generate_turn_key $turnkey /var/lib/turn/turnserver.conf
+    generate_turn_key "$turnkey" /var/lib/turn/turnserver.conf
 
     chmod -R 700 /var/lib/turn/turnserver.conf
     chown -R matrix:matrix /var/lib/turn
 
-    echo '[Unit]' > /etc/systemd/system/turn.service
-    echo 'Description=TURN server' >> /etc/systemd/system/turn.service
-    echo 'After=network.target nginx.target' >> /etc/systemd/system/turn.service
-    echo '' >> /etc/systemd/system/turn.service
-    echo '[Service]' >> /etc/systemd/system/turn.service
-    echo 'Type=simple' >> /etc/systemd/system/turn.service
-    echo 'User=matrix' >> /etc/systemd/system/turn.service
-    echo "WorkingDirectory=/var/lib/turn" >> /etc/systemd/system/turn.service
-    echo "ExecStart=/usr/bin/turnserver -c /var/lib/turn/turnserver.conf --pidfile /var/lib/matrix/homeserver.pid" >> /etc/systemd/system/turn.service
-    echo "Environment=REPORT_STATS=\"no\"" >> /etc/systemd/system/turn.service
-    echo 'Restart=always' >> /etc/systemd/system/turn.service
-    echo 'RestartSec=10' >> /etc/systemd/system/turn.service
-    echo '' >> /etc/systemd/system/turn.service
-    echo '[Install]' >> /etc/systemd/system/turn.service
-    echo 'WantedBy=multi-user.target' >> /etc/systemd/system/turn.service
+    { echo '[Unit]';
+      echo 'Description=TURN server';
+      echo 'After=network.target nginx.target';
+      echo '';
+      echo '[Service]';
+      echo 'Type=simple';
+      echo 'User=matrix';
+      echo "WorkingDirectory=/var/lib/turn";
+      echo "ExecStart=/usr/bin/turnserver -c /var/lib/turn/turnserver.conf --pidfile /var/lib/matrix/homeserver.pid";
+      echo "Environment=REPORT_STATS=\"no\"";
+      echo 'Restart=always';
+      echo 'RestartSec=10';
+      echo '';
+      echo '[Install]';
+      echo 'WantedBy=multi-user.target'; } > /etc/systemd/system/turn.service
     systemctl enable turn
     systemctl daemon-reload
     systemctl start turn
@@ -178,21 +178,22 @@ function install_turn {
     firewall_add turn ${TURN_PORT}
     firewall_add turn-http ${TURN_HTTP_PORT}
 
-    TURN_ONION_HOSTNAME=$(add_onion_service turn ${TURN_PORT} ${TURN_ONION_PORT})
+    #TURN_ONION_HOSTNAME=$(add_onion_service turn ${TURN_PORT} ${TURN_ONION_PORT})
+    add_onion_service turn ${TURN_PORT} ${TURN_ONION_PORT}
 
-    echo '<?xml version="1.0" standalone="no"?><!--*-nxml-*-->' > /etc/avahi/services/turn.service
-    echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">' >> /etc/avahi/services/turn.service
-    echo '<service-group>' >> /etc/avahi/services/turn.service
-    echo '  <name replace-wildcards="yes">%h TURN</name>' >> /etc/avahi/services/turn.service
-    echo '  <service>' >> /etc/avahi/services/turn.service
-    echo '    <type>_turn._tcp</type>' >> /etc/avahi/services/turn.service
-    echo "    <port>$TURN_PORT</port>" >> /etc/avahi/services/turn.service
-    echo '  </service>' >> /etc/avahi/services/turn.service
-    echo '  <service>' >> /etc/avahi/services/turn.service
-    echo '    <type>_turn._udp</type>' >> /etc/avahi/services/turn.service
-    echo "    <port>$TURN_PORT</port>" >> /etc/avahi/services/turn.service
-    echo '  </service>' >> /etc/avahi/services/turn.service
-    echo '</service-group>' >> /etc/avahi/services/turn.service
+    { echo '<?xml version="1.0" standalone="no"?><!--*-nxml-*-->';
+      echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">';
+      echo '<service-group>';
+      echo '  <name replace-wildcards="yes">%h TURN</name>';
+      echo '  <service>';
+      echo '    <type>_turn._tcp</type>';
+      echo "    <port>$TURN_PORT</port>";
+      echo '  </service>';
+      echo '  <service>';
+      echo '    <type>_turn._udp</type>';
+      echo "    <port>$TURN_PORT</port>";
+      echo '  </service>';
+      echo '</service-group>'; } > /etc/avahi/services/turn.service
 
     systemctl restart avahi-daemon
     systemctl restart nginx
