taller dialog

diff --git a/src/freedombone-app-xmpp b/src/freedombone-app-xmpp
--- a/src/freedombone-app-xmpp
+++ b/src/freedombone-app-xmpp
@@ -884,10 +884,18 @@ function install_xmpp_main {
     fi
 
     # create a certificate
-    if [[ "$(cert_exists ${DEFAULT_DOMAIN_NAME} pem)" == "0" ]]; then
-        if [[ "$(cert_exists xmpp)" == "0" ]]; then
+    if [ ! -f /etc/ssl/certs/${DEFAULT_DOMAIN_NAME}.pem ]; then
+        if [ ! -f /etc/ssl/certs/xmpp.crt ]; then
             ${PROJECT_NAME}-addcert -h xmpp --dhkey ${DH_KEYLENGTH}
             check_certificates xmpp
+            if [ ! -f /etc/ssl/certs/xmpp.crt ]; then
+                echo $'Failed to create xmpp certificate'
+                exit 72352
+            fi
+            if [ ! -f /etc/ssl/private/xmpp.key ]; then
+                echo $'Failed to create xmpp private certificate'
+                exit 36829
+            fi
         fi
     fi
 
