static analysis of freedombone commands

diff --git a/src/freedombone-tests b/src/freedombone-tests
--- a/src/freedombone-tests
+++ b/src/freedombone-tests
@@ -88,7 +88,18 @@ function test_static_analysis {
         if ! shellcheck --exclude SC2034,SC1090 "$filename"; then
             echo ''
             echo $"${filename} failed static analysis"
-            exit 24687242
+            exit 3857395935
+        fi
+    done
+
+    FILES="/usr/local/bin/${PROJECT_NAME}-*"
+
+    for filename in $FILES
+    do
+        if ! shellcheck --exclude SC2034,SC1090 "$filename"; then
+            echo ''
+            echo $"${filename} failed static analysis"
+            exit 784243468435
         fi
     done
 }
