Move remote gnusocial backup to app script

diff --git a/src/freedombone-utils-backup b/src/freedombone-utils-backup
--- a/src/freedombone-utils-backup
+++ b/src/freedombone-utils-backup
@@ -281,4 +281,86 @@ function set_user_permissions {
 	done
 }
 
+function backup_directory_to_friend {
+	BACKUP_KEY_EXISTS=$(gpg --list-keys "$ADMIN_NAME (backup key)")
+	if [ ! "$?" = "0" ]; then
+		echo $"Backup key could not be found"
+		function_check restart_site
+		restart_site
+		exit 43382
+	fi
+	ADMIN_BACKUP_KEY_ID=$(gpg --list-keys "$ADMIN_NAME (backup key)" | grep 'pub ' | awk -F ' ' '{print $2}' | awk -F '/' '{print $2}')
+	if [ ! -d $SERVER_DIRECTORY/backup/${2} ]; then
+		mkdir -p $SERVER_DIRECTORY/backup/${2}
+	fi
+	obnam force-lock -r $SERVER_DIRECTORY/backup/${2} --encrypt-with ${ADMIN_BACKUP_KEY_ID} ${1}
+	obnam backup -r $SERVER_DIRECTORY/backup/${2} --encrypt-with ${ADMIN_BACKUP_KEY_ID} ${1}
+	if [[ $ENABLE_VERIFICATION == "yes" ]]; then
+		obnam verify -r $SERVER_DIRECTORY/backup/${2} --encrypt-with ${ADMIN_BACKUP_KEY_ID} ${1}
+		if [ ! "$?" = "0" ]; then
+			if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+				shred -zu /root/temp${2}/*
+				rm -rf /root/temp${2}
+			fi
+			# Send a warning email
+			echo "Unable to verify ${2}" | mail -s "${PROJECT_NAME} backup to friends" ${ADMIN_EMAIL_ADDRESS}
+			function_check restart_site
+			restart_site
+			exit 953
+		fi
+	fi
+	obnam forget --keep=30d -r $SERVER_DIRECTORY/backup/${2} --encrypt-with ${ADMIN_BACKUP_KEY_ID}
+	if [ ! "$?" = "0" ]; then
+		if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+			shred -zu /root/temp${2}/*
+			rm -rf /root/temp${2}
+		fi
+		# Send a warning email
+		echo "Unable to backup ${2}" | mail -s "${PROJECT_NAME} backup to friends" ${ADMIN_EMAIL_ADDRESS}
+		function_check restart_site
+		restart_site
+		exit 853
+	fi
+	if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+		shred -zu /root/temp${2}/*
+		rm -rf /root/temp${2}
+	fi
+}
+
+function backup_database_remote {
+	if [ ${#DATABASE_PASSWORD} -lt 2 ]; then
+		echo $"No MariaDB password was given"
+		function_check restart_site
+		restart_site
+		exit 5783
+	fi
+	if [ ! -d $SERVER_DIRECTORY/backup/${1} ]; then
+		mkdir -p $SERVER_DIRECTORY/backup/${1}
+	fi
+	if [ ! -d $SERVER_DIRECTORY/backup/${1}data ]; then
+		mkdir -p $SERVER_DIRECTORY/backup/${1}data
+	fi
+	if [ ! -d /root/temp${1}data ]; then
+		mkdir -p /root/temp${1}data
+	fi
+	echo "Obtaining ${1} database backup"
+	mysqldump --password=$DATABASE_PASSWORD ${1} > /root/temp${1}data/${1}.sql
+	if [ ! -s /root/temp${1}data/${1}.sql ]; then
+		echo $"${1} database could not be saved"
+		shred -zu /root/temp${1}data/*
+		rm -rf /root/temp${1}data
+		# Send a warning email
+		echo $"Unable to export ${1} database" | mail -s $"${PROJECT_NAME} backup to friends" $ADMIN_EMAIL_ADDRESS
+		function_check restart_site
+		restart_site
+		exit 5738
+	fi
+}
+
+function backup_database_to_friend {
+	database_name=$1
+	backup_database_remote $database_name
+	backup_directory_to_friend /root/temp${database_name}data ${database_name}data
+}
+
 # NOTE: deliberately no exit 0
