cryptpad webserver configuration

diff --git a/src/freedombone-app-cryptpad b/src/freedombone-app-cryptpad
--- a/src/freedombone-app-cryptpad
+++ b/src/freedombone-app-cryptpad
@@ -110,6 +110,11 @@ function upgrade_cryptpad {
     chown -R cryptpad:cryptpad $CRYPTPAD_DIR
 
     systemctl start cryptpad
+
+    if ! grep "debug|kanban" /etc/nginx/sites-available/cryptpad; then
+        sed -i 's/location ~.*/location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media|profile|contacts|todo|filepicker|debug|kanban)$ {/g' /etc/nginx/sites-available/cryptpad
+        systemctl restart nginx
+    fi
 }
 
 function backup_local_cryptpad {
@@ -383,11 +388,14 @@ function mesh_install_cryptpad {
       echo '  add_header X-Content-Type-Options nosniff;';
       echo '  add_header X-Frame-Options SAMEORIGIN;';
       echo '';
-      echo "  if (\$uri = /pad/inner.html) {";
-      echo "    set \$scriptSrc \"'self' 'unsafe-eval' 'unsafe-inline'\";";
+      echo "  set \$unsafe 0;";
+      echo "  if (\$uri = \"/pad/inner.html\") { set \$unsafe 1; }";
+      echo "  if (\$host != sandbox.cryptpad.info) { set \$unsafe 0; }";
+      echo "  if (\$unsafe) {";
+      echo "    set \$scriptSrc \"'self' 'unsafe-eval' 'unsafe-inline' P${PEER_ID}.local\";";
       echo '  }';
       echo '';
-      echo '  location = /cryptpad_websocket {';
+      echo '  location ^~ /cryptpad_websocket {';
       echo "    proxy_pass http://[::]:$CRYPTPAD_PORT;";
       echo "    proxy_set_header X-Real-IP \$remote_addr;";
       echo "    proxy_set_header Host \$host;";
@@ -444,7 +452,7 @@ function mesh_install_cryptpad {
       echo "    try_files \$uri =404;";
       echo '  }';
       echo '';
-      echo '  location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media)$ {';
+      echo '  location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media|profile|contacts|todo|filepicker|debug|kanban)$ {';
       echo "    rewrite ^(.*)\$ \$1/ redirect;";
       echo '  }';
       echo '';
@@ -549,6 +557,7 @@ function install_cryptpad_main {
       echo "  root $CRYPTPAD_DIR;";
       echo '';
       echo '  index index.html;';
+      echo '  error_page 404 /customize.dist/404.html;';
       echo '';
       echo "  if (\$args ~ ver=) {";
       echo "      set \$cacheControl max-age=31536000;";
@@ -559,11 +568,15 @@ function install_cryptpad_main {
       echo '  add_header X-Content-Type-Options nosniff;';
       echo '  add_header X-Frame-Options SAMEORIGIN;';
       echo '';
-      echo "  if (\$uri = /pad/inner.html) {";
-      echo "    set \$scriptSrc \"'self' 'unsafe-eval' 'unsafe-inline'\";";
+
+      echo "  set \$unsafe 0;";
+      echo "  if (\$uri = \"/pad/inner.html\") { set \$unsafe 1; }";
+      echo "  if (\$host != sandbox.cryptpad.info) { set \$unsafe 0; }";
+      echo "  if (\$unsafe) {";
+      echo "    set \$scriptSrc \"'self' 'unsafe-eval' 'unsafe-inline' $CRYPTPAD_ONION_HOSTNAME\";";
       echo '  }';
       echo '';
-      echo '  location = /cryptpad_websocket {';
+      echo '  location ^~ /cryptpad_websocket {';
       echo "    proxy_pass http://localhost:$CRYPTPAD_PORT;";
       echo "    proxy_set_header X-Real-IP \$remote_addr;";
       echo "    proxy_set_header Host \$host;";
@@ -620,7 +633,7 @@ function install_cryptpad_main {
       echo "    try_files \$uri =404;";
       echo '  }';
       echo '';
-      echo '  location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media)$ {';
+      echo '  location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media|profile|contacts|todo|filepicker|debug|kanban)$ {';
       echo "    rewrite ^(.*)\$ \$1/ redirect;";
       echo '  }';
       echo '';
