Allow root user

diff --git a/src/freedombone-pass b/src/freedombone-pass
--- a/src/freedombone-pass
+++ b/src/freedombone-pass
@@ -146,8 +146,10 @@ if [ ! $CURR_USERNAME ]; then
 fi
 
 if [ ! -d /home/$CURR_USERNAME ]; then
-    echo $"Error: User $CURR_USERNAME does not exist"
-    exit 2
+    if [[ "$CURR_USERNAME" != "root" ]]; then
+        echo $"Error: User $CURR_USERNAME does not exist"
+        exit 2
+    fi
 fi
 
 if [ ${REMOVE_APP} ]; then
