Error if password can't be encrypted

diff --git a/src/freedombone-pass b/src/freedombone-pass
--- a/src/freedombone-pass
+++ b/src/freedombone-pass
@@ -119,6 +119,10 @@ function run_tests {
         exit 78352
     fi
     ${PROJECT_NAME}-pass -u root -a tests -p "$pass"
+    if [ ! "$?" = "0" ]; then
+        echo $'Unable to encrypt password'
+        exit 72725
+    fi
     returned_pass=$(${PROJECT_NAME}-pass -u root -a tests)
     if [[ "$pass" != "$returned_pass" ]]; then
         echo "pass     :${pass}:"
