More checking for owncloud install

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -39,10 +39,6 @@ FREEDOMBONE_WEBSITE="http://freedombone.uk.to"
 # Contact details
 FREEDOMBONE_BITMESSAGE="BM-2cWuhmBvVdfrHhLoZTdspCkKeiTorUesSL"
 
-DOMAIN_NAME=
-MY_USERNAME=
-SYSTEM_TYPE=
-
 # Are we installing on a Beaglebone Black (BBB) or some other system?
 INSTALLING_ON_BBB="no"
 
@@ -60,6 +56,10 @@ VARIANT_NONMAILBOX="nonmailbox"
 VARIANT_SOCIAL="social"
 VARIANT_MEDIA="media"
 VARIANT_TOR_DONGLE="tordongle"
+
+DOMAIN_NAME=
+MY_USERNAME=
+SYSTEM_TYPE=$VARIANT_FULL
 
 # An optional configuration file which overrides some of these variables
 CONFIGURATION_FILE="freedombone.cfg"
@@ -6168,7 +6168,7 @@ function install_owncloud_music_app {
       return
   fi
   if ! grep -Fxq "install_owncloud" $COMPLETION_FILE; then
-	  echo 'Tried to install the Owncloud music app, but Owncloud installation was not found'
+      echo 'Tried to install the Owncloud music app, but Owncloud installation was not found'
       exit 9823
   fi
 
@@ -6253,11 +6253,13 @@ function install_owncloud {
       OWNCLOUD_DOMAIN_NAME=$DOMAIN_NAME
   fi
   if [ ! $OWNCLOUD_DOMAIN_NAME ]; then
-      return
+      echo 'No Owncloud domain name was specified'
+      exit 3095
   fi
-  if ! [[ $SYSTEM_TYPE == "$VARIANT_CLOUD" ]]; then
-      if [ $SYSTEM_TYPE ]; then
-          return
+  if [[ $SYSTEM_TYPE != "$VARIANT_CLOUD" ]]; then
+      if [[ $SYSTEM_TYPE != "$VARIANT_FULL" ]]; then
+          echo "Owncloud install did not recognise the system type $SYSTEM_TYPE"
+          exit 6746
       fi
   fi
   apt-get -y --force-yes install owncloud
