Option for interactive install function

diff --git a/src/freedombone-utils-depends b/src/freedombone-utils-depends
--- a/src/freedombone-utils-depends
+++ b/src/freedombone-utils-depends
@@ -30,10 +30,17 @@
 
 function function_check {
     if [ ! "$(type ${1} 2>/dev/null)" ]; then
-		echo $"Dependency error: The function ${1} has not been defined"
-		exit 72528
+        echo $"Dependency error: The function ${1} has not been defined"
+        exit 72528
     fi
 }
 
+function function_exists {
+    if [ ! "$(type ${1} 2>/dev/null)" ]; then
+        echo "0"
+    else
+        echo "1"
+    fi
+}
 
 # NOTE: deliberately there is no "exit 0"
