Remove directory if it already exists

diff --git a/src/freedombone-app-bludit b/src/freedombone-app-bludit
--- a/src/freedombone-app-bludit
+++ b/src/freedombone-app-bludit
@@ -217,23 +217,22 @@ function install_bludit {
     apt-get -yq install php-gettext php-curl php-gd php-mysql git curl
     apt-get -yq install memcached php-memcached php-intl exiftool libfcgi0ldbl
 
-    if [ ! -d "/var/www/$BLUDIT_DOMAIN_NAME" ]; then
-        mkdir "/var/www/$BLUDIT_DOMAIN_NAME"
+    if [ -d "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" ]; then
+        rm -rf "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
     fi
-    if [ ! -d "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" ]; then
-        if [ -d /repos/bludit ]; then
-            mkdir "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
-            cp -r -p /repos/bludit/. "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
-            cd "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" || exit 324687356
-            git pull
-        else
-            git_clone $BLUDIT_REPO "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
-        fi
 
-        if [ ! -d "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" ]; then
-            echo $'Unable to clone bludit repo'
-            exit 87525
-        fi
+    if [ -d /repos/bludit ]; then
+        mkdir "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
+        cp -r -p /repos/bludit/. "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
+        cd "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" || exit 324687356
+        git pull
+    else
+        git_clone $BLUDIT_REPO "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
+    fi
+
+    if [ ! -d "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" ]; then
+        echo $'Unable to clone bludit repo'
+        exit 87525
     fi
 
     cd "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" || exit 36587356
