More pleroma checks

diff --git a/src/freedombone-app-pleroma b/src/freedombone-app-pleroma
--- a/src/freedombone-app-pleroma
+++ b/src/freedombone-app-pleroma
@@ -223,8 +223,16 @@ function pleroma_create_database {
         write_config_param "PLEROMA_SECRET_KEY" "$PLEROMA_SECRET_KEY"
     fi
 
-    pleroma_secret=config/dev.secret.exs
-    cp config/dev.exs $pleroma_secret
+    if [ ! -d $PLEROMA_DIR/config ]; then
+        echo $"Missing directory $PLEROMA_DIR/config"
+        exit 7835393
+    fi
+    pleroma_secret=$PLEROMA_DIR/config/dev.secret.exs
+    if [ ! -f $PLEROMA_DIR/config/dev.exs ]; then
+        echo $"Did not find $PLEROMA_DIR/config/dev.exs"
+        exit 78923528
+    fi
+    cp $PLEROMA_DIR/config/dev.exs $pleroma_secret
     sed -i "s|username:.*|username: \"pleroma\",|g" $pleroma_secret
     sed -i "s|password:.*|password: \"$PLEROMA_ADMIN_PASSWORD\",|g" $pleroma_secret
     sed -i "s|database:.*|database: \"pleroma\",|g" $pleroma_secret
@@ -246,7 +254,7 @@ function pleroma_create_database {
     fi
 
     cd $PLEROMA_DIR
-    chown -R pleroma:pleroma *
+    chown -R pleroma:pleroma $PLEROMA_DIR/*
     sudo -u pleroma mix local.rebar --force
     if [ ! "$?" = "0" ]; then
         run_system_query_postgresql "ALTER USER pleroma NOSUPERUSER;"
