Add xmpp address to email headers

diff --git a/src/freedombone-adduser b/src/freedombone-adduser
--- a/src/freedombone-adduser
+++ b/src/freedombone-adduser
@@ -75,30 +75,30 @@ fi
 
 if [ "$SSH_PUBLIC_KEY" ]; then
     if [ ${#SSH_PUBLIC_KEY} -gt 5 ]; then
-	if [ -f "$SSH_PUBLIC_KEY" ]; then
-	    mkdir /home/$MY_USERNAME/.ssh
-	    cp $SSH_PUBLIC_KEY /home/$MY_USERNAME/.ssh/authorized_keys
-	    chown -R $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.ssh
-	    echo $'ssh public key installed'
-	else
-	    if [[ "$SSH_PUBLIC_KEY" == "ssh-"* ]]; then
-		mkdir /home/$MY_USERNAME/.ssh
-		echo "$SSH_PUBLIC_KEY" > /home/$MY_USERNAME/.ssh/authorized_keys
-		chown -R $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.ssh
-		echo $'ssh public key installed'
-	    else
-		echo $'The second parameter does not look like an ssh key'
-		exit 5
-	    fi
-	fi
+        if [ -f "$SSH_PUBLIC_KEY" ]; then
+            mkdir /home/$MY_USERNAME/.ssh
+            cp $SSH_PUBLIC_KEY /home/$MY_USERNAME/.ssh/authorized_keys
+            chown -R $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.ssh
+            echo $'ssh public key installed'
+        else
+            if [[ "$SSH_PUBLIC_KEY" == "ssh-"* ]]; then
+                mkdir /home/$MY_USERNAME/.ssh
+                echo "$SSH_PUBLIC_KEY" > /home/$MY_USERNAME/.ssh/authorized_keys
+                chown -R $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.ssh
+                echo $'ssh public key installed'
+            else
+                echo $'The second parameter does not look like an ssh key'
+                exit 5
+            fi
+        fi
     fi
 fi
 
 if [ -d /home/$MY_USERNAME/Maildir ]; then
     if grep -q "set from=" /home/$MY_USERNAME/.muttrc; then
-	sed -i "s|set from=.*|set from='$MY_USERNAME <$MY_USERNAME@$HOSTNAME>'|g" /home/$MY_USERNAME/.muttrc
+        sed -i "s|set from=.*|set from='$MY_USERNAME <$MY_USERNAME@$HOSTNAME>'|g" /home/$MY_USERNAME/.muttrc
     else
-	echo "set from='$MY_USERNAME <$MY_USERNAME@$HOSTNAME>'" >> /home/$MY_USERNAME/.muttrc
+        echo "set from='$MY_USERNAME <$MY_USERNAME@$HOSTNAME>'" >> /home/$MY_USERNAME/.muttrc
     fi
 
     USERN='$USER@'
@@ -154,17 +154,17 @@ monkeysphere-authentication update-users
 if [ -f /home/$MY_USERNAME/.muttrc ]; then
     # encrypt outgoing mail to the "sent" folder
     if ! grep -q "pgp_encrypt_only_command" /home/$MY_USERNAME/.muttrc; then
-	echo '' >> /home/$MY_USERNAME/.muttrc
-	echo $'# Encrypt items in the Sent folder' >> /home/$MY_USERNAME/.muttrc
-	echo "set pgp_encrypt_only_command=\"/usr/lib/mutt/pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust --encrypt-to 0x$MY_GPG_PUBLIC_KEY_ID -- -r %r -- %f\"" >> /home/$MY_USERNAME/.muttrc
+        echo '' >> /home/$MY_USERNAME/.muttrc
+        echo $'# Encrypt items in the Sent folder' >> /home/$MY_USERNAME/.muttrc
+        echo "set pgp_encrypt_only_command=\"/usr/lib/mutt/pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust --encrypt-to 0x$MY_GPG_PUBLIC_KEY_ID -- -r %r -- %f\"" >> /home/$MY_USERNAME/.muttrc
     else
-	sed -i "s|set pgp_encrypt_only_command.*|set pgp_encrypt_only_command=\"/usr/lib/mutt/pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust --encrypt-to 0x$MY_GPG_PUBLIC_KEY_ID -- -r %r -- %f\"|g" /home/$MY_USERNAME/.muttrc
+        sed -i "s|set pgp_encrypt_only_command.*|set pgp_encrypt_only_command=\"/usr/lib/mutt/pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust --encrypt-to 0x$MY_GPG_PUBLIC_KEY_ID -- -r %r -- %f\"|g" /home/$MY_USERNAME/.muttrc
     fi
 
     if ! grep -q "pgp_encrypt_sign_command" /home/$MY_USERNAME/.muttrc; then
-	echo "set pgp_encrypt_sign_command=\"/usr/lib/mutt/pgpewrap gpg %?p?--passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust --encrypt-to 0x$MY_GPG_PUBLIC_KEY_ID -- -r %r -- %f\"" >> /home/$MY_USERNAME/.muttrc
+        echo "set pgp_encrypt_sign_command=\"/usr/lib/mutt/pgpewrap gpg %?p?--passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust --encrypt-to 0x$MY_GPG_PUBLIC_KEY_ID -- -r %r -- %f\"" >> /home/$MY_USERNAME/.muttrc
     else
-	sed -i "s|set pgp_encrypt_sign_command.*|set pgp_encrypt_sign_command=\"/usr/lib/mutt/pgpewrap gpg %?p?--passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust --encrypt-to 0x$MY_GPG_PUBLIC_KEY_ID -- -r %r -- %f\"|g" /home/$MY_USERNAME/.muttrc
+        sed -i "s|set pgp_encrypt_sign_command.*|set pgp_encrypt_sign_command=\"/usr/lib/mutt/pgpewrap gpg %?p?--passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust --encrypt-to 0x$MY_GPG_PUBLIC_KEY_ID -- -r %r -- %f\"|g" /home/$MY_USERNAME/.muttrc
     fi
 fi
 
@@ -203,9 +203,9 @@ if grep -q "install_xmpp" $COMPLETION_FILE; then
     echo $"Adding an XMPP account for $MY_USERNAME"
     ${PROJECT_NAME}-addxmpp -e "$MY_USERNAME@$HOSTNAME" -p "$NEW_USER_PASSWORD"
     if [ ! "$?" = "0" ]; then
-	echo $"XMPP account not created"
-	userdel -r $MY_USERNAME
-	exit 8
+        echo $"XMPP account not created"
+        userdel -r $MY_USERNAME
+        exit 8
     fi
 fi
 
@@ -214,10 +214,10 @@ if grep -q "install_xmpp_client" $COMPLETION_FILE; then
     XMPP_CLIENT_DIR=/home/$MY_USERNAME/.local/share/profanity
     XMPP_CLIENT_ACCOUNTS=$XMPP_CLIENT_DIR/accounts
     if [ ! -d $XMPP_CLIENT_DIR ]; then
-	mkdir -p $XMPP_CLIENT_DIR
+        mkdir -p $XMPP_CLIENT_DIR
     fi
     if [ ! -d /home/$MY_USERNAME/.config/profanity ]; then
-	mkdir -p /home/$MY_USERNAME/.config/profanity
+        mkdir -p /home/$MY_USERNAME/.config/profanity
     fi
     echo "[${MY_USERNAME}@${HOSTNAME}]" > $XMPP_CLIENT_ACCOUNTS
     echo 'enabled=true' >> $XMPP_CLIENT_ACCOUNTS
@@ -243,17 +243,17 @@ fi
 if grep -q "Blog domain" $COMPLETION_FILE; then
     FULLBLOG_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Blog domain" | awk -F ':' '{print $2}')
     if [ ! -d /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/users ]; then
-	echo $'Blog users directory not found'
-	if grep -q "install_xmpp" $COMPLETION_FILE; then
-	    ${PROJECT_NAME}-rmxmpp -e "$MY_USERNAME@$HOSTNAME"
-	fi
-	userdel -r $MY_USERNAME
-	exit 9
+        echo $'Blog users directory not found'
+        if grep -q "install_xmpp" $COMPLETION_FILE; then
+            ${PROJECT_NAME}-rmxmpp -e "$MY_USERNAME@$HOSTNAME"
+        fi
+        userdel -r $MY_USERNAME
+        exit 9
     fi
     NEW_USER_PASSWORD_HASH=$(${PROJECT_NAME}-sec --bloghash "$NEW_USER_PASSWORD")
     if [ ${#NEW_USER_PASSWORD_HASH} -lt 8 ]; then
-	echo $'Blog admin password could not be hashed'
-	exit 783528
+        echo $'Blog admin password could not be hashed'
+        exit 783528
     fi
     echo ';Password' > /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/users/$MY_USERNAME.ini
     echo "password = $NEW_USER_PASSWORD_HASH" >> /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/users/$MY_USERNAME.ini
@@ -267,46 +267,46 @@ if grep -q "install_sip" $COMPLETION_FILE; then
     SIP_EXTENSION=$(${PROJECT_NAME}-sipfreeext)
     ${PROJECT_NAME}-addsipuser -u $MY_USERNAME -e $SIP_EXTENSION -p "$NEW_USER_PASSWORD"
     if [ ! "$?" = "0" ]; then
-	echo $'SIP user could not be added. Ensure that extension numbers are in order and do no exceed 299'
-	if grep -q "install_xmpp" $COMPLETION_FILE; then
-	    ${PROJECT_NAME}-rmxmpp -e "$MY_USERNAME@$HOSTNAME"
-	fi
-	if grep -q "Blog domain" $COMPLETION_FILE; then
-	    if [ -f /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/users/$MY_USERNAME.ini ]; then
-		rm /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/users/$MY_USERNAME.ini
-	    fi
-	fi
-	userdel -r $MY_USERNAME
-	exit 10
+        echo $'SIP user could not be added. Ensure that extension numbers are in order and do no exceed 299'
+        if grep -q "install_xmpp" $COMPLETION_FILE; then
+            ${PROJECT_NAME}-rmxmpp -e "$MY_USERNAME@$HOSTNAME"
+        fi
+        if grep -q "Blog domain" $COMPLETION_FILE; then
+            if [ -f /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/users/$MY_USERNAME.ini ]; then
+                rm /var/www/$FULLBLOG_DOMAIN_NAME/htdocs/config/users/$MY_USERNAME.ini
+            fi
+        fi
+        userdel -r $MY_USERNAME
+        exit 10
     fi
 fi
 
 if grep -q "install_gnusocial" $COMPLETION_FILE; then
     MICROBLOG_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "GNU Social domain" | awk -F ':' '{print $2}')
     if [ -d /var/www/$MICROBLOG_DOMAIN_NAME ]; then
-	cd /var/www/$MICROBLOG_DOMAIN_NAME/htdocs
-	php scripts/registeruser.php -n $MY_USERNAME -w "$NEW_USER_PASSWORD" -e "$MY_USERNAME@$HOSTNAME"
-	${PROJECT_NAME}-addemail -u $MY_USERNAME -e "noreply@$MICROBLOG_DOMAIN_NAME" -g gnusocial --public no
-	echo $'Created GNU Social user'
+        cd /var/www/$MICROBLOG_DOMAIN_NAME/htdocs
+        php scripts/registeruser.php -n $MY_USERNAME -w "$NEW_USER_PASSWORD" -e "$MY_USERNAME@$HOSTNAME"
+        ${PROJECT_NAME}-addemail -u $MY_USERNAME -e "noreply@$MICROBLOG_DOMAIN_NAME" -g gnusocial --public no
+        echo $'Created GNU Social user'
     else
-	echo $"Unable to find GNU Social installation at /var/www/$MICROBLOG_DOMAIN_NAME/htdocs"
-	userdel -r $MY_USERNAME
-	exit 11
+        echo $"Unable to find GNU Social installation at /var/www/$MICROBLOG_DOMAIN_NAME/htdocs"
+        userdel -r $MY_USERNAME
+        exit 11
     fi
 fi
 
 if grep -q "install_irc_client" $COMPLETION_FILE; then
     IRC_PORT=6697
     if grep -q "IRC_PORT" $CONFIGURATION_FILE; then
-	IRC_PORT=$(grep "IRC_PORT" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
+        IRC_PORT=$(grep "IRC_PORT" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
     fi
     IRC_PASSWORD=$(cat /etc/ngircd/ngircd.conf | grep "Password =" | head -n 1 | awk -F '=' '{print $2}')
     if [ ${#IRC_PASSWORD} -lt 2 ]; then
-	IRC_PASSWORD=
+        IRC_PASSWORD=
     fi
 
     if [ ! -d /home/$MY_USERNAME/.irssi ]; then
-	mkdir /home/$MY_USERNAME/.irssi
+        mkdir /home/$MY_USERNAME/.irssi
     fi
 
     echo 'servers = (' > /home/$MY_USERNAME/.irssi/config
@@ -369,7 +369,7 @@ fi
 
 if [ -f /etc/nginx/.htpasswd ]; then
     if ! grep "${MY_USERNAME}:" /etc/nginx/.htpasswd; then
-	echo "$NEW_USER_PASSWORD" | htpasswd -i -s /etc/nginx/.htpasswd $MY_USERNAME
+        echo "$NEW_USER_PASSWORD" | htpasswd -i -s /etc/nginx/.htpasswd $MY_USERNAME
     fi
 fi
 
@@ -381,8 +381,8 @@ fi
 # add user for SIP STUN/TURN
 if [ -d /etc/turnserver ]; then
     if grep -q "DEFAULT_DOMAIN_NAME" $CONFIGURATION_FILE; then
-	DEFAULT_DOMAIN_NAME=$(grep "DEFAULT_DOMAIN_NAME" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-	echo "${MY_USERNAME}:${NEW_USER_PASSWORD}:${DEFAULT_DOMAIN_NAME}:authorized" >> /etc/turnserver/turnusers.txt
+        DEFAULT_DOMAIN_NAME=$(grep "DEFAULT_DOMAIN_NAME" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
+        echo "${MY_USERNAME}:${NEW_USER_PASSWORD}:${DEFAULT_DOMAIN_NAME}:authorized" >> /etc/turnserver/turnusers.txt
     fi
 fi
 
