Different way of recording the admin user

diff --git a/src/freedombone-rmuser b/src/freedombone-rmuser
--- a/src/freedombone-rmuser
+++ b/src/freedombone-rmuser
@@ -12,16 +12,33 @@ if [ ! -d /home/$MY_USERNAME ]; then
     exit 2
 fi
 
-if [ -f /home/$MY_USERNAME/.freedombone_administrator ]; then
-    echo "The administrator user cannot be removed"
+COMPLETION_FILE=$HOME/freedombone-completed.txt
+if [ ! -f $COMPLETION_FILE ]; then
+    echo "$COMPLETION_FILE not found"
     exit 3
+fi
+
+if ! grep -q "Admin user" $CONFIGURATION_FILE; then
+    echo "No admin user specified in $COMPLETION_FILE"
+    exit 4
+fi
+
+ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
+if [ ! $ADMIN_USERNAME ]; then
+    echo "No admin username specified in $COMPLETION_FILE"
+    exit 5
+fi
+
+if [[ $MY_USERNAME == $ADMIN_USERNAME ]]; then
+    echo "The administrator user cannot be removed"
+    exit 6
 fi
 
 echo '>>> REMOVE USER <<<'
 read -p "Do you really wish to remove the user '$MY_USERNAME' (y/n) ?" yn
 if [[ $yn != 'y' && $yn != 'Y' && $yn != 'yes' && $yn != 'Yes' && $yn != 'YES' ]]; then
     echo "User $MY_USERNAME was not removed"
-    exit 4
+    exit 7
 fi
 
 freedombone-rmxmpp -e "$MY_USERNAME@$HOSTNAME"
