The mirrored app doesn't need to be installed, but should have a script

diff --git a/src/freedombone-mirrors b/src/freedombone-mirrors
--- a/src/freedombone-mirrors
+++ b/src/freedombone-mirrors
@@ -128,14 +128,16 @@ function update_installed_apps_repos {
 
     # only deal with a single app
     if [ $SYNC_SINGLE_APP ]; then
-        if [[ "$(app_is_installed ${SYNC_SINGLE_APP})" == "1" ]]; then
-            filename=/usr/share/${PROJECT_NAME}/apps/${PROJECT_NAME}-app-${SYNC_SINGLE_APP}
-            APP_REPOS=($(cat ${MAIN_COMMAND} $filename | grep "_REPO=\"" | grep -v "(cat " | uniq -u | sed 's|${PROJECT_NAME}|'"${PROJECT_NAME}"'|g'))
-            for line in "${APP_REPOS[@]}"
-            do
-                INSTALLED_APPS_REPOS+=("${line}")
-            done
+        filename=/usr/share/${PROJECT_NAME}/apps/${PROJECT_NAME}-app-${SYNC_SINGLE_APP}
+        if [ ! -f $filename ]; then
+            echo $"The app $SYNC_SINGLE_APP was not found"
+            exit 36822
         fi
+        APP_REPOS=($(cat ${MAIN_COMMAND} $filename | grep "_REPO=\"" | grep -v "(cat " | uniq -u | sed 's|${PROJECT_NAME}|'"${PROJECT_NAME}"'|g'))
+        for line in "${APP_REPOS[@]}"
+        do
+            INSTALLED_APPS_REPOS+=("${line}")
+        done
         return
     fi
 
