Turn the combining of scripts into a function

diff --git a/src/freedombone-image-make b/src/freedombone-image-make
--- a/src/freedombone-image-make
+++ b/src/freedombone-image-make
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # .---.                  .              .
 # |                      |              |
@@ -33,6 +33,12 @@ PROJECT_NAME='freedombone'
 
 export TEXTDOMAIN=${PROJECT_NAME}-image-make
 export TEXTDOMAINDIR="/usr/share/locale"
+
+PROJECT_INSTALL_DIR=/usr/local/bin
+if [ -f /usr/bin/${PROJECT_NAME} ]; then
+	PROJECT_INSTALL_DIR=/usr/bin
+fi
+source $PROJECT_INSTALL_DIR/${PROJECT_NAME}-vars
 
 #set -x # Enable debugging
 
@@ -180,27 +186,11 @@ TEMP_CUSTOMISE3=/tmp/${PROJECT_NAME}-image-customise3
 TEMP_CUSTOMISE4=/tmp/${PROJECT_NAME}-image-customise4
 
 # cat all the things together
-cp $PROJECT_INSTALL_DIR/${PROJECT_NAME}-vars $TEMP_CUSTOMISE2
-echo $'Adding utilities to customised customisation script'
-UTILS_FILES=/usr/share/${PROJECT_NAME}/utils/${PROJECT_NAME}-utils-*
-for f in $UTILS_FILES
-do
-  cat $f >> $TEMP_CUSTOMISE2
-done
-echo $'Adding base system to customised customisation script'
-BASE_SYSTEM_FILES=/usr/share/${PROJECT_NAME}/base/${PROJECT_NAME}-base-*
-for f in $BASE_SYSTEM_FILES
-do
-  cat $f >> $TEMP_CUSTOMISE2
-done
-echo $'Adding apps to customised customisation script'
-APP_FILES=/usr/share/${PROJECT_NAME}/apps/${PROJECT_NAME}-app-*
-for f in $APP_FILES
-do
-  cat $f >> $TEMP_CUSTOMISE2
-done
-echo $'Removing headers from customised customisation script'
-sed -i 's|#!/bin/bash||g' $TEMP_CUSTOMISE2
+combine_all_scripts $TEMP_CUSTOMISE2
+if [ ! -f $TEMP_CUSTOMISE2 ]; then
+	echo $'Could not combine scripts'
+	exit 627219
+fi
 
 echo $'Changing values within customised customisation script'
 cp $PROJECT_INSTALL_DIR/${PROJECT_NAME}-image-customise $TEMP_CUSTOMISE3
