Try installing patchwork on mesh images

diff --git a/src/freedombone-image-customise b/src/freedombone-image-customise
--- a/src/freedombone-image-customise
+++ b/src/freedombone-image-customise
@@ -561,6 +561,27 @@ INSTALL_DIR=$HOME/build
 
 INSTALLING_MESH=
 
+install_patchwork() {
+    chroot "$rootdir" apt-get g++ m4 libtool automake nodejs
+    chroot "$rootdir" apt-get libxext-dev libxtst-dev libxkbfile-dev
+    git clone https://github.com/ssbc/patchwork $rootdir/etc/patchwork
+
+    cat <<EOF > $rootdir/usr/bin/install_patchwork
+#!/bin/bash
+cd /etc/patchwork
+npm install
+EOF
+    chroot "$rootdir" /bin/chmod +x /usr/bin/install_patchwork
+    chroot "$rootdir" /usr/bin/install_patchwork
+    if [ ! -f /usr/bin/patchwork ]; then
+        if [ ! -f /usr/local/bin/patchwork ]; then
+            echo $'Unable to install SSB Patchwork peer'
+            exit 783524
+        fi
+    fi
+    rm $rootdir/usr/bin/install_patchwork
+}
+
 initialise_mesh() {
     if [[ $VARIANT != "mesh"* ]]; then
         return
@@ -597,6 +618,7 @@ initialise_mesh() {
     install_tomb
     #install_tahoelafs
     #install_librevault
+    install_patchwork
     install_ipfs
     install_tox
     install_web_server
