Get cryptpad config file

diff --git a/src/freedombone-app-cryptpad b/src/freedombone-app-cryptpad
--- a/src/freedombone-app-cryptpad
+++ b/src/freedombone-app-cryptpad
@@ -489,12 +489,6 @@ function install_cryptpad {
     else
         sed -i "s|domain:.*|domain: 'http://$CRYPTPAD_ONION_HOSTNAME',|g" config.js
     fi
-    #if [[ $ONION_ONLY != 'no' ]]; then
-    #    sed -i "/module.exports/a ]," config.js
-    #    sed -i "/module.exports/a '\/etc\/ssl\/private\/${CRYPTPAD_DOMAIN_NAME}.key'" config.js
-    #    sed -i "/module.exports/a '\/etc\/ssl\/certs\/${CRYPTPAD_DOMAIN_NAME}.pem'" config.js
-    #    sed -i "/module.exports/a privKeyAndCertFiles: [" config.js
-    #fi
 
     chown -R cryptpad:cryptpad $CRYPTPAD_DIR
 
@@ -518,6 +512,16 @@ function install_cryptpad {
     systemctl enable cryptpad.service
     systemctl daemon-reload
     systemctl start cryptpad.service
+
+    if [ ! -d $CRYPTPAD_DIR/customize/api ]; then
+        mkdir -p $CRYPTPAD_DIR/customize/api
+    fi
+    wget 127.0.0.1:$CRYPTPAD_PORT/api/config -O $CRYPTPAD_DIR/customize/api/config
+    if [ ! -f $CRYPTPAD_DIR/customize/api/config ]; then
+        echo $'Unable to wget api/config'
+        exit 89252
+    fi
+    chown -R cryptpad:cryptpad $CRYPTPAD_DIR
 
     systemctl restart nginx
 
