Function to remove tox

diff --git a/src/freedombone-app-tox b/src/freedombone-app-tox
--- a/src/freedombone-app-tox
+++ b/src/freedombone-app-tox
@@ -62,6 +62,40 @@ function remove_tox_node {
 		exit 763836
 	fi
 	sed -i '/install_tox_node/d' $COMPLETION_FILE
+	sed -i '/configure_firewall_for_tox/d' $COMPLETION_FILE
+}
+
+function remove_tox_avahi {
+	if ! grep -Fxq "tox_avahi" $COMPLETION_FILE; then
+		return
+	fi
+	cd $INSTALL_DIR/toxid
+	make uninstall
+	rm -rf $INSTALL_DIR/toxid
+	sed -i '/toxavahi/d' /etc/crontab
+	systemctl restart cron
+	sed -i '/tox_avahi/d' $COMPLETION_FILE
+}
+
+function remove_tox_client {
+	if ! grep -Fxq "install_tox_client" $COMPLETION_FILE; then
+		return
+	fi
+
+	${PROJECT_NAME}-mesh-install -f tox_client --remove yes
+	if [ ! "$?" = "0" ]; then
+		echo $'Could not remove Tox client'
+		exit 737253
+	fi
+	sed -i '/install_tox_client/d' $COMPLETION_FILE
+	sed -i '/Tox /d' $COMPLETION_FILE
+	sed -i '/Toxic /d' $COMPLETION_FILE
+}
+
+function remove_tox {
+	remove_tox_client
+	remove_tox_avahi
+	remove_tox_node
 }
 
 function configure_firewall_for_tox {
