Ensure that prosody directory is available

diff --git a/src/freedombone-app-xmpp b/src/freedombone-app-xmpp
--- a/src/freedombone-app-xmpp
+++ b/src/freedombone-app-xmpp
@@ -298,6 +298,7 @@ function remove_xmpp {
     if [ -d /var/lib/prosody ]; then
         rm -rf /var/lib/prosody
     fi
+    groupdel prosody
 
     remove_completion_param install_xmpp
     sed -i '/xmpp/d' $COMPLETION_FILE
@@ -417,6 +418,13 @@ function install_xmpp_main {
     if [ ! -d /etc/prosody ]; then
         echo $"ERROR: prosody does not appear to have installed. $CHECK_MESSAGE"
         exit 52367
+    fi
+
+    groupadd prosody
+
+    if [ ! -d /var/lib/prosody ]; then
+        mkdir /var/lib/prosody
+        chown -R prosody:prosody /var/lib/prosody
     fi
 
     # obtain the prosody modules
@@ -590,7 +598,12 @@ function install_xmpp_main {
             XMPP_PASSWORD="$(create_password ${MINIMUM_PASSWORD_LENGTH})"
         fi
     fi
+
     prosodyctl register $MY_USERNAME $DEFAULT_DOMAIN_NAME "$XMPP_PASSWORD"
+    if [ ! "$?" = "0" ]; then
+        echo $'Unable to register prosody user'
+        exit 347682
+    fi
 
     ${PROJECT_NAME}-pass -u $MY_USERNAME -a xmpp -p "$XMPP_PASSWORD"
 
