Install horst for wifi network monitoring

diff --git a/src/freedombone-mesh-batman b/src/freedombone-mesh-batman
--- a/src/freedombone-mesh-batman
+++ b/src/freedombone-mesh-batman
@@ -260,6 +260,38 @@ function start {
     verify
 }
 
+function monitor {
+    if [ -z "$IFACE" ] ; then
+        echo 'error: unable to find wifi interface, not enabling batman-adv mesh'
+        exit 723657
+    fi
+
+    stop
+
+    echo "info: monitoring mesh network $WIFI_SSID on $IFACE"
+
+    systemctl stop network-manager
+    sleep 5
+
+    global_rate_limit
+
+    # Might have to re-enable wifi
+    rfkill unblock $(rfkill list|awk -F: "/phy/ {print $1}") || true
+
+    ifconfig $IFACE down
+    ifconfig $IFACE mtu 1532
+    ifconfig $IFACE hw ether $(assign_peer_address)
+    iwconfig $IFACE enc off
+    iwconfig $IFACE mode monitor channel $CHANNEL
+    sleep 1
+    iwconfig $IFACE ap $CELLID
+
+    modprobe batman-adv
+    batctl if add $IFACE
+    ifconfig $IFACE up
+    horst -i $IFACE
+}
+
 if ! grep -q "$IFACE" /proc/net/dev; then
     echo 'Interface $IFACE was not found'
     stop
@@ -267,7 +299,7 @@ if ! grep -q "$IFACE" /proc/net/dev; then
 fi
 
 case "$1" in
-    start|stop|status)
+    start|stop|status|monitor)
         $1
         ;;
     restart)
