Email archiving command

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -5187,6 +5187,19 @@ function email_archiving {
       return
   fi
 
+  # ensure that the mail archive script is up to date
+  if [ -f /usr/local/bin/${PROJECT_NAME}-archive-mail ]; then
+      cp /usr/local/bin/${PROJECT_NAME}-archive-mail /etc/cron.daily/archivemail
+  else
+      if [ -f /usr/bin/${PROJECT_NAME}-archive-mail ]; then
+          cp /usr/bin/${PROJECT_NAME}-archive-mail /etc/cron.daily/archivemail
+      else
+          echo "/usr/bin/${PROJECT_NAME}-archive-email was not found. ${PROJECT_NAME} might not have fully installed."
+          exit 62379
+      fi
+  fi
+  chmod +x /etc/cron.daily/archivemail
+
   # update to the next commit
   if [ -d $INSTALL_DIR/cleanup-maildir ]; then
       if grep -q "cleanup-maildir commit" $COMPLETION_FILE; then
@@ -5222,28 +5235,6 @@ function email_archiving {
   fi
 
   cp $INSTALL_DIR/cleanup-maildir/cleanup-maildir /usr/bin
-  echo '#!/bin/bash' > /etc/cron.daily/archivemail
-  echo 'for d in /home/*/ ; do' >> /etc/cron.daily/archivemail
-  echo '  USERNAME=$(echo "$d" | awk -F '"'"'/'"'"' '"'"'{print $3}'"'"')' >> /etc/cron.daily/archivemail
-  echo '  if [[ $USERNAME != "git" ]]; then' >> /etc/cron.daily/archivemail
-  echo '    if [ -d /home/$USERNAME/Maildir ]; then' >> /etc/cron.daily/archivemail
-  echo '      MUTTRC=/home/$USERNAME/.muttrc' >> /etc/cron.daily/archivemail
-  echo '      python /usr/bin/cleanup-maildir --archive-folder="archive" --maildir-root="/home/$USERNAME/Maildir" archive ""' >> /etc/cron.daily/archivemail
-  echo '      chown -R $USERNAME:$USERNAME /home/$USERNAME/Maildir/archive-*' >> /etc/cron.daily/archivemail
-  echo '      if [ -f $MUTTRC ]; then' >> /etc/cron.daily/archivemail
-  echo '        MUTT_MAILBOXES=$(grep "mailboxes =" $MUTTRC)' >> /etc/cron.daily/archivemail
-  echo '        BACKUP_DIRECTORY=archive-$(date +"%Y")' >> /etc/cron.daily/archivemail
-  echo '        if [[ $MUTT_MAILBOXES != *$BACKUP_DIRECTORY* ]]; then' >> /etc/cron.daily/archivemail
-  echo '          sed -i "s|$MUTT_MAILBOXES|$MUTT_MAILBOXES =$BACKUP_DIRECTORY|g" $MUTTRC' >> /etc/cron.daily/archivemail
-  echo '          chown $USERNAME:$USERNAME $MUTTRC' >> /etc/cron.daily/archivemail
-  echo '        fi' >> /etc/cron.daily/archivemail
-  echo '      fi' >> /etc/cron.daily/archivemail
-  echo '    fi' >> /etc/cron.daily/archivemail
-  echo '  fi' >> /etc/cron.daily/archivemail
-  echo 'done' >> /etc/cron.daily/archivemail
-
-  echo 'exit 0' >> /etc/cron.daily/archivemail
-  chmod +x /etc/cron.daily/archivemail
 
   echo 'email_archiving' >> $COMPLETION_FILE
 }
