Test domain gets modified

diff --git a/src/freedombone-utils-web b/src/freedombone-utils-web
--- a/src/freedombone-utils-web
+++ b/src/freedombone-utils-web
@@ -165,11 +165,13 @@ function nginx_keybase {
 function test_domain_name {
     if [ $1 ]; then
         TEST_DOMAIN_NAME=$1
-        function_check validate_domain_name
-        validate_domain_name
-        if [[ $TEST_DOMAIN_NAME != $1 && $TEST_DOMAIN_NAME != 'ttrss' ]]; then
-            echo $"Invalid domain name $TEST_DOMAIN_NAME"
-            exit 8528
+        if [[ $TEST_DOMAIN_NAME != 'ttrss' ]]; then
+            function_check validate_domain_name
+            validate_domain_name
+            if [[ $TEST_DOMAIN_NAME != $1 ]]; then
+                echo $"Invalid domain name $TEST_DOMAIN_NAME"
+                exit 8528
+            fi
         fi
     fi
 }
