Check for index file

diff --git a/src/freedombone-utils-gnusocialtools b/src/freedombone-utils-gnusocialtools
--- a/src/freedombone-utils-gnusocialtools
+++ b/src/freedombone-utils-gnusocialtools
@@ -181,6 +181,11 @@ function install_pleroma {
         echo 'Unable to build pleroma'
         exit 7629352
     fi
+    if [ ! -f ~/build/pleroma/dist/index.html ]; then
+        echo $'Unable to build pleroma index.html'
+        exit 5282682
+    fi
+
     mv ~/build/pleroma/dist/index.html ~/build/pleroma/dist/pleroma.html
     cp -r ~/build/pleroma/dist/* /var/www/$pleroma_domain/htdocs/
 
