Check that blog gets created

diff --git a/src/freedombone-app-pelican b/src/freedombone-app-pelican
--- a/src/freedombone-app-pelican
+++ b/src/freedombone-app-pelican
@@ -800,6 +800,10 @@ function install_pelican {
     install_pelican_website_onion
 
     pelican_regenerate_blog
+    if [ ! -d $PELICAN_BLOG_INSTALL_DIR/output ]; then
+        echo $'Failed to generate pelican blog'
+        exit 521892
+    fi
 
     function_check nginx_ensite
     nginx_ensite $PELICAN_DOMAIN_NAME
