Check for versioned configuration

diff --git a/src/freedombone-app-vpn b/src/freedombone-app-vpn
--- a/src/freedombone-app-vpn
+++ b/src/freedombone-app-vpn
@@ -252,6 +252,10 @@ function install_vpn {
     cd /etc/openvpn/easy-rsa
     . ./vars
     ./clean-all
+    if [ ! -f openssl-1.0.0.cnf ]; then
+        echo $'openssl-1.0.0.cnf was not found'
+        exit 7392353
+    fi
     cp openssl-1.0.0.cnf openssl.cnf
     echo '
 
