Check that directory exists

diff --git a/src/freedombone-app-ipfs b/src/freedombone-app-ipfs
--- a/src/freedombone-app-ipfs
+++ b/src/freedombone-app-ipfs
@@ -408,18 +408,10 @@ fi
 
 IPFS_PATH=\$GOPATH/bin
 export PATH="\$GOPATH/bin:\$PATH:"
-if ! grep -q 'GOPATH/bin' ~/.bashrc; then
-    echo 'export PATH="\$GOPATH/bin:\$PATH:";' >> ~/.bashrc
-else
-    sed -i "s|systemctl set-environment GOPATH=.*|systemctl set-environment GOPATH=\$GOPATH|g" ~/.bashrc
-fi
+echo 'export PATH="\$GOPATH/bin:\$PATH:";' >> /home/$MY_USERNAME/.bashrc
 
-# set gopath for the user
-if ! grep -q "GOPATH=" /home/$MY_USERNAME/.bashrc; then
-    echo "export GOPATH=$GOPATH" >> /home/$MY_USERNAME/.bashrc
-    echo 'export PATH="\$GOPATH/bin:\$PATH:";' >> /home/$MY_USERNAME/.bashrc
-else
-    sed -i "s|export GOPATH=.*|export GOPATH=\$GOPATH|g" /home/$MY_USERNAME/.bashrc
+if grep -q 'GOPATH/bin' ~/.bashrc; then
+    sed -i "s|systemctl set-environment GOPATH=.*|systemctl set-environment GOPATH=\$GOPATH|g" ~/.bashrc
 fi
 chown $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.bashrc
 
@@ -427,6 +419,11 @@ IPFS_GO_REPO2=$(echo "$IPFS_GO_REPO" | sed 's|https://||g')
 go get -u ${IPFS_GO_REPO2}/cmd/ipfs
 if [ ! "$?" = "0" ]; then
     exit 8242
+fi
+
+if [ ! -d $GOPATH/src/$IPFS_GO_REPO2 ]; then
+    echo $'go get failed to get ipfs'
+    exit 63923
 fi
 
 cd \$GOPATH/src/$IPFS_GO_REPO2
@@ -519,6 +516,11 @@ function install_ipfs_go {
     go get -u ${IPFS_GO_REPO2}/cmd/ipfs
     if [ ! "$?" = "0" ]; then
         exit 8242
+    fi
+
+    if [ ! -d $GOPATH/src/$IPFS_GO_REPO2 ]; then
+        echo $'go get failed to get ipfs'
+        exit 63923
     fi
 
     cd $GOPATH/src/$IPFS_GO_REPO2
