Check that mercurial gets installed

diff --git a/src/freedombone-app-xmpp b/src/freedombone-app-xmpp
--- a/src/freedombone-app-xmpp
+++ b/src/freedombone-app-xmpp
@@ -788,8 +788,14 @@ function install_xmpp_main {
 
     apt-get -yq install lua-sec lua-bitop lua5.1 liblua5.1-dev
     apt-get -yq install libidn11-dev libssl-dev lua-dbi-sqlite3
+    rm -rf /tmp/*
     apt-get -yq mercurial
     apt-get -yq install prosody
+
+    if [ ! -f /usr/bin/hg ]; then
+        echo $"Couldn't install mercurial"
+        exit 52825
+    fi
 
     if [ ! -d /etc/prosody ]; then
         echo $"ERROR: prosody does not appear to have installed. $CHECK_MESSAGE"
