Default movim admin login

diff --git a/src/freedombone-app-movim b/src/freedombone-app-movim
--- a/src/freedombone-app-movim
+++ b/src/freedombone-app-movim
@@ -39,7 +39,7 @@ MOVIM_ONION_PORT=8117
 MOVIM_REPO="https://github.com/movim/movim"
 MOVIM_COMMIT='add1a247804eb0e34fc28a74c2eeea16792ffa8e'
 MOVIM_ADMIN_PASSWORD=
-MOVIM_DAEMON_PORT=8081
+MOVIM_DAEMON_PORT=8880
 
 movim_variables=(ONION_ONLY
                  MOVIM_DOMAIN_NAME
@@ -319,7 +319,7 @@ function install_movim {
     repair_databases_script
 
     apt-get -yq install php-gettext php5-curl php5-gd php5-mysql git curl php-xml-parser
-    apt-get -yq install php5-memcached php5-intl exiftool
+    apt-get -yq install php5-memcached php5-intl exiftool php5-imagick
 
     if [ ! -d /var/www/$MOVIM_DOMAIN_NAME ]; then
         mkdir /var/www/$MOVIM_DOMAIN_NAME
@@ -354,6 +354,14 @@ function install_movim {
     sed -i "s|'database'.*|'database'    => 'movim'|g" db.inc.php
     php mud.php db --set
 
+    # default login
+    if [ ! -f /var/www/$MOVIM_DOMAIN_NAME/htdocs/app/models/config/Config.php ]; then
+        echo $'Unable to find Config.php'
+        exit 72352
+    fi
+    sed -i "s|'admin'|'${MY_USERNAME}'|g" /var/www/$MOVIM_DOMAIN_NAME/htdocs/app/models/config/Config.php
+    sed -i "s|'password'|'${MOVIM_ADMIN_PASSWORD}'|g" /var/www/$MOVIM_DOMAIN_NAME/htdocs/app/models/config/Config.php
+
     chmod u+rwx /var/www/$MOVIM_DOMAIN_NAME/htdocs
     chown -R www-data:www-data /var/www/$MOVIM_DOMAIN_NAME/htdocs
 
@@ -378,6 +386,9 @@ function install_movim {
     else
         echo "ExecStart=/usr/bin/php /var/www/$MOVIM_DOMAIN_NAME/htdocs/daemon.php start --url=http://$MOVIM_ONION_HOSTNAME --port=$MOVIM_DAEMON_PORT" >> /etc/systemd/system/movim.service
     fi
+    echo 'StandardOutput=syslog' >> /etc/systemd/system/movim.service
+    echo 'SyslogIdentifier=movim' >> /etc/systemd/system/movim.service
+    echo 'PIDFile=/run/movim.pid' >> /etc/systemd/system/movim.service
     echo 'Restart=on-failure' >> /etc/systemd/system/movim.service
     echo 'RestartSec=10' >> /etc/systemd/system/movim.service
     echo '' >> /etc/systemd/system/movim.service
