Remove old daemon commands

diff --git a/src/freedombone-mesh b/src/freedombone-mesh
--- a/src/freedombone-mesh
+++ b/src/freedombone-mesh
@@ -121,28 +121,21 @@ function install_toxcore {
     sudo cp /tmp/tox-bootstrapd.conf /etc/tox-bootstrapd.conf
     rm /tmp/tox-bootstrapd.conf
 
-    if [ -f /bin/systemctl ]; then
-        if [ ! -f ~/develop/toxcore/other/bootstrap_daemon/tox-bootstrapd.service ]; then
-            echo $"File not found ~/develop/toxcore/other/bootstrap_daemon/tox-bootstrapd.service"
-            exit 7359
-        fi
-        sudo cp ~/develop/toxcore/other/bootstrap_daemon/tox-bootstrapd.service /etc/systemd/system/
-
-        sudo systemctl daemon-reload
-        sudo systemctl enable tox-bootstrapd.service
-        sudo systemctl start tox-bootstrapd.service
-        if [ ! "$?" = "0" ]; then
-            sudo systemctl status tox-bootstrapd.service
-            exit 5846
-        fi
-
-        sudo systemctl restart tox-bootstrapd.service
-    else
-        sudo cp ~/develop/toxcore/other/bootstrap_daemon/tox-bootstrapd.sh /etc/init.d/tox-bootstrapd
-        sudo chmod 755 /etc/init.d/tox-bootstrapd
-        sudo update-rc.d tox-bootstrapd defaults
-        sudo service tox-bootstrapd start
+    if [ ! -f ~/develop/toxcore/other/bootstrap_daemon/tox-bootstrapd.service ]; then
+        echo $"File not found ~/develop/toxcore/other/bootstrap_daemon/tox-bootstrapd.service"
+        exit 7359
     fi
+    sudo cp ~/develop/toxcore/other/bootstrap_daemon/tox-bootstrapd.service /etc/systemd/system/
+
+    sudo systemctl daemon-reload
+    sudo systemctl enable tox-bootstrapd.service
+    sudo systemctl start tox-bootstrapd.service
+    if [ ! "$?" = "0" ]; then
+        sudo systemctl status tox-bootstrapd.service
+        exit 5846
+    fi
+
+    sudo systemctl restart tox-bootstrapd.service
 
     TOX_PUBLIC_KEY=$(cat /var/log/syslog | grep tox | grep "Public Key" | awk -F ' ' '{print $8}' | tail -1)
     if [ ${#TOX_PUBLIC_KEY} -lt 30 ]; then
