Check that microblog config file exists

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -8532,8 +8532,14 @@ function install_gnu_social {
         exit 72357
     fi
 
-    # Some useful settings
+    # check microblog has a config file
     microblog_config_file=/var/www/$MICROBLOG_DOMAIN_NAME/htdocs/config.php
+    if [ ! -f $microblog_config_file ]; then
+        echo $'Microblog config.php not found'
+        exit 87586
+    fi
+
+    # Some useful settings
     if ! grep -q "Recommended GNU social settings" $microblog_config_file; then
         echo "" >> $microblog_config_file
         echo "// Recommended GNU social settings" >> $microblog_config_file
