service file path

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -7584,7 +7584,11 @@ function install_tox_node {
       echo ')' >> /etc/tox-bootstrapd.conf
   fi
 
-  cp $INSTALL_DIR/toxcore/tox-bootstrapd.service /etc/systemd/system/
+  if [ ! -f $INSTALL_DIR/toxcore/other/bootstrap_daemon/tox-bootstrapd.service ]; then
+      echo "File not found $INSTALL_DIR/toxcore/other/bootstrap_daemon/tox-bootstrapd.service"
+      exit 7359
+  fi
+  cp $INSTALL_DIR/toxcore/other/bootstrap_daemon/tox-bootstrapd.service /etc/systemd/system/
   systemctl daemon-reload
   systemctl enable tox-bootstrapd.service
   systemctl start tox-bootstrapd.service
