Tidying

diff --git a/src/freedombone-addcert b/src/freedombone-addcert
--- a/src/freedombone-addcert
+++ b/src/freedombone-addcert
@@ -58,284 +58,284 @@ FRIENDS_MIRRORS_SSH_PORT=
 MY_MIRRORS_PASSWORD=
 
 function read_repo_servers {
-	if [ -f $CONFIGURATION_FILE ]; then
-		if grep -q "FRIENDS_MIRRORS_SERVER" $CONFIGURATION_FILE; then
-			FRIENDS_MIRRORS_SERVER=$(grep "FRIENDS_MIRRORS_SERVER" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-		fi
-		if grep -q "FRIENDS_MIRRORS_SSH_PORT" $CONFIGURATION_FILE; then
-			FRIENDS_MIRRORS_SSH_PORT=$(grep "FRIENDS_MIRRORS_SSH_PORT" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-		fi
-		if grep -q "MY_MIRRORS_PASSWORD" $CONFIGURATION_FILE; then
-			MY_MIRRORS_PASSWORD=$(grep "MY_MIRRORS_PASSWORD" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-		fi
-		if grep -q "FRIENDS_MIRRORS_PASSWORD" $CONFIGURATION_FILE; then
-			FRIENDS_MIRRORS_PASSWORD=$(grep "FRIENDS_MIRRORS_PASSWORD" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-		fi
+    if [ -f $CONFIGURATION_FILE ]; then
+	if grep -q "FRIENDS_MIRRORS_SERVER" $CONFIGURATION_FILE; then
+	    FRIENDS_MIRRORS_SERVER=$(grep "FRIENDS_MIRRORS_SERVER" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
 	fi
-
-	if [ ! $FRIENDS_MIRRORS_SERVER ]; then
-		return
+	if grep -q "FRIENDS_MIRRORS_SSH_PORT" $CONFIGURATION_FILE; then
+	    FRIENDS_MIRRORS_SSH_PORT=$(grep "FRIENDS_MIRRORS_SSH_PORT" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
 	fi
-	if [ ${#FRIENDS_MIRRORS_SERVER} -lt 2 ]; then
-		return
+	if grep -q "MY_MIRRORS_PASSWORD" $CONFIGURATION_FILE; then
+	    MY_MIRRORS_PASSWORD=$(grep "MY_MIRRORS_PASSWORD" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
 	fi
-
-	MAIN_COMMAND=/usr/local/bin/${PROJECT_NAME}
-	if [ ! -f $MAIN_COMMAND ]; then
-		MAIN_COMMAND=/usr/bin/${PROJECT_NAME}
+	if grep -q "FRIENDS_MIRRORS_PASSWORD" $CONFIGURATION_FILE; then
+	    FRIENDS_MIRRORS_PASSWORD=$(grep "FRIENDS_MIRRORS_PASSWORD" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
 	fi
+    fi
 
-	REPOS=($(cat ${MAIN_COMMAND} | grep "_REPO=\"" | uniq -u | sed 's|${PROJECT_NAME}|'"${PROJECT_NAME}"'|g'))
+    if [ ! $FRIENDS_MIRRORS_SERVER ]; then
+	return
+    fi
+    if [ ${#FRIENDS_MIRRORS_SERVER} -lt 2 ]; then
+	return
+    fi
 
-	for line in "${REPOS[@]}"
-	do
-		repo_name=$(echo "$line" | awk -F '=' '{print $1}')
-		mirrors_name=$(echo "$repo_name" | sed "s|_REPO||g" | awk '{print tolower($0)}')
-		friends_repo_url="ssh://mirrors@${FRIENDS_MIRRORS_SERVER}:${FRIENDS_MIRRORS_SSH_PORT}/home/mirrors/${mirrors_name}"
-		${repo_name}="${friends_repo_url}"
-	done
+    MAIN_COMMAND=/usr/local/bin/${PROJECT_NAME}
+    if [ ! -f $MAIN_COMMAND ]; then
+	MAIN_COMMAND=/usr/bin/${PROJECT_NAME}
+    fi
+
+    REPOS=($(cat ${MAIN_COMMAND} | grep "_REPO=\"" | uniq -u | sed 's|${PROJECT_NAME}|'"${PROJECT_NAME}"'|g'))
+
+    for line in "${REPOS[@]}"
+    do
+	repo_name=$(echo "$line" | awk -F '=' '{print $1}')
+	mirrors_name=$(echo "$repo_name" | sed "s|_REPO||g" | awk '{print tolower($0)}')
+	friends_repo_url="ssh://mirrors@${FRIENDS_MIRRORS_SERVER}:${FRIENDS_MIRRORS_SSH_PORT}/home/mirrors/${mirrors_name}"
+	${repo_name}="${friends_repo_url}"
+    done
 }
 
 function show_help {
-	echo ''
-	echo $"${PROJECT_NAME}-addcert -h [hostname] -c [country code] -a [area] -l [location]"
-	echo $'                    -o [organisation] -u [unit] --ca "" --nodh ""'
-	echo ''
-	echo $'Creates a self-signed certificate for the given hostname'
-	echo ''
-	echo $'     --help                   Show help'
-	echo $'  -h --hostname [name]        Hostname'
-	echo $'  -e --letsencrypt [hostname] Hostname to use with Lets Encrypt'
-	echo $'  -s --server [url]           Lets Encrypt server URL'
-	echo $'  -c --country [code]         Optional country code (eg. US, GB, etc)'
-	echo $'  -a --area [description]     Optional area description'
-	echo $'  -l --location [locn]        Optional location name'
-	echo $'  -o --organisation [name]    Optional organisation name'
-	echo $'  -u --unit [name]            Optional unit name'
-	echo $'     --email [address]        Email address for letsencrypt'
-	echo $'     --dhkey [bits]           DH key length in bits'
-	echo $'     --nodh ""                Do not calculate DH params'
-	echo $'     --ca ""                  Certificate authority cert'
-	echo ''
-	exit 0
+    echo ''
+    echo $"${PROJECT_NAME}-addcert -h [hostname] -c [country code] -a [area] -l [location]"
+    echo $'                    -o [organisation] -u [unit] --ca "" --nodh ""'
+    echo ''
+    echo $'Creates a self-signed certificate for the given hostname'
+    echo ''
+    echo $'     --help                   Show help'
+    echo $'  -h --hostname [name]        Hostname'
+    echo $'  -e --letsencrypt [hostname] Hostname to use with Lets Encrypt'
+    echo $'  -s --server [url]           Lets Encrypt server URL'
+    echo $'  -c --country [code]         Optional country code (eg. US, GB, etc)'
+    echo $'  -a --area [description]     Optional area description'
+    echo $'  -l --location [locn]        Optional location name'
+    echo $'  -o --organisation [name]    Optional organisation name'
+    echo $'  -u --unit [name]            Optional unit name'
+    echo $'     --email [address]        Email address for letsencrypt'
+    echo $'     --dhkey [bits]           DH key length in bits'
+    echo $'     --nodh ""                Do not calculate DH params'
+    echo $'     --ca ""                  Certificate authority cert'
+    echo ''
+    exit 0
 }
 
 while [[ $# > 1 ]]
 do
-key="$1"
+    key="$1"
 
-case $key in
+    case $key in
 	--help)
-	show_help
-	;;
+	    show_help
+	    ;;
 	-h|--hostname)
-	shift
-	HOSTNAME="$1"
-	;;
+	    shift
+	    HOSTNAME="$1"
+	    ;;
 	-e|--letsencrypt)
-	shift
-	LETSENCRYPT_HOSTNAME="$1"
-	;;
+	    shift
+	    LETSENCRYPT_HOSTNAME="$1"
+	    ;;
 	--email)
-	shift
-	MY_EMAIL_ADDRESS="$1"
-	;;
+	    shift
+	    MY_EMAIL_ADDRESS="$1"
+	    ;;
 	-s|--server)
-	shift
-	LETSENCRYPT_SERVER="$1"
-	;;
+	    shift
+	    LETSENCRYPT_SERVER="$1"
+	    ;;
 	-c|--country)
-	shift
-	COUNTRY_CODE="$1"
-	;;
+	    shift
+	    COUNTRY_CODE="$1"
+	    ;;
 	-a|--area)
-	shift
-	AREA="$1"
-	;;
+	    shift
+	    AREA="$1"
+	    ;;
 	-l|--location)
-	shift
-	LOCATION="$1"
-	;;
+	    shift
+	    LOCATION="$1"
+	    ;;
 	-o|--organisation)
-	shift
-	ORGANISATION="$1"
-	;;
+	    shift
+	    ORGANISATION="$1"
+	    ;;
 	-u|--unit)
-	shift
-	UNIT="$1"
-	;;
+	    shift
+	    UNIT="$1"
+	    ;;
 	--ca)
-	shift
-	EXTENSIONS="-extensions v3_ca"
-	ORGANISATION="Freedombone-CA"
-	;;
+	    shift
+	    EXTENSIONS="-extensions v3_ca"
+	    ORGANISATION="Freedombone-CA"
+	    ;;
 	--nodh)
-	shift
-	NODH="true"
-	;;
+	    shift
+	    NODH="true"
+	    ;;
 	--dhkey)
-	shift
-	DH_KEYLENGTH=${1}
-	;;
+	    shift
+	    DH_KEYLENGTH=${1}
+	    ;;
 	*)
-	# unknown option
-	;;
-esac
-shift
+	    # unknown option
+	    ;;
+    esac
+    shift
 done
 
 if [ ! $HOSTNAME ]; then
-	if [ ! $LETSENCRYPT_HOSTNAME ]; then
-		echo $'No hostname specified'
-		exit 5748
-	fi
+    if [ ! $LETSENCRYPT_HOSTNAME ]; then
+	echo $'No hostname specified'
+	exit 5748
+    fi
 fi
 
 if ! which openssl > /dev/null ;then
-	echo $"$0: openssl is not installed, exiting" 1>&2
-	exit 5689
+    echo $"$0: openssl is not installed, exiting" 1>&2
+    exit 5689
 fi
 
 if [ ! -d /etc/ssl/mycerts ]; then
-	mkdir /etc/ssl/mycerts
+    mkdir /etc/ssl/mycerts
 fi
 
 CERTFILE=$HOSTNAME
 
 function add_cert_letsencrypt {
-	CERTFILE=$LETSENCRYPT_HOSTNAME
+    CERTFILE=$LETSENCRYPT_HOSTNAME
 
-	# obtain the email address for the admin user
-	if [ ! $MY_EMAIL_ADDRESS ]; then
-		if [ -f $CONFIGURATION_FILE ]; then
-			if grep -q "MY_EMAIL_ADDRESS=" $CONFIGURATION_FILE; then
-				MY_EMAIL_ADDRESS=$(cat $CONFIGURATION_FILE | grep "MY_EMAIL_ADDRESS=" | awk -F '=' '{print $2}')
-			fi
-		fi
+    # obtain the email address for the admin user
+    if [ ! $MY_EMAIL_ADDRESS ]; then
+	if [ -f $CONFIGURATION_FILE ]; then
+	    if grep -q "MY_EMAIL_ADDRESS=" $CONFIGURATION_FILE; then
+		MY_EMAIL_ADDRESS=$(cat $CONFIGURATION_FILE | grep "MY_EMAIL_ADDRESS=" | awk -F '=' '{print $2}')
+	    fi
 	fi
-	if [ ! $MY_EMAIL_ADDRESS ]; then
-		if [ -f $COMPLETION_FILE ]; then
-			if grep -q "Admin user:" $COMPLETION_FILE; then
-				ADMIN_USER=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
-				MY_EMAIL_ADDRESS=$ADMIN_USER@$HOSTNAME
-			fi
-		fi
+    fi
+    if [ ! $MY_EMAIL_ADDRESS ]; then
+	if [ -f $COMPLETION_FILE ]; then
+	    if grep -q "Admin user:" $COMPLETION_FILE; then
+		ADMIN_USER=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
+		MY_EMAIL_ADDRESS=$ADMIN_USER@$HOSTNAME
+	    fi
 	fi
+    fi
 
-	if [ ! -d $INSTALL_DIR ]; then
-		mkdir -p $INSTALL_DIR
-	fi
-	cd $INSTALL_DIR
+    if [ ! -d $INSTALL_DIR ]; then
+	mkdir -p $INSTALL_DIR
+    fi
+    cd $INSTALL_DIR
 
-	# obtain the repo
+    # obtain the repo
+    if [ ! -d ${INSTALL_DIR}/letsencrypt ]; then
+	git_clone $LETSENCRYPT_REPO ${INSTALL_DIR}/letsencrypt
 	if [ ! -d ${INSTALL_DIR}/letsencrypt ]; then
-		git_clone $LETSENCRYPT_REPO ${INSTALL_DIR}/letsencrypt
-		if [ ! -d ${INSTALL_DIR}/letsencrypt ]; then
-			exit 76283
-		fi
-	else
-		cd ${INSTALL_DIR}/letsencrypt
-		git_pull $LETSENCRYPT_REPO
+	    exit 76283
 	fi
-
-	# stop the web server
-	systemctl stop nginx
-
+    else
 	cd ${INSTALL_DIR}/letsencrypt
-	./letsencrypt-auto certonly --server $LETSENCRYPT_SERVER --standalone -d $LETSENCRYPT_HOSTNAME --renew-by-default --agree-tos --email $MY_EMAIL_ADDRESS
-	if [ ! "$?" = "0" ]; then
-		echo $"Failed to install letsencrypt for domain $LETSENCRYPT_HOSTNAME"
-		systemctl start nginx
-		exit 63216
-	fi
+	git_pull $LETSENCRYPT_REPO
+    fi
 
-	# replace some legacy filenames
-	if [ -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.bundle.crt ]; then
-		mv /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.bundle.crt /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
-	fi
-	if [ -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.crt ]; then
-		mv /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.crt /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
-	fi
-	sed -i "s|ssl_certificate /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.bundle.crt|ssl_certificate /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem|g" /etc/nginx/sites-available/$LETSENCRYPT_HOSTNAME
-	sed -i "s|ssl_certificate /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.crt|ssl_certificate /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem|g" /etc/nginx/sites-available/$LETSENCRYPT_HOSTNAME
+    # stop the web server
+    systemctl stop nginx
 
-	# link the private key
-	if [ -f /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key ]; then
-		if [ ! -f /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key.old ]; then
-			mv /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key.old
-		else
-			rm -f /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key
-		fi
-	fi
-	ln -s /etc/letsencrypt/live/${LETSENCRYPT_HOSTNAME}/privkey.pem /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key
-
-	# link the public key
-	if [ -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem ]; then
-		if [ ! -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem.old ]; then
-			mv /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem.old
-		else
-			rm -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
-		fi
-	fi
-	ln -s /etc/letsencrypt/live/${LETSENCRYPT_HOSTNAME}/fullchain.pem /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
-
-	cp /etc/letsencrypt/live/${LETSENCRYPT_HOSTNAME}/fullchain.pem /etc/ssl/mycerts/${LETSENCRYPT_HOSTNAME}.pem
-
+    cd ${INSTALL_DIR}/letsencrypt
+    ./letsencrypt-auto certonly --server $LETSENCRYPT_SERVER --standalone -d $LETSENCRYPT_HOSTNAME --renew-by-default --agree-tos --email $MY_EMAIL_ADDRESS
+    if [ ! "$?" = "0" ]; then
+	echo $"Failed to install letsencrypt for domain $LETSENCRYPT_HOSTNAME"
 	systemctl start nginx
+	exit 63216
+    fi
 
-	${PROJECT_NAME}-pin-cert $LETSENCRYPT_HOSTNAME
-	if [ ! "$?" = "0" ]; then
-		echo $"Certificate for $LETSENCRYPT_HOSTNAME could not be pinned"
-		exit 62878
+    # replace some legacy filenames
+    if [ -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.bundle.crt ]; then
+	mv /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.bundle.crt /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
+    fi
+    if [ -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.crt ]; then
+	mv /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.crt /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
+    fi
+    sed -i "s|ssl_certificate /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.bundle.crt|ssl_certificate /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem|g" /etc/nginx/sites-available/$LETSENCRYPT_HOSTNAME
+    sed -i "s|ssl_certificate /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.crt|ssl_certificate /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem|g" /etc/nginx/sites-available/$LETSENCRYPT_HOSTNAME
+
+    # link the private key
+    if [ -f /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key ]; then
+	if [ ! -f /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key.old ]; then
+	    mv /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key.old
+	else
+	    rm -f /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key
 	fi
+    fi
+    ln -s /etc/letsencrypt/live/${LETSENCRYPT_HOSTNAME}/privkey.pem /etc/ssl/private/${LETSENCRYPT_HOSTNAME}.key
+
+    # link the public key
+    if [ -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem ]; then
+	if [ ! -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem.old ]; then
+	    mv /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem.old
+	else
+	    rm -f /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
+	fi
+    fi
+    ln -s /etc/letsencrypt/live/${LETSENCRYPT_HOSTNAME}/fullchain.pem /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
+
+    cp /etc/letsencrypt/live/${LETSENCRYPT_HOSTNAME}/fullchain.pem /etc/ssl/mycerts/${LETSENCRYPT_HOSTNAME}.pem
+
+    systemctl start nginx
+
+    ${PROJECT_NAME}-pin-cert $LETSENCRYPT_HOSTNAME
+    if [ ! "$?" = "0" ]; then
+	echo $"Certificate for $LETSENCRYPT_HOSTNAME could not be pinned"
+	exit 62878
+    fi
 }
 
 function add_cert_selfsigned {
-	if [[ $ORGANISATION == "Freedombone-CA" ]]; then
-		CERTFILE="ca-$HOSTNAME"
-	fi
+    if [[ $ORGANISATION == "Freedombone-CA" ]]; then
+	CERTFILE="ca-$HOSTNAME"
+    fi
 
-	openssl req -x509 ${EXTENSIONS} -nodes -days 3650 -sha256 \
-		-subj "/O=$ORGANISATION/OU=$UNIT/C=$COUNTRY_CODE/ST=$AREA/L=$LOCATION/CN=$HOSTNAME" \
-		-newkey rsa:4096 -keyout /etc/ssl/private/${CERTFILE}.key \
-		-out /etc/ssl/certs/${CERTFILE}.crt
-	chmod 400 /etc/ssl/private/${CERTFILE}.key
-	chmod 640 /etc/ssl/certs/${CERTFILE}.crt
-	cp /etc/ssl/certs/${CERTFILE}.crt /etc/ssl/mycerts
+    openssl req -x509 ${EXTENSIONS} -nodes -days 3650 -sha256 \
+	    -subj "/O=$ORGANISATION/OU=$UNIT/C=$COUNTRY_CODE/ST=$AREA/L=$LOCATION/CN=$HOSTNAME" \
+	    -newkey rsa:4096 -keyout /etc/ssl/private/${CERTFILE}.key \
+	    -out /etc/ssl/certs/${CERTFILE}.crt
+    chmod 400 /etc/ssl/private/${CERTFILE}.key
+    chmod 640 /etc/ssl/certs/${CERTFILE}.crt
+    cp /etc/ssl/certs/${CERTFILE}.crt /etc/ssl/mycerts
 
-	${PROJECT_NAME}-pin-cert $CERTFILE
-	if [ ! "$?" = "0" ]; then
-		echo $"Certificate for $CERTFILE could not be pinned"
-		exit 62879
-	fi
+    ${PROJECT_NAME}-pin-cert $CERTFILE
+    if [ ! "$?" = "0" ]; then
+	echo $"Certificate for $CERTFILE could not be pinned"
+	exit 62879
+    fi
 }
 
 function generate_dh_params {
-	if [ ! $NODH ]; then
-		if [ ! -f /etc/ssl/certs/${CERTFILE}.dhparam ]; then
-			${PROJECT_NAME}-dhparam -h ${CERTFILE} --fast yes
-		fi
+    if [ ! $NODH ]; then
+	if [ ! -f /etc/ssl/certs/${CERTFILE}.dhparam ]; then
+	    ${PROJECT_NAME}-dhparam -h ${CERTFILE} --fast yes
 	fi
+    fi
 }
 
 function restart_web_server {
-	if [ -f /etc/init.d/nginx ]; then
-		/etc/init.d/nginx reload
-	fi
+    if [ -f /etc/init.d/nginx ]; then
+	/etc/init.d/nginx reload
+    fi
 }
 
 function make_cert_bundle {
-	# Create a bundle of your certificates
-	cat /etc/ssl/mycerts/*.crt /etc/ssl/mycerts/*.pem > /etc/ssl/${PROJECT_NAME}-bundle.crt
-	tar -czvf /etc/ssl/${PROJECT_NAME}-certs.tar.gz /etc/ssl/mycerts/*.crt /etc/ssl/mycerts/*.pem
+    # Create a bundle of your certificates
+    cat /etc/ssl/mycerts/*.crt /etc/ssl/mycerts/*.pem > /etc/ssl/${PROJECT_NAME}-bundle.crt
+    tar -czvf /etc/ssl/${PROJECT_NAME}-certs.tar.gz /etc/ssl/mycerts/*.crt /etc/ssl/mycerts/*.pem
 }
 
 function create_cert {
-	if [ $LETSENCRYPT_HOSTNAME ]; then
-		add_cert_letsencrypt
-	else
-		add_cert_selfsigned
-	fi
+    if [ $LETSENCRYPT_HOSTNAME ]; then
+	add_cert_letsencrypt
+    else
+	add_cert_selfsigned
+    fi
 }
 
 read_repo_servers
diff --git a/src/freedombone-app-batman b/src/freedombone-app-batman
--- a/src/freedombone-app-batman
+++ b/src/freedombone-app-batman
@@ -34,16 +34,16 @@ ENABLE_BATMAN="no"
 BATMAN_CELLID='any'
 
 function configure_firewall_for_batma {
-	if grep -Fxq "configure_firewall_for_batman" $COMPLETION_FILE; then
-		return
-	fi
-	if [[ $ENABLE_BATMAN != "yes" ]]; then
-		return
-	fi
+    if grep -Fxq "configure_firewall_for_batman" $COMPLETION_FILE; then
+	return
+    fi
+    if [[ $ENABLE_BATMAN != "yes" ]]; then
+	return
+    fi
 
-	function_check save_firewall_settings
-	save_firewall_settings
-	echo 'configure_firewall_for_batman' >> $COMPLETION_FILE
+    function_check save_firewall_settings
+    save_firewall_settings
+    echo 'configure_firewall_for_batman' >> $COMPLETION_FILE
 }
 
 function reconfigure_batman {
@@ -71,90 +71,90 @@ function restore_remote_batman {
 }
 
 function remove_batman {
-	if ! grep -Fxq "install_batman" $COMPLETION_FILE; then
-		return
-	fi
+    if ! grep -Fxq "install_batman" $COMPLETION_FILE; then
+	return
+    fi
 
-	${PROJECT_NAME}-mesh-install -f batman --remove yes
-	if [ ! "$?" = "0" ]; then
-		echo $'Failed to remove batman'
-		exit 79353
-	fi
-	sed -i '/install_batman/d' $COMPLETION_FILE
-	sed -i '/configure_firewall_for_batman/d' $COMPLETION_FILE
+    ${PROJECT_NAME}-mesh-install -f batman --remove yes
+    if [ ! "$?" = "0" ]; then
+	echo $'Failed to remove batman'
+	exit 79353
+    fi
+    sed -i '/install_batman/d' $COMPLETION_FILE
+    sed -i '/configure_firewall_for_batman/d' $COMPLETION_FILE
 }
 
 function mesh_install_batman {
-	chroot "$rootdir" apt-get -y install iproute bridge-utils libnetfilter-conntrack3 batctl
-	chroot "$rootdir" apt-get -y install python-dev libevent-dev ebtables python-pip git
-	chroot "$rootdir" apt-get -y install wireless-tools rfkill
+    chroot "$rootdir" apt-get -y install iproute bridge-utils libnetfilter-conntrack3 batctl
+    chroot "$rootdir" apt-get -y install python-dev libevent-dev ebtables python-pip git
+    chroot "$rootdir" apt-get -y install wireless-tools rfkill
 
-	if ! grep -q "batman_adv" $rootdir/etc/modules; then
-		echo 'batman_adv' >> $rootdir/etc/modules
-	fi
+    if ! grep -q "batman_adv" $rootdir/etc/modules; then
+	echo 'batman_adv' >> $rootdir/etc/modules
+    fi
 
-	BATMAN_SCRIPT=$rootdir/var/lib/batman
+    BATMAN_SCRIPT=$rootdir/var/lib/batman
 
-	if [ -f /usr/local/bin/${PROJECT_NAME}-mesh-batman ]; then
-		cp /usr/local/bin/${PROJECT_NAME}-mesh-batman $BATMAN_SCRIPT
-	else
-		cp /usr/bin/${PROJECT_NAME}-mesh-batman $BATMAN_SCRIPT
-	fi
+    if [ -f /usr/local/bin/${PROJECT_NAME}-mesh-batman ]; then
+	cp /usr/local/bin/${PROJECT_NAME}-mesh-batman $BATMAN_SCRIPT
+    else
+	cp /usr/bin/${PROJECT_NAME}-mesh-batman $BATMAN_SCRIPT
+    fi
 
-	BATMAN_DAEMON=$rootdir/etc/systemd/system/batman.service
-	echo '[Unit]' > $BATMAN_DAEMON
-	echo 'Description=B.A.T.M.A.N. Advanced' >> $BATMAN_DAEMON
-	echo 'After=network.target' >> $BATMAN_DAEMON
-	echo '' >> $BATMAN_DAEMON
-	echo '[Service]' >> $BATMAN_DAEMON
-	echo 'RemainAfterExit=yes' >> $BATMAN_DAEMON
-	echo "ExecStart=/var/lib/batman start" >> $BATMAN_DAEMON
-	echo "ExecStop=/var/lib/batman stop" >> $BATMAN_DAEMON
-	echo 'Restart=on-failure' >> $BATMAN_DAEMON
-	echo 'SuccessExitStatus=3 4' >> $BATMAN_DAEMON
-	echo 'RestartForceExitStatus=3 4' >> $BATMAN_DAEMON
-	echo '' >> $BATMAN_DAEMON
-	echo '# Allow time for the server to start/stop' >> $BATMAN_DAEMON
-	echo 'TimeoutSec=300' >> $BATMAN_DAEMON
-	echo '' >> $BATMAN_DAEMON
-	echo '[Install]' >> $BATMAN_DAEMON
-	echo 'WantedBy=multi-user.target' >> $BATMAN_DAEMON
-	chroot "$rootdir" systemctl enable batman
+    BATMAN_DAEMON=$rootdir/etc/systemd/system/batman.service
+    echo '[Unit]' > $BATMAN_DAEMON
+    echo 'Description=B.A.T.M.A.N. Advanced' >> $BATMAN_DAEMON
+    echo 'After=network.target' >> $BATMAN_DAEMON
+    echo '' >> $BATMAN_DAEMON
+    echo '[Service]' >> $BATMAN_DAEMON
+    echo 'RemainAfterExit=yes' >> $BATMAN_DAEMON
+    echo "ExecStart=/var/lib/batman start" >> $BATMAN_DAEMON
+    echo "ExecStop=/var/lib/batman stop" >> $BATMAN_DAEMON
+    echo 'Restart=on-failure' >> $BATMAN_DAEMON
+    echo 'SuccessExitStatus=3 4' >> $BATMAN_DAEMON
+    echo 'RestartForceExitStatus=3 4' >> $BATMAN_DAEMON
+    echo '' >> $BATMAN_DAEMON
+    echo '# Allow time for the server to start/stop' >> $BATMAN_DAEMON
+    echo 'TimeoutSec=300' >> $BATMAN_DAEMON
+    echo '' >> $BATMAN_DAEMON
+    echo '[Install]' >> $BATMAN_DAEMON
+    echo 'WantedBy=multi-user.target' >> $BATMAN_DAEMON
+    chroot "$rootdir" systemctl enable batman
 }
 
 function install_batman {
-	if [ $INSTALLING_MESH ]; then
-		mesh_install_batman
-		return
-	fi
-	if grep -Fxq "install_batman" $COMPLETION_FILE; then
-		return
-	fi
-	if [[ $ENABLE_BATMAN != "yes" ]]; then
-		return
-	fi
+    if [ $INSTALLING_MESH ]; then
+	mesh_install_batman
+	return
+    fi
+    if grep -Fxq "install_batman" $COMPLETION_FILE; then
+	return
+    fi
+    if [[ $ENABLE_BATMAN != "yes" ]]; then
+	return
+    fi
 
-	${PROJECT_NAME}-mesh-install -f batman
-	if [ ! "$?" = "0" ]; then
-		echo $'Failed to install batman'
-		exit 72524
-	fi
+    ${PROJECT_NAME}-mesh-install -f batman
+    if [ ! "$?" = "0" ]; then
+	echo $'Failed to install batman'
+	exit 72524
+    fi
 
-	if ! grep -q "Mesh Networking (B.A.T.M.A.N)" /home/$MY_USERNAME/README; then
-		echo '' >> /home/$MY_USERNAME/README
-		echo '' >> /home/$MY_USERNAME/README
-		echo 'Mesh Networking (B.A.T.M.A.N)' >> /home/$MY_USERNAME/README
-		echo '=============================' >> /home/$MY_USERNAME/README
-		echo "Mesh ESSID: $WIFI_SSID" >> /home/$MY_USERNAME/README
-		echo "Mesh cell ID: $BATMAN_CELLID" >> /home/$MY_USERNAME/README
-		echo "Mesh wifi channel: $WIFI_CHANNEL" >> /home/$MY_USERNAME/README
-		chown $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/README
-		chmod 600 /home/$MY_USERNAME/README
-	fi
+    if ! grep -q "Mesh Networking (B.A.T.M.A.N)" /home/$MY_USERNAME/README; then
+	echo '' >> /home/$MY_USERNAME/README
+	echo '' >> /home/$MY_USERNAME/README
+	echo 'Mesh Networking (B.A.T.M.A.N)' >> /home/$MY_USERNAME/README
+	echo '=============================' >> /home/$MY_USERNAME/README
+	echo "Mesh ESSID: $WIFI_SSID" >> /home/$MY_USERNAME/README
+	echo "Mesh cell ID: $BATMAN_CELLID" >> /home/$MY_USERNAME/README
+	echo "Mesh wifi channel: $WIFI_CHANNEL" >> /home/$MY_USERNAME/README
+	chown $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/README
+	chmod 600 /home/$MY_USERNAME/README
+    fi
 
-	function_check configure_firewall_for_batman
-	configure_firewall_for_batman
-	echo 'install_batman' >> $COMPLETION_FILE
+    function_check configure_firewall_for_batman
+    configure_firewall_for_batman
+    echo 'install_batman' >> $COMPLETION_FILE
 }
 
 # NOTE: deliberately no exit 0
diff --git a/src/freedombone-app-dlna b/src/freedombone-app-dlna
--- a/src/freedombone-app-dlna
+++ b/src/freedombone-app-dlna
@@ -31,205 +31,205 @@
 VARIANTS='full media'
 
 function reconfigure_dlna {
-	echo ''
+    echo ''
 }
 
 function upgrade_dlna {
-	echo ''
+    echo ''
 }
 
 function configure_firewall_for_dlna {
-	if grep -Fxq "configure_firewall_for_dlna" $COMPLETION_FILE; then
-		return
-	fi
-	if [[ $INSTALLED_WITHIN_DOCKER == "yes" ]]; then
-		# docker does its own firewalling
-		return
-	fi
-	iptables -A INPUT -p udp --dport 1900 -j ACCEPT
-	iptables -A INPUT -p tcp --dport 8200 -j ACCEPT
-	function_check save_firewall_settings
-	save_firewall_settings
+    if grep -Fxq "configure_firewall_for_dlna" $COMPLETION_FILE; then
+	return
+    fi
+    if [[ $INSTALLED_WITHIN_DOCKER == "yes" ]]; then
+	# docker does its own firewalling
+	return
+    fi
+    iptables -A INPUT -p udp --dport 1900 -j ACCEPT
+    iptables -A INPUT -p tcp --dport 8200 -j ACCEPT
+    function_check save_firewall_settings
+    save_firewall_settings
 
-	OPEN_PORTS+=('DLNA     1900')
-	OPEN_PORTS+=('DLNA     8200')
-	echo 'configure_firewall_for_dlna' >> $COMPLETION_FILE
+    OPEN_PORTS+=('DLNA     1900')
+    OPEN_PORTS+=('DLNA     8200')
+    echo 'configure_firewall_for_dlna' >> $COMPLETION_FILE
 }
 
 function backup_local_dlna {
-	source_directory=/var/cache/minidlna
-	if [ -d $source_directory ]; then
-		dest_directory=dlna
-		echo $"Backing up $source_directory to $dest_directory"
+    source_directory=/var/cache/minidlna
+    if [ -d $source_directory ]; then
+	dest_directory=dlna
+	echo $"Backing up $source_directory to $dest_directory"
 
-		function_check backup_directory_to_usb
-		backup_directory_to_usb $source_directory $dest_directory
+	function_check backup_directory_to_usb
+	backup_directory_to_usb $source_directory $dest_directory
 
-		echo $"Backup to $dest_directory complete"
-	fi
+	echo $"Backup to $dest_directory complete"
+    fi
 }
 
 function restore_local_dlna {
-	if [ -d /var/cache/minidlna ]; then
-		if [ -d $USB_MOUNT/backup/dlna ]; then
-			echo $"Restoring DLNA cache"
-			temp_restore_dir=/root/tempdlna
-			function_check restore_directory_from_usb
-			restore_directory_from_usb $temp_restore_dir dlna
-			cp -r $temp_restore_dir/var/cache/minidlna/* /var/cache/minidlna/
-			if [ ! "$?" = "0" ]; then
-				rm -rf $temp_restore_dir
-				function_check set_user_permissions
-				set_user_permissions
-				function_check backup_unmount_drive
-				backup_unmount_drive
-				exit 982572
-			fi
-			rm -rf $temp_restore_dir
-		fi
+    if [ -d /var/cache/minidlna ]; then
+	if [ -d $USB_MOUNT/backup/dlna ]; then
+	    echo $"Restoring DLNA cache"
+	    temp_restore_dir=/root/tempdlna
+	    function_check restore_directory_from_usb
+	    restore_directory_from_usb $temp_restore_dir dlna
+	    cp -r $temp_restore_dir/var/cache/minidlna/* /var/cache/minidlna/
+	    if [ ! "$?" = "0" ]; then
+		rm -rf $temp_restore_dir
+		function_check set_user_permissions
+		set_user_permissions
+		function_check backup_unmount_drive
+		backup_unmount_drive
+		exit 982572
+	    fi
+	    rm -rf $temp_restore_dir
 	fi
+    fi
 }
 
 function backup_remote_dlna {
-	if [ -d /var/cache/minidlna ]; then
-		echo $"Backing up DLNA cache"
-		backup_directory_to_friend /var/cache/minidlna dlna
-		echo $"Backup of DLNA cache complete"
-	fi
+    if [ -d /var/cache/minidlna ]; then
+	echo $"Backing up DLNA cache"
+	backup_directory_to_friend /var/cache/minidlna dlna
+	echo $"Backup of DLNA cache complete"
+    fi
 }
 
 function restore_remote_dlna {
-	if [ -d /var/cache/minidlna ]; then
-		if [ -d $SERVER_DIRECTORY/backup/dlna ]; then
-			echo $"Restoring DLNA cache"
-			temp_restore_dir=/root/tempdlna
-			function_check restore_directory_from_friend
-			restore_directory_from_friend $temp_restore_dir dlna
-			cp -r $temp_restore_dir/var/cache/minidlna/* /var/cache/minidlna/
-			if [ ! "$?" = "0" ]; then
-				exit 982
-			fi
-			rm -rf $temp_restore_dir
-			echo $"Restore of DLNA complete"
-		fi
+    if [ -d /var/cache/minidlna ]; then
+	if [ -d $SERVER_DIRECTORY/backup/dlna ]; then
+	    echo $"Restoring DLNA cache"
+	    temp_restore_dir=/root/tempdlna
+	    function_check restore_directory_from_friend
+	    restore_directory_from_friend $temp_restore_dir dlna
+	    cp -r $temp_restore_dir/var/cache/minidlna/* /var/cache/minidlna/
+	    if [ ! "$?" = "0" ]; then
+		exit 982
+	    fi
+	    rm -rf $temp_restore_dir
+	    echo $"Restore of DLNA complete"
 	fi
+    fi
 }
 
 function remove_dlna {
-	if ! grep -Fxq "install_dlna" $COMPLETION_FILE; then
-		return
-	fi
-	service minidlna stop
-	apt-get -y remove --purge minidlna
-	if [ -f /etc/minidlna.conf ]; then
-		rm /etc/minidlna.conf
-	fi
-	iptables -D INPUT -p udp --dport 1900 -j ACCEPT
-	iptables -D INPUT -p tcp --dport 8200 -j ACCEPT
-	function_check save_firewall_settings
-	save_firewall_settings
-	sed -i '/install_dlna/d' $COMPLETION_FILE
+    if ! grep -Fxq "install_dlna" $COMPLETION_FILE; then
+	return
+    fi
+    service minidlna stop
+    apt-get -y remove --purge minidlna
+    if [ -f /etc/minidlna.conf ]; then
+	rm /etc/minidlna.conf
+    fi
+    iptables -D INPUT -p udp --dport 1900 -j ACCEPT
+    iptables -D INPUT -p tcp --dport 8200 -j ACCEPT
+    function_check save_firewall_settings
+    save_firewall_settings
+    sed -i '/install_dlna/d' $COMPLETION_FILE
 }
 
 function install_dlna_main {
-	if grep -Fxq "install_dlna_main" $COMPLETION_FILE; then
-		return
-	fi
+    if grep -Fxq "install_dlna_main" $COMPLETION_FILE; then
+	return
+    fi
 
-	apt-get -y install minidlna
+    apt-get -y install minidlna
 
-	if [ ! -f /etc/minidlna.conf ]; then
-		echo $"ERROR: minidlna does not appear to have installed. $CHECK_MESSAGE"
-		exit 55
-	fi
+    if [ ! -f /etc/minidlna.conf ]; then
+	echo $"ERROR: minidlna does not appear to have installed. $CHECK_MESSAGE"
+	exit 55
+    fi
 
-	sed -i "s|media_dir=/var/lib/minidlna|media_dir=A,/home/$MY_USERNAME/Music|g" /etc/minidlna.conf
-	if ! grep -q "/home/$MY_USERNAME/Pictures" /etc/minidlna.conf; then
-		echo "media_dir=P,/home/$MY_USERNAME/Pictures" >> /etc/minidlna.conf
-	fi
-	if ! grep -q "/home/$MY_USERNAME/Videos" /etc/minidlna.conf; then
-		echo "media_dir=V,/home/$MY_USERNAME/Videos" >> /etc/minidlna.conf
-	fi
-	if ! grep -q "$USB_MOUNT/Music" /etc/minidlna.conf; then
-		echo "media_dir=A,$USB_MOUNT/Music" >> /etc/minidlna.conf
-	fi
-	if ! grep -q "$USB_MOUNT/Pictures" /etc/minidlna.conf; then
-		echo "media_dir=P,$USB_MOUNT/Pictures" >> /etc/minidlna.conf
-	fi
-	if ! grep -q "$USB_MOUNT/Videos" /etc/minidlna.conf; then
-		echo "media_dir=V,$USB_MOUNT/Videos" >> /etc/minidlna.conf
-	fi
-	sed -i 's/#root_container=./root_container=B/g' /etc/minidlna.conf
-	if [[ $SYSTEM_TYPE != "$VARIANT_MESH" ]]; then
-		sed -i 's/#network_interface=/network_interface=eth0/g' /etc/minidlna.conf
-	else
-		sed -i 's/#network_interface=/network_interface=$WIFI_INTERFACE/g' /etc/minidlna.conf
-	fi
-	sed -i "s/#friendly_name=/friendly_name=\"${PROJECT_NAME} Media\"/g" /etc/minidlna.conf
-	sed -i 's|#db_dir=/var/cache/minidlna|db_dir=/var/cache/minidlna|g' /etc/minidlna.conf
-	sed -i 's/#inotify=yes/inotify=yes/g' /etc/minidlna.conf
-	sed -i 's/#notify_interval=895/notify_interval=300/g' /etc/minidlna.conf
-	sed -i "s|#presentation_url=/|presentation_url=http://localhost:8200|g" /etc/minidlna.conf
-	service minidlna force-reload
-	service minidlna reload
+    sed -i "s|media_dir=/var/lib/minidlna|media_dir=A,/home/$MY_USERNAME/Music|g" /etc/minidlna.conf
+    if ! grep -q "/home/$MY_USERNAME/Pictures" /etc/minidlna.conf; then
+	echo "media_dir=P,/home/$MY_USERNAME/Pictures" >> /etc/minidlna.conf
+    fi
+    if ! grep -q "/home/$MY_USERNAME/Videos" /etc/minidlna.conf; then
+	echo "media_dir=V,/home/$MY_USERNAME/Videos" >> /etc/minidlna.conf
+    fi
+    if ! grep -q "$USB_MOUNT/Music" /etc/minidlna.conf; then
+	echo "media_dir=A,$USB_MOUNT/Music" >> /etc/minidlna.conf
+    fi
+    if ! grep -q "$USB_MOUNT/Pictures" /etc/minidlna.conf; then
+	echo "media_dir=P,$USB_MOUNT/Pictures" >> /etc/minidlna.conf
+    fi
+    if ! grep -q "$USB_MOUNT/Videos" /etc/minidlna.conf; then
+	echo "media_dir=V,$USB_MOUNT/Videos" >> /etc/minidlna.conf
+    fi
+    sed -i 's/#root_container=./root_container=B/g' /etc/minidlna.conf
+    if [[ $SYSTEM_TYPE != "$VARIANT_MESH" ]]; then
+	sed -i 's/#network_interface=/network_interface=eth0/g' /etc/minidlna.conf
+    else
+	sed -i 's/#network_interface=/network_interface=$WIFI_INTERFACE/g' /etc/minidlna.conf
+    fi
+    sed -i "s/#friendly_name=/friendly_name=\"${PROJECT_NAME} Media\"/g" /etc/minidlna.conf
+    sed -i 's|#db_dir=/var/cache/minidlna|db_dir=/var/cache/minidlna|g' /etc/minidlna.conf
+    sed -i 's/#inotify=yes/inotify=yes/g' /etc/minidlna.conf
+    sed -i 's/#notify_interval=895/notify_interval=300/g' /etc/minidlna.conf
+    sed -i "s|#presentation_url=/|presentation_url=http://localhost:8200|g" /etc/minidlna.conf
+    service minidlna force-reload
+    service minidlna reload
 
-	sed -i 's/fs.inotify.max_user_watches*/fs.inotify.max_user_watches=65536/g' /etc/sysctl.conf
-	if ! grep -q "max_user_watches" $COMPLETION_FILE; then
-		echo 'fs.inotify.max_user_watches=65536' >> /etc/sysctl.conf
-	fi
-	/sbin/sysctl -p
+    sed -i 's/fs.inotify.max_user_watches*/fs.inotify.max_user_watches=65536/g' /etc/sysctl.conf
+    if ! grep -q "max_user_watches" $COMPLETION_FILE; then
+	echo 'fs.inotify.max_user_watches=65536' >> /etc/sysctl.conf
+    fi
+    /sbin/sysctl -p
 
-	function_check configure_firewall_for_dlna
-	configure_firewall_for_dlna
-	echo 'install_dlna_main' >> $COMPLETION_FILE
+    function_check configure_firewall_for_dlna
+    configure_firewall_for_dlna
+    echo 'install_dlna_main' >> $COMPLETION_FILE
 }
 
 function script_for_attaching_usb_drive {
-	if grep -Fxq "script_for_attaching_usb_drive" $COMPLETION_FILE; then
-		return
-	fi
-	echo '#!/bin/bash' > /usr/bin/attach-music
-	echo 'remove-music' >> /usr/bin/attach-music
-	echo "if [ ! -d $USB_MOUNT ]; then" >> /usr/bin/attach-music
-	echo "  mkdir $USB_MOUNT" >> /usr/bin/attach-music
-	echo 'fi' >> /usr/bin/attach-music
-	echo "mount /dev/sda1 $USB_MOUNT" >> /usr/bin/attach-music
-	echo "chown root:root $USB_MOUNT" >> /usr/bin/attach-music
-	echo "chown -R minidlna:minidlna $USB_MOUNT/*" >> /usr/bin/attach-music
-	echo 'service minidlna restart' >> /usr/bin/attach-music
-	echo 'minidlnad -R' >> /usr/bin/attach-music
-	chmod +x /usr/bin/attach-music
-	ln -s /usr/bin/attach-music /usr/bin/attach-usb
-	ln -s /usr/bin/attach-music /usr/bin/attach-videos
-	ln -s /usr/bin/attach-music /usr/bin/attach-pictures
-	ln -s /usr/bin/attach-music /usr/bin/attach-media
+    if grep -Fxq "script_for_attaching_usb_drive" $COMPLETION_FILE; then
+	return
+    fi
+    echo '#!/bin/bash' > /usr/bin/attach-music
+    echo 'remove-music' >> /usr/bin/attach-music
+    echo "if [ ! -d $USB_MOUNT ]; then" >> /usr/bin/attach-music
+    echo "  mkdir $USB_MOUNT" >> /usr/bin/attach-music
+    echo 'fi' >> /usr/bin/attach-music
+    echo "mount /dev/sda1 $USB_MOUNT" >> /usr/bin/attach-music
+    echo "chown root:root $USB_MOUNT" >> /usr/bin/attach-music
+    echo "chown -R minidlna:minidlna $USB_MOUNT/*" >> /usr/bin/attach-music
+    echo 'service minidlna restart' >> /usr/bin/attach-music
+    echo 'minidlnad -R' >> /usr/bin/attach-music
+    chmod +x /usr/bin/attach-music
+    ln -s /usr/bin/attach-music /usr/bin/attach-usb
+    ln -s /usr/bin/attach-music /usr/bin/attach-videos
+    ln -s /usr/bin/attach-music /usr/bin/attach-pictures
+    ln -s /usr/bin/attach-music /usr/bin/attach-media
 
-	echo '#!/bin/bash' > /usr/bin/remove-music
-	echo "if [ -d $USB_MOUNT ]; then" >> /usr/bin/remove-music
-	echo "  umount $USB_MOUNT" >> /usr/bin/remove-music
-	echo "  rm -rf $USB_MOUNT" >> /usr/bin/remove-music
-	echo 'fi' >> /usr/bin/remove-music
-	chmod +x /usr/bin/remove-music
-	ln -s /usr/bin/remove-music /usr/bin/detach-music
-	ln -s /usr/bin/remove-music /usr/bin/detach-usb
-	ln -s /usr/bin/remove-music /usr/bin/remove-usb
-	ln -s /usr/bin/remove-music /usr/bin/detach-media
-	ln -s /usr/bin/remove-music /usr/bin/remove-media
-	ln -s /usr/bin/remove-music /usr/bin/detach-videos
-	ln -s /usr/bin/remove-music /usr/bin/remove-videos
-	ln -s /usr/bin/remove-music /usr/bin/detach-pictures
-	ln -s /usr/bin/remove-music /usr/bin/remove-pictures
+    echo '#!/bin/bash' > /usr/bin/remove-music
+    echo "if [ -d $USB_MOUNT ]; then" >> /usr/bin/remove-music
+    echo "  umount $USB_MOUNT" >> /usr/bin/remove-music
+    echo "  rm -rf $USB_MOUNT" >> /usr/bin/remove-music
+    echo 'fi' >> /usr/bin/remove-music
+    chmod +x /usr/bin/remove-music
+    ln -s /usr/bin/remove-music /usr/bin/detach-music
+    ln -s /usr/bin/remove-music /usr/bin/detach-usb
+    ln -s /usr/bin/remove-music /usr/bin/remove-usb
+    ln -s /usr/bin/remove-music /usr/bin/detach-media
+    ln -s /usr/bin/remove-music /usr/bin/remove-media
+    ln -s /usr/bin/remove-music /usr/bin/detach-videos
+    ln -s /usr/bin/remove-music /usr/bin/remove-videos
+    ln -s /usr/bin/remove-music /usr/bin/detach-pictures
+    ln -s /usr/bin/remove-music /usr/bin/remove-pictures
 
-	echo 'script_for_attaching_usb_drive' >> $COMPLETION_FILE
+    echo 'script_for_attaching_usb_drive' >> $COMPLETION_FILE
 }
 
 function install_dlna {
-	if grep -Fxq "install_dlna" $COMPLETION_FILE; then
-		return
-	fi
-	install_dlna_main
-	script_for_attaching_usb_drive
-	echo 'install_dlna' >> $COMPLETION_FILE
+    if grep -Fxq "install_dlna" $COMPLETION_FILE; then
+	return
+    fi
+    install_dlna_main
+    script_for_attaching_usb_drive
+    echo 'install_dlna' >> $COMPLETION_FILE
 }
 
 # NOTE: deliberately no exit 0
diff --git a/src/freedombone-app-ipfs b/src/freedombone-app-ipfs
--- a/src/freedombone-app-ipfs
+++ b/src/freedombone-app-ipfs
@@ -35,251 +35,251 @@ IPFS_COMMIT='20b06a4cbce8884f5b194da6e98cb11f2c77f166'
 IPFS_PORT=4001
 
 function reconfigure_ipfs {
-	echo -n ''
+    echo -n ''
 }
 
 function upgrade_ipfs {
-	if ! grep -Fxq "install_ipfs" $COMPLETION_FILE; then
-		return
-	fi
+    if ! grep -Fxq "install_ipfs" $COMPLETION_FILE; then
+	return
+    fi
 
-	function_check select_go_version
-	select_go_version
+    function_check select_go_version
+    select_go_version
 
-	function_check set_repo_commit
-	set_repo_commit $GOPATH/src/github.com/ipfs/go-ipfs "ipfs commit" "$IPFS_COMMIT" $IPFS_REPO
+    function_check set_repo_commit
+    set_repo_commit $GOPATH/src/github.com/ipfs/go-ipfs "ipfs commit" "$IPFS_COMMIT" $IPFS_REPO
 }
 
 function backup_local_ipfs {
-	if ! grep -q "Admin user" $COMPLETION_FILE; then
-		return
-	fi
-	ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
-	source_directory=/home/$ADMIN_USERNAME/.ipfs
-	if [ -d $source_directory ]; then
-		dest_directory=ipfs
-		echo $"Backing up $source_directory to $dest_directory"
+    if ! grep -q "Admin user" $COMPLETION_FILE; then
+	return
+    fi
+    ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
+    source_directory=/home/$ADMIN_USERNAME/.ipfs
+    if [ -d $source_directory ]; then
+	dest_directory=ipfs
+	echo $"Backing up $source_directory to $dest_directory"
 
-		function_check backup_directory_to_usb
-		backup_directory_to_usb $source_directory $dest_directory
+	function_check backup_directory_to_usb
+	backup_directory_to_usb $source_directory $dest_directory
 
-		echo $"Backup to $dest_directory complete"
-	fi
+	echo $"Backup to $dest_directory complete"
+    fi
 }
 
 function restore_local_ipfs {
-	if ! grep -q "Admin user" $COMPLETION_FILE; then
-		return
+    if ! grep -q "Admin user" $COMPLETION_FILE; then
+	return
+    fi
+    if [ -d $USB_MOUNT/backup/ipfs ]; then
+	echo $"Restoring IPFS"
+	temp_restore_dir=/root/tempipfs
+	function_check restore_directory_from_usb
+	restore_directory_from_usb $temp_restore_dir ipfs
+	ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
+	cp -rf $temp_restore_dir/home/$ADMIN_USERNAME/.ipfs/* /home/$ADMIN_USERNAME/.ipfs
+	if [ ! "$?" = "0" ]; then
+	    rm -rf $temp_restore_dir
+	    function_check set_user_permissions
+	    set_user_permissions
+	    function_check backup_unmount_drive
+	    backup_unmount_drive
+	    exit 27627
 	fi
-	if [ -d $USB_MOUNT/backup/ipfs ]; then
-		echo $"Restoring IPFS"
-		temp_restore_dir=/root/tempipfs
-		function_check restore_directory_from_usb
-		restore_directory_from_usb $temp_restore_dir ipfs
-		ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
-		cp -rf $temp_restore_dir/home/$ADMIN_USERNAME/.ipfs/* /home/$ADMIN_USERNAME/.ipfs
-		if [ ! "$?" = "0" ]; then
-			rm -rf $temp_restore_dir
-			function_check set_user_permissions
-			set_user_permissions
-			function_check backup_unmount_drive
-			backup_unmount_drive
-			exit 27627
-		fi
-		rm -rf $temp_restore_dir
-		echo $"Restore of IPFS complete"
-	fi
+	rm -rf $temp_restore_dir
+	echo $"Restore of IPFS complete"
+    fi
 }
 
 function backup_remote_ipfs {
-	if ! grep -q "Admin user" $COMPLETION_FILE; then
-		return
-	fi
-	ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
-	if [ -d /home/$ADMIN_USERNAME/.ipfs ]; then
-		echo $"Backing up IPFS"
-		backup_directory_to_friend /home/$ADMIN_USERNAME/.ipfs ipfs
-		echo $"Backup of IPFS complete"
-	fi
+    if ! grep -q "Admin user" $COMPLETION_FILE; then
+	return
+    fi
+    ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
+    if [ -d /home/$ADMIN_USERNAME/.ipfs ]; then
+	echo $"Backing up IPFS"
+	backup_directory_to_friend /home/$ADMIN_USERNAME/.ipfs ipfs
+	echo $"Backup of IPFS complete"
+    fi
 }
 
 function restore_remote_ipfs {
-	if [ -d $SERVER_DIRECTORY/backup/ipfs ]; then
-		echo $"Restoring IPFS"
-		temp_restore_dir=/root/tempipfs
-		function_check restore_directory_from_friend
-		restore_directory_from_friend $temp_restore_dir ipfs
-		cp -rf $temp_restore_dir/home/$ADMIN_USERNAME/.ipfs/* /home/$ADMIN_USERNAME/.ipfs
-		if [ ! "$?" = "0" ]; then
-			function_check set_user_permissions
-			set_user_permissions
-			rm -rf $temp_restore_dir
-			exit 276357
-		fi
-		rm -rf $temp_restore_dir
-		echo $"Restore of IPFS complete"
+    if [ -d $SERVER_DIRECTORY/backup/ipfs ]; then
+	echo $"Restoring IPFS"
+	temp_restore_dir=/root/tempipfs
+	function_check restore_directory_from_friend
+	restore_directory_from_friend $temp_restore_dir ipfs
+	cp -rf $temp_restore_dir/home/$ADMIN_USERNAME/.ipfs/* /home/$ADMIN_USERNAME/.ipfs
+	if [ ! "$?" = "0" ]; then
+	    function_check set_user_permissions
+	    set_user_permissions
+	    rm -rf $temp_restore_dir
+	    exit 276357
 	fi
+	rm -rf $temp_restore_dir
+	echo $"Restore of IPFS complete"
+    fi
 }
 
 function remove_ipfs {
-	if ! grep -Fxq "install_ipfs" $COMPLETION_FILE; then
-		return
-	fi
-	function_check select_go_version
-	select_go_version
-	systemctl stop ipfs
-	systemctl disable ipfs
-	systemctl daemon-reload
-	rm /etc/systemd/system/ipfs.service
-	rm -rf $GOPATH/src/github.com/ipfs
-	iptables -D INPUT -p tcp --dport $IPFS_PORT -j ACCEPT
-	function_check save_firewall_settings
-	save_firewall_settings
-	sed -i '/install_ipfs/d' $COMPLETION_FILE
-	sed -i '/ipfs /d' $COMPLETION_FILE
-	sed -i '/configure_firewall_for_ipfs/d' $COMPLETION_FILE
+    if ! grep -Fxq "install_ipfs" $COMPLETION_FILE; then
+	return
+    fi
+    function_check select_go_version
+    select_go_version
+    systemctl stop ipfs
+    systemctl disable ipfs
+    systemctl daemon-reload
+    rm /etc/systemd/system/ipfs.service
+    rm -rf $GOPATH/src/github.com/ipfs
+    iptables -D INPUT -p tcp --dport $IPFS_PORT -j ACCEPT
+    function_check save_firewall_settings
+    save_firewall_settings
+    sed -i '/install_ipfs/d' $COMPLETION_FILE
+    sed -i '/ipfs /d' $COMPLETION_FILE
+    sed -i '/configure_firewall_for_ipfs/d' $COMPLETION_FILE
 }
 
 function configure_firewall_for_ipfs {
-	if grep -Fxq "configure_firewall_for_ipfs" $COMPLETION_FILE; then
-		return
-	fi
-	if [[ $ONION_ONLY != "no" ]]; then
-		return
-	fi
-	iptables -A INPUT -p tcp --dport $IPFS_PORT -j ACCEPT
-	function_check save_firewall_settings
-	save_firewall_settings
+    if grep -Fxq "configure_firewall_for_ipfs" $COMPLETION_FILE; then
+	return
+    fi
+    if [[ $ONION_ONLY != "no" ]]; then
+	return
+    fi
+    iptables -A INPUT -p tcp --dport $IPFS_PORT -j ACCEPT
+    function_check save_firewall_settings
+    save_firewall_settings
 
-	OPEN_PORTS+=("IPFS     $IPFS_PORT")
-	echo 'configure_firewall_for_ipfs' >> $COMPLETION_FILE
+    OPEN_PORTS+=("IPFS     $IPFS_PORT")
+    echo 'configure_firewall_for_ipfs' >> $COMPLETION_FILE
 }
 
 function install_ipfs {
-	if grep -Fxq "install_ipfs" $COMPLETION_FILE; then
-		return
-	fi
+    if grep -Fxq "install_ipfs" $COMPLETION_FILE; then
+	return
+    fi
 
-	function_check select_go_version
-	select_go_version
+    function_check select_go_version
+    select_go_version
 
-	apt-get -y install golang libpam0g-dev fuse
+    apt-get -y install golang libpam0g-dev fuse
 
-	if [ ! -d /home/git ]; then
-		# add a gogs user account
-		adduser --disabled-login --gecos 'Gogs' git
+    if [ ! -d /home/git ]; then
+	# add a gogs user account
+	adduser --disabled-login --gecos 'Gogs' git
 
-		# install Go
-		if ! grep -q "export GOPATH=" ~/.bashrc; then
-			echo "export GOPATH=$GOPATH" >> ~/.bashrc
-		else
-			sed -i "s|export GOPATH=.*|export GOPATH=$GOPATH|g" ~/.bashrc
-		fi
-		systemctl set-environment GOPATH=$GOPATH
-		if ! grep -q "systemctl set-environment GOPATH=" ~/.bashrc; then
-			echo "systemctl set-environment GOPATH=$GOPATH" >> ~/.bashrc
-		else
-			sed -i "s|systemctl set-environment GOPATH=.*|systemctl set-environment GOPATH=$GOPATH|g" ~/.bashrc
-		fi
-		if [ ! -d $GOPATH ]; then
-			mkdir -p $GOPATH
-		fi
-	fi
-
-	IPFS_PATH=$GOPATH/bin
-	export PATH="$GOPATH/bin:$PATH:"
-	if ! grep -q 'GOPATH/bin' ~/.bashrc; then
-		echo 'export PATH="$GOPATH/bin:$PATH:";' >> ~/.bashrc
+	# install Go
+	if ! grep -q "export GOPATH=" ~/.bashrc; then
+	    echo "export GOPATH=$GOPATH" >> ~/.bashrc
 	else
-		sed -i "s|systemctl set-environment GOPATH=.*|systemctl set-environment GOPATH=$GOPATH|g" ~/.bashrc
+	    sed -i "s|export GOPATH=.*|export GOPATH=$GOPATH|g" ~/.bashrc
 	fi
-
-	# set gopath for the user
-	if ! grep -q "GOPATH=" /home/$MY_USERNAME/.bashrc; then
-		echo "export GOPATH=$GOPATH" >> /home/$MY_USERNAME/.bashrc
-		echo 'export PATH="$GOPATH/bin:$PATH:";' >> /home/$MY_USERNAME/.bashrc
+	systemctl set-environment GOPATH=$GOPATH
+	if ! grep -q "systemctl set-environment GOPATH=" ~/.bashrc; then
+	    echo "systemctl set-environment GOPATH=$GOPATH" >> ~/.bashrc
 	else
-		sed -i "s|export GOPATH=.*|export GOPATH=$GOPATH|g" /home/$MY_USERNAME/.bashrc
+	    sed -i "s|systemctl set-environment GOPATH=.*|systemctl set-environment GOPATH=$GOPATH|g" ~/.bashrc
 	fi
-	chown $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.bashrc
-
-	IPFS_GO_REPO2=$(echo "$IPFS_GO_REPO" | sed 's|https://||g')
-	go get -u ${IPFS_GO_REPO2}/cmd/ipfs
-	if [ ! "$?" = "0" ]; then
-		exit 8242
+	if [ ! -d $GOPATH ]; then
+	    mkdir -p $GOPATH
 	fi
+    fi
 
-	cd $GOPATH/src/$IPFS_GO_REPO2
-	git checkout $IPFS_COMMIT -b $IPFS_COMMIT
-	if ! grep -q "ipfs commit" $COMPLETION_FILE; then
-		echo "ipfs commit:$IPFS_COMMIT" >> $COMPLETION_FILE
-	else
-		sed -i "s/ipfs commit.*/ipfs commit:$IPFS_COMMIT/g" $COMPLETION_FILE
+    IPFS_PATH=$GOPATH/bin
+    export PATH="$GOPATH/bin:$PATH:"
+    if ! grep -q 'GOPATH/bin' ~/.bashrc; then
+	echo 'export PATH="$GOPATH/bin:$PATH:";' >> ~/.bashrc
+    else
+	sed -i "s|systemctl set-environment GOPATH=.*|systemctl set-environment GOPATH=$GOPATH|g" ~/.bashrc
+    fi
+
+    # set gopath for the user
+    if ! grep -q "GOPATH=" /home/$MY_USERNAME/.bashrc; then
+	echo "export GOPATH=$GOPATH" >> /home/$MY_USERNAME/.bashrc
+	echo 'export PATH="$GOPATH/bin:$PATH:";' >> /home/$MY_USERNAME/.bashrc
+    else
+	sed -i "s|export GOPATH=.*|export GOPATH=$GOPATH|g" /home/$MY_USERNAME/.bashrc
+    fi
+    chown $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.bashrc
+
+    IPFS_GO_REPO2=$(echo "$IPFS_GO_REPO" | sed 's|https://||g')
+    go get -u ${IPFS_GO_REPO2}/cmd/ipfs
+    if [ ! "$?" = "0" ]; then
+	exit 8242
+    fi
+
+    cd $GOPATH/src/$IPFS_GO_REPO2
+    git checkout $IPFS_COMMIT -b $IPFS_COMMIT
+    if ! grep -q "ipfs commit" $COMPLETION_FILE; then
+	echo "ipfs commit:$IPFS_COMMIT" >> $COMPLETION_FILE
+    else
+	sed -i "s/ipfs commit.*/ipfs commit:$IPFS_COMMIT/g" $COMPLETION_FILE
+    fi
+
+    # initialise
+    su -c "$IPFS_PATH/ipfs init -b 4096" - $MY_USERNAME
+    if [ ! -d /home/$MY_USERNAME/.ipfs ]; then
+	echo "IPFS could not be initialised for user $MY_USERNAME"
+	exit 7358
+    fi
+
+    # directories to mount to
+    if [ ! -d /ipfs ]; then
+	mkdir /ipfs
+	mkdir /ipns
+	chown $MY_USERNAME:$MY_USERNAME /ipfs
+	chown $MY_USERNAME:$MY_USERNAME /ipns
+    fi
+
+    if [ -f /etc/fuse.conf ]; then
+	chown $MY_USERNAME:$MY_USERNAME /etc/fuse.conf
+    fi
+    if [ -f /dev/fuse ]; then
+	chown $MY_USERNAME:$MY_USERNAME /dev/fuse
+    fi
+
+    echo '[Unit]' > /etc/systemd/system/ipfs.service
+    echo 'Description=IPFS daemon' >> /etc/systemd/system/ipfs.service
+    echo 'After=syslog.target' >> /etc/systemd/system/ipfs.service
+    echo 'After=network.target' >> /etc/systemd/system/ipfs.service
+    echo '' >> /etc/systemd/system/ipfs.service
+    echo '[Service]' >> /etc/systemd/system/ipfs.service
+    echo 'Type=simple' >> /etc/systemd/system/ipfs.service
+    echo "User=$MY_USERNAME" >> /etc/systemd/system/ipfs.service
+    echo "Group=$MY_USERNAME" >> /etc/systemd/system/ipfs.service
+    echo "WorkingDirectory=/home/$MY_USERNAME" >> /etc/systemd/system/ipfs.service
+    echo "ExecStart=$IPFS_PATH/ipfs daemon --mount" >> /etc/systemd/system/ipfs.service
+    echo 'Restart=on-failure' >> /etc/systemd/system/ipfs.service
+    echo "Environment=\"USER=$MY_USERNAME\" \"HOME=/home/$MY_USERNAME\" \"GOPATH=$GOPATH\" \"GVM_ROOT=$GVM_HOME\"" >> /etc/systemd/system/ipfs.service
+    echo '' >> /etc/systemd/system/ipfs.service
+    echo '[Install]' >> /etc/systemd/system/ipfs.service
+    echo 'WantedBy=multi-user.target' >> /etc/systemd/system/ipfs.service
+
+    systemctl enable ipfs
+    systemctl daemon-reload
+    systemctl restart ipfs
+
+    if [ -d /etc/avahi ]; then
+	su -c "echo $($IPFS_PATH/ipfs id | grep '\"ID\":' | awk -F '\"' '{print $4}') > /tmp/ipfsid" - $MY_USERNAME
+	if [ ! -f /tmp/ipfsid ]; then
+	    echo 'No IPFS identity was created'
+	    exit 37895
 	fi
-
-	# initialise
-	su -c "$IPFS_PATH/ipfs init -b 4096" - $MY_USERNAME
-	if [ ! -d /home/$MY_USERNAME/.ipfs ]; then
-		echo "IPFS could not be initialised for user $MY_USERNAME"
-		exit 7358
+	IPFS_PEER_ID=$(cat /tmp/ipfsid)
+	if [ ${#IPFS_PEER_ID} -lt 10 ]; then
+	    echo 'Invalid IPFS peer ID'
+	    echo "$IPFS_PEER_ID"
+	    exit 74782
 	fi
+	# Add an avahi service
+	function_check create_avahi_service
+	create_avahi_service ipfs "ipfs" udp $IPFS_PORT "$IPFS_PEER_ID"
+	rm /tmp/ipfsid
+    fi
 
-	# directories to mount to
-	if [ ! -d /ipfs ]; then
-		mkdir /ipfs
-		mkdir /ipns
-		chown $MY_USERNAME:$MY_USERNAME /ipfs
-		chown $MY_USERNAME:$MY_USERNAME /ipns
-	fi
+    function_check configure_firewall_for_ipfs
+    configure_firewall_for_ipfs
 
-	if [ -f /etc/fuse.conf ]; then
-		chown $MY_USERNAME:$MY_USERNAME /etc/fuse.conf
-	fi
-	if [ -f /dev/fuse ]; then
-		chown $MY_USERNAME:$MY_USERNAME /dev/fuse
-	fi
-
-	echo '[Unit]' > /etc/systemd/system/ipfs.service
-	echo 'Description=IPFS daemon' >> /etc/systemd/system/ipfs.service
-	echo 'After=syslog.target' >> /etc/systemd/system/ipfs.service
-	echo 'After=network.target' >> /etc/systemd/system/ipfs.service
-	echo '' >> /etc/systemd/system/ipfs.service
-	echo '[Service]' >> /etc/systemd/system/ipfs.service
-	echo 'Type=simple' >> /etc/systemd/system/ipfs.service
-	echo "User=$MY_USERNAME" >> /etc/systemd/system/ipfs.service
-	echo "Group=$MY_USERNAME" >> /etc/systemd/system/ipfs.service
-	echo "WorkingDirectory=/home/$MY_USERNAME" >> /etc/systemd/system/ipfs.service
-	echo "ExecStart=$IPFS_PATH/ipfs daemon --mount" >> /etc/systemd/system/ipfs.service
-	echo 'Restart=on-failure' >> /etc/systemd/system/ipfs.service
-	echo "Environment=\"USER=$MY_USERNAME\" \"HOME=/home/$MY_USERNAME\" \"GOPATH=$GOPATH\" \"GVM_ROOT=$GVM_HOME\"" >> /etc/systemd/system/ipfs.service
-	echo '' >> /etc/systemd/system/ipfs.service
-	echo '[Install]' >> /etc/systemd/system/ipfs.service
-	echo 'WantedBy=multi-user.target' >> /etc/systemd/system/ipfs.service
-
-	systemctl enable ipfs
-	systemctl daemon-reload
-	systemctl restart ipfs
-
-	if [ -d /etc/avahi ]; then
-		su -c "echo $($IPFS_PATH/ipfs id | grep '\"ID\":' | awk -F '\"' '{print $4}') > /tmp/ipfsid" - $MY_USERNAME
-		if [ ! -f /tmp/ipfsid ]; then
-			echo 'No IPFS identity was created'
-			exit 37895
-		fi
-		IPFS_PEER_ID=$(cat /tmp/ipfsid)
-		if [ ${#IPFS_PEER_ID} -lt 10 ]; then
-			echo 'Invalid IPFS peer ID'
-			echo "$IPFS_PEER_ID"
-			exit 74782
-		fi
-		# Add an avahi service
-		function_check create_avahi_service
-		create_avahi_service ipfs "ipfs" udp $IPFS_PORT "$IPFS_PEER_ID"
-		rm /tmp/ipfsid
-	fi
-
-	function_check configure_firewall_for_ipfs
-	configure_firewall_for_ipfs
-
-	echo 'install_ipfs' >> $COMPLETION_FILE
+    echo 'install_ipfs' >> $COMPLETION_FILE
 }
