More info on copy failure

diff --git a/src/freedombone-utils-go b/src/freedombone-utils-go
--- a/src/freedombone-utils-go
+++ b/src/freedombone-utils-go
@@ -214,7 +214,11 @@ function mesh_upgrade_golang {
         exit 356356785
     fi
     # shellcheck disable=SC2086
-    cp ${rootdir}/home/go/go${GO_VERSION}/bin/* "${rootdir}/usr/bin"
+    if ! cp ${rootdir}/home/go/go${GO_VERSION}/bin/* "${rootdir}/usr/bin"; then
+        ls -la "${rootdir}/home/go/go${GO_VERSION}"
+        echo $'Copying golang binaries failed'
+        exit 246824628
+    fi
 }
 
 function upgrade_golang {
