Make configuration of remote backup locations a separate command

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -395,53 +395,19 @@ function show_help {
 
 
 function interactive_configuration_remote_backups {
-  # clear any existing list
-  if [ -f $FRIENDS_SERVERS_LIST ]; then
-      rm -f $FRIENDS_SERVERS_LIST
-      touch $FRIENDS_SERVERS_LIST
-  fi
-  # number of entries made
-  entering_remote_backups_ctr=1
-
-  entering_remote_backups_done="no"
-  while [[ $entering_remote_backups_done == "no" ]]
-  do
-      data=$(tempfile 2>/dev/null)
-      trap "rm -f $data" 0 1 2 5 15
-      dialog --backtitle "Freedombone Configuration" \
-          --title "Remote Backup ${entering_remote_backups_ctr}" \
-          --form "\nPlease specify the SSH login details:" 11 55 4 \
-          "Username:" 1 1 "" 1 16 16 15 \
-          "Domain:" 2 1 "" 2 16 16 15 \
-          "SSH port:" 3 1 "22" 3 16 5 4 \
-          "Password:" 4 1 "" 4 16 20 100 \
-          2> $data
-      sel=$?
-      case $sel in
-          1) entering_remote_backups_done="yes";;
-          255) entering_remote_backups_done="yes";;
-      esac
-      remote_ssh_username=$(cat $data | sed -n 1p)
-      remote_ssh_domain=$(cat $data | sed -n 2p)
-      remote_ssh_port=$(cat $data | sed -n 3p)
-      remote_ssh_password=$(cat $data | sed -n 4p)
-      if [[ $remote_ssh_username != "" && \
-          $remote_ssh_domain != "" && \
-          $remote_ssh_port != "" && \
-          $remote_ssh_password != "" ]]; then
-
-          if [ ${#remote_ssh_password} -lt $MINIMUM_PASSWORD_LENGTH ]; then
-              dialog --title "Password quality check" --msgbox "The password given was too short. It must be at least $MINIMUM_PASSWORD_LENGTH characters" 6 40
-          else
-              echo "$remote_ssh_username@$remote_ssh_domain:$remote_ssh_port//home/$remote_ssh_username $remote_ssh_password" >> $FRIENDS_SERVERS_LIST
-              entering_remote_backups_ctr=$((entering_remote_backups_ctr + 1))
-          fi
-      else
-          entering_remote_backups_done="yes"
+  if [ ! -f /usr/local/bin/freedombone-remote ]; then
+      if [ ! -f /usr/bin/freedombone-remote ]; then
+          echo 'The command /usr/bin/freedombone-remote was not found'
+          exit 87354
       fi
-  done
-  if [ -f $FRIENDS_SERVERS_LIST ]; then
-      chown $MY_USERNAME:$MY_USERNAME $FRIENDS_SERVERS_LIST
+  fi
+  freedombone-remote -u $MY_USERNAME -l $FRIENDS_SERVERS_LIST -m $MINIMUM_PASSWORD_LENGTH
+  if [ ! "$?" = "0" ]; then
+      echo 'Command failed:'
+      echo ''
+      echo "  freedombone-remote -u $MY_USERNAME -l $FRIENDS_SERVERS_LIST -m $MINIMUM_PASSWORD_LENGTH"
+      echo ''
+      exit 65892
   fi
 }
 
