More checks for failures

diff --git a/src/freedombone-app-koel b/src/freedombone-app-koel
--- a/src/freedombone-app-koel
+++ b/src/freedombone-app-koel
@@ -692,8 +692,14 @@ function install_koel {
             cat /home/$MY_USERNAME/freedombone/image_build/composer_install | php
         fi
     fi
-    npm install
+    npm install -g yarn
+    yarn install
+    if [ ! "$?" = "0" ]; then
+        echo $"Can't install yarn"
+        exit 682427
+    fi
     php composer.phar install
+    npm install
 
     function_check get_mariadb_password
     get_mariadb_password
@@ -711,6 +717,10 @@ function install_koel {
     sed -i 's/MAIL_PORT=.*/MAIL_PORT=25/g' .env
 
     php artisan koel:init
+    if [ ! "$?" = "0" ]; then
+        echo $"Can't install koel:init"
+        exit 78362
+    fi
     koel_remove_gravatar
     chown -R www-data:www-data /var/www/$KOEL_DOMAIN_NAME/htdocs
 
