Better extension detection

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -8634,13 +8634,24 @@ function install_gnu_social_theme {
     git checkout $MICROBLOG_THEME_COMMIT -b $MICROBLOG_THEME_COMMIT
 
     # download a custom background image
+    MICROBLOG_BACKGROUND_IMAGE_URL_EXT=
     if [ $MICROBLOG_BACKGROUND_IMAGE_URL ]; then
-        MICROBLOG_BACKGROUND_IMAGE_URL_EXT=$(echo $MICROBLOG_BACKGROUND_IMAGE_URL | awk -F '.' '{print $2}')
-        wget $MICROBLOG_BACKGROUND_IMAGE_URL -O img/custom.${MICROBLOG_BACKGROUND_IMAGE_URL_EXT}
-        if [ ! -f img/custom.${MICROBLOG_BACKGROUND_IMAGE_URL_EXT} ]; then
-            echo "$MICROBLOG_BACKGROUND_IMAGE_URL"
-            echo $'Custom background image for microblog could not be downloaded'
-            exit 87524
+        if [[ $$MICROBLOG_BACKGROUND_IMAGE_URL == *".jpeg" || $$MICROBLOG_BACKGROUND_IMAGE_URL == *".jpg" ]]; then
+            MICROBLOG_BACKGROUND_IMAGE_URL_EXT="jpg"
+        fi
+        if [[ $$MICROBLOG_BACKGROUND_IMAGE_URL == *".png" ]]; then
+            MICROBLOG_BACKGROUND_IMAGE_URL_EXT="png"
+        fi
+        if [[ $$MICROBLOG_BACKGROUND_IMAGE_URL == *".gif" ]]; then
+            MICROBLOG_BACKGROUND_IMAGE_URL_EXT="gif"
+        fi
+        if [ $MICROBLOG_BACKGROUND_IMAGE_URL_EXT ]; then
+            wget $MICROBLOG_BACKGROUND_IMAGE_URL -O img/custom.${MICROBLOG_BACKGROUND_IMAGE_URL_EXT}
+            if [ ! -f img/custom.${MICROBLOG_BACKGROUND_IMAGE_URL_EXT} ]; then
+                echo "$MICROBLOG_BACKGROUND_IMAGE_URL"
+                echo $'Custom background image for microblog could not be downloaded'
+                exit 87524
+            fi
         fi
     fi
 
@@ -8670,8 +8681,10 @@ function install_gnu_social_theme {
         echo "\$config['site']['qvitter']['customwelcometext']['es'] = '$MICROBLOG_WELCOME_MESSAGE';" >> $microblog_config_file
         echo "\$config['site']['qvitter']['blocked_ips'] = array();" >> $microblog_config_file
     else
-        if [ -f img/custom.${MICROBLOG_BACKGROUND_IMAGE_URL_EXT} ]; then
-            sed -i "s|\$config['site']['qvitter']['sitebackground'].*|\$config['site']['qvitter']['sitebackground'] = 'img/custom.${MICROBLOG_BACKGROUND_IMAGE_URL_EXT}';|g" $microblog_config_file
+        if [ $MICROBLOG_BACKGROUND_IMAGE_URL_EXT ]; then
+            if [ -f img/custom.${MICROBLOG_BACKGROUND_IMAGE_URL_EXT} ]; then
+                sed -i "s|\$config['site']['qvitter']['sitebackground'].*|\$config['site']['qvitter']['sitebackground'] = 'img/custom.${MICROBLOG_BACKGROUND_IMAGE_URL_EXT}';|g" $microblog_config_file
+            fi
         fi
     fi
 
