turtl app

diff --git a/src/freedombone-utils-database b/src/freedombone-utils-database
--- a/src/freedombone-utils-database
+++ b/src/freedombone-utils-database
@@ -288,4 +288,37 @@ function database_reinstall {
     apt-get -yq install mariadb-server
 }
 
+function install_rethinkdb {
+    if [ ! -d $INSTALL_DIR ]; then
+        mkdir -p $INSTALL_DIR
+    fi
+
+    cd $INSTALL_DIR
+    echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | tee /etc/apt/sources.list.d/rethinkdb.list
+
+    wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | apt-key add -
+    apt-get update
+    apt-get -yq install rethinkdb
+    if [ ! -f /etc/rethinkdb/default.conf.sample ]; then
+        echo $'rethinkdb example configuration not found'
+        exit 78252
+    fi
+    cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/default.conf
+    systemctl restart rethinkdb
+}
+
+function remove_rethinkdb {
+    if [ ! -d /etc/rethinkdb ]; then
+        return
+    fi
+    apt-get -yq remove rethinkdb
+    if [ -d /etc/rethinkdb ]; then
+        rm -rf /etc/rethinkdb
+    fi
+    if [ -f /etc/apt/sources.list.d/rethinkdb.list ]; then
+        rm /etc/apt/sources.list.d/rethinkdb.list
+        apt-get update
+    fi
+}
+
 # NOTE: deliberately there is no "exit 0"
