Warnings if tlsdate doesn't build

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -1681,7 +1681,15 @@ function set_repo_commit {
 					cd $INSTALL_DIR/tlsdate
 					make clean
 					./configure
+					if [ ! "$?" = "0" ]; then
+						echo $'Failed to configure tlsdate'
+						exit 727824
+					fi
 					make
+					if [ ! "$?" = "0" ]; then
+						echo $'Failed to build tlsdate'
+						exit 728752
+					fi
 					make install
 				fi
 				if [[ $repo_dir == *"gpgit" ]]; then
