Install peertube

diff --git a/src/freedombone-app-peertube b/src/freedombone-app-peertube
--- a/src/freedombone-app-peertube
+++ b/src/freedombone-app-peertube
@@ -535,6 +535,11 @@ function install_peertube {
         echo $'Failed to run yarn install'
         exit 63754235
     fi
+    npm install
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install peertube'
+        exit 7835243
+    fi
     npm run build
     if [ ! "$?" = "0" ]; then
         echo $'Failed to build peertube'
