Additional peertube dependencies

diff --git a/src/freedombone-app-peertube b/src/freedombone-app-peertube
--- a/src/freedombone-app-peertube
+++ b/src/freedombone-app-peertube
@@ -772,9 +772,21 @@ function install_peertube {
     git checkout $PEERTUBE_COMMIT -b $PEERTUBE_COMMIT
     set_completion_param "peertube commit" "$PEERTUBE_COMMIT"
 
-    if ! npm install -g yarn; then
+    if ! npm install -g yarn@1.5.1; then
         echo $'Failed to install yarn'
         exit 79353234
+    fi
+    if ! npm install minimatch@3.0.2; then
+        echo $'Failed to install minimatch'
+        exit 3578356
+    fi
+    if ! npm install graceful-fs; then
+        echo $'Failed to install graceful-fs'
+        exit 34687246
+    fi
+    if ! npm install coffeescript; then
+        echo $'Failed to install coffeescript'
+        exit 57385757
     fi
     yarn add -D webpack --network-concurrency 1
     if ! yarn install; then
