Exit if the gpg key cannot be split

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -6607,6 +6607,10 @@ function split_gpg_key_into_fragments {
   if [[ $ENABLE_SOCIAL_KEY_MANAGEMENT == "yes" ]]; then
       echo 'Splitting GPG key. You may need to enter your passphrase.'
       freedombone-splitkey -u $MY_USERNAME -e $MY_EMAIL_ADDRESS
+      if [ ! -d /home/$MY_USERNAME/.gnupg_fragments ]; then
+          echo 'Yhe GPG key could not be split'
+          exit 86548
+      fi
   fi
 }
 
