Check for composer failure

diff --git a/src/freedombone-app-koel b/src/freedombone-app-koel
--- a/src/freedombone-app-koel
+++ b/src/freedombone-app-koel
@@ -704,6 +704,10 @@ function install_koel {
     fi
     npm install -g yarn
     php composer.phar install
+    if [ ! "$?" = "0" ]; then
+        echo $'Unable to run composer install'
+        exit 7252198
+    fi
     npm install
 
     function_check get_mariadb_password
