Remove hardcoded variants

diff --git a/src/freedombone-utils-dns b/src/freedombone-utils-dns
--- a/src/freedombone-utils-dns
+++ b/src/freedombone-utils-dns
@@ -45,197 +45,197 @@ GET_IP_ADDRESS_URL="checkip.two-dns.de"
 
 # other possible services to obtain the external IP address
 EXTERNAL_IP_SERVICES=( \
-	    'https://check.torproject.org/' \
-		'https://www.whatsmydns.net/whats-my-ip-address.html' \
-		'https://www.privateinternetaccess.com/pages/whats-my-ip/' \
-		'http://checkip.two-dns.de' \
-		'http://ip.dnsexit.com' \
-		'http://ifconfig.me/ip' \
-		'http://ipecho.net/plain' \
-		'http://checkip.dyndns.org/plain' \
-		'http://ipogre.com/linux.php' \
-		'http://whatismyipaddress.com/' \
-		'http://ip.my-proxy.com/' \
-		'http://websiteipaddress.com/WhatIsMyIp' \
-		'http://getmyipaddress.org/' \
-		'http://www.my-ip-address.net/' \
-		'http://myexternalip.com/raw' \
-		'http://www.canyouseeme.org/' \
-		'http://www.trackip.net/' \
-		'http://icanhazip.com/' \
-		'http://www.iplocation.net/' \
-		'http://www.howtofindmyipaddress.com/' \
-		'http://www.ipchicken.com/' \
-		'http://whatsmyip.net/' \
-		'http://www.ip-adress.com/' \
-		'http://checkmyip.com/' \
-		'http://www.tracemyip.org/' \
-		'http://checkmyip.net/' \
-		'http://www.lawrencegoetz.com/programs/ipinfo/' \
-		'http://www.findmyip.co/' \
-		'http://ip-lookup.net/' \
-		'http://www.dslreports.com/whois' \
-		'http://www.mon-ip.com/en/my-ip/' \
-		'http://www.myip.ru' \
-		'http://ipgoat.com/' \
-		'http://www.myipnumber.com/my-ip-address.asp' \
-		'http://www.whatsmyipaddress.net/' \
-		'http://formyip.com/' \
-		'http://www.displaymyip.com/' \
-		'http://www.bobborst.com/tools/whatsmyip/' \
-		'http://www.geoiptool.com/' \
-		'http://checkip.dyndns.com/' \
-		'http://myexternalip.com/' \
-		'http://www.ip-adress.eu/' \
-		'http://www.infosniper.net/' \
-		'http://wtfismyip.com/' \
-		'http://ipinfo.io/' \
-		'http://httpbin.org/ip')
+        'https://check.torproject.org/' \
+        'https://www.whatsmydns.net/whats-my-ip-address.html' \
+        'https://www.privateinternetaccess.com/pages/whats-my-ip/' \
+        'http://checkip.two-dns.de' \
+        'http://ip.dnsexit.com' \
+        'http://ifconfig.me/ip' \
+        'http://ipecho.net/plain' \
+        'http://checkip.dyndns.org/plain' \
+        'http://ipogre.com/linux.php' \
+        'http://whatismyipaddress.com/' \
+        'http://ip.my-proxy.com/' \
+        'http://websiteipaddress.com/WhatIsMyIp' \
+        'http://getmyipaddress.org/' \
+        'http://www.my-ip-address.net/' \
+        'http://myexternalip.com/raw' \
+        'http://www.canyouseeme.org/' \
+        'http://www.trackip.net/' \
+        'http://icanhazip.com/' \
+        'http://www.iplocation.net/' \
+        'http://www.howtofindmyipaddress.com/' \
+        'http://www.ipchicken.com/' \
+        'http://whatsmyip.net/' \
+        'http://www.ip-adress.com/' \
+        'http://checkmyip.com/' \
+        'http://www.tracemyip.org/' \
+        'http://checkmyip.net/' \
+        'http://www.lawrencegoetz.com/programs/ipinfo/' \
+        'http://www.findmyip.co/' \
+        'http://ip-lookup.net/' \
+        'http://www.dslreports.com/whois' \
+        'http://www.mon-ip.com/en/my-ip/' \
+        'http://www.myip.ru' \
+        'http://ipgoat.com/' \
+        'http://www.myipnumber.com/my-ip-address.asp' \
+        'http://www.whatsmyipaddress.net/' \
+        'http://formyip.com/' \
+        'http://www.displaymyip.com/' \
+        'http://www.bobborst.com/tools/whatsmyip/' \
+        'http://www.geoiptool.com/' \
+        'http://checkip.dyndns.com/' \
+        'http://myexternalip.com/' \
+        'http://www.ip-adress.eu/' \
+        'http://www.infosniper.net/' \
+        'http://wtfismyip.com/' \
+        'http://ipinfo.io/' \
+        'http://httpbin.org/ip')
 
 function create_freedns_updater {
-	if [[ $ONION_ONLY != "no" ]]; then
-		return
-	fi
+    if [[ $ONION_ONLY != "no" ]]; then
+        return
+    fi
 
-	# currently inadyn doesn't work as expected with freeDNS, so this is a workaround
-	if grep -Fxq "create_freedns_updater" $COMPLETION_FILE; then
-		return
-	fi
-	if [[ $DDNS_PROVIDER != "default@freedns.afraid.org" ]]; then
-		return
-	fi
-	if [[ $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
-		return
-	fi
+    # currently inadyn doesn't work as expected with freeDNS, so this is a workaround
+    if grep -Fxq "create_freedns_updater" $COMPLETION_FILE; then
+        return
+    fi
+    if [[ $DDNS_PROVIDER != "default@freedns.afraid.org" ]]; then
+        return
+    fi
+    if [[ $SYSTEM_TYPE == "mesh"* ]]; then
+        return
+    fi
 
-	FREEDNS_WGET='wget -q --read-timeout=0.0 --waitretry=5 --tries=4 https://freedns.afraid.org/dynamic/update.php?'
+    FREEDNS_WGET='wget -q --read-timeout=0.0 --waitretry=5 --tries=4 https://freedns.afraid.org/dynamic/update.php?'
 
-	echo '#!/bin/bash' > /usr/bin/dynamicdns
-	echo 'cd /tmp' >> /usr/bin/dynamicdns
-	if [ $DEFAULT_DOMAIN_CODE ]; then
-		echo "# $DEFAULT_DOMAIN_NAME" >> /usr/bin/dynamicdns
-		echo "$FREEDNS_WGET$DEFAULT_DOMAIN_CODE=" >> /usr/bin/dynamicdns
-	fi
-	if [ $WIKI_CODE ]; then
-		if [[ $WIKI_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
-			echo "# $WIKI_DOMAIN_NAME" >> /usr/bin/dynamicdns
-			echo "$FREEDNS_WGET$WIKI_CODE=" >> /usr/bin/dynamicdns
-		fi
-	fi
-	if [ $FULLBLOG_CODE ]; then
-		if [[ $FULLBLOG_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
-			echo "# $FULLBLOG_DOMAIN_NAME" >> /usr/bin/dynamicdns
-			echo "$FREEDNS_WGET$FULLBLOG_CODE=" >> /usr/bin/dynamicdns
-		fi
-	fi
-	if [ $HUBZILLA_CODE ]; then
-		if [[ $HUBZILLA_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
-			echo "# $HUBZILLA_DOMAIN_NAME" >> /usr/bin/dynamicdns
-			echo "$FREEDNS_WGET$HUBZILLA_CODE=" >> /usr/bin/dynamicdns
-		fi
-	fi
-	if [ $MICROBLOG_CODE ]; then
-		if [[ $MICROBLOG_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
-			echo "# $MICROBLOG_DOMAIN_NAME" >> /usr/bin/dynamicdns
-			echo "$FREEDNS_WGET$MICROBLOG_CODE=" >> /usr/bin/dynamicdns
-		fi
-	fi
-	if [ $GIT_CODE ]; then
-		if [[ $GIT_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
-			echo "# $GIT_DOMAIN_NAME" >> /usr/bin/dynamicdns
-			echo "$FREEDNS_WGET$GIT_CODE=" >> /usr/bin/dynamicdns
-		fi
-	fi
-	if [ $MEDIAGOBLIN_CODE ]; then
-		if [[ $MEDIAGOBLIN_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
-			echo "# $MEDIAGOBLIN_DOMAIN_NAME" >> /usr/bin/dynamicdns
-			echo "$FREEDNS_WGET$MEDIAGOBLIN_CODE=" >> /usr/bin/dynamicdns
-		fi
-	fi
-	echo 'exit 0' >> /usr/bin/dynamicdns
-	chmod 600 /usr/bin/dynamicdns
-	chmod +x /usr/bin/dynamicdns
+    echo '#!/bin/bash' > /usr/bin/dynamicdns
+    echo 'cd /tmp' >> /usr/bin/dynamicdns
+    if [ $DEFAULT_DOMAIN_CODE ]; then
+        echo "# $DEFAULT_DOMAIN_NAME" >> /usr/bin/dynamicdns
+        echo "$FREEDNS_WGET$DEFAULT_DOMAIN_CODE=" >> /usr/bin/dynamicdns
+    fi
+    if [ $WIKI_CODE ]; then
+        if [[ $WIKI_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
+            echo "# $WIKI_DOMAIN_NAME" >> /usr/bin/dynamicdns
+            echo "$FREEDNS_WGET$WIKI_CODE=" >> /usr/bin/dynamicdns
+        fi
+    fi
+    if [ $FULLBLOG_CODE ]; then
+        if [[ $FULLBLOG_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
+            echo "# $FULLBLOG_DOMAIN_NAME" >> /usr/bin/dynamicdns
+            echo "$FREEDNS_WGET$FULLBLOG_CODE=" >> /usr/bin/dynamicdns
+        fi
+    fi
+    if [ $HUBZILLA_CODE ]; then
+        if [[ $HUBZILLA_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
+            echo "# $HUBZILLA_DOMAIN_NAME" >> /usr/bin/dynamicdns
+            echo "$FREEDNS_WGET$HUBZILLA_CODE=" >> /usr/bin/dynamicdns
+        fi
+    fi
+    if [ $MICROBLOG_CODE ]; then
+        if [[ $MICROBLOG_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
+            echo "# $MICROBLOG_DOMAIN_NAME" >> /usr/bin/dynamicdns
+            echo "$FREEDNS_WGET$MICROBLOG_CODE=" >> /usr/bin/dynamicdns
+        fi
+    fi
+    if [ $GIT_CODE ]; then
+        if [[ $GIT_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
+            echo "# $GIT_DOMAIN_NAME" >> /usr/bin/dynamicdns
+            echo "$FREEDNS_WGET$GIT_CODE=" >> /usr/bin/dynamicdns
+        fi
+    fi
+    if [ $MEDIAGOBLIN_CODE ]; then
+        if [[ $MEDIAGOBLIN_CODE != "$DEFAULT_DOMAIN_CODE" ]]; then
+            echo "# $MEDIAGOBLIN_DOMAIN_NAME" >> /usr/bin/dynamicdns
+            echo "$FREEDNS_WGET$MEDIAGOBLIN_CODE=" >> /usr/bin/dynamicdns
+        fi
+    fi
+    echo 'exit 0' >> /usr/bin/dynamicdns
+    chmod 600 /usr/bin/dynamicdns
+    chmod +x /usr/bin/dynamicdns
 
-	if ! grep -q "/usr/bin/dynamicdns" /etc/crontab; then
-		function_check cron_add_mins
-		cron_add_mins 3 '/usr/bin/dynamicdns'
-		systemctl restart cron
-	fi
+    if ! grep -q "/usr/bin/dynamicdns" /etc/crontab; then
+        function_check cron_add_mins
+        cron_add_mins 3 '/usr/bin/dynamicdns'
+        systemctl restart cron
+    fi
 
-	echo 'create_freedns_updater' >> $COMPLETION_FILE
+    echo 'create_freedns_updater' >> $COMPLETION_FILE
 }
 
 function add_ddns_domain {
-	if [ ! $1 ]; then
-		echo $'ddns domain not specified'
-		exit 5638
-	fi
-	CURRENT_DDNS_DOMAIN="$1"
-	if [[ $ONION_ONLY != "no" ]]; then
-		return
-	fi
-	if [ ! -f /etc/inadyn.conf ]; then
-		echo $'Unable to find inadyn configuration file /etc/inadyn.conf'
-		exit 5745
-	fi
-	if ! grep -q "$DDNS_PROVIDER" /etc/inadyn.conf; then
-		echo '' >> /etc/inadyn.conf
-		echo "system $DDNS_PROVIDER" >> /etc/inadyn.conf
-		echo '  ssl' >> /etc/inadyn.conf
-		echo "  checkip-url $GET_IP_ADDRESS_URL /" >> /etc/inadyn.conf
-		if [ $DDNS_USERNAME ]; then
-			echo "  username $DDNS_USERNAME" >> /etc/inadyn.conf
-		fi
-		if [ $DDNS_PASSWORD ]; then
-			echo "  password $DDNS_PASSWORD" >> /etc/inadyn.conf
-		fi
-	fi
+    if [ ! $1 ]; then
+        echo $'ddns domain not specified'
+        exit 5638
+    fi
+    CURRENT_DDNS_DOMAIN="$1"
+    if [[ $ONION_ONLY != "no" ]]; then
+        return
+    fi
+    if [ ! -f /etc/inadyn.conf ]; then
+        echo $'Unable to find inadyn configuration file /etc/inadyn.conf'
+        exit 5745
+    fi
+    if ! grep -q "$DDNS_PROVIDER" /etc/inadyn.conf; then
+        echo '' >> /etc/inadyn.conf
+        echo "system $DDNS_PROVIDER" >> /etc/inadyn.conf
+        echo '  ssl' >> /etc/inadyn.conf
+        echo "  checkip-url $GET_IP_ADDRESS_URL /" >> /etc/inadyn.conf
+        if [ $DDNS_USERNAME ]; then
+            echo "  username $DDNS_USERNAME" >> /etc/inadyn.conf
+        fi
+        if [ $DDNS_PASSWORD ]; then
+            echo "  password $DDNS_PASSWORD" >> /etc/inadyn.conf
+        fi
+    fi
 
-	if ! grep -q "$CURRENT_DDNS_DOMAIN" /etc/inadyn.conf; then
-		echo "  alias $CURRENT_DDNS_DOMAIN" >> /etc/inadyn.conf
-	fi
-	chmod 600 /etc/inadyn.conf
-	systemctl restart inadyn
-	systemctl daemon-reload
+    if ! grep -q "$CURRENT_DDNS_DOMAIN" /etc/inadyn.conf; then
+        echo "  alias $CURRENT_DDNS_DOMAIN" >> /etc/inadyn.conf
+    fi
+    chmod 600 /etc/inadyn.conf
+    systemctl restart inadyn
+    systemctl daemon-reload
 }
 
 function configure_dns {
-	if grep -Fxq "configure_dns" $COMPLETION_FILE; then
-		return
-	fi
-	echo 'domain localdomain' > /etc/resolv.conf
-	echo 'search localdomain' >> /etc/resolv.conf
-	echo "nameserver $NAMESERVER1" >> /etc/resolv.conf
-	echo "nameserver $NAMESERVER2" >> /etc/resolv.conf
+    if grep -Fxq "configure_dns" $COMPLETION_FILE; then
+        return
+    fi
+    echo 'domain localdomain' > /etc/resolv.conf
+    echo 'search localdomain' >> /etc/resolv.conf
+    echo "nameserver $NAMESERVER1" >> /etc/resolv.conf
+    echo "nameserver $NAMESERVER2" >> /etc/resolv.conf
 
-	# prevent resolv.conf from changing
-	chattr +i /etc/resolv.conf
+    # prevent resolv.conf from changing
+    chattr +i /etc/resolv.conf
 
-	echo 'configure_dns' >> $COMPLETION_FILE
+    echo 'configure_dns' >> $COMPLETION_FILE
 }
 
 function set_hostname {
-	DEFAULT_DOMAIN_NAME="$1"
+    DEFAULT_DOMAIN_NAME="$1"
 
-	echo "$DEFAULT_DOMAIN_NAME" > /etc/hostname
-	hostname $DEFAULT_DOMAIN_NAME
+    echo "$DEFAULT_DOMAIN_NAME" > /etc/hostname
+    hostname $DEFAULT_DOMAIN_NAME
 
-	if grep -q "127.0.1.1" /etc/hosts; then
-		sed -i "s/127.0.1.1.*/127.0.1.1       $DEFAULT_DOMAIN_NAME/g" /etc/hosts
-	else
-		echo "127.0.1.1  $DEFAULT_DOMAIN_NAME" >> /etc/hosts
-	fi
+    if grep -q "127.0.1.1" /etc/hosts; then
+        sed -i "s/127.0.1.1.*/127.0.1.1       $DEFAULT_DOMAIN_NAME/g" /etc/hosts
+    else
+        echo "127.0.1.1  $DEFAULT_DOMAIN_NAME" >> /etc/hosts
+    fi
 }
 
 function set_your_domain_name {
-	if grep -Fxq "set_your_domain_name" $COMPLETION_FILE; then
-		return
-	fi
+    if grep -Fxq "set_your_domain_name" $COMPLETION_FILE; then
+        return
+    fi
 
-	function_check set_hostname
-	set_hostname $DEFAULT_DOMAIN_NAME
+    function_check set_hostname
+    set_hostname $DEFAULT_DOMAIN_NAME
 
-	echo 'set_your_domain_name' >> $COMPLETION_FILE
+    echo 'set_your_domain_name' >> $COMPLETION_FILE
 }
 
 # NOTE: deliberately no exit 0
diff --git a/src/freedombone-utils-interactive b/src/freedombone-utils-interactive
--- a/src/freedombone-utils-interactive
+++ b/src/freedombone-utils-interactive
@@ -29,81 +29,81 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 function interactive_configuration_remote_backups {
-	if [[ $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
-		return
-	fi
-	if [ ! -f /usr/local/bin/${PROJECT_NAME}-remote ]; then
-		if [ ! -f /usr/bin/${PROJECT_NAME}-remote ]; then
-			echo $"The command ${PROJECT_NAME}-remote was not found"
-			exit 87354
-		fi
-	fi
-	${PROJECT_NAME}-remote -u $MY_USERNAME -l $FRIENDS_SERVERS_LIST -m $MINIMUM_PASSWORD_LENGTH -r yes
-	if [ ! "$?" = "0" ]; then
-		echo $'Command failed:'
-		echo ''
-		echo $"  ${PROJECT_NAME}-remote -u $MY_USERNAME -l $FRIENDS_SERVERS_LIST -m $MINIMUM_PASSWORD_LENGTH -r yes"
-		echo ''
-		exit 65892
-	fi
+    if [[ $SYSTEM_TYPE == "mesh"* ]]; then
+        return
+    fi
+    if [ ! -f /usr/local/bin/${PROJECT_NAME}-remote ]; then
+        if [ ! -f /usr/bin/${PROJECT_NAME}-remote ]; then
+            echo $"The command ${PROJECT_NAME}-remote was not found"
+            exit 87354
+        fi
+    fi
+    ${PROJECT_NAME}-remote -u $MY_USERNAME -l $FRIENDS_SERVERS_LIST -m $MINIMUM_PASSWORD_LENGTH -r yes
+    if [ ! "$?" = "0" ]; then
+        echo $'Command failed:'
+        echo ''
+        echo $"  ${PROJECT_NAME}-remote -u $MY_USERNAME -l $FRIENDS_SERVERS_LIST -m $MINIMUM_PASSWORD_LENGTH -r yes"
+        echo ''
+        exit 65892
+    fi
 }
 
 function interactive_configuration {
-	if [ ! -f /usr/local/bin/${PROJECT_NAME}-config ]; then
-		if [ ! -f /usr/bin/${PROJECT_NAME}-config ]; then
-			echo $"The command ${PROJECT_NAME}-config was not found"
-			exit 63935
-		fi
-	fi
-	if [ -f /tmp/meshuserdevice ]; then
-		rm -f /tmp/meshuserdevice
-	fi
+    if [ ! -f /usr/local/bin/${PROJECT_NAME}-config ]; then
+        if [ ! -f /usr/bin/${PROJECT_NAME}-config ]; then
+            echo $"The command ${PROJECT_NAME}-config was not found"
+            exit 63935
+        fi
+    fi
+    if [ -f /tmp/meshuserdevice ]; then
+        rm -f /tmp/meshuserdevice
+    fi
 
-	if [[ $ONION_ONLY == "no" ]]; then
-		if [[ $MINIMAL_INSTALL == "no" ]]; then
-			${PROJECT_NAME}-config \
-						   -f $CONFIGURATION_FILE \
-						   -w $PROJECT_WEBSITE \
-						   -m $MINIMUM_PASSWORD_LENGTH
-		else
-			${PROJECT_NAME}-config \
-						   -f $CONFIGURATION_FILE \
-						   -w $PROJECT_WEBSITE \
-						   -m $MINIMUM_PASSWORD_LENGTH \
-						   --minimal "yes"
-		fi
-	else
-		${PROJECT_NAME}-config \
-					   -f $CONFIGURATION_FILE \
-					   -w $PROJECT_WEBSITE \
-					   -m $MINIMUM_PASSWORD_LENGTH \
-					   --onion "yes"
-	fi
-	if [ -f /tmp/meshuserdevice ]; then
-		# mesh network user device installation
-		rm -f /tmp/meshuserdevice
-		exit 0
-	fi
-	if [ ! "$?" = "0" ]; then
-		echo $'Command failed:'
-		echo ''
-		echo $"  ${PROJECT_NAME}-config -u $MY_USERNAME -f $CONFIGURATION_FILE -w $PROJECT_WEBSITE -b $PROJECT_BITMESSAGE -m $MINIMUM_PASSWORD_LENGTH --minimal [yes|no]"
-		echo ''
-		exit 73594
-	fi
+    if [[ $ONION_ONLY == "no" ]]; then
+        if [[ $MINIMAL_INSTALL == "no" ]]; then
+            ${PROJECT_NAME}-config \
+                           -f $CONFIGURATION_FILE \
+                           -w $PROJECT_WEBSITE \
+                           -m $MINIMUM_PASSWORD_LENGTH
+        else
+            ${PROJECT_NAME}-config \
+                           -f $CONFIGURATION_FILE \
+                           -w $PROJECT_WEBSITE \
+                           -m $MINIMUM_PASSWORD_LENGTH \
+                           --minimal "yes"
+        fi
+    else
+        ${PROJECT_NAME}-config \
+                       -f $CONFIGURATION_FILE \
+                       -w $PROJECT_WEBSITE \
+                       -m $MINIMUM_PASSWORD_LENGTH \
+                       --onion "yes"
+    fi
+    if [ -f /tmp/meshuserdevice ]; then
+        # mesh network user device installation
+        rm -f /tmp/meshuserdevice
+        exit 0
+    fi
+    if [ ! "$?" = "0" ]; then
+        echo $'Command failed:'
+        echo ''
+        echo $"  ${PROJECT_NAME}-config -u $MY_USERNAME -f $CONFIGURATION_FILE -w $PROJECT_WEBSITE -b $PROJECT_BITMESSAGE -m $MINIMUM_PASSWORD_LENGTH --minimal [yes|no]"
+        echo ''
+        exit 73594
+    fi
 
-	if [[ $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
-		FRIENDS_SERVERS_LIST=/home/$MY_USERNAME/backup.list
+    if [[ $SYSTEM_TYPE == "mesh"* ]]; then
+        FRIENDS_SERVERS_LIST=/home/$MY_USERNAME/backup.list
 
-		dialog --title $"Encrypted backup to other servers" \
-			   --backtitle $"${PROJECT_NAME} Configuration" \
-			   --defaultno \
-			   --yesno $"\nDo you wish to configure some remote backup locations?" 7 60
-		sel=$?
-		case $sel in
-			0) interactive_configuration_remote_backups;;
-		esac
-	fi
+        dialog --title $"Encrypted backup to other servers" \
+               --backtitle $"${PROJECT_NAME} Configuration" \
+               --defaultno \
+               --yesno $"\nDo you wish to configure some remote backup locations?" 7 60
+        sel=$?
+        case $sel in
+            0) interactive_configuration_remote_backups;;
+        esac
+    fi
 }
 
 # NOTE: deliberately no exit 0
diff --git a/src/freedombone-utils-time b/src/freedombone-utils-time
--- a/src/freedombone-utils-time
+++ b/src/freedombone-utils-time
@@ -43,88 +43,88 @@ TLSDATE_REPO="https://github.com/bashrc/tlsdate"
 TLSDATE_COMMIT='505e31540eebde8074e7dc93b29be0d848def06a'
 
 function check_date {
-	curr_date=$(date)
-	if [[ $curr_date == *"1970"* ]]; then
-		apt-get -y install ntp
-	fi
+    curr_date=$(date)
+    if [[ $curr_date == *"1970"* ]]; then
+        apt-get -y install ntp
+    fi
 }
 
 function time_synchronisation {
-	# mesh peers typically don't sync over the internet
-	if [[ $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
-		return
-	fi
+    # mesh peers typically don't sync over the internet
+    if [[ $SYSTEM_TYPE == "mesh"* ]]; then
+        return
+    fi
 
-	if [ -f /usr/local/bin/${PROJECT_NAME}-update-date ]; then
-		cp /usr/local/bin/${PROJECT_NAME}-update-date /usr/bin/updatedate
-	else
-		cp /usr/bin/${PROJECT_NAME}-update-date /usr/bin/updatedate
-	fi
-	chmod +x /usr/bin/updatedate
+    if [ -f /usr/local/bin/${PROJECT_NAME}-update-date ]; then
+        cp /usr/local/bin/${PROJECT_NAME}-update-date /usr/bin/updatedate
+    else
+        cp /usr/bin/${PROJECT_NAME}-update-date /usr/bin/updatedate
+    fi
+    chmod +x /usr/bin/updatedate
 
-	if grep -Fxq "time_synchronisation" $COMPLETION_FILE; then
-		return
-	fi
+    if grep -Fxq "time_synchronisation" $COMPLETION_FILE; then
+        return
+    fi
 
-	apt-get -y install tlsdate
-	apt-get -y remove ntpdate
+    apt-get -y install tlsdate
+    apt-get -y remove ntpdate
 
-	function_check cron_add_mins
-	cron_add_mins 15 '/usr/bin/updatedate'
+    function_check cron_add_mins
+    cron_add_mins 15 '/usr/bin/updatedate'
 
-	systemctl restart cron
+    systemctl restart cron
 
-	echo 'time_synchronisation' >> $COMPLETION_FILE
+    echo 'time_synchronisation' >> $COMPLETION_FILE
 }
 
 function time_synchronisation_tlsdate {
-	# mesh peers typically don't sync over the internet
-	if [[ $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
-		return
-	fi
+    # mesh peers typically don't sync over the internet
+    if [[ $SYSTEM_TYPE == "mesh"* ]]; then
+        return
+    fi
 
-	if [ -f /usr/local/bin/${PROJECT_NAME}-update-date ]; then
-		cp /usr/local/bin/${PROJECT_NAME}-update-date /usr/bin/updatedate
-	else
-		cp /usr/bin/${PROJECT_NAME}-update-date /usr/bin/updatedate
-	fi
-	chmod +x /usr/bin/updatedate
+    if [ -f /usr/local/bin/${PROJECT_NAME}-update-date ]; then
+        cp /usr/local/bin/${PROJECT_NAME}-update-date /usr/bin/updatedate
+    else
+        cp /usr/bin/${PROJECT_NAME}-update-date /usr/bin/updatedate
+    fi
+    chmod +x /usr/bin/updatedate
 
-	if [ ! -d $INSTALL_DIR ]; then
-		mkdir -p $INSTALL_DIR
-	fi
-	set_repo_commit $INSTALL_DIR/tlsdate "tlsdate commit" "$TLSDATE_COMMIT" $TLSDATE_REPO
+    if [ ! -d $INSTALL_DIR ]; then
+        mkdir -p $INSTALL_DIR
+    fi
+    set_repo_commit $INSTALL_DIR/tlsdate "tlsdate commit" "$TLSDATE_COMMIT" $TLSDATE_REPO
 
-	if grep -Fxq "time_synchronisation_tlsdate" $COMPLETION_FILE; then
-		return
-	fi
+    if grep -Fxq "time_synchronisation_tlsdate" $COMPLETION_FILE; then
+        return
+    fi
 
-	apt-get -y remove tlsdate ntpdate
-	apt-get -y install build-essential autoconf libevent-dev
-	apt-get -y install pkg-config libtool libssl-dev
+    apt-get -y remove tlsdate ntpdate
+    apt-get -y install build-essential autoconf libevent-dev
+    apt-get -y install pkg-config libtool libssl-dev
 
-	cd $INSTALL_DIR
-	function_check git_clone
-	git_clone $TLSDATE_REPO $INSTALL_DIR/tlsdate
-	cd $INSTALL_DIR/tlsdate
-	git checkout $TLSDATE_COMMIT -b $TLSDATE_COMMIT
-	./autogen.sh
-	./configure
-	if [ ! "$?" = "0" ]; then
-		echo $'Unable to configure tlsdate'
-		exit 6825277
-	fi
-	make
-	if [ ! "$?" = "0" ]; then
-		echo $'Unable to build tlsdate'
-		exit 3792726
-	fi
-	make install
+    cd $INSTALL_DIR
+    function_check git_clone
+    git_clone $TLSDATE_REPO $INSTALL_DIR/tlsdate
+    cd $INSTALL_DIR/tlsdate
+    git checkout $TLSDATE_COMMIT -b $TLSDATE_COMMIT
+    ./autogen.sh
+    ./configure
+    if [ ! "$?" = "0" ]; then
+        echo $'Unable to configure tlsdate'
+        exit 6825277
+    fi
+    make
+    if [ ! "$?" = "0" ]; then
+        echo $'Unable to build tlsdate'
+        exit 3792726
+    fi
+    make install
 
-	function_check cron_add_mins
-	cron_add_mins 15 '/usr/bin/updatedate'
+    function_check cron_add_mins
+    cron_add_mins 15 '/usr/bin/updatedate'
 
-	echo 'time_synchronisation_tlsdate' >> $COMPLETION_FILE
+    echo 'time_synchronisation_tlsdate' >> $COMPLETION_FILE
 }
 
 # NOTE: deliberately no exit 0
