Check that the mount directory exists

diff --git a/src/freedombone-prep b/src/freedombone-prep
--- a/src/freedombone-prep
+++ b/src/freedombone-prep
@@ -46,7 +46,7 @@ DOWNLOAD_LINK2="http://ynezz.ibawizard.net/beagleboard/jessie/$DEBIAN_FILE_NAME.
 
 function show_help {
     echo ''
-    echo 'freedombone-prep -d [microSD device] --ip [BBB LAN IP address] --iprouter [Router LAN IP address]'
+    echo 'freedombone-prep -d [microSD device] --ip [BBB LAN IP address] --iprouter [Router LAN IP address] --mount [mount directory]'
     echo ''
     echo 'See the manpage for more details'
     echo ''
@@ -56,6 +56,12 @@ function show_help {
 if [[ $NO_OF_ARGS == 0 ]]; then
   show_help
   exit 0
+fi
+
+if [ ! -d $MICROSD_MOUNT_POINT ]; then
+    echo "The mount directory $MICROSD_MOUNT_POINT does not exist."
+    echo 'Use the --mount option to specify where the microSD gets mounted to.'
+    exit 67563
 fi
 
 while [[ $# > 1 ]]
@@ -152,6 +158,16 @@ if [ ! -b ${MICROSD_DRIVE}1 ]; then
         echo "microSD drive not found at ${MICROSD_DRIVE}1"
         exit 5
     fi
+fi
+
+if [ ! -d $MICROSD_MOUNT_POINT/BOOT ]; then
+    echo "The boot partition $MICROSD_MOUNT_POINT/BOOT was not found."
+    exit 67857
+fi
+
+if [ ! -d $MICROSD_MOUNT_POINT/rootfs ]; then
+    echo "The rootfs partition $MICROSD_MOUNT_POINT/rootfs was not found."
+    exit 65688
 fi
 
 $SUDO cp $MICROSD_MOUNT_POINT/BOOT/bbb-uEnv.txt $MICROSD_MOUNT_POINT/BOOT/uEnv.txt
