More consolidation of mesh functions

diff --git a/src/freedombone-utils-web b/src/freedombone-utils-web
--- a/src/freedombone-utils-web
+++ b/src/freedombone-utils-web
@@ -392,7 +392,43 @@ function install_dynamicdns {
 	echo 'install_dynamicdns' >> $COMPLETION_FILE
 }
 
+function install_command_line_browser {
+	if grep -Fxq "install_command_line_browser" $COMPLETION_FILE; then
+		return
+	fi
+	apt-get -y install elinks
+
+	# set the home page
+	if ! grep -q "WWW_HOME" /home/$MY_USERNAME/.bashrc; then
+		if ! grep -q 'control' /home/$MY_USERNAME/.bashrc; then
+			echo "export WWW_HOME=$DEFAULT_SEARCH" >> /home/$MY_USERNAME/.bashrc
+		else
+			sed -i "/control/i export WWW_HOME=$DEFAULT_SEARCH" /home/$MY_USERNAME/.bashrc
+		fi
+	fi
+
+	echo 'install_command_line_browser' >> $COMPLETION_FILE
+}
+
+function mesh_web_server {
+	if [ -d /etc/apache2 ]; then
+		chroot "$rootdir" apt-get -y remove --purge apache2
+		chroot "$rootdir" rm -rf /etc/apache2
+	fi
+
+	chroot "$rootdir" apt-get -y install nginx
+
+	if [ ! -d $rootdir/etc/nginx ]; then
+		echo $'Unable to install web server'
+		exit 346825
+	fi
+}
+
 function install_web_server {
+	if [ $INSTALLING_MESH ]; then
+		mesh_web_server
+		return
+	fi
 	if [[ $SYSTEM_TYPE == "$VARIANT_CHAT" ]]; then
 		return
 	fi
@@ -528,38 +564,6 @@ function install_web_server {
 	configure_firewall_for_web_access
 
 	echo 'install_web_server' >> $COMPLETION_FILE
-}
-
-function install_command_line_browser {
-	if grep -Fxq "install_command_line_browser" $COMPLETION_FILE; then
-		return
-	fi
-	apt-get -y install elinks
-
-	# set the home page
-	if ! grep -q "WWW_HOME" /home/$MY_USERNAME/.bashrc; then
-		if ! grep -q 'control' /home/$MY_USERNAME/.bashrc; then
-			echo "export WWW_HOME=$DEFAULT_SEARCH" >> /home/$MY_USERNAME/.bashrc
-		else
-			sed -i "/control/i export WWW_HOME=$DEFAULT_SEARCH" /home/$MY_USERNAME/.bashrc
-		fi
-	fi
-
-	echo 'install_command_line_browser' >> $COMPLETION_FILE
-}
-
-function mesh_web_server {
-	if [ -d /etc/apache2 ]; then
-		chroot "$rootdir" apt-get -y remove --purge apache2
-		chroot "$rootdir" rm -rf /etc/apache2
-	fi
-
-	chroot "$rootdir" apt-get -y install nginx
-
-	if [ ! -d $rootdir/etc/nginx ]; then
-		echo $'Unable to install web server'
-		exit 346825
-	fi
 }
 
 # NOTE: deliberately no exit 0
