Tidying

diff --git a/src/freedombone-app-bludit b/src/freedombone-app-bludit
--- a/src/freedombone-app-bludit
+++ b/src/freedombone-app-bludit
@@ -38,10 +38,10 @@ BLUDIT_REPO="https://github.com/bludit/bludit"
 BLUDIT_COMMIT='0e27e31a84421b3e6bd000a77bc89c2dff3c446a'
 
 bludit_variables=(ONION_ONLY
-                       BLUDIT_DOMAIN_NAME
-                       BLUDIT_CODE
-                       DDNS_PROVIDER
-                       MY_USERNAME)
+                  BLUDIT_DOMAIN_NAME
+                  BLUDIT_CODE
+                  DDNS_PROVIDER
+                  MY_USERNAME)
 
 function logging_on_bludit {
     echo -n ''
@@ -112,9 +112,9 @@ function configure_interactive_bludit {
         esac
         case $(cat "$data") in
             1) # call some function for option 1
-               ;;
+            ;;
             2) # call some function for option 2
-               ;;
+            ;;
             3) rm -f "$data"
                break;;
         esac
@@ -255,19 +255,19 @@ function install_bludit {
     if [ -d "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" ]; then
         rm -rf "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
     fi
-      if [ -d /repos/bludit ]; then
-          mkdir "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
-          cp -r -p /repos/bludit/. "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
-          cd "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" || exit 324687356
-          git pull
-      else
-          git_clone $BLUDIT_REPO "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
-      fi
+    if [ -d /repos/bludit ]; then
+        mkdir "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
+        cp -r -p /repos/bludit/. "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
+        cd "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" || exit 324687356
+        git pull
+    else
+        git_clone $BLUDIT_REPO "/var/www/$BLUDIT_DOMAIN_NAME/htdocs"
+    fi
 
-        if [ ! -d "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" ]; then
-            echo $'Unable to clone bludit repo'
-            exit 87525
-        fi
+    if [ ! -d "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" ]; then
+        echo $'Unable to clone bludit repo'
+        exit 87525
+    fi
 
     cd "/var/www/$BLUDIT_DOMAIN_NAME/htdocs" || exit 36587356
     git checkout $BLUDIT_COMMIT -b $BLUDIT_COMMIT
