Fall back to a self-signed cert if lets encrypt doesn't register

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -9826,6 +9826,10 @@ function install_mediagoblin {
             ${PROJECT_NAME}-addcert -h $MEDIAGOBLIN_DOMAIN_NAME --dhkey $DH_KEYLENGTH
         else
             ${PROJECT_NAME}-addcert -e $MEDIAGOBLIN_DOMAIN_NAME -s $LETSENCRYPT_SERVER --dhkey $DH_KEYLENGTH --email $MY_EMAIL_ADDRESS
+            if [ ! "$?" = "0" ]; then
+                echo $'Lets Encrypt failed for this domain, so try making a self-signed cert'
+                ${PROJECT_NAME}-addcert -h $MEDIAGOBLIN_DOMAIN_NAME --dhkey $DH_KEYLENGTH
+            fi          
         fi
         check_certificates $MEDIAGOBLIN_DOMAIN_NAME
     fi
