Loading of app variables

diff --git a/src/freedombone-app-hubzilla b/src/freedombone-app-hubzilla
--- a/src/freedombone-app-hubzilla
+++ b/src/freedombone-app-hubzilla
@@ -40,6 +40,16 @@ HUBZILLA_ADMIN_PASSWORD=
 HUBZILLA_COMMIT='8aee932525d0bc341713fe7052e2a5ab318a69c0'
 HUBZILLA_ADDONS_COMMIT='4456f097e3faf2adeab696ad08e3f213e82199bd'
 
+hubzilla_variables=(ONION_ONLY
+                    HUBZILLA_DOMAIN_NAME
+                    HUBZILLA_CODE
+                    DDNS_PROVIDER
+                    MY_USERNAME
+                    HUBZILLA_REPO
+                    HUBZILLA_COMMIT
+                    HUBZILLA_ADDONS_REPO
+                    HUBZILLA_ADDONS_COMMIT)
+
 function hubzilla_renew_cert {
     dialog --title $"Renew SSL certificate" \
            --backtitle $"Freedombone Control Panel" \
@@ -126,21 +136,6 @@ function configure_interactive_hubzilla {
 }
 
 function install_interactive_hubzilla {
-    if [ ! $ONION_ONLY ]; then
-        ONION_ONLY='no'
-    fi
-    if grep -q "ONION_ONLY" $CONFIGURATION_FILE; then
-        ONION_ONLY=$(grep "ONION_ONLY" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
-    if grep -q "HUBZILLA_DOMAIN_NAME" $CONFIGURATION_FILE; then
-        HUBZILLA_DOMAIN_NAME=$(grep "HUBZILLA_DOMAIN_NAME" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
-    if grep -q "HUBZILLA_CODE" $CONFIGURATION_FILE; then
-        HUBZILLA_CODE=$(grep "HUBZILLA_CODE" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
-    if grep -q "DDNS_PROVIDER" $CONFIGURATION_FILE; then
-        DDNS_PROVIDER=$(grep "DDNS_PROVIDER" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
     if [[ $ONION_ONLY != "no" ]]; then
         HUBZILLA_DOMAIN_NAME='hubzilla.local'
     else
@@ -250,10 +245,6 @@ function reconfigure_hubzilla {
 }
 
 function upgrade_hubzilla {
-    if grep -q "HUBZILLA_DOMAIN_NAME" $CONFIGURATION_FILE; then
-        HUBZILLA_DOMAIN_NAME=$(grep "HUBZILLA_DOMAIN_NAME" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
-
     HUBZILLA_PATH=/var/www/$HUBZILLA_DOMAIN_NAME/htdocs
 
     function_check set_repo_commit
@@ -269,88 +260,66 @@ function upgrade_hubzilla {
 }
 
 function backup_local_hubzilla {
-    if grep -q "hubzilla domain" $COMPLETION_FILE; then
-        HUBZILLA_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "hubzilla domain" | awk -F ':' '{print $2}')
-        hubzilla_path=/var/www/${HUBZILLA_DOMAIN_NAME}/htdocs
-        if [ -d $hubzilla_path ]; then
-            echo $"Backing up Hubzilla"
-            function_check backup_database_to_usb
-            backup_database_to_usb hubzilla
+    hubzilla_path=/var/www/${HUBZILLA_DOMAIN_NAME}/htdocs
+    if [ -d $hubzilla_path ]; then
+        function_check backup_database_to_usb
+        backup_database_to_usb hubzilla
 
-            backup_directory_to_usb $hubzilla_path hubzilla
-
-            echo $"Hubzilla backup complete"
-        fi
+        backup_directory_to_usb $hubzilla_path hubzilla
     fi
 }
 
 function restore_local_hubzilla {
-    if ! grep -q "hubzilla domain" $COMPLETION_FILE; then
-        return
-    fi
-    HUBZILLA_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "hubzilla domain" | awk -F ':' '{print $2}')
-    if [ $HUBZILLA_DOMAIN_NAME ]; then
-        echo $"Restoring Hubzilla"
-        temp_restore_dir=/root/temphubzilla
-        hubzilla_dir=/var/www/${HUBZILLA_DOMAIN_NAME}/htdocs
+    temp_restore_dir=/root/temphubzilla
+    hubzilla_dir=/var/www/${HUBZILLA_DOMAIN_NAME}/htdocs
 
-        function_check hubzilla_create_database
-        hubzilla_create_database
+    function_check hubzilla_create_database
+    hubzilla_create_database
 
-        restore_database hubzilla ${HUBZILLA_DOMAIN_NAME}
-        if [ -d $USB_MOUNT/backup/hubzilla ]; then
-            if [ ! -d $hubzilla_dir/store/[data]/smarty3 ]; then
-                mkdir -p $hubzilla_dir/store/[data]/smarty3
-            fi
-            chmod 777 $hubzilla_dir/store/[data]/smarty3
-            chown -R www-data:www-data $hubzilla_dir/*
-            if [ -d $temp_restore_dir ]; then
-                rm -rf $temp_restore_dir
-            fi
+    restore_database hubzilla ${HUBZILLA_DOMAIN_NAME}
+    if [ -d $USB_MOUNT/backup/hubzilla ]; then
+        if [ ! -d $hubzilla_dir/store/[data]/smarty3 ]; then
+            mkdir -p $hubzilla_dir/store/[data]/smarty3
         fi
-        echo $"Restore of Hubzilla complete"
+        chmod 777 $hubzilla_dir/store/[data]/smarty3
+        chown -R www-data:www-data $hubzilla_dir/*
+        if [ -d $temp_restore_dir ]; then
+            rm -rf $temp_restore_dir
+        fi
     fi
 }
 
 function backup_remote_hubzilla {
-    if grep -q "hubzilla domain" $COMPLETION_FILE; then
-        HUBZILLA_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "hubzilla domain" | awk -F ':' '{print $2}')
-        temp_backup_dir=/var/www/${HUBZILLA_DOMAIN_NAME}/htdocs
-        if [ -d $temp_backup_dir ]; then
-            suspend_site ${HUBZILLA_DOMAIN_NAME}
-            backup_database_to_friend hubzilla
-            echo "Backing up Hubzilla installation"
-            backup_directory_to_friend $temp_backup_dir hubzilla
-            restart_site
-            echo "Backup of Hubzilla complete"
-        else
-            echo $"Hubzilla domain specified but not found in /var/www/${HUBZILLA_DOMAIN_NAME}"
-            exit 2578
-        fi
+    temp_backup_dir=/var/www/${HUBZILLA_DOMAIN_NAME}/htdocs
+    if [ -d $temp_backup_dir ]; then
+        suspend_site ${HUBZILLA_DOMAIN_NAME}
+        backup_database_to_friend hubzilla
+        echo "Backing up Hubzilla installation"
+        backup_directory_to_friend $temp_backup_dir hubzilla
+        restart_site
+        echo "Backup of Hubzilla complete"
+    else
+        echo $"Hubzilla domain specified but not found in /var/www/${HUBZILLA_DOMAIN_NAME}"
+        exit 2578
     fi
 }
 
 function restore_remote_hubzilla {
-    if grep -q "hubzilla domain" $COMPLETION_FILE; then
-        echo $"Restoring Hubzilla"
-        HUBZILLA_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "hubzilla domain" | awk -F ':' '{print $2}')
-        function_check restore_database_from_friend
+    function_check restore_database_from_friend
 
-        function_check hubzilla_create_database
-        hubzilla_create_database
+    function_check hubzilla_create_database
+    hubzilla_create_database
 
-        restore_database_from_friend hubzilla ${HUBZILLA_DOMAIN_NAME}
-        if [ -d $SERVER_DIRECTORY/backup/hubzilla ]; then
-            if [ ! -d /var/www/${HUBZILLA_DOMAIN_NAME}/htdocs/store/[data]/smarty3 ]; then
-                mkdir -p /var/www/${HUBZILLA_DOMAIN_NAME}/htdocs/store/[data]/smarty3
-            fi
-            chmod 777 /var/www/${HUBZILLA_DOMAIN_NAME}/htdocs/store/[data]/smarty3
-            chown -R www-data:www-data /var/www/${HUBZILLA_DOMAIN_NAME}/htdocs/*
+    restore_database_from_friend hubzilla ${HUBZILLA_DOMAIN_NAME}
+    if [ -d $SERVER_DIRECTORY/backup/hubzilla ]; then
+        if [ ! -d /var/www/${HUBZILLA_DOMAIN_NAME}/htdocs/store/[data]/smarty3 ]; then
+            mkdir -p /var/www/${HUBZILLA_DOMAIN_NAME}/htdocs/store/[data]/smarty3
         fi
-        if [ -d /root/temphubzilla ]; then
-            rm -rf /root/temphubzilla
-        fi
-        echo $"Restore of Hubzilla complete"
+        chmod 777 /var/www/${HUBZILLA_DOMAIN_NAME}/htdocs/store/[data]/smarty3
+        chown -R www-data:www-data /var/www/${HUBZILLA_DOMAIN_NAME}/htdocs/*
+    fi
+    if [ -d /root/temphubzilla ]; then
+        rm -rf /root/temphubzilla
     fi
 }
 
@@ -359,7 +328,6 @@ function remove_hubzilla {
         return
     fi
     echo $'Removing Hubzilla'
-    HUBZILLA_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "hubzilla domain" | awk -F ':' '{print $2}')
     nginx_dissite $HUBZILLA_DOMAIN_NAME
     if [ -d /var/www/$HUBZILLA_DOMAIN_NAME ]; then
         rm -rf /var/www/$HUBZILLA_DOMAIN_NAME
@@ -376,22 +344,6 @@ function remove_hubzilla {
 }
 
 function install_hubzilla {
-    if [ ! $ONION_ONLY ]; then
-        ONION_ONLY='no'
-    fi
-    if grep -q "ONION_ONLY" $CONFIGURATION_FILE; then
-        ONION_ONLY=$(grep "ONION_ONLY" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
-    if grep -q "HUBZILLA_DOMAIN_NAME" $CONFIGURATION_FILE; then
-        HUBZILLA_DOMAIN_NAME=$(grep "HUBZILLA_DOMAIN_NAME" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
-    if grep -q "HUBZILLA_CODE" $CONFIGURATION_FILE; then
-        HUBZILLA_CODE=$(grep "HUBZILLA_CODE" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
-    if grep -q "DDNS_PROVIDER" $CONFIGURATION_FILE; then
-        DDNS_PROVIDER=$(grep "DDNS_PROVIDER" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
-
     if [ ! $HUBZILLA_DOMAIN_NAME ]; then
         return
     fi
diff --git a/src/freedombone-app-rss b/src/freedombone-app-rss
--- a/src/freedombone-app-rss
+++ b/src/freedombone-app-rss
@@ -42,6 +42,15 @@ RSS_READER_PATH=/etc/share/tt-rss
 RSS_READER_GNUSOCIAL_REPO="https://github.com/bashrc/ttrss-gnusocial"
 RSS_READER_GNUSOCIAL_COMMIT='20b2535e3f2b0ddc0117b584bdcaa6bf7a2d9fa2'
 
+rss_variables=(RSS_READER_REPO
+               RSS_MOBILE_READER_REPO
+               RSS_READER_COMMIT
+               RSS_MOBILE_READER_COMMIT
+               RSS_READER_ADMIN_PASSWORD
+               RSS_READER_DOMAIN_NAME
+               USB_MOUNT
+               MY_USERNAME)
+
 function install_interactive_rss {
     echo -n ''
 }
@@ -81,14 +90,14 @@ function reconfigure_rss {
 }
 
 function upgrade_rss {
-    if grep -Fxq "install_rss" $COMPLETION_FILE; then
+    if [[ $(app_is_installed rss) == "1" ]]; then
         function_check set_repo_commit
         set_repo_commit $RSS_READER_PATH "rss reader commit" "$RSS_READER_COMMIT" $RSS_READER_REPO
         function_check rss_modifications
         rss_modifications
     fi
 
-    if grep -Fxq "install_rss_mobile_reader" $COMPLETION_FILE; then
+    if [[ $(app_is_installed rss_mobile_reader) == "1" ]]; then
         if [ ! $RSS_READER_PATH ]; then
             RSS_READER_PATH=/etc/share/tt-rss
         fi
@@ -116,105 +125,86 @@ function upgrade_rss {
 }
 
 function backup_local_rss {
-    RSS_READER_DOMAIN_NAME='ttrss'
-    if grep -q "rss reader domain" $COMPLETION_FILE; then
+    if [ -d /etc/share/tt-rss ]; then
         RSS_READER_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "rss reader domain" | awk -F ':' '{print $2}')
-    fi
 
-    if grep -q "rss reader domain" $COMPLETION_FILE; then
-        if [ -d /etc/share/tt-rss ]; then
-            RSS_READER_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "rss reader domain" | awk -F ':' '{print $2}')
+        echo $"Backing up ttrss"
 
-            echo $"Backing up ttrss"
+        function_check backup_database_to_usb
+        backup_database_to_usb ttrss
 
-            function_check backup_database_to_usb
-            backup_database_to_usb ttrss
+        backup_directory_to_usb /etc/share/tt-rss ttrss
 
-            backup_directory_to_usb /etc/share/tt-rss ttrss
-
-            echo $"ttrss backup complete"
-        fi
+        echo $"ttrss backup complete"
     fi
 }
 
 function restore_local_rss {
-    if ! grep -q "rss reader domain" $COMPLETION_FILE; then
-        return
+    temp_restore_dir=/root/tempttrss
+
+    function_check rss_create_database
+    rss_create_database
+
+    restore_database ttrss ${RSS_READER_DOMAIN_NAME}
+
+    if [ -d /etc/share/tt-rss ]; then
+        if [ -d /root/tempttrss/etc/share/tt-rss ]; then
+            rm -rf /etc/share/tt-rss
+            mv /root/tempttrss/etc/share/tt-rss /etc/share/
+            if [ ! "$?" = "0" ]; then
+                function_check set_user_permissions
+                set_user_permissions
+
+                function_check backup_unmount_drive
+                backup_unmount_drive
+                exit 528823
+            fi
+            if [ -d /etc/letsencrypt/live/${RSS_READER_DOMAIN_NAME} ]; then
+                ln -s /etc/letsencrypt/live/${RSS_READER_DOMAIN_NAME}/privkey.pem /etc/ssl/private/${2}.key
+                ln -s /etc/letsencrypt/live/${RSS_READER_DOMAIN_NAME}/fullchain.pem /etc/ssl/certs/${2}.pem
+            else
+                # Ensure that the bundled SSL cert is being used
+                if [ -f /etc/ssl/certs/${RSS_READER_DOMAIN_NAME}.bundle.crt ]; then
+                    sed -i "s|${RSS_READER_DOMAIN_NAME}.crt|${RSS_READER_DOMAIN_NAME}.bundle.crt|g" /etc/nginx/sites-available/${2}
+                fi
+            fi
+        fi
     fi
-    RSS_READER_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "rss reader domain" | awk -F ':' '{print $2}')
-    if [ $RSS_READER_DOMAIN_NAME ]; then
-        echo $"Restoring ttrss"
-        temp_restore_dir=/root/tempttrss
 
-        function_check rss_create_database
-        rss_create_database
+    function_check rss_modifications
+    rss_modifications
 
-        restore_database ttrss ${RSS_READER_DOMAIN_NAME}
-
-        if [ -d /etc/share/tt-rss ]; then
-            if [ -d /root/tempttrss/etc/share/tt-rss ]; then
-                rm -rf /etc/share/tt-rss
-                mv /root/tempttrss/etc/share/tt-rss /etc/share/
-                if [ ! "$?" = "0" ]; then
-                    function_check set_user_permissions
-                    set_user_permissions
-
-                    function_check backup_unmount_drive
-                    backup_unmount_drive
-                    exit 528823
-                fi
-                if [ -d /etc/letsencrypt/live/${RSS_READER_DOMAIN_NAME} ]; then
-                    ln -s /etc/letsencrypt/live/${RSS_READER_DOMAIN_NAME}/privkey.pem /etc/ssl/private/${2}.key
-                    ln -s /etc/letsencrypt/live/${RSS_READER_DOMAIN_NAME}/fullchain.pem /etc/ssl/certs/${2}.pem
-                else
-                    # Ensure that the bundled SSL cert is being used
-                    if [ -f /etc/ssl/certs/${RSS_READER_DOMAIN_NAME}.bundle.crt ]; then
-                        sed -i "s|${RSS_READER_DOMAIN_NAME}.crt|${RSS_READER_DOMAIN_NAME}.bundle.crt|g" /etc/nginx/sites-available/${2}
-                    fi
-                fi
-            fi
+    if [ -d $USB_MOUNT/backup/ttrss ]; then
+        chown -R www-data:www-data /etc/share/tt-rss
+        if [ -d $temp_restore_dir ]; then
+            rm -rf $temp_restore_dir
         fi
-
-        function_check rss_modifications
-        rss_modifications
-
-        if [ -d $USB_MOUNT/backup/ttrss ]; then
-            chown -R www-data:www-data /etc/share/tt-rss
-            if [ -d $temp_restore_dir ]; then
-                rm -rf $temp_restore_dir
-            fi
-        fi
-        echo $"Restore of ttrss complete"
     fi
 }
 
 function backup_remote_rss {
-    if grep -q "rss reader domain" $COMPLETION_FILE; then
-        RSS_READER_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "rss reader domain" | awk -F ':' '{print $2}')
-        if [ -d /etc/share/tt-rss ]; then
-            function_check suspend_site
-            suspend_site ${RSS_READER_DOMAIN_NAME}
+    if [ -d /etc/share/tt-rss ]; then
+        function_check suspend_site
+        suspend_site ${RSS_READER_DOMAIN_NAME}
 
-            function_check backup_database_to_friend
-            backup_database_to_friend ttrss
+        function_check backup_database_to_friend
+        backup_database_to_friend ttrss
 
-            echo $"Backing up RSS reader installation"
+        echo $"Backing up RSS reader installation"
 
-            function_check backup_directory_to_friend
-            backup_directory_to_friend /etc/share/tt-rss ttrss
+        function_check backup_directory_to_friend
+        backup_directory_to_friend /etc/share/tt-rss ttrss
 
-            function_check restart_site
-            restart_site
-        else
-            echo $"RSS reader domain specified but not found in /etc/share/ttrss}"
-        fi
+        function_check restart_site
+        restart_site
+    else
+        echo $"RSS reader domain specified but not found in /etc/share/ttrss}"
     fi
 }
 
 function restore_remote_rss {
     if grep -q "rss reader domain" $COMPLETION_FILE; then
         echo $"Restoring ttrss"
-        RSS_READER_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "rss reader domain" | awk -F ':' '{print $2}')
         function_check restore_database_from_friend
 
         function_check rss_create_database
@@ -256,9 +246,6 @@ function remove_rss {
     if [[ $(app_is_installed rss) == "0" ]]; then
         return
     fi
-    if grep -q "RSS_READER_DOMAIN_NAME" $CONFIGURATION_FILE; then
-        RSS_READER_DOMAIN_NAME=$(grep "RSS_READER_DOMAIN_NAME" $CONFIGURATION_FILE | awk -F '=' '{print $2}')
-    fi
     nginx_dissite $RSS_READER_DOMAIN_NAME
     function_check remove_onion_service
     remove_onion_service ttrss ${RSS_READER_ONION_PORT} ${RSS_MOBILE_READER_ONION_PORT}
@@ -292,10 +279,6 @@ function rss_modifications {
 }
 
 function install_rss_main {
-    if grep -Fxq "install_rss_main" $COMPLETION_FILE; then
-        return
-    fi
-
     apt-get -y install php-gettext php5-curl php5-gd php5-mysql git
     apt-get -y install curl php-xml-parser php5-mcrypt
 
@@ -520,7 +503,7 @@ function install_rss_main {
         chmod 600 /home/$MY_USERNAME/README
     fi
 
-    echo 'install_rss_main' >> $COMPLETION_FILE
+    install_completed rss_main
 }
 
 function install_rss_gnusocial {
@@ -560,8 +543,7 @@ function install_rss_gnusocial {
         echo "rss reader gnusocial commit:$RSS_READER_GNUSOCIAL_COMMIT" >> $COMPLETION_FILE
     fi
     chown -R www-data:www-data $RSS_READER_GNUSOCIAL_PATH
-
-    echo 'install_rss_gnusocial' >> $COMPLETION_FILE
+    install_completed rss_gnusocial
 }
 
 function install_rss_mobile_reader {
@@ -612,8 +594,7 @@ function install_rss_mobile_reader {
     chown -R www-data:www-data $RSS_MOBILE_READER_PATH
     chown -R www-data:www-data $RSS_READER_PATH
     chmod a+x $RSS_MOBILE_READER_PATH
-
-    echo 'install_rss_mobile_reader' >> $COMPLETION_FILE
+    install_completed rss_mobile_reader
 }
 
 function install_rss {
