Option to install only from a configuration file

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -58,6 +58,9 @@ DOMAIN_NAME=
 MY_USERNAME=
 SYSTEM_TYPE=$VARIANT_FULL
 
+# whether the system is being installed from a pre-created configuration file
+INSTALLING_FROM_CONFIGURATION_FILE="no"
+
 # An optional configuration file which overrides some of these variables
 CONFIGURATION_FILE="freedombone.cfg"
 
@@ -354,6 +357,7 @@ function show_help {
   echo ''
   echo '  -h --help             Show help'
   echo '     menuconfig         Easy interactive installation'
+  echo '  -c --config           Installing from a configuration file'
   echo '     --bbb              Installing on Beaglebone Black'
   echo '  -u --user             User to install the system as'
   echo '  -d --domain           Default domain name'
@@ -507,6 +511,13 @@ else
   case $key in
     -h|--help)
     show_help
+    ;;
+    # load a configuration file
+    -c|--config)
+    shift
+    CONFIGURATION_FILE="$1"
+    INSTALLING_FROM_CONFIGURATION_FILE="yes"
+    break
     ;;
     # username within /home
     -u|--user)
@@ -693,6 +704,13 @@ function read_configuration {
   if [ ! $INSTALLING_ON_BBB ]; then
       if [[ $USB_DRIVE == /dev/sda1 ]]; then
           USB_DRIVE=/dev/sdb1
+      fi
+  fi
+
+  if [[ $INSTALLING_FROM_CONFIGURATION_FILE == "yes"  ]]; then
+      if [ ! -f $CONFIGURATION_FILE ]; then
+          echo "The configuration file $CONFIGURATION_FILE was not found"
+          exit 8935
       fi
   fi
 
