Exit if peertube install fails

diff --git a/src/freedombone-app-peertube b/src/freedombone-app-peertube
--- a/src/freedombone-app-peertube
+++ b/src/freedombone-app-peertube
@@ -661,6 +661,10 @@ fi
 EOF
     chmod +x $rootdir/usr/bin/install_peertube
     chroot "$rootdir" /usr/bin/install_peertube
+    if [ ! "$?" = "0" ]; then
+        echo $'PeerTube install failed'
+        exit 735638
+    fi
 
     echo '[Unit]' > $rootdir/etc/systemd/system/peertube.service
     echo 'Description=PeerTube Decentralized video streaming platform' >> $rootdir/etc/systemd/system/peertube.service
