Check that toxid was built

diff --git a/src/freedombone-app-tox b/src/freedombone-app-tox
--- a/src/freedombone-app-tox
+++ b/src/freedombone-app-tox
@@ -497,8 +497,12 @@ make
 make install
 EOF
 
+	if [ ! -f $rootdir/usr/local/bin/toxid ]; then
+		echo $'toxid not found'
+		exit 74370
+	fi
 	if [ ! -f $rootdir/usr/local/bin/toxavahi ]; then
-	  exit 3621729
+		exit 3621729
 	fi
 	echo "* *     * * *   root    /usr/local/bin/toxavahi > /dev/null" >> $rootdir/etc/crontab
 }
