Additional python packages for searx

diff --git a/src/freedombone-app-searx b/src/freedombone-app-searx
--- a/src/freedombone-app-searx
+++ b/src/freedombone-app-searx
@@ -855,6 +855,18 @@ function install_searx {
         exit 63738
     fi
 
+    pip install requests --upgrade
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install requests'
+        exit 357282
+    fi
+
+    pip install pygments --upgrade
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install pygments'
+        exit 357282
+    fi
+
     if [ ! -d $SEARX_PATH ]; then
         mkdir -p $SEARX_PATH
     fi
