Also check for successful mysql installation

diff --git a/src/freedombone-utils-database b/src/freedombone-utils-database
--- a/src/freedombone-utils-database
+++ b/src/freedombone-utils-database
@@ -158,6 +158,11 @@ function install_mariadb {
         exit 54
     fi
 
+    if [ ! -f /usr/bin/mysql ]; then
+        echo $"ERROR: mariadb-server does not appear to have installed. $CHECK_MESSAGE"
+        exit 34672
+    fi
+
     mysqladmin -u root password "$MARIADB_PASSWORD"
     mark_completed $FUNCNAME
 }
