Check for sql schema early

diff --git a/src/freedombone-app-kanboard b/src/freedombone-app-kanboard
--- a/src/freedombone-app-kanboard
+++ b/src/freedombone-app-kanboard
@@ -438,6 +438,11 @@ function install_kanboard {
     chmod a+w "/var/www/$KANBOARD_DOMAIN_NAME/htdocs/data"
     chown -R www-data:www-data "/var/www/$KANBOARD_DOMAIN_NAME/htdocs"
 
+    if [ ! -f "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs/app/Schema/Sql/mysql.sql" ]; then
+        echo $'kanboard sql file not found'
+        exit 6358356
+    fi
+
     function_check kanboard_create_database
     kanboard_create_database
 
@@ -613,10 +618,6 @@ function install_kanboard {
     sed -i "s|define('DB_PORT'.*|define('DB_PORT', null);|g" "$kanboard_configfile"
     logging_off_kanboard
 
-    if [ ! -f "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs/app/Schema/Sql/mysql.sql" ]; then
-        echo $'kanboard sql file not found'
-        exit 6358356
-    fi
     initialise_database kanboard "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs/app/Schema/Sql/mysql.sql"
     cd "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs" || exit 24582468
     install_composer
