Onion servive for keyserver

diff --git a/src/freedombone-app-keyserver b/src/freedombone-app-keyserver
--- a/src/freedombone-app-keyserver
+++ b/src/freedombone-app-keyserver
@@ -141,6 +141,7 @@ function remove_keyserver {
     remove_config_param KEYSERVER_CODE
     function_check remove_onion_service
     remove_onion_service keyserver ${KEYSERVER_ONION_PORT}
+    remove_onion_service sks 11370 11371 11372
     remove_completion_param "install_keyserver"
 
     firewall_remove 11370 tcp
@@ -286,6 +287,22 @@ function install_keyserver {
     echo '' >> $sksconf_file
     echo 'max_matches:                    500' >> $sksconf_file
     chown debian-sks: $sksconf_file
+
+    if ! grep -q "hidden_service_sks" /etc/tor/torrc; then
+        echo 'HiddenServiceDir /var/lib/tor/hidden_service_sks/' >> /etc/tor/torrc
+        echo "HiddenServicePort 11370 127.0.0.1:11370" >> /etc/tor/torrc
+        echo "HiddenServicePort 11371 127.0.0.1:11371" >> /etc/tor/torrc
+        echo "HiddenServicePort 11372 127.0.0.1:11372" >> /etc/tor/torrc
+        echo $'Added onion site for sks'
+    fi
+
+    onion_update
+    wait_for_onion_service 'sks'
+
+    if [ ! -f /var/lib/tor/hidden_service_xmpp/hostname ]; then
+        echo $'xmpp onion site hostname not found'
+        exit 65349
+    fi
 
     KEYSERVER_ONION_HOSTNAME=$(add_onion_service keyserver 80 ${KEYSERVER_ONION_PORT})
 
