Kanboard permissions

diff --git a/src/freedombone-app-kanboard b/src/freedombone-app-kanboard
--- a/src/freedombone-app-kanboard
+++ b/src/freedombone-app-kanboard
@@ -613,11 +613,15 @@ function install_kanboard {
     sed -i "s|define('DB_PORT'.*|define('DB_PORT', null);|g" "$kanboard_configfile"
     logging_off_kanboard
 
+    if [ ! -f "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs/app/Schema/Sql/mysql.sql" ]; then
+        echo $'kanboard sql file not found'
+        exit 6358356
+    fi
     initialise_database kanboard "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs/app/Schema/Sql/mysql.sql"
-    chown -R www-data:www-data "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs"
-
     cd "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs" || exit 24582468
     install_composer
+
+    chown -R www-data:www-data "/var/www/${KANBOARD_DOMAIN_NAME}/htdocs"
 
     systemctl restart mariadb
     systemctl restart php7.0-fpm
