Install myqr in images

diff --git a/src/freedombone-image-customise b/src/freedombone-image-customise
--- a/src/freedombone-image-customise
+++ b/src/freedombone-image-customise
@@ -147,6 +147,21 @@ PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
 # eg. sda2
 EXTERNAL_DRIVE=
 
+
+image_install_myqr() {
+    if [ -f "$rootdir/usr/local/bin/myqr" ]; then
+        return
+    fi
+    # shellcheck disable=SC2086
+    chroot "$rootdir" $INSTALL_PACKAGES python3-pip
+    chroot "$rootdir" pip3 install myqr
+    if [ ! -f "$rootdir/usr/local/bin/myqr" ]; then
+        echo $'Failed to install myqr'
+        exit 3683653
+    fi
+}
+
+
 configure_backports() {
     echo "deb http://${DEBIAN_REPO}/debian/ ${DEBIAN_VERSION}-backports main" >> "$rootdir/etc/apt/sources.list"
 }
@@ -2383,6 +2398,7 @@ create_generic_image
 atheros_wifi
 continue_installation
 image_install_nodejs
+image_install_myqr
 initialise_mesh
 configure_wifi
 configure_user_interface
diff --git a/src/freedombone-utils-setup b/src/freedombone-utils-setup
--- a/src/freedombone-utils-setup
+++ b/src/freedombone-utils-setup
@@ -867,6 +867,18 @@ function microsd_card_optimisations {
       systemctl enable optimisations
 }
 
+function install_myqr {
+    if [ -f /usr/local/bin/myqr ]; then
+        return
+    fi
+    $INSTALL_PACKAGES python3-pip
+    pip3 install myqr
+    if [ ! -f /usr/local/bin/myqr ]; then
+        echo $'Failed to install myqr'
+        exit 3683653
+    fi
+}
+
 function setup_utils {
     read_config_param "PROJECT_REPO"
     write_config_param "PROJECT_REPO" "$PROJECT_REPO"
@@ -1098,6 +1110,9 @@ function setup_utils {
 
     function_check install_shellcheck
     install_shellcheck
+
+    function_check install_myqr
+    install_myqr
 }
 
 function setup_email {
