Can configure wifi from image builder

diff --git a/src/freedombone-image b/src/freedombone-image
--- a/src/freedombone-image
+++ b/src/freedombone-image
@@ -100,6 +100,13 @@ MIRROR='http://ftp.de.debian.org/debian'
 # Whether to only install debian but nothing else
 DEBIAN_INSTALL_ONLY='no'
 
+# wifi settings
+WIFI_INTERFACE='wlan0'
+WIFI_SSID=
+WIFI_TYPE='wpa-psk'
+WIFI_PASSPHRASE=
+WIFI_HOTSPOT='no'
+
 mesh_router_setup_script() {
     # create a setup script for a mesh router
     mesh_script_filename=$1
@@ -220,24 +227,46 @@ do
             shift
             DEBIAN_INSTALL_ONLY="$1"
             ;;
-        *)
-            # unknown option
-            ;;
-    esac
-    shift
+        --interface|--if)
+			shift
+			WIFI_INTERFACE="$1"
+			;;
+        --ssid|--essid)
+			shift
+			WIFI_SSID="$1"
+			;;
+        --wifitype)
+			shift
+			WIFI_TYPE="$1"
+			;;
+        --wifipass|--passphrase)
+			shift
+			WIFI_PASSPHRASE="$1"
+			;;
+        --hotspot)
+			shift
+			if [[ $"$1" == $'yes' || $"$1" == $'y' ]]; then
+				WIFI_HOTSPOT='yes'
+			fi			
+			;;
+		*)
+			# unknown option
+			;;
+	esac
+	shift
 done
 
 if [[ $INTERACTIVE == "yes" || $INTERACTIVE == "y" || $INTERACTIVE == "Yes" ]]; then
-    ${PROJECT_NAME}-config --minimal "$MINIMAL_INSTALL"
-    if [ -f freedombone.cfg ]; then
-        CONFIG_FILENAME=freedombone.cfg
-        DEFAULT_DOMAIN_NAME=$(cat $CONFIG_FILENAME | grep 'DEFAULT_DOMAIN_NAME' | awk -F '=' '{print $2}')
-    fi
+	${PROJECT_NAME}-config --minimal "$MINIMAL_INSTALL"
+	if [ -f freedombone.cfg ]; then
+		CONFIG_FILENAME=freedombone.cfg
+		DEFAULT_DOMAIN_NAME=$(cat $CONFIG_FILENAME | grep 'DEFAULT_DOMAIN_NAME' | awk -F '=' '{print $2}')
+	fi
 fi
 
 if [[ $GENERIC_IMAGE == "yes" ]]; then
-    USERNAME=$GENERIC_IMAGE_USERNAME
-    PASSWORD=$GENERIC_IMAGE_PASSWORD
+	USERNAME=$GENERIC_IMAGE_USERNAME
+	PASSWORD=$GENERIC_IMAGE_PASSWORD
 fi
 
 # If this is a mesh variant then create an appropriate script
@@ -248,45 +277,45 @@ fi
 #fi
 
 if [ ! $PASSWORD ]; then
-    # generate a random password
-    PASSWORD="$(openssl rand -base64 10 | cut -c1-8)"
+	# generate a random password
+	PASSWORD="$(openssl rand -base64 10 | cut -c1-8)"
 fi
 
 # Move any existing images into a build subdirectory
 image_types=( xz img sig vdi qcow2 )
 for im in "${image_types[@]}"
 do
-    no_of_files=$(ls -afq ${CURR_DIR}/${PROJECT_NAME}*.${im} | wc -l)
-    if (( no_of_files > 0 )); then
-        if [ ! -d ${CURR_DIR}/build ]; then
-            mkdir ${CURR_DIR}/build
-        fi
-        mv -f ${CURR_DIR}/${PROJECT_NAME}*.${im} ${CURR_DIR}/build
-    fi
+	no_of_files=$(ls -afq ${CURR_DIR}/${PROJECT_NAME}*.${im} | wc -l)
+	if (( no_of_files > 0 )); then
+		if [ ! -d ${CURR_DIR}/build ]; then
+			mkdir ${CURR_DIR}/build
+		fi
+		mv -f ${CURR_DIR}/${PROJECT_NAME}*.${im} ${CURR_DIR}/build
+	fi
 done
 
 # Delete anything which didn't move
 for im in "${image_types[@]}"
 do
-    no_of_files=$(ls -afq ${CURR_DIR}/${PROJECT_NAME}*.${im} | wc -l)
-    if (( no_of_files > 0 )); then
-        rm -f ${CURR_DIR}/${PROJECT_NAME}*.${im}
-    fi
+	no_of_files=$(ls -afq ${CURR_DIR}/${PROJECT_NAME}*.${im} | wc -l)
+	if (( no_of_files > 0 )); then
+		rm -f ${CURR_DIR}/${PROJECT_NAME}*.${im}
+	fi
 done
 
 # Remove any existing login credentials file
 if [ -f ${CURR_DIR}/${PROJECT_NAME}_login_credentials.txt ]; then
-    rm ${CURR_DIR}/${PROJECT_NAME}_login_credentials.txt
+	rm ${CURR_DIR}/${PROJECT_NAME}_login_credentials.txt
 fi
 
 if [ -d $TEMPBUILD_DIR ]; then
-    rm -rf $TEMPBUILD_DIR
+	rm -rf $TEMPBUILD_DIR
 fi
 mkdir -p $TEMPBUILD_DIR
 if [ -f /usr/local/bin/$MAKEFILE ]; then
-    cp /usr/local/bin/$MAKEFILE $TEMPBUILD_DIR/Makefile
+	cp /usr/local/bin/$MAKEFILE $TEMPBUILD_DIR/Makefile
 else
-    cp /usr/bin/$MAKEFILE $TEMPBUILD_DIR/Makefile
+	cp /usr/bin/$MAKEFILE $TEMPBUILD_DIR/Makefile
 fi
 
 cp -r /etc/${PROJECT_NAME}/* $TEMPBUILD_DIR
@@ -295,64 +324,69 @@ chown -R $CURR_USER:$CURR_USER $TEMPBUILD_DIR
 cd $TEMPBUILD_DIR
 
 if [[ $MINIMAL_INSTALL == "yes" ]]; then
-    IMAGE_NAME='min'
+	IMAGE_NAME='min'
 fi
 
 if [[ $ONION_ONLY != "no" ]]; then
-    IMAGE_NAME='onion'
+	IMAGE_NAME='onion'
 fi
 
 cd $TEMPBUILD_DIR
 make $IMAGE_TYPE \
-     USERNAME="$USERNAME" \
-     PASSWORD="$PASSWORD" \
-     ROUTER_IP_ADDRESS="$ROUTER_IP_ADDRESS" \
-     BOX_IP_ADDRESS="$BOX_IP_ADDRESS" \
-     NAMESERVER1="$NAMESERVER1" \
-     NAMESERVER2="$NAMESERVER2" \
-     PROJECT_NAME="$PROJECT_NAME" \
-     CONFIG_FILENAME="$CONFIG_FILENAME" \
-     IMAGE_SIZE="$IMAGE_SIZE" \
-     SSH_PUBKEY="$SSH_PUBKEY" \
-     GENERIC_IMAGE="$GENERIC_IMAGE" \
-     MINIMAL_INSTALL="$MINIMAL_INSTALL" \
-     SSH_PORT="$SSH_PORT" \
-     ONION_ONLY="$ONION_ONLY" \
-     IMAGE_NAME="$IMAGE_NAME" \
-     PROJECT_REPO="$PROJECT_REPO" \
-     MIRROR="$MIRROR" \
-     BUILD_MIRROR="$MIRROR" \
-     DEBIAN_INSTALL_ONLY="$DEBIAN_INSTALL_ONLY"
-
+	 USERNAME="$USERNAME" \
+	 PASSWORD="$PASSWORD" \
+	 ROUTER_IP_ADDRESS="$ROUTER_IP_ADDRESS" \
+	 BOX_IP_ADDRESS="$BOX_IP_ADDRESS" \
+	 NAMESERVER1="$NAMESERVER1" \
+	 NAMESERVER2="$NAMESERVER2" \
+	 PROJECT_NAME="$PROJECT_NAME" \
+	 CONFIG_FILENAME="$CONFIG_FILENAME" \
+	 IMAGE_SIZE="$IMAGE_SIZE" \
+	 SSH_PUBKEY="$SSH_PUBKEY" \
+	 GENERIC_IMAGE="$GENERIC_IMAGE" \
+	 MINIMAL_INSTALL="$MINIMAL_INSTALL" \
+	 SSH_PORT="$SSH_PORT" \
+	 ONION_ONLY="$ONION_ONLY" \
+	 IMAGE_NAME="$IMAGE_NAME" \
+	 PROJECT_REPO="$PROJECT_REPO" \
+	 MIRROR="$MIRROR" \
+	 BUILD_MIRROR="$MIRROR" \
+	 DEBIAN_INSTALL_ONLY="$DEBIAN_INSTALL_ONLY" \
+	 WIFI_INTERFACE="$WIFI_INTERFACE" \
+	 WIFI_SSID="$WIFI_SSID" \
+	 WIFI_TYPE="$WIFI_TYPE" \
+	 WIFI_PASSPHRASE="$WIFI_PASSPHRASE" \
+	 WIFI_HOTSPOT="$WIFI_HOTSPOT"
+	 
 if [ ! "$?" = "0" ]; then
-    echo $'Build failed'
-    rm -rf $TEMPBUILD_DIR
-    exit 1
+	echo $'Build failed'
+	rm -rf $TEMPBUILD_DIR
+	exit 1
 fi
 
 EXPECTED_EXTENSION='xz'
 if [[ $IMAGE_TYPE == "qemu"* ]]; then
-    EXPECTED_EXTENSION='qcow2'
+	EXPECTED_EXTENSION='qcow2'
 fi
 if [[ $IMAGE_TYPE == "virtualbox"* ]]; then
-    EXPECTED_EXTENSION='vdi'
+	EXPECTED_EXTENSION='vdi'
 fi
 
 shopt -s nullglob
 imgfiles=(build/${PROJECT_NAME}*.${EXPECTED_EXTENSION})
 if [ ${#imgfiles[@]} -eq 0 ]; then
-    echo $'Image was not created'
-    rm -rf $TEMPBUILD_DIR
-    exit 2
+	echo $'Image was not created'
+	rm -rf $TEMPBUILD_DIR
+	exit 2
 fi
 
 # Move images from temporary directory to the current directory
 for im in "${image_types[@]}"
 do
-    no_of_files=$(ls -afq build/${PROJECT_NAME}*.${im} | wc -l)
-    if (( no_of_files > 0 )); then
-        mv build/${PROJECT_NAME}*.${im} ${CURR_DIR}/
-    fi
+	no_of_files=$(ls -afq build/${PROJECT_NAME}*.${im} | wc -l)
+	if (( no_of_files > 0 )); then
+		mv build/${PROJECT_NAME}*.${im} ${CURR_DIR}/
+	fi
 done
 
 # Remove the temporary directory
@@ -367,32 +401,32 @@ Image was created.
 You will be able to log into it with:
 "
 if [[ $IMAGE_TYPE != "virtualbox"* && $IMAGE_TYPE != "qemu"* ]]; then
-    echo $"    ssh $USERNAME@$DEFAULT_DOMAIN_NAME -p $SSH_PORT
+	echo $"    ssh $USERNAME@$DEFAULT_DOMAIN_NAME -p $SSH_PORT
 
-    Password: $PASSWORD
+Password: $PASSWORD
 "
 else
-    if [[ $IMAGE_TYPE != "qemu"* ]]; then
-        echo $"    Username: $USERNAME
-    Password: $PASSWORD
+	if [[ $IMAGE_TYPE != "qemu"* ]]; then
+		echo $"    Username: $USERNAME
+Password: $PASSWORD
 "
-    else
-        if [[ $IMAGE_TYPE != "qemu-x86_64"* && $IMAGE_TYPE != "qemu-amd64"* ]]; then
-            echo "qemu-system-i386 -m ${VM_MEMORY} $(ls ${PROJECT_NAME}*.qcow2)"
-        else
-            echo "qemu-system-x86_64 -m ${VM_MEMORY} $(ls ${PROJECT_NAME}*.qcow2)"
-        fi
-        echo $"
-    Username: $USERNAME
-    Password: $PASSWORD
+	else
+		if [[ $IMAGE_TYPE != "qemu-x86_64"* && $IMAGE_TYPE != "qemu-amd64"* ]]; then
+			echo "qemu-system-i386 -m ${VM_MEMORY} $(ls ${PROJECT_NAME}*.qcow2)"
+		else
+			echo "qemu-system-x86_64 -m ${VM_MEMORY} $(ls ${PROJECT_NAME}*.qcow2)"
+		fi
+		echo $"
+Username: $USERNAME
+Password: $PASSWORD
 "
-    fi
+	fi
 fi
 ls -lh ${PROJECT_NAME}*.img ${PROJECT_NAME}*.sig ${PROJECT_NAME}*.xz ${PROJECT_NAME}*.vdi ${PROJECT_NAME}*.qcow2
 
 # Remove the mesh script after use
 if [[ $VARIANT == "mesh"* ]]; then
-    rm -f $CONFIG_FILENAME
+	rm -f $CONFIG_FILENAME
 fi
 
 # record the default login credentials for later use
@@ -401,12 +435,12 @@ Password: $PASSWORD" > ${CURR_DIR}/${PROJECT_NAME}_login_credentials.txt
 chmod 600 ${CURR_DIR}/${PROJECT_NAME}_login_credentials.txt
 
 if [[ $IMAGE_TYPE != "virtualbox"* && $IMAGE_TYPE != "qemu"* ]]; then
-    echo ''
-    echo $'You can copy the image to a microSD card with:'
-    echo ''
-    echo "    unxz -k ${PROJECT_NAME}*.img.xz"
-    echo "    sudo dd bs=1M if=${PROJECT_NAME}*.img of=/dev/sdX conv=fdatasync"
-    echo ''
+	echo ''
+	echo $'You can copy the image to a microSD card with:'
+	echo ''
+	echo "    unxz -k ${PROJECT_NAME}*.img.xz"
+	echo "    sudo dd bs=1M if=${PROJECT_NAME}*.img of=/dev/sdX conv=fdatasync"
+	echo ''
 fi
 
 exit 0
