More generic gogs directories

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -213,7 +213,7 @@ HUBZILLA_ADDONS_COMMIT='e32f98d65850a8681e8242f3db8b6484abb35c67'
 GIT_DOMAIN_NAME=
 GIT_CODE=
 GIT_ONION_PORT=8090
-GIT_DOMAIN_REPO="https://github.com/gogits/gogs.git"
+GIT_DOMAIN_REPO="https://github.com/gogits/gogs"
 GIT_ADMIN_PASSWORD=
 GOGS_COMMIT='efea642d6cf419c9587d44b95ff2bc04e89f7bfe'
 GO_PACKAGE_MANAGER_REPO="https://github.com/gpmgo/gopm"
@@ -6675,9 +6675,12 @@ function install_gogs {
     if [ ! -d $GOPATH/src/github.com/gogits ]; then
         mkdir -p $GOPATH/src/github.com/gogits
     fi
-    cd $GOPATH/src/github.com/gogits
     git_clone $GIT_DOMAIN_REPO $GOPATH/src/github.com/gogits/gogs
-    cd gogs
+    if [ ! -d $GOPATH/src/github.com/gogits/gogs ]; then
+        echo $"Unable to clone repo $GOPATH/src/github.com/gogits/gogs"
+        exit 85482
+    fi
+    cd $GOPATH/src/github.com/gogits/gogs
     git checkout $GOGS_COMMIT -b $GOGS_COMMIT
     if ! grep -q "Gogs commit" $COMPLETION_FILE; then
         echo "Gogs commit:$GOGS_COMMIT" >> $COMPLETION_FILE
@@ -9636,7 +9639,7 @@ function install_ipfs {
         exit 8242
     fi
 
-    cd /home/git/go/src/github.com/ipfs/go-ipfs
+    cd /home/git/go/src/$IPFS_GO_REPO2
     git checkout $IPFS_COMMIT -b $IPFS_COMMIT
     if ! grep -q "ipfs commit" $COMPLETION_FILE; then
         echo "ipfs commit:$IPFS_COMMIT" >> $COMPLETION_FILE
