Local backup of gnusocial

diff --git a/src/freedombone-utils-backup b/src/freedombone-utils-backup
--- a/src/freedombone-utils-backup
+++ b/src/freedombone-utils-backup
@@ -28,6 +28,26 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+# whether a given site is being suspended during backup
+SUSPENDED_SITE=
+
+function suspend_site {
+	# suspends a given website
+	SUSPENDED_SITE="$1"
+	nginx_dissite $SUSPENDED_SITE
+	service nginx reload
+}
+
+function restart_site {
+	# restarts a given website
+	if [ ! $SUSPENDED_SITE ]; then
+		return
+	fi
+	nginx_ensite $SUSPENDED_SITE
+	service nginx reload
+	SUSPENDED_SITE=
+}
+
 function configure_backup_key {
 	if grep -Fxq "configure_backup_key" $COMPLETION_FILE; then
 		return
@@ -160,6 +180,85 @@ function backup_unmount_drive {
 		rm -rf /dev/mapper/encrypted_usb
 	fi
 	echo $"Backup to USB drive is complete. You can now unplug it."
+}
+
+function backup_database_local {
+	if [ ${#DATABASE_PASSWORD} -lt 2 ]; then
+		echo $"No MariaDB password was given"
+		function_check restart_site
+		restart_site
+		exit 10
+	fi
+	if [ ! -d $USB_MOUNT/backup/${1} ]; then
+		mkdir -p $USB_MOUNT/backup/${1}
+	fi
+	if [ ! -d $USB_MOUNT/backup/${1}data ]; then
+		mkdir -p $USB_MOUNT/backup/${1}data
+	fi
+	if [ ! -d /root/temp${1}data ]; then
+		mkdir -p /root/temp${1}data
+	fi
+	echo $"Obtaining ${1} database backup"
+	mysqldump --lock-tables --password="$DATABASE_PASSWORD" ${1} > /root/temp${1}data/${1}.sql
+	if [ ! -s /root/temp${1}data/${1}.sql ]; then
+		echo $"${1} database could not be saved"
+		shred -zu /root/temp${1}data/*
+		rm -rf /root/temp${1}data
+		umount $USB_MOUNT
+		rm -rf $USB_MOUNT
+		restart_site
+		exit 6835872
+	fi
+}
+
+function backup_directory_to_usb {
+	if [ ! -d ${1} ]; then
+		echo $"WARNING: directory does not exist: ${1}"
+	else
+		BACKUP_KEY_EXISTS=$(gpg --list-keys "$ADMIN_NAME (backup key)")
+		if [ ! "$?" = "0" ]; then
+			echo $"Backup key could not be found"
+			function_check restart_site
+			restart_site
+			exit 6
+		fi
+		MY_BACKUP_KEY_ID=$(gpg --list-keys "$ADMIN_NAME (backup key)" | grep 'pub ' | awk -F ' ' '{print $2}' | awk -F '/' '{print $2}')
+		if [ ! -d $USB_MOUNT/backup/${2} ]; then
+			mkdir -p $USB_MOUNT/backup/${2}
+		fi
+		obnam force-lock -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+		obnam backup -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+		if [[ $ENABLE_BACKUP_VERIFICATION == "yes" ]]; then
+			obnam verify -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+			if [ ! "$?" = "0" ]; then
+				umount $USB_MOUNT
+				rm -rf $USB_MOUNT
+				if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+					shred -zu ${1}/*
+					rm -rf ${1}
+				fi
+				function_check restart_site
+				restart_site
+				exit 683252
+			fi
+		fi
+		obnam forget --keep=30d -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID
+		if [ ! "$?" = "0" ]; then
+			umount $USB_MOUNT
+			rm -rf $USB_MOUNT
+			if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+				shred -zu ${1}/*
+				rm -rf ${1}
+			fi
+			function_check restart_site
+			restart_site
+			exit 7
+		fi
+		if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+			shred -zu ${1}/*
+			rm -rf ${1}
+		fi
+	fi
 }
 
 # NOTE: deliberately no exit 0
