Tox client check for exit success

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -6564,6 +6564,10 @@ function install_tox_client {
     fi
 
     ${PROJECT_NAME}-mesh-install tox_client
+    if [ ! "$?" = "0" ]; then       
+        echo $'Could not install Tox client'
+        exit 67248
+    fi
 
     # initial setup of username
     su -c "echo 'n
