Backup and restore of postgresql

diff --git a/src/freedombone-backup-remote b/src/freedombone-backup-remote
--- a/src/freedombone-backup-remote
+++ b/src/freedombone-backup-remote
@@ -336,6 +336,28 @@ function backup_mariadb {
     fi
 }
 
+function backup_postgresql {
+    if [ ! -d /etc/postgresql ]; then
+        return
+    fi
+
+    temp_backup_dir=/root/temppostgresql
+    if [ ! -d $temp_backup_dir ]; then
+        mkdir $temp_backup_dir
+    fi
+    sudo -u postgres pg_dumpall --roles-only > $temp_backup_dir/postgresql.sql
+    if [ ! -s $temp_backup_dir/postgresql.sql ]; then
+        echo $"Unable to backup postgresql settings"
+        rm -rf $temp_backup_dir
+        umount $USB_MOUNT
+        rm -rf $USB_MOUNT
+        exit 684365
+    fi
+    echo "$DATABASE_PASSWORD" > $temp_backup_dir/db
+    chmod 400 $temp_backup_dir/db
+    backup_directory_to_friend $temp_backup_dir postgresql
+}
+
 # Returns the filename of a key share
 function get_key_share {
     no_of_shares=$1
@@ -410,6 +432,7 @@ if [[ $TEST_MODE == "no" ]]; then
     backup_web_server
     backup_admin_readme
     backup_mariadb
+    backup_postgresql
     backup_certs
     backup_mailing_list
     backup_apps remote
