Install composer

diff --git a/src/freedombone-utils-web b/src/freedombone-utils-web
--- a/src/freedombone-utils-web
+++ b/src/freedombone-utils-web
@@ -917,4 +917,20 @@ function create_default_web_site {
     fi
 }
 
+function install_composer {
+    # curl -sS https://getcomposer.org/installer | php
+    if [ -f ~/${PROJECT_NAME}/image_build/composer_install ]; then
+        cat ~/${PROJECT_NAME}/image_build/composer_install | php
+    else
+        if [ -f /home/$MY_USERNAME/${PROJECT_NAME}/image_build/composer_install ]; then
+            cat /home/$MY_USERNAME/${PROJECT_NAME}/image_build/composer_install | php
+        fi
+    fi
+    php composer.phar install
+    if [ ! "$?" = "0" ]; then
+        echo $'Unable to run composer install'
+        exit 7252198
+    fi
+}
+
 # NOTE: deliberately no exit 0
