Check for exit success

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -3048,6 +3048,10 @@ function configure_avahi {
     fi
 
     ${PROJECT_NAME}-mesh-install avahi
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install avahi'
+        exit 68442
+    fi
 
     if [ $DEFAULT_DOMAIN_NAME ]; then
         sed -i "s|#host-name=.*|host-name=$DEFAULT_DOMAIN_NAME|g" /etc/avahi/avahi-daemon.conf
@@ -3071,6 +3075,10 @@ function mesh_babel {
     fi
 
     ${PROJECT_NAME}-mesh-install babel
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install babel'
+        exit 67242
+    fi
 
     echo 'mesh_babel' >> $COMPLETION_FILE
 }
@@ -3084,6 +3092,10 @@ function mesh_batman {
     fi
 
     ${PROJECT_NAME}-mesh-install -f batman
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install batman'
+        exit 72524
+    fi
 
     if ! grep -q "Mesh Networking (B.A.T.M.A.N)" /home/$MY_USERNAME/README; then
         echo '' >> /home/$MY_USERNAME/README
@@ -6513,6 +6525,10 @@ function install_tox_node {
     fi
 
     ${PROJECT_NAME}-mesh-install -f tox_node
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install tox node'
+        exit 26778
+    fi
 
     TOX_ONION_HOSTNAME=$(add_onion_service tox ${TOX_PORT} ${TOX_PORT})
 
