Warn about rethinkdb not supporting arm

diff --git a/src/freedombone-app-turtl b/src/freedombone-app-turtl
--- a/src/freedombone-app-turtl
+++ b/src/freedombone-app-turtl
@@ -442,6 +442,11 @@ __ENDCONFIG__
     # start the turtl server
     systemctl restart rethinkdb
 
+    if [ ! -f $TURTL_BASE_DIR/quicklisp/setup.lisp ]; then
+        echo $"$TURTL_BASE_DIR/quicklisp/setup.lisp was not found"
+        exit 6238234
+    fi
+
     echo '[Unit]' > /etc/systemd/system/turtl.service
     echo 'Description=Note taking service' >> /etc/systemd/system/turtl.service
     echo 'Documentation=http://turtl.it' >> /etc/systemd/system/turtl.service
