Add a tahoelafs introducer to the full install

diff --git a/src/freedombone-app-tahoelafs b/src/freedombone-app-tahoelafs
--- a/src/freedombone-app-tahoelafs
+++ b/src/freedombone-app-tahoelafs
@@ -28,7 +28,7 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-VARIANTS='mesh'
+VARIANTS='full mesh'
 
 TAHOELAFS_REPO="https://github.com/tahoe-lafs/tahoe-lafs"
 TAHOELAFS_COMMIT='30b421d48b3d1dae2ef507bf27a1f3816300cd92'
@@ -42,7 +42,7 @@ TAHOE_COMMAND="cd /var/lib/tahoelafs && venv/bin/tahoe"
 function reconfigure_tahoelafs {
     for d in /home/*/ ; do
         USERNAME=$(echo "$d" | awk -F '/' '{print $3}')
-        if [[ $USERNAME != "git" && $USERNAME != "mirrors" && $USERNAME != "sync" ]]; then
+        if [[ $USERNAME != "git" && $USERNAME != "mirrors" && $USERNAME != "sync" && $USERNAME != "tahoelafs" ]]; then
             if [ -d /home/$USERNAME/.tahoe ]; then
                 su -c "$TAHOE_COMMAND stop" - $USERNAME
                 rm -rf /home/$USERNAME/.tahoe
@@ -257,17 +257,65 @@ function install_tahoelafs {
 
     apt-get -y install build-essential python-pip python-dev libffi-dev libssl-dev python-virtualenv
 
-    git_clone $TAHOELAFS_REPO /var/lib/tahoelafs
-    cd /var/lib/tahoelafs
+    # create a user to run the introducer
+    if [ ! -d /home/tahoelafs ]; then
+        # add a gogs user account
+        adduser --disabled-login --gecos 'tahoe-lafs' tahoelafs
+    fi
+
+    if [ -d /home/tahoelafs/Maildir ]; then
+        rm -rf /home/tahoelafs/Maildir
+    fi
+
+    if [ ! -d /home/tahoelafs/.tahoe-introducer ]; then
+        mkdir /home/tahoelafs/.tahoe-introducer
+    fi
+
+    git_clone $TAHOELAFS_REPO /home/tahoelafs/tahoelafs
+    cd /home/tahoelafs/tahoelafs
     git checkout $TAHOELAFS_COMMIT -b $TAHOELAFS_COMMIT
     virtualenv venv
     venv/bin/pip install --editable .
     configure_firewall_for_tahoelafs
-    reconfigure_tahoelafs
-    tahoelafs_update_script /usr/bin/update-tahoelafs
 
-    function_check cron_add_mins
-    cron_add_mins 1 "/usr/bin/update-tahoelafs 2> /dev/null"
+    su -c "cd $TAHOE_COMMAND create-introducer /home/tahoelafs/.tahoe-introducer" - tahoelafs
+    TAHOELAFS_CONFIG=/home/tahoelafs/.tahoe-introducer/tahoe.cfg
+    if [ ! -f $TAHOELAFS_CONFIG ]; then
+        exit 62831
+    fi
+
+    sed -i "s|nickname =.*|nickname = $HOSTNAME|g" $TAHOELAFS_CONFIG
+
+    if ! grep -q "[storage]" $TAHOELAFS_CONFIG; then
+        echo '' >> $TAHOELAFS_CONFIG
+        echo '[storage]' >> $TAHOELAFS_CONFIG
+        echo 'enabled = true' >> $TAHOELAFS_CONFIG
+        echo "reserved_space = $TAHOELAFS_STORAGE_SPACE" >> $TAHOELAFS_CONFIG
+    fi
+
+    chown -R tahoelafs:tahoelafs /home/tahoelafs
+
+    TAHOELAFS_DAEMON_FILE=/etc/systemd/system/tahoelafs.service
+    echo '[Unit]' > $TAHOELAFS_DAEMON_FILE
+    echo 'Description=Tahoe-LAFS introducer' >> $TAHOELAFS_DAEMON_FILE
+    echo 'After=syslog.target' >> $TAHOELAFS_DAEMON_FILE
+    echo 'After=network.target' >> $TAHOELAFS_DAEMON_FILE
+    echo '' >> $TAHOELAFS_DAEMON_FILE
+    echo '[Service]' >> $TAHOELAFS_DAEMON_FILE
+    echo 'Type=simple' >> $TAHOELAFS_DAEMON_FILE
+    echo "User=tahoelafs" >> $TAHOELAFS_DAEMON_FILE
+    echo "Group=tahoelafs" >> $TAHOELAFS_DAEMON_FILE
+    echo "WorkingDirectory=/home/tahoelafs" >> $TAHOELAFS_DAEMON_FILE
+    echo "ExecStart=venv/bin/tahoe start /home/tahoelafs/.tahoe-introducer" >> $TAHOELAFS_DAEMON_FILE
+    echo "ExecStop=venv/bin/tahoe stop /home/tahoelafs/.tahoe-introducer" >> $TAHOELAFS_DAEMON_FILE
+    echo 'Restart=on-failure' >> $TAHOELAFS_DAEMON_FILE
+    echo "Environment=\"USER=tahoelafs\" \"HOME=/home/tahoelafs\"" >> $TAHOELAFS_DAEMON_FILE
+    echo '' >> $TAHOELAFS_DAEMON_FILE
+    echo '[Install]' >> $TAHOELAFS_DAEMON_FILE
+    echo 'WantedBy=multi-user.target' >> $TAHOELAFS_DAEMON_FILE
+    systemctl enable tahoelafs
+    systemctl daemon-reload
+    systemctl start tahoelafs
 
     echo 'install_tahoelafs' >> $COMPLETION_FILE
 }
