Add bmx7 mesh protocol

diff --git a/src/freedombone-image-customise b/src/freedombone-image-customise
--- a/src/freedombone-image-customise
+++ b/src/freedombone-image-customise
@@ -128,6 +128,9 @@ MESH_TEXT_EDITOR='pluma'
 BMX6_REPO="https://github.com/bmx-routing/bmx6"
 BMX6_COMMIT='39dd1f2d99ac5a3fa28e92f8173c15039132e181'
 
+BMX7_REPO="https://github.com/bmx-routing/bmx7"
+BMX7_COMMIT='0a82c7c10fef44b259b35e77ab33632aa132d219'
+
 PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
 
 function configure_backports {
@@ -644,13 +647,31 @@ EOF
 }
 
 mesh_shutdown_script() {
+    mesh_shutdown_script=$rootdir/usr/bin/meshshutdown
+    echo '#!/bin/bash' > $mesh_shutdown_script
+    echo '' >> $mesh_shutdown_script
+    echo "if grep -q 'batman-adv' ${MESH_CURRENT_PROTOCOL}; then" >> $mesh_shutdown_script
+    echo '    batman stop' >> $mesh_shutdown_script
+    echo 'fi' >> $mesh_shutdown_script
+    echo '' >> $mesh_shutdown_script
+    echo "if grep -q 'bmx6' ${MESH_CURRENT_PROTOCOL}; then" >> $mesh_shutdown_script
+    echo '    bmx stop' >> $mesh_shutdown_script
+    echo 'fi' >> $mesh_shutdown_script
+    echo '' >> $mesh_shutdown_script
+    echo "if grep -q 'bmx7' ${MESH_CURRENT_PROTOCOL}; then" >> $mesh_shutdown_script
+    echo '    bmxsec stop' >> $mesh_shutdown_script
+    echo 'fi' >> $mesh_shutdown_script
+    chroot "$rootdir" chmod +x /usr/bin/meshshutdown
+
     echo '[Unit]' > $rootdir/etc/systemd/system/meshshutdown.service
     echo 'Description=Shuts down the mesh' >> $rootdir/etc/systemd/system/meshshutdown.service
     echo 'Before=shutdown.target' >> $rootdir/etc/systemd/system/meshshutdown.service
     echo '' >> $rootdir/etc/systemd/system/meshshutdown.service
     echo '[Service]' >> $rootdir/etc/systemd/system/meshshutdown.service
+    echo 'User=root' >> $rootdir/etc/systemd/system/meshshutdown.service
+    echo 'Group=root' >> $rootdir/etc/systemd/system/meshshutdown.service
     echo 'ExecStart=/bin/true' >> $rootdir/etc/systemd/system/meshshutdown.service
-    echo 'ExecStop=/bin/bash /usr/local/bin/batman stop' >> $rootdir/etc/systemd/system/meshshutdown.service
+    echo 'ExecStop=/bin/bash /usr/bin/meshshutdown' >> $rootdir/etc/systemd/system/meshshutdown.service
     echo 'RemainAfterExit=yes' >> $rootdir/etc/systemd/system/meshshutdown.service
     echo '' >> $rootdir/etc/systemd/system/meshshutdown.service
     echo '[Install]' >> $rootdir/etc/systemd/system/meshshutdown.service
@@ -700,19 +721,91 @@ EOF
         exit 79835292
     fi
 
+    rm $rootdir/usr/bin/install_bmx6
+
     echo '[Unit]' > $rootdir/etc/systemd/system/bmx6.service
     echo 'Description=BMX6 mesh routing protocol' >> $rootdir/etc/systemd/system/bmx6.service
     echo 'Requires=network.target' >> $rootdir/etc/systemd/system/bmx6.service
     echo 'After=network.target' >> $rootdir/etc/systemd/system/bmx6.service
     echo '' >> $rootdir/etc/systemd/system/bmx6.service
     echo '[Service]' >> $rootdir/etc/systemd/system/bmx6.service
+    echo 'Type=forking' >> $rootdir/etc/systemd/system/bmx6.service
     echo 'User=root' >> $rootdir/etc/systemd/system/bmx6.service
     echo 'Group=root' >> $rootdir/etc/systemd/system/bmx6.service
     echo 'ExecStart=/usr/sbin/bmx6 dev=wlan0' >> $rootdir/etc/systemd/system/bmx6.service
+    echo 'ExecStop=/usr/bin/kill -15 $MAINPID' >> $rootdir/etc/systemd/system/bmx6.service
+    echo 'PIDFile=/var/run/bmx6/pid' >> $rootdir/etc/systemd/system/bmx6.service
     echo 'Restart=on-failure' >> $rootdir/etc/systemd/system/bmx6.service
     echo '' >> $rootdir/etc/systemd/system/bmx6.service
     echo '[Install]' >> $rootdir/etc/systemd/system/bmx6.service
     echo 'WantedBy=multi-user.target' >> $rootdir/etc/systemd/system/bmx6.service
+}
+
+install_bmx7() {
+    chroot "$rootdir" apt-get -qy install libjson-c-dev zlib1g-dev libiw-dev
+
+    git clone $BMX7_REPO $rootdir/etc/bmx7
+
+    cat <<EOF > $rootdir/usr/bin/install_bmx7
+#!/bin/bash
+cd /etc
+wget https://polarssl.org/code/releases/polarssl-1.3.3-gpl.tgz
+tar xzvf polarssl-1.3.3-gpl.tgz
+cd /etc/polarssl-1.3.3
+make
+sudo make install
+
+cd /etc/bmx7
+git checkout $BMX7_COMMIT -b $BMX7_COMMIT
+make EXTRA_CFLAGS="-DCRYPTLIB=POLARSSL_1_3_3"
+make install
+
+cd /etc/bmx7/lib/bmx7_http_info
+make
+make install
+
+cd /etc/bmx7/lib/bmx7_json
+make
+make install
+
+cd /etc/bmx7/lib/bmx7_tun
+make
+make install
+
+cd /etc/bmx7/lib/bmx7_sms
+make
+make install
+
+cd /etc/bmx7/lib/bmx7_topology
+make
+make install
+EOF
+    chroot "$rootdir" chmod +x /usr/bin/install_bmx7
+    chroot "$rootdir" /usr/bin/install_bmx7
+
+    if [ ! -f $rootdir/usr/sbin/bmx7 ]; then
+        echo $'bmx7 was not installed'
+        exit 67836235
+    fi
+
+    rm $rootdir/usr/bin/install_bmx7
+
+    echo '[Unit]' > $rootdir/etc/systemd/system/bmx7.service
+    echo 'Description=BMX7 mesh routing protocol' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'Requires=network.target' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'After=network.target' >> $rootdir/etc/systemd/system/bmx7.service
+    echo '' >> $rootdir/etc/systemd/system/bmx7.service
+    echo '[Service]' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'Type=forking' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'User=root' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'Group=root' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'ExecStart=/usr/sbin/bmx7 dev=wlan0' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'ExecStop=/usr/bin/kill -15 $MAINPID' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'PIDFile=/var/run/bmx6/pid' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'Restart=on-failure' >> $rootdir/etc/systemd/system/bmx7.service
+    echo '' >> $rootdir/etc/systemd/system/bmx7.service
+    echo '[Install]' >> $rootdir/etc/systemd/system/bmx7.service
+    echo 'WantedBy=multi-user.target' >> $rootdir/etc/systemd/system/bmx7.service
 }
 
 initialise_mesh() {
@@ -751,10 +844,14 @@ initialise_mesh() {
     # dhcp daemon for hotspot on secondary wifi adapter
     chroot "$rootdir" apt-get -yq install dnsmasq
 
+    # set the default protocol to be used
+    echo 'batman-adv' > $rootdir$MESH_DEFAULT_PROTOCOL
+
     configure_firewall
     install_avahi
     install_batman
     install_bmx6
+    install_bmx7
     mesh_shutdown_script
     install_vpn
     install_tomb
