Add fedwiki friends module

diff --git a/src/freedombone-app-fedwiki b/src/freedombone-app-fedwiki
--- a/src/freedombone-app-fedwiki
+++ b/src/freedombone-app-fedwiki
@@ -262,6 +262,7 @@ function remove_fedwiki {
     rm /etc/systemd/system/fedwiki.service
     systemctl daemon-reload
 
+    npm uninstall -g wiki-security-friends
     npm uninstall -g wiki
 
     function_check remove_nodejs
@@ -399,6 +400,12 @@ function install_fedwiki {
         exit 6293523
     fi
 
+    npm install -g wiki-security-friends@0.1.0
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install wiki-security-friends'
+        exit 783533
+    fi
+
     if [ ! -f /usr/local/bin/wiki ]; then
         echo $'wiki was not installed'
         exit 5293524
@@ -439,6 +446,8 @@ function install_fedwiki {
     fedwiki_setup_web
 
     ${PROJECT_NAME}-pass -u $MY_USERNAME -a fedwiki -p "$FEDWIKI_ADMIN_PASSWORD"
+
+    fedwiki_auth_file=/var/lib/fedwiki/status/owner.json
 
     function_check add_ddns_domain
     add_ddns_domain $FEDWIKI_DOMAIN_NAME
