Fix wget for nodejs repo key

diff --git a/src/freedombone-utils-nodejs b/src/freedombone-utils-nodejs
--- a/src/freedombone-utils-nodejs
+++ b/src/freedombone-utils-nodejs
@@ -71,7 +71,11 @@ function mesh_install_nodejs {
 
     $mesh_install_nodejs_prefix apt-get -qy install wget curl g++ m4 libtool automake
     $mesh_install_nodejs_prefix apt-get -yq install libxext-dev libxtst-dev libxkbfile-dev
-    $mesh_install_nodejs_prefix wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key > /root/node.gpg.key
+    $mesh_install_nodejs_prefix wget https://deb.nodesource.com/gpgkey/nodesource.gpg.key -O /root/node.gpg.key
+    if [ ! -f $rootdir/root/node.gpg.key ]; then
+        echo $'Unable to obtain gpg key for nodejs repo'
+        exit 6389252
+    fi
     $mesh_install_nodejs_prefix apt-key add /root/node.gpg.key
     echo "deb https://deb.nodesource.com/node_6.x stretch main" > $rootdir/etc/apt/sources.list.d/nodesource.list
     echo "deb-src https://deb.nodesource.com/node_6.x stretch main" >> $rootdir/etc/apt/sources.list.d/nodesource.list
