Add GNU Social user

diff --git a/src/freedombone-adduser b/src/freedombone-adduser
--- a/src/freedombone-adduser
+++ b/src/freedombone-adduser
@@ -229,6 +229,19 @@ if grep -q "install_sip" $COMPLETION_FILE; then
     fi
 fi
 
+if grep -q "install_gnu_social" $COMPLETION_FILE; then
+    MICROBLOG_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "GNU Social domain" | awk -F ':' '{print $2}')
+    if [ -d /var/www/$MICROBLOG_DOMAIN_NAME ]; then
+        cd /var/www/$MICROBLOG_DOMAIN_NAME/htdocs
+        php scripts/registeruser.php -n $MY_USERNAME -w "$NEW_USER_PASSWORD" -e "$MY_USERNAME@$HOSTNAME"
+        echo $'Created GNU Social user'
+    else
+        echo $"Unable to find GNU Social installation at /var/www/$MICROBLOG_DOMAIN_NAME/htdocs"
+        userdel -r $MY_USERNAME
+        exit 11
+    fi
+fi
+
 #if grep -q "install_owncloud" $COMPLETION_FILE; then
 #    export OC_PASS="$NEW_USER_PASSWORD"
 #    occ user:add --password-from-env --display-name="$MY_USERNAME" --group="users" $MY_USERNAME
