Compile toxid on mesh nodes

diff --git a/src/freedombone-image-mesh b/src/freedombone-image-mesh
--- a/src/freedombone-image-mesh
+++ b/src/freedombone-image-mesh
@@ -386,6 +386,34 @@ function compile_toxcore {
 	echo $'toxcore compile completed' >> $INSTALL_LOG
 }
 
+function compile_toxid {
+	if [ ! -d $INSTALL_DIR/toxid ]; then
+		echo $'toxid repo not found' >> $INSTALL_LOG
+		exit 52682
+	fi
+	cd $INSTALL_DIR/toxid
+	if [ -f $INSTALL_DIR/make_toxid.txt ]; then
+		rm $INSTALL_DIR/make_toxid.txt
+	fi
+	make > $INSTALL_DIR/make_toxid.txt
+	if [ ! "$?" = "0" ]; then
+		echo $'Failed to compile toxid' >> $INSTALL_LOG
+		echo $"See $INSTALL_DIR/make_toxid.txt" >> $INSTALL_LOG
+		exit 58432
+	fi
+	rm $INSTALL_DIR/make_toxid.txt
+	make install
+
+	toxavahi
+
+	# publish regularly
+	if ! grep -q "toxavahi" /etc/crontab; then
+		echo "* *     * * *   root    toxavahi > /dev/null" >> /etc/crontab
+	fi
+
+	systemctl restart avahi-daemon
+}
+
 function compile_tox_client {
 	echo $'Compiling tox client' >> $INSTALL_LOG
 
@@ -479,6 +507,7 @@ if [ -f /root/.initial_mesh_setup ]; then
 	configure_zeronet_mail
 	configure_zeronet_forum
 	compile_toxcore
+	compile_toxid
 	compile_tox_client
 	configure_toxcore
 	configure_zeronet
