Ensure that the backup key is trusted

diff --git a/src/freedombone-backup-local b/src/freedombone-backup-local
--- a/src/freedombone-backup-local
+++ b/src/freedombone-backup-local
@@ -380,6 +380,18 @@ function simple_store_backup_keys {
     simple_backup_password=
 }
 
+function trust_backup_key {
+    GPG_BACKUP_ID=$(gpg --list-keys "(backup key)" | sed -n '2p' | sed 's/^[ \t]*//')
+    if [ ! "$GPG_BACKUP_ID" ]; then
+        echo $'Unable to get gpg backup key ID'
+        umount $USB_MOUNT
+        rm -rf $USB_MOUNT
+        exit 54875684
+    fi
+    # shellcheck disable=SC2086
+    (echo trust && echo 5 && echo y && echo quit) | gpg --command-fd 0 --edit-key $GPG_BACKUP_ID
+}
+
 backup_device="$1"
 backup_admin_username="$2"
 
@@ -420,6 +432,9 @@ check_storage_space_remaining
 
 increment_backup_progress
 simple_store_backup_keys
+
+increment_backup_progress
+trust_backup_key
 
 increment_backup_progress
 backup_users
diff --git a/src/freedombone-restore-local b/src/freedombone-restore-local
--- a/src/freedombone-restore-local
+++ b/src/freedombone-restore-local
@@ -926,6 +926,18 @@ function simple_restore_backup_keys {
     simple_backup_password=
 }
 
+function trust_backup_key {
+    GPG_BACKUP_ID=$(gpg --list-keys "(backup key)" | sed -n '2p' | sed 's/^[ \t]*//')
+    if [ ! "$GPG_BACKUP_ID" ]; then
+        echo $'Unable to get gpg backup key ID'
+        umount $USB_MOUNT
+        rm -rf $USB_MOUNT
+        exit 54875684
+    fi
+    # shellcheck disable=SC2086
+    (echo trust && echo 5 && echo y && echo quit) | gpg --command-fd 0 --edit-key $GPG_BACKUP_ID
+}
+
 backup_device="$1"
 restore_app_name="$2"
 
@@ -948,6 +960,7 @@ backup_mount_drive "${backup_device}" "${ADMIN_USERNAME}" "${restore_app_name}"
 check_backup_exists
 check_admin_user
 simple_restore_backup_keys
+trust_backup_key
 copy_gpg_keys
 gpg_agent_setup root
 restore_blocklist
