gnusocial plugin for rss reader

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -516,6 +516,8 @@ RSS_READER_DOMAIN_NAME=ttrss
 RSS_MOBILE_READER_REPO="https://github.com/g2ttrss/g2ttrss-mobile"
 RSS_MOBILE_READER_COMMIT='c5af46ebf64076e4c62c978551fa749af268710b'
 RSS_READER_PATH=/etc/share/tt-rss
+RSS_READER_GNUSOCIAL_REPO="https://github.com/bashrc/ttrss-gnusocial"
+RSS_READER_GNUSOCIAL_COMMIT='d7c154829bd7ed0a6301bc14cf65d259c5fe844b'
 
 function show_help {
     echo ''
@@ -8260,6 +8262,48 @@ function install_rss_reader {
     echo 'install_rss_reader' >> $COMPLETION_FILE
 }
 
+function install_rss_reader_gnusocial {
+    if [[ $SYSTEM_TYPE == "$VARIANT_MAILBOX" || $SYSTEM_TYPE == "$VARIANT_CHAT" || $SYSTEM_TYPE == "$VARIANT_MEDIA" || $SYSTEM_TYPE == "$VARIANT_DEVELOPER" || $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
+        return
+    fi
+
+    if [ ! $MICROBLOG_DOMAIN_NAME ]; then
+        return
+    fi
+
+    if [ ! $RSS_READER_PATH ]; then
+        RSS_READER_PATH=/etc/share/tt-rss
+    fi
+    RSS_READER_GNUSOCIAL_PATH=${RSS_READER_PATH}/plugins/gnusocial
+
+    # update to the next commit
+    set_repo_commit $RSS_READER_GNUSOCIAL_PATH "RSS reader gnusocial commit" "$RSS_READER_GNUSOCIAL_COMMIT" $RSS_READER_GNUSOCIAL_REPO
+
+    if grep -Fxq "install_rss_reader_gnusocial" $COMPLETION_FILE; then
+        return
+    fi
+
+    if [ ! -d $INSTALL_DIR ]; then
+        mkdir -p $INSTALL_DIR
+    fi
+
+    cd $INSTALL_DIR
+    git_clone $RSS_READER_GNUSOCIAL_REPO ttrss-gnusocial
+    if [ ! -d $INSTALL_DIR/ttrss-gnusocial ]; then
+        echo $'Could not clone repo for RSS reader GNU Social plugin'
+        exit 52838
+    fi
+    cp -r $INSTALL_DIR/ttrss-gnusocial $RSS_READER_GNUSOCIAL_PATH
+    cd $RSS_READER_GNUSOCIAL_PATH
+    git checkout $RSS_READER_GNUSOCIAL_COMMIT -b $RSS_READER_GNUSOCIAL_COMMIT
+    if ! grep -q "RSS reader gnusocial commit" $COMPLETION_FILE; then
+        echo "RSS reader gnusocial commit:$RSS_READER_GNUSOCIAL_COMMIT" >> $COMPLETION_FILE
+    fi
+    echo "  define('gnusocial_url', '$MICROBLOG_DOMAIN_NAME');" >> $RSS_READER_PATH/config.php
+
+    echo 'install_rss_reader_gnusocial' >> $COMPLETION_FILE
+}
+
 function install_rss_mobile_reader {
     if [[ $SYSTEM_TYPE == "$VARIANT_MAILBOX" || $SYSTEM_TYPE == "$VARIANT_CHAT" || $SYSTEM_TYPE == "$VARIANT_MEDIA" || $SYSTEM_TYPE == "$VARIANT_DEVELOPER" || $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
         return
@@ -10335,6 +10379,7 @@ expire_gnu_social_posts
 install_gnu_social_theme
 install_gnu_social_markdown
 install_rss_reader
+install_rss_reader_gnusocial
 install_rss_mobile_reader
 install_hubzilla
 #install_search_engine
