Detect binary

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -7537,6 +7537,11 @@ function install_tox_node {
   fi
   make install
 
+  if [ ! -f /usr/local/bin/tox-bootstrapd ]; then
+      echo "File not found /usr/local/bin/tox-bootstrapd"
+      exit 73862
+  fi
+
   useradd --home-dir /var/lib/tox-bootstrapd --create-home --system --shell /sbin/nologin --comment "Account to run Tox's DHT bootstrap daemon" --user-group tox-bootstrapd
   chmod 700 /var/lib/tox-bootstrapd
   if [ ! -f $INSTALL_DIR/toxcore/other/bootstrap_daemon/tox-bootstrapd.conf ]; then
