Check that tor gets installed

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -3699,6 +3699,10 @@ function install_tor {
         return
     fi
     apt-get -y install tor
+    if [ ! -f /etc/tor/torrc ]; then
+        echo 'Tor failed to install'
+        exit 38259
+    fi
     echo 'install_tor' >> $COMPLETION_FILE
 }
 
