Preparations for let's encrypt

diff --git a/src/freedombone-renew-cert b/src/freedombone-renew-cert
--- a/src/freedombone-renew-cert
+++ b/src/freedombone-renew-cert
@@ -39,9 +39,17 @@ function show_help {
     echo ''
     echo '     --help                  Show help'
     echo '  -h --hostname [name]       Hostname'
-    echo '  -p --provider [name]       eg. startssl'
+    echo '  -p --provider [name]       eg. startssl/letsencrypt'
     echo ''
     exit 0
+}
+
+function renew_startssl {
+    echo "Renewing Let's Encrypt certificate"
+	letsencrypt renew --cert-path /etc/ssl/certs/$HOSTNAME.pem
+	if [ ! "$?" = "0" ]; then
+		echo "Unable to renew Let's encrypt certificate"
+	fi
 }
 
 function renew_startssl {
@@ -184,7 +192,11 @@ fi
 if [[ $PROVIDER == 'startssl' || $PROVIDER == 'StartSSL' ]]; then
     renew_startssl
 else
-    echo "$PROVIDER is not currently supported"
+	if [[ $PROVIDER == 'letsencrypt' ]]; then
+		renew_letsencrypt
+	else
+		echo "$PROVIDER is not currently supported"
+	fi
 fi
 
 exit 0
