Check that toxid gets installed

diff --git a/src/freedombone-image-customise b/src/freedombone-image-customise
--- a/src/freedombone-image-customise
+++ b/src/freedombone-image-customise
@@ -755,8 +755,11 @@ function mesh_tox_avahi {
 	echo '    exit 2' >> $TEMP_SCRIPT
 	echo 'fi' >> $TEMP_SCRIPT
 	echo 'make install' >> $TEMP_SCRIPT
+	echo 'if [ ! -f /usr/local/bin/toxavahi ]; then' >> $TEMP_SCRIPT
+	echo '  exit 3' >> $TEMP_SCRIPT
+	echo 'fi' >> $TEMP_SCRIPT
 	echo 'toxavahi' >> $TEMP_SCRIPT
-	echo 'echo "* *     * * *   root    toxavahi > /dev/null" >> /etc/crontab' >> $TEMP_SCRIPT
+	echo 'echo "* *     * * *   root    /usr/local/bin/toxavahi > /dev/null" >> /etc/crontab' >> $TEMP_SCRIPT
 	echo 'systemctl restart avahi-daemon' >> $TEMP_SCRIPT
 	echo 'exit 0' >> $TEMP_SCRIPT
 	chmod +x $TEMP_SCRIPT
@@ -764,7 +767,7 @@ function mesh_tox_avahi {
 
 	chroot "$rootdir" /root/$TEMP_SCRIPT_NAME
 	if [ ! "$?" = "0" ]; then
-		echo $'Unable to install toxid'
+		echo $"Unable to install toxid, returned $?"
 		rm $TEMP_SCRIPT
 		exit 62835
 	fi
