distro info

diff --git a/src/freedombone-image-make b/src/freedombone-image-make
--- a/src/freedombone-image-make
+++ b/src/freedombone-image-make
@@ -36,7 +36,7 @@ export TEXTDOMAINDIR="/usr/share/locale"
 
 PROJECT_INSTALL_DIR=/usr/local/bin
 if [ -f /usr/bin/${PROJECT_NAME} ]; then
-	PROJECT_INSTALL_DIR=/usr/bin
+    PROJECT_INSTALL_DIR=/usr/bin
 fi
 
 source /usr/share/${PROJECT_NAME}/utils/${PROJECT_NAME}-utils-setup
@@ -80,8 +80,8 @@ vendor_dir="${basedir}/vendor"
 vmdebootstrap_dir="${vendor_dir}/vmdebootstrap"
 
 if [ -z "$MIRROR" ] || [ -z "$SUITE" ] ; then
-	echo $"error: Missing MIRROR and SUITE settings inherited from Makefile."
-	exit 1
+    echo $"error: Missing MIRROR and SUITE settings inherited from Makefile."
+    exit 1
 fi
 
 # Packages to install in all Freedombone environments
@@ -100,9 +100,9 @@ dev_pkgs="build-essential devscripts make man-db emacs org-mode git mercurial"
 echo Building $MACHINE $PROJECT_NAME for $ARCHITECTURE.
 
 case "$MACHINE" in
-	beaglebone)
-		extra_pkgs="$beaglebone_pkgs"
-		extra_opts="\
+    beaglebone)
+        extra_pkgs="$beaglebone_pkgs"
+        extra_opts="\
  --variant minbase \
  --bootoffset=2mib \
  --bootsize 128M \
@@ -112,10 +112,10 @@ case "$MACHINE" in
  --foreign /usr/bin/qemu-arm-static \
  --roottype btrfs \
 "
-		;;
-	cubietruck | a20-olinuxino-lime | a20-olinuxino-lime2 | a20-olinuxino-micro | cubieboard2)
-		extra_pkgs="$a20_pkgs"
-		extra_opts="\
+        ;;
+    cubietruck | a20-olinuxino-lime | a20-olinuxino-lime2 | a20-olinuxino-micro | cubieboard2)
+        extra_pkgs="$a20_pkgs"
+        extra_opts="\
  --variant minbase \
  --bootoffset=1mib \
  --bootsize 128M \
@@ -125,29 +125,29 @@ case "$MACHINE" in
  --foreign /usr/bin/qemu-arm-static \
  --roottype btrfs \
 "
-		;;
-	virtualbox)
-		extra_opts="\
+        ;;
+    virtualbox)
+        extra_opts="\
  --grub \
  --roottype btrfs \
 "   ;;
-	qemu)
-		extra_opts="\
+    qemu)
+        extra_opts="\
  --grub \
  --roottype btrfs \
 "   ;;
-	usb)
-		extra_opts="\
+    usb)
+        extra_opts="\
  --grub \
  --roottype btrfs \
 "   ;;
-	meshclient)
-		extra_opts="\
+    meshclient)
+        extra_opts="\
  --grub \
  --roottype btrfs \
 "   ;;
-	all)
-		extra_opts="\
+    all)
+        extra_opts="\
  --grub \
  --roottype btrfs \
 "   ;;
@@ -156,29 +156,29 @@ esac
 # allow for lots of extra fun customization options.
 for customization in $CUSTOMIZATIONS
 do
-	case "$customization" in
-		development)
-			extra_pkgs="$extra_pkgs $dev_pkgs"
-			;;
-	esac
+    case "$customization" in
+        development)
+            extra_pkgs="$extra_pkgs $dev_pkgs"
+            ;;
+    esac
 done
 
 for p in $base_pkgs $extra_pkgs; do
-	pkgopts="$pkgopts --package $p"
+    pkgopts="$pkgopts --package $p"
 done
 
 # Make sure file is owned by current user, not root
 touch $(dirname $IMAGE)/${PROJECT_NAME}.log
 
 if [ -x vendor/vmdebootstrap/vmdebootstrap ] ; then
-	VMDEBOOTSTRAP=vendor/vmdebootstrap/vmdebootstrap
+    VMDEBOOTSTRAP=vendor/vmdebootstrap/vmdebootstrap
 else
-	VMDEBOOTSTRAP=vmdebootstrap
+    VMDEBOOTSTRAP=vmdebootstrap
 fi
 
 PROJECT_INSTALL_DIR=/usr/local/bin
 if [ -f /usr/bin/${PROJECT_NAME} ]; then
-	PROJECT_INSTALL_DIR=/usr/bin
+    PROJECT_INSTALL_DIR=/usr/bin
 fi
 
 echo $'Making customised customisation script'
@@ -190,17 +190,17 @@ TEMP_CUSTOMISE4=/tmp/${PROJECT_NAME}-image-customise4
 # cat all the things together
 combine_all_scripts $TEMP_CUSTOMISE2
 if [ ! -f $TEMP_CUSTOMISE2 ]; then
-	echo $'Could not combine scripts'
-	exit 627219
+    echo $'Could not combine scripts'
+    exit 627219
 fi
 
 echo $'Changing values within customised customisation script'
 cp $PROJECT_INSTALL_DIR/${PROJECT_NAME}-image-customise $TEMP_CUSTOMISE3
 if [ $MYUSERNAME ]; then
-	sed -i "s|MY_USERNAME=.*|MY_USERNAME=${MYUSERNAME}|g" $TEMP_CUSTOMISE3
+    sed -i "s|MY_USERNAME=.*|MY_USERNAME=${MYUSERNAME}|g" $TEMP_CUSTOMISE3
 fi
 if [ $MYPASSWORD ]; then
-	sed -i "s|MY_PASSWORD=.*|MY_PASSWORD=${MYPASSWORD}|g" $TEMP_CUSTOMISE3
+    sed -i "s|MY_PASSWORD=.*|MY_PASSWORD=${MYPASSWORD}|g" $TEMP_CUSTOMISE3
 fi
 sed -i "s|ROUTER_IP_ADDRESS=.*|ROUTER_IP_ADDRESS=${ROUTER_IP_ADDRESS}|g" $TEMP_CUSTOMISE3
 sed -i "s|BOX_IP_ADDRESS=.*|BOX_IP_ADDRESS=${BOX_IP_ADDRESS}|g" $TEMP_CUSTOMISE3
@@ -229,13 +229,13 @@ sed -i 's|#!/bin/bash||g' $TEMP_CUSTOMISE3
 
 cat $TEMP_CUSTOMISE2 $TEMP_CUSTOMISE3 > $TEMP_CUSTOMISE4
 if [ -f $TEMP_CUSTOMISE ]; then
-	sudo rm $TEMP_CUSTOMISE
+    sudo rm $TEMP_CUSTOMISE
 fi
 sudo mv $TEMP_CUSTOMISE4 $TEMP_CUSTOMISE
 rm $TEMP_CUSTOMISE2 $TEMP_CUSTOMISE3
 if [ ! -f $TEMP_CUSTOMISE ]; then
-	echo $'Customised customisation script could not be created'
-	exit 735892
+    echo $'Customised customisation script could not be created'
+    exit 735892
 fi
 sudo chmod +x $TEMP_CUSTOMISE
 echo $'Customised customisation script created'
@@ -245,27 +245,27 @@ echo $"starting $VMDEBOOTSTRAP"
 
 # Run vmdebootstrap script to create image
 sudo -H \
-	 SUITE="$SUITE" \
-	 MIRROR="$MIRROR" \
-	 BUILD_MIRROR="$BUILD_MIRROR"\
-	 MACHINE="$MACHINE" \
-	 ARCHITECTURE="$ARCHITECTURE" \
-	 SOURCE="$SOURCE" \
-	 CUSTOM_SETUP="$CUSTOM_SETUP" \
-	 $VMDEBOOTSTRAP \
-	 --log $(dirname $IMAGE)/${PROJECT_NAME}.log \
-	 --log-level debug \
-	 --size $IMAGE_SIZE \
-	 --image $IMAGE.img \
-	 --hostname ${PROJECT_NAME} \
-	 --verbose \
-	 --mirror $BUILD_MIRROR \
-	 --customize "$TEMP_CUSTOMISE" \
-	 --lock-root-password \
-	 --arch $ARCHITECTURE \
-	 --distribution $SUITE \
-	 $extra_opts \
-	 $pkgopts
+     SUITE="$SUITE" \
+     MIRROR="$MIRROR" \
+     BUILD_MIRROR="$BUILD_MIRROR"\
+     MACHINE="$MACHINE" \
+     ARCHITECTURE="$ARCHITECTURE" \
+     SOURCE="$SOURCE" \
+     CUSTOM_SETUP="$CUSTOM_SETUP" \
+     $VMDEBOOTSTRAP \
+     --log $(dirname $IMAGE)/${PROJECT_NAME}.log \
+     --log-level debug \
+     --size $IMAGE_SIZE \
+     --image $IMAGE.img \
+     --hostname ${PROJECT_NAME} \
+     --verbose \
+     --mirror $BUILD_MIRROR \
+     --customize "$TEMP_CUSTOMISE" \
+     --lock-root-password \
+     --arch $ARCHITECTURE \
+     --distribution $SUITE \
+     $extra_opts \
+     $pkgopts
 
 echo $'Removing customised customisation script'
 sudo shred -zu $TEMP_CUSTOMISE
