Try adding a user

diff --git a/src/freedombone-app-matrix b/src/freedombone-app-matrix
--- a/src/freedombone-app-matrix
+++ b/src/freedombone-app-matrix
@@ -379,10 +379,10 @@ function install_matrix {
     rm -f ${MATRIX_DATA_DIR}/.procmailrc
     rm -f ${MATRIX_DATA_DIR}/.emacs-mutt
 
-    #if [[ $(add_user_matrix "${MY_USERNAME}" "${MATRIX_PASSWORD}") != "0" ]]; then
-    #    echo $'Failed to add matrix admin user';
-    #    exit 879352
-    #fi
+    if [[ $(add_user_matrix "${MY_USERNAME}" "${MATRIX_PASSWORD}") != "0" ]]; then
+        echo $'Failed to add matrix admin user';
+        exit 879352
+    fi
 
     APP_INSTALLED=1
 }
