Check that all chosen apps actually do get installed

diff --git a/src/freedombone-addremove b/src/freedombone-addremove
--- a/src/freedombone-addremove
+++ b/src/freedombone-addremove
@@ -174,6 +174,10 @@ function install_apps_selected {
     # install the apps
     read_configuration
     install_apps interactive
+    if [ ! $APP_INSTALLED_SUCCESS ]; then
+        echo $'One or more apps failed to install'
+        exit 357223
+    fi
 }
 
 if [[ $1 == "test"* ]]; then
diff --git a/src/freedombone-utils-setup b/src/freedombone-utils-setup
--- a/src/freedombone-utils-setup
+++ b/src/freedombone-utils-setup
@@ -545,11 +545,18 @@ function setup_apps {
 
     if [[ $is_interactive == "menuconfig"* ]]; then
         ${PROJECT_NAME}-addremove add-all
+        if [ ! "$?" = "0" ]; then
+            exit 72524
+        fi
     fi
 
     if [[ $is_interactive == "noninteractive" || $is_interactive == "headless" ]]; then
         function_check install_apps
         install_apps
+        if [ ! $APP_INSTALLED_SUCCESS ]; then
+            echo $'One or more apps failed to install'
+            exit 368224
+        fi
     fi
 }
 
