No return value check on gnusocial due to expected warnings

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -8811,11 +8811,12 @@ function install_gnu_social {
                             --admin-pass="$MICROBLOG_ADMIN_PASSWORD" \
                             --site-profile="community" \
                             --ssl=${gnu_social_ssl}
-    if [ ! "$?" = "0" ]; then
-        # failed to install
-        echo $'Could not install GNU Social'
-        exit 72357
-    fi
+    # There can be a lot of warnings here so the return value check is disabled
+    #if [ ! "$?" = "0" ]; then
+    #    # failed to install
+    #    echo $'Could not install GNU Social'
+    #    exit 72357
+    #fi
 
     # check microblog has a config file
     microblog_config_file=/var/www/$MICROBLOG_DOMAIN_NAME/htdocs/config.php
