Keep track of sks onion domain

diff --git a/src/freedombone-app-keyserver b/src/freedombone-app-keyserver
--- a/src/freedombone-app-keyserver
+++ b/src/freedombone-app-keyserver
@@ -149,6 +149,7 @@ function remove_keyserver {
     firewall_remove 11372 tcp
 
     sed -i '/keyserver/d' $COMPLETION_FILE
+    sed -i '/sks onion/d' $COMPLETION_FILE
     if [ -d /var/lib/sks ]; then
         rm -rf /var/lib/sks
     fi
@@ -299,10 +300,11 @@ function install_keyserver {
     onion_update
     wait_for_onion_service 'sks'
 
-    if [ ! -f /var/lib/tor/hidden_service_xmpp/hostname ]; then
-        echo $'xmpp onion site hostname not found'
-        exit 65349
+    if [ ! -f /var/lib/tor/hidden_service_sks/hostname ]; then
+        echo $'sks onion site hostname not found'
+        exit 8352982
     fi
+    SKS_ONION_HOSTNAME=$(cat /var/lib/tor/hidden_service_sks/hostname)
 
     KEYSERVER_ONION_HOSTNAME=$(add_onion_service keyserver 80 ${KEYSERVER_ONION_PORT})
 
@@ -410,6 +412,7 @@ function install_keyserver {
 
     set_completion_param "keyserver domain" "$KEYSERVER_DOMAIN_NAME"
     set_completion_param "keyserver onion domain" "$KEYSERVER_ONION_HOSTNAME"
+    set_completion_param "sks onion domain" "$SKS_ONION_HOSTNAME"
 
     APP_INSTALLED=1
 }
