Install cryptpad on mesh clients

diff --git a/src/freedombone-image-mesh b/src/freedombone-image-mesh
--- a/src/freedombone-image-mesh
+++ b/src/freedombone-image-mesh
@@ -85,6 +85,24 @@ VPN_MESH_TLS_PORT=653
 
 SCUTTLEBOT_PORT=8010
 
+CRYPTPAD_PORT=9003
+CRYPTPAD_DIR=/etc/cryptpad
+
+function enable_cryptpad {
+    if [ ! -d $CRYPTPAD_DIR ]; then
+        return
+    fi
+    if [ ! -d $CRYPTPAD_DIR/customize/api ]; then
+        mkdir -p $CRYPTPAD_DIR/customize/api
+    fi
+    wget 127.0.0.1:$CRYPTPAD_PORT/api/config -O $CRYPTPAD_DIR/customize/api/config
+    if [ ! -f $CRYPTPAD_DIR/customize/api/config ]; then
+        echo $'Unable to wget api/config'
+        exit 89252
+    fi
+    chown -R cryptpad:cryptpad $CRYPTPAD_DIR
+}
+
 # Debian stretch has a problem where the formerly predictable wlan0 and eth0
 # device names get assigned random names. This is a hacky workaround.
 # Also adding net.ifnames=0 to kernel options on bootloader may work.
@@ -873,12 +891,16 @@ if [ -f $MESH_INSTALL_SETUP ]; then
     #create_ram_disk 1
     #setup_amnesic_data
     change_avahi_name
+    if [ -d $CRYPTPAD_DIR ]; then
+        systemctl start cryptpad
+    fi
     configure_toxcore
     create_tox_user
     #setup_tahoelafs
     mesh_setup_vpn
     initialise_scuttlebot_pub
     setup_ipfs
+    enable_cryptpad
     mesh_amnesic
     make_root_read_only
 
