Prepare for the return of duplicity

diff --git a/src/freedombone-utils-backup b/src/freedombone-utils-backup
--- a/src/freedombone-utils-backup
+++ b/src/freedombone-utils-backup
@@ -247,6 +247,56 @@ function set_obnam_client_name {
     echo "client-name = ${PROJECT_NAME}" >> /etc/obnam.conf
 }
 
+function backup_directory_to_usb_duplicity {
+    echo "$BACKUP_DUMMY_PASSWORD" | duplicity full --encrypt-key $MY_BACKUP_KEY_ID --full-if-older-than 4W --exclude-other-filesystems ${1} file://$USB_MOUNT/backup/${2}
+    if [[ $ENABLE_BACKUP_VERIFICATION == "yes" ]]; then
+        echo "$BACKUP_DUMMY_PASSWORD" | duplicity verify --encrypt-key $MY_BACKUP_KEY_ID --full-if-older-than 4W --exclude-other-filesystems ${1} file://$USB_MOUNT/backup/${2}
+        if [ ! "$?" = "0" ]; then
+            umount $USB_MOUNT
+            rm -rf $USB_MOUNT
+            if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+                shred -zu ${1}/*
+                rm -rf ${1}
+            fi
+            function_check restart_site
+            restart_site
+            exit 683252
+        fi
+    fi
+}
+
+function backup_directory_to_usb_obnam {
+    set_obnam_client_name
+    echo "$BACKUP_DUMMY_PASSWORD" | obnam force-lock -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+    echo "$BACKUP_DUMMY_PASSWORD" | obnam backup -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+    if [[ $ENABLE_BACKUP_VERIFICATION == "yes" ]]; then
+        echo "$BACKUP_DUMMY_PASSWORD" | obnam verify -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+        if [ ! "$?" = "0" ]; then
+            umount $USB_MOUNT
+            rm -rf $USB_MOUNT
+            if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+                shred -zu ${1}/*
+                rm -rf ${1}
+            fi
+            function_check restart_site
+            restart_site
+            exit 683252
+        fi
+    fi
+    echo "$BACKUP_DUMMY_PASSWORD" | obnam forget --keep=30d -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID
+    if [ ! "$?" = "0" ]; then
+        umount $USB_MOUNT
+        rm -rf $USB_MOUNT
+        if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+            shred -zu ${1}/*
+            rm -rf ${1}
+        fi
+        function_check restart_site
+        restart_site
+        exit 7
+    fi
+}
+
 function backup_directory_to_usb {
     if [ ! -d ${1} ]; then
         echo $"WARNING: directory does not exist: ${1}"
@@ -263,40 +313,24 @@ function backup_directory_to_usb {
         if [ ! -d $USB_MOUNT/backup/${2} ]; then
             mkdir -p $USB_MOUNT/backup/${2}
         fi
-        set_obnam_client_name
-        echo "$BACKUP_DUMMY_PASSWORD" | obnam force-lock -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
-        echo "$BACKUP_DUMMY_PASSWORD" | obnam backup -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
-        if [[ $ENABLE_BACKUP_VERIFICATION == "yes" ]]; then
-            echo "$BACKUP_DUMMY_PASSWORD" | obnam verify -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
-            if [ ! "$?" = "0" ]; then
-                umount $USB_MOUNT
-                rm -rf $USB_MOUNT
-                if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
-                    shred -zu ${1}/*
-                    rm -rf ${1}
-                fi
-                function_check restart_site
-                restart_site
-                exit 683252
-            fi
-        fi
-        echo "$BACKUP_DUMMY_PASSWORD" | obnam forget --keep=30d -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID
-        if [ ! "$?" = "0" ]; then
-            umount $USB_MOUNT
-            rm -rf $USB_MOUNT
-            if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
-                shred -zu ${1}/*
-                rm -rf ${1}
-            fi
-            function_check restart_site
-            restart_site
-            exit 7
-        fi
+
+        #backup_directory_to_usb_duplicity ${1} ${2}
+        backup_directory_to_usb_obnam ${1} ${2}
+
         if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
             shred -zu ${1}/*
             rm -rf ${1}
         fi
     fi
+}
+
+function restore_directory_from_usb_obnam {
+    set_obnam_client_name
+    echo "$BACKUP_DUMMY_PASSWORD" | obnam restore -r $USB_MOUNT/backup/${2} --to ${1}
+}
+
+function restore_directory_from_usb_duplicity {
+    echo "$BACKUP_DUMMY_PASSWORD" | duplicity restore --force file://$USB_MOUNT/backup/${2} ${1}
 }
 
 function restore_directory_from_usb {
@@ -313,8 +347,17 @@ function restore_directory_from_usb {
     if [ ! -d ${1} ]; then
         mkdir ${1}
     fi
+    #restore_directory_from_usb_duplicity ${1} ${2}
+    restore_directory_from_usb_obnam ${1} ${2}
+}
+
+function restore_directory_from_friend_obnam {
     set_obnam_client_name
-    echo "$BACKUP_DUMMY_PASSWORD" | obnam restore -r $USB_MOUNT/backup/${2} --to ${1}
+    echo "$BACKUP_DUMMY_PASSWORD" | obnam restore -r $SERVER_DIRECTORY/backup/${2} --to ${1}
+}
+
+function restore_directory_from_friend_duplicity {
+    echo "$BACKUP_DUMMY_PASSWORD" | duplicity restore --force file://$SERVER_DIRECTORY/backup/${2} ${1}
 }
 
 function restore_directory_from_friend {
@@ -331,8 +374,8 @@ function restore_directory_from_friend {
     if [ ! -d ${1} ]; then
         mkdir ${1}
     fi
-    set_obnam_client_name
-    echo "$BACKUP_DUMMY_PASSWORD" | obnam restore -r $SERVER_DIRECTORY/backup/${2} --to ${1}
+    #restore_directory_from_friend_duplicity ${1} ${2}
+    restore_directory_from_friend_obnam ${1} ${2}
 }
 
 function backup_database_to_usb {
@@ -357,19 +400,23 @@ function set_user_permissions {
     done
 }
 
-function backup_directory_to_friend {
-    BACKUP_KEY_EXISTS=$(gpg --list-keys "$ADMIN_NAME (backup key)")
-    if [ ! "$?" = "0" ]; then
-        echo $"Backup key could not be found"
-        function_check restart_site
-        restart_site
-        exit 43382
+function backup_directory_to_friend_duplicity {
+    echo "$BACKUP_DUMMY_PASSWORD" | duplicity full --ssh-askpass --encrypt-key ${ADMIN_BACKUP_KEY_ID} --full-if-older-than 4W --exclude-other-filesystems ${1} $SERVER_DIRECTORY/backup/${2}
+    if [[ $ENABLE_BACKUP_VERIFICATION == "yes" ]]; then
+        echo "$BACKUP_DUMMY_PASSWORD" | duplicity verify --ssh-askpass --encrypt-key ${ADMIN_BACKUP_KEY_ID} --full-if-older-than 4W --exclude-other-filesystems ${1} $SERVER_DIRECTORY/backup/${2}
+        if [ ! "$?" = "0" ]; then
+            if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+                shred -zu ${1}/*
+                rm -rf ${1}
+            fi
+            function_check restart_site
+            restart_site
+            exit 683252
+        fi
     fi
+}
 
-    ADMIN_BACKUP_KEY_ID=$(gpg --list-keys "$ADMIN_NAME (backup key)" | sed -n '2p' | sed 's/^[ \t]*//')
-    if [ ! -d $SERVER_DIRECTORY/backup/${2} ]; then
-        mkdir -p $SERVER_DIRECTORY/backup/${2}
-    fi
+function backup_directory_to_friend_obnam {
     set_obnam_client_name
     echo "$BACKUP_DUMMY_PASSWORD" | obnam force-lock -r $SERVER_DIRECTORY/backup/${2} --encrypt-with ${ADMIN_BACKUP_KEY_ID} ${1}
     echo "$BACKUP_DUMMY_PASSWORD" | obnam backup -r $SERVER_DIRECTORY/backup/${2} --encrypt-with ${ADMIN_BACKUP_KEY_ID} ${1}
@@ -399,6 +446,25 @@ function backup_directory_to_friend {
         restart_site
         exit 853
     fi
+}
+
+function backup_directory_to_friend {
+    BACKUP_KEY_EXISTS=$(gpg --list-keys "$ADMIN_NAME (backup key)")
+    if [ ! "$?" = "0" ]; then
+        echo $"Backup key could not be found"
+        function_check restart_site
+        restart_site
+        exit 43382
+    fi
+
+    ADMIN_BACKUP_KEY_ID=$(gpg --list-keys "$ADMIN_NAME (backup key)" | sed -n '2p' | sed 's/^[ \t]*//')
+    if [ ! -d $SERVER_DIRECTORY/backup/${2} ]; then
+        mkdir -p $SERVER_DIRECTORY/backup/${2}
+    fi
+
+    #backup_directory_to_friend_duplicity ${1} ${2}
+    backup_directory_to_friend_obnam ${1} ${2}
+
     if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
         shred -zu /root/temp${2}/*
         rm -rf /root/temp${2}
