Temporary npm downgrade

diff --git a/src/freedombone-app-peertube b/src/freedombone-app-peertube
--- a/src/freedombone-app-peertube
+++ b/src/freedombone-app-peertube
@@ -776,26 +776,23 @@ function install_peertube {
         echo $'Failed to install yarn'
         exit 79353234
     fi
-    if ! npm install minimatch@3.0.2; then
-        echo $'Failed to install minimatch'
-        exit 3578356
-    fi
-    if ! npm install graceful-fs; then
-        echo $'Failed to install graceful-fs'
-        exit 34687246
-    fi
-    if ! npm install coffeescript; then
-        echo $'Failed to install coffeescript'
-        exit 57385757
-    fi
     yarn add -D webpack --network-concurrency 1
     if ! yarn install; then
         echo $'Failed to run yarn install'
         exit 63754235
     fi
+    if ! npm install -g npm@4; then
+        # https://github.com/KraigM/homebridge-harmonyhub/issues/119
+        echo $'Failed to downgrade npm'
+        exit 3476835
+    fi
     if ! npm install; then
         echo $'Failed to install peertube'
         exit 7835243
+    fi
+    if ! npm install -g "npm@${NPM_VERSION}"; then
+        echo $'Failed to restore npm after downgrade'
+        exit 5737583
     fi
     if ! npm run build; then
         echo $'Failed to build peertube'
