Tidying

diff --git a/src/freedombone-app-batman b/src/freedombone-app-batman
--- a/src/freedombone-app-batman
+++ b/src/freedombone-app-batman
@@ -35,10 +35,10 @@ BATMAN_CELLID='any'
 
 function configure_firewall_for_batma {
     if grep -Fxq "configure_firewall_for_batman" $COMPLETION_FILE; then
-	return
+		return
     fi
     if [[ $ENABLE_BATMAN != "yes" ]]; then
-	return
+		return
     fi
 
     function_check save_firewall_settings
@@ -72,13 +72,13 @@ function restore_remote_batman {
 
 function remove_batman {
     if ! grep -Fxq "install_batman" $COMPLETION_FILE; then
-	return
+		return
     fi
 
     ${PROJECT_NAME}-mesh-install -f batman --remove yes
     if [ ! "$?" = "0" ]; then
-	echo $'Failed to remove batman'
-	exit 79353
+		echo $'Failed to remove batman'
+		exit 79353
     fi
     sed -i '/install_batman/d' $COMPLETION_FILE
     sed -i '/configure_firewall_for_batman/d' $COMPLETION_FILE
@@ -90,15 +90,15 @@ function mesh_install_batman {
     chroot "$rootdir" apt-get -y install wireless-tools rfkill
 
     if ! grep -q "batman_adv" $rootdir/etc/modules; then
-	echo 'batman_adv' >> $rootdir/etc/modules
+		echo 'batman_adv' >> $rootdir/etc/modules
     fi
 
     BATMAN_SCRIPT=$rootdir/var/lib/batman
 
     if [ -f /usr/local/bin/${PROJECT_NAME}-mesh-batman ]; then
-	cp /usr/local/bin/${PROJECT_NAME}-mesh-batman $BATMAN_SCRIPT
+		cp /usr/local/bin/${PROJECT_NAME}-mesh-batman $BATMAN_SCRIPT
     else
-	cp /usr/bin/${PROJECT_NAME}-mesh-batman $BATMAN_SCRIPT
+		cp /usr/bin/${PROJECT_NAME}-mesh-batman $BATMAN_SCRIPT
     fi
 
     BATMAN_DAEMON=$rootdir/etc/systemd/system/batman.service
@@ -124,32 +124,32 @@ function mesh_install_batman {
 
 function install_batman {
     if [ $INSTALLING_MESH ]; then
-	mesh_install_batman
-	return
+		mesh_install_batman
+		return
     fi
     if grep -Fxq "install_batman" $COMPLETION_FILE; then
-	return
+		return
     fi
     if [[ $ENABLE_BATMAN != "yes" ]]; then
-	return
+		return
     fi
 
     ${PROJECT_NAME}-mesh-install -f batman
     if [ ! "$?" = "0" ]; then
-	echo $'Failed to install batman'
-	exit 72524
+		echo $'Failed to install batman'
+		exit 72524
     fi
 
     if ! grep -q "Mesh Networking (B.A.T.M.A.N)" /home/$MY_USERNAME/README; then
-	echo '' >> /home/$MY_USERNAME/README
-	echo '' >> /home/$MY_USERNAME/README
-	echo 'Mesh Networking (B.A.T.M.A.N)' >> /home/$MY_USERNAME/README
-	echo '=============================' >> /home/$MY_USERNAME/README
-	echo "Mesh ESSID: $WIFI_SSID" >> /home/$MY_USERNAME/README
-	echo "Mesh cell ID: $BATMAN_CELLID" >> /home/$MY_USERNAME/README
-	echo "Mesh wifi channel: $WIFI_CHANNEL" >> /home/$MY_USERNAME/README
-	chown $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/README
-	chmod 600 /home/$MY_USERNAME/README
+		echo '' >> /home/$MY_USERNAME/README
+		echo '' >> /home/$MY_USERNAME/README
+		echo 'Mesh Networking (B.A.T.M.A.N)' >> /home/$MY_USERNAME/README
+		echo '=============================' >> /home/$MY_USERNAME/README
+		echo "Mesh ESSID: $WIFI_SSID" >> /home/$MY_USERNAME/README
+		echo "Mesh cell ID: $BATMAN_CELLID" >> /home/$MY_USERNAME/README
+		echo "Mesh wifi channel: $WIFI_CHANNEL" >> /home/$MY_USERNAME/README
+		chown $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/README
+		chmod 600 /home/$MY_USERNAME/README
     fi
 
     function_check configure_firewall_for_batman
