mailpile app

diff --git a/src/freedombone-utils-dns b/src/freedombone-utils-dns
--- a/src/freedombone-utils-dns
+++ b/src/freedombone-utils-dns
@@ -160,6 +160,27 @@ function add_ddns_domain {
     systemctl daemon-reload
 }
 
+function remove_ddns_domain {
+    if [ ! $1 ]; then
+        echo $'ddns domain not specified'
+        exit 5638
+    fi
+    CURRENT_DDNS_DOMAIN="$1"
+    if [[ $ONION_ONLY != "no" ]]; then
+        return
+    fi
+    if [ ! -f /etc/inadyn.conf ]; then
+        echo $'Unable to find inadyn configuration file /etc/inadyn.conf'
+        exit 5745
+    fi
+    if grep -q "$CURRENT_DDNS_DOMAIN" /etc/inadyn.conf; then
+        systemctl stop inadyn
+        sed -i "/alias $CURRENT_DDNS_DOMAIN/d" /etc/inadyn.conf
+        systemctl start inadyn
+        systemctl daemon-reload
+    fi
+}
+
 function configure_dns {
     if [[ $(is_completed $FUNCNAME) == "1" ]]; then
         return
