Cerificate pinning

diff --git a/src/freedombone-addcert b/src/freedombone-addcert
--- a/src/freedombone-addcert
+++ b/src/freedombone-addcert
@@ -205,7 +205,14 @@ if [ $LETSENCRYPT_HOSTNAME ]; then
     ln -s /etc/letsencrypt/live/${LETSENCRYPT_HOSTNAME}/fullchain.pem /etc/ssl/certs/${LETSENCRYPT_HOSTNAME}.pem
 
     cp /etc/letsencrypt/live/${LETSENCRYPT_HOSTNAME}/fullchain.pem /etc/ssl/mycerts/${LETSENCRYPT_HOSTNAME}.pem
+
     systemctl start nginx
+
+    ${PROJECT_NAME}-pin-cert $LETSENCRYPT_HOSTNAME
+    if [ ! "$?" = "0" ]; then
+        echo $"Certificate for $LETSENCRYPT_HOSTNAME could not be pinned"
+        exit 62878
+    fi
 else
     CERTFILE=$HOSTNAME
     if [[ $ORGANISATION == "Freedombone-CA" ]]; then
@@ -219,6 +226,12 @@ else
     chmod 400 /etc/ssl/private/${CERTFILE}.key
     chmod 640 /etc/ssl/certs/${CERTFILE}.crt
     cp /etc/ssl/certs/${CERTFILE}.crt /etc/ssl/mycerts
+
+    ${PROJECT_NAME}-pin-cert $CERTFILE
+    if [ ! "$?" = "0" ]; then
+        echo $"Certificate for $CERTFILE could not be pinned"
+        exit 62879
+    fi
 fi
 
 # generate DH params
