Move back to go implementation of ipfs

diff --git a/src/freedombone-app-ipfs b/src/freedombone-app-ipfs
--- a/src/freedombone-app-ipfs
+++ b/src/freedombone-app-ipfs
@@ -227,6 +227,7 @@ npm install -g n@${IPFS_N_VERSION} --save
 n ${IPFS_NODE_VERSION}
 npm install -g ronin@${IPFS_JS_RONIN_VERSION} --save
 npm install -g ipfs@${IPFS_JS_VERSION} --save
+exit 0
 EOF
     chroot ${rootdir} chmod +x /root/install-ipfs.sh
     chroot ${rootdir} /root/install-ipfs.sh
@@ -375,8 +376,98 @@ function install_ipfs_js {
     echo 'install_ipfs_js' >> $COMPLETION_FILE
 }
 
+function mesh_install_ipfs_go {
+    chroot ${rootdir} apt-get -y install golang libpam0g-dev fuse
+
+    mesh_upgrade_golang
+
+    GOPATH=/home/git/gvm/pkgsets/go${GO_VERSION}/global
+
+    cat <<EOF > ${rootdir}/root/install_ipfs_go.sh
+#!/bin/bash
+
+if [ ! -d /home/git ]; then
+    adduser --disabled-login --gecos 'Gogs' git
+
+    # install Go
+    if ! grep -q "export GOPATH=" ~/.bashrc; then
+        echo "export GOPATH=\$GOPATH" >> ~/.bashrc
+    else
+        sed -i "s|export GOPATH=.*|export GOPATH=\$GOPATH|g" ~/.bashrc
+    fi
+    systemctl set-environment GOPATH=\$GOPATH
+    if ! grep -q "systemctl set-environment GOPATH=" ~/.bashrc; then
+        echo "systemctl set-environment GOPATH=\$GOPATH" >> ~/.bashrc
+    else
+        sed -i "s|systemctl set-environment GOPATH=.*|systemctl set-environment GOPATH=\$GOPATH|g" ~/.bashrc
+    fi
+    if [ ! -d \$GOPATH ]; then
+        mkdir -p \$GOPATH
+    fi
+fi
+
+IPFS_PATH=\$GOPATH/bin
+export PATH="\$GOPATH/bin:\$PATH:"
+if ! grep -q 'GOPATH/bin' ~/.bashrc; then
+    echo 'export PATH="\$GOPATH/bin:\$PATH:";' >> ~/.bashrc
+else
+    sed -i "s|systemctl set-environment GOPATH=.*|systemctl set-environment GOPATH=\$GOPATH|g" ~/.bashrc
+fi
+
+# set gopath for the user
+if ! grep -q "GOPATH=" /home/$MY_USERNAME/.bashrc; then
+    echo "export GOPATH=$GOPATH" >> /home/$MY_USERNAME/.bashrc
+    echo 'export PATH="\$GOPATH/bin:\$PATH:";' >> /home/$MY_USERNAME/.bashrc
+else
+    sed -i "s|export GOPATH=.*|export GOPATH=\$GOPATH|g" /home/$MY_USERNAME/.bashrc
+fi
+chown $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.bashrc
+
+IPFS_GO_REPO2=$(echo "$IPFS_GO_REPO" | sed 's|https://||g')
+go get -u ${IPFS_GO_REPO2}/cmd/ipfs
+if [ ! "$?" = "0" ]; then
+    exit 8242
+fi
+
+cd \$GOPATH/src/$IPFS_GO_REPO2
+git checkout $IPFS_COMMIT -b $IPFS_COMMIT
+exit 0
+EOF
+    chroot ${rootdir} chmod +x /root/install_ipfs_go.sh
+    chroot ${rootdir} /root/install_ipfs_go.sh
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install ipfs go'
+        cat ${rootdir}/root/install_ipfs_go.sh
+        rm -f ${rootdir}/root/install_ipfs_go.sh
+        exit 365728
+    fi
+    chroot ${rootdir} rm -f /root/install_ipfs_go.sh
+
+    echo '[Unit]' > ${rootdir}/etc/systemd/system/ipfs.service
+    echo 'Description=IPFS go daemon' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo 'After=syslog.target' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo 'After=network.target' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo '' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo '[Service]' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo 'Type=simple' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo "User=$MY_USERNAME" >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo "Group=$MY_USERNAME" >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo "WorkingDirectory=/home/$MY_USERNAME" >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo "ExecStart=$IPFS_PATH/ipfs daemon --mount" >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo 'Restart=on-failure' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo "Environment=\"USER=$MY_USERNAME\" \"HOME=/home/$MY_USERNAME\" \"GOPATH=$GOPATH\" \"GVM_ROOT=$GVM_HOME\"" >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo '' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo '[Install]' >> ${rootdir}/etc/systemd/system/ipfs.service
+    echo 'WantedBy=multi-user.target' >> ${rootdir}/etc/systemd/system/ipfs.service
+
+    chroot ${rootdir} systemctl enable ipfs
+}
 
 function install_ipfs_go {
+    if [ $INSTALLING_MESH ]; then
+        mesh_install_ipfs_go
+        return
+    fi
     if grep -Fxq "install_ipfs_go" $COMPLETION_FILE; then
         return
     fi
@@ -506,6 +597,6 @@ function install_ipfs_go {
 }
 
 function install_ipfs {
-    install_ipfs_js
-    #install_ipfs_go
+    #install_ipfs_js
+    install_ipfs_go
 }
diff --git a/src/freedombone-utils-go b/src/freedombone-utils-go
--- a/src/freedombone-utils-go
+++ b/src/freedombone-utils-go
@@ -28,7 +28,11 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-GO_VERSION=1.5
+# For reasons unknown we initially have to upgrade to an intermediate version
+# before getting to the version we want
+GO_INTERMEDIATE_VERSION=1.4.2
+
+GO_VERSION=1.6.3
 
 GO_PACKAGE_MANAGER_REPO="https://github.com/gpmgo/gopm"
 GVM_HOME=/home/git/gvm
@@ -36,113 +40,235 @@ GVM_REPO="https://github.com/moovweb/gvm"
 GVM_COMMIT='25ea8ae158e2861c92e2b22c458e60840157832f'
 
 function select_go_version {
-	if [ ! -d $GVM_HOME/bin ]; then
-		echo $'GVM was not installed'
-		exit 629532
-	fi
-	export GVM_ROOT=$GVM_HOME
-	if ! grep -q "GVM_ROOT=" ~/.bashrc; then
-		echo "export GVM_ROOT=$GVM_ROOT" >> ~/.bashrc
-	else
-		sed -i "s|export GVM_ROOT=.*|export GVM_ROOT=$GVM_ROOT|g" ~/.bashrc
-	fi
-	cd $GVM_ROOT/bin
-	[[ -s "$GVM_ROOT/scripts/gvm" ]] && source "$GVM_ROOT/scripts/gvm"
-	gvm use go${GO_VERSION} --default
-	systemctl set-environment GOPATH=$GOPATH
+    if [ ! -d $GVM_HOME/bin ]; then
+        echo $'GVM was not installed'
+        exit 629532
+    fi
+    export GVM_ROOT=$GVM_HOME
+    if ! grep -q "GVM_ROOT=" ~/.bashrc; then
+        echo "export GVM_ROOT=$GVM_ROOT" >> ~/.bashrc
+    else
+        sed -i "s|export GVM_ROOT=.*|export GVM_ROOT=$GVM_ROOT|g" ~/.bashrc
+    fi
+    cd $GVM_ROOT/bin
+    [[ -s "$GVM_ROOT/scripts/gvm" ]] && source "$GVM_ROOT/scripts/gvm"
+    gvm use go${GO_VERSION} --default
 
-	if [ ${#GOPATH} -lt 2 ]; then
-		echo $'GOPATH was not set'
-		exit 629825
-	fi
+    if [ ${#GOPATH} -lt 2 ]; then
+        echo $'GOPATH was not set'
+        exit 629825
+    fi
+
+    systemctl set-environment GOPATH=$GOPATH
+}
+
+function mesh_upgrade_golang {
+    cat <<EOF > ${rootdir}/root/upgrade_golang.sh
+#!/bin/bash
+
+export GVM_ROOT=$GVM_HOME
+
+apt-get -y install build-essential libc6-dev
+apt-get -y install gcc-multilib g++-multilib make
+apt-get -y install curl git mercurial binutils bison
+if [ ! -d $INSTALL_DIR ]; then
+    mkdir $INSTALL_DIR
+fi
+cd $INSTALL_DIR
+
+git clone $GVM_REPO gvm
+
+cd $INSTALL_DIR/gvm
+git checkout $GVM_COMMIT -b $GVM_COMMIT
+if [ ! -f binscripts/gvm-installer ]; then
+    echo $'gvm installer not found'
+fi
+chmod +x binscripts/gvm-installer
+
+if [ -d /root/.gvm ]; then
+    rm -rf /root/.gvm
+fi
+if [ -d $GVM_HOME ]; then
+    rm -rf $GVM_HOME
+fi
+if ! grep -q "export GVM_ROOT=" ~/.bashrc; then
+    echo "export GVM_ROOT=$GVM_HOME" >> ~/.bashrc
+else
+    sed -i "s|export GVM_ROOT=.*|export GVM_ROOT=$GVM_HOME|g" ~/.bashrc
+fi
+
+if [ ! -d /home/git ]; then
+    adduser --disabled-login --gecos 'Gogs' git
+fi
+if [ -d /home/git/Maildir ]; then
+    rm -rf /home/git/Maildir
+fi
+
+./binscripts/gvm-installer master /home/git
+
+if [ ! -d $GVM_HOME ]; then
+    echo $'Unable to install gvm'
+    exit 83537
+fi
+
+[[ -s "$GVM_HOME/scripts/gvm" ]] && source "$GVM_HOME/scripts/gvm"
+if [ ! -f $GVM_HOME/bin/gvm ]; then
+    echo $'gvm was not installed'
+fi
+if ! grep -q "export GVM_ROOT=" ~/.bashrc; then
+    echo "export GVM_ROOT=$GVM_HOME" >> ~/.bashrc
+fi
+
+cd $GVM_HOME/bin
+
+$GVM_HOME/bin/gvm install go${GO_INTERMEDIATE_VERSION}
+if [ ! "\$?" = "0" ]; then
+    echo $"Unable to install intermediate go version ${GO_INTERMEDIATE_VERSION}"
+    if [ -f $GVM_HOME/logs/go-go${GO_INTERMEDIATE_VERSION}-compile.log ]; then
+        cat $GVM_HOME/logs/go-go${GO_INTERMEDIATE_VERSION}-compile.log
+    fi
+    exit 352872
+fi
+
+export GOROOT_BOOTSTRAP=/home/git/gvm/gos/go${GO_INTERMEDIATE_VERSION}
+
+$GVM_HOME/bin/gvm install go${GO_VERSION}
+if [ ! "\$?" = "0" ]; then
+    echo $"Unable to install go version ${GO_VERSION}"
+    if [ -f $GVM_HOME/logs/go-go${GO_VERSION}-compile.log ]; then
+        cat $GVM_HOME/logs/go-go${GO_VERSION}-compile.log
+    fi
+    exit 529252
+fi
+
+chown -R git:git $GVM_HOME
+
+if [ ! -d $GVM_HOME/bin ]; then
+    echo $'GVM was not installed'
+    exit 629532
+fi
+
+if ! grep -q "GVM_ROOT=" ~/.bashrc; then
+    echo "export GVM_ROOT=$GVM_HOME" >> ~/.bashrc
+else
+    sed -i "s|export GVM_ROOT=.*|export GVM_ROOT=$GVM_HOME|g" ~/.bashrc
+fi
+
+cd $GVM_HOME/bin
+[[ -s "$GVM_HOME/scripts/gvm" ]] && source "$GVM_HOME/scripts/gvm"
+#$GVM_HOME/bin/gvm use go${GO_VERSION} --default
+#if [ ! "\$?" = "0" ]; then
+#    echo $"Unable to use go version ${GO_VERSION}"
+#    if [ -f $GVM_HOME/logs/go-go${GO_VERSION}-compile.log ]; then
+#        cat $GVM_HOME/logs/go-go${GO_VERSION}-compile.log
+#    fi
+#fi
+
+echo "export GOPATH=/home/git/gvm/pkgsets/go${GO_VERSION}/global" >> ~/.bashrc
+export GOPATH=/home/git/gvm/pkgsets/go${GO_VERSION}/global
+systemctl set-environment GOPATH=\$GOPATH
+
+exit 0
+EOF
+    chroot ${rootdir} chmod +x /root/upgrade_golang.sh
+    chroot ${rootdir} /root/upgrade_golang.sh
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to upgrade golang'
+        cat ${rootdir}/root/upgrade_golang.sh
+        rm -f ${rootdir}/root/upgrade_golang.sh
+        exit 836535
+    fi
+    rm -f ${rootdir}/root/upgrade_golang.sh
 }
 
 function upgrade_golang {
-	if [[ $SYSTEM_TYPE == "$VARIANT_WRITER" || $SYSTEM_TYPE == "$VARIANT_MAILBOX" || $SYSTEM_TYPE == "$VARIANT_CLOUD" || $SYSTEM_TYPE == "$VARIANT_SOCIAL" || $SYSTEM_TYPE == "$VARIANT_MEDIA" || $SYSTEM_TYPE == "$VARIANT_CHAT" || $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
-		return
-	fi
+    if [[ $SYSTEM_TYPE == "$VARIANT_WRITER" || $SYSTEM_TYPE == "$VARIANT_MAILBOX" || $SYSTEM_TYPE == "$VARIANT_CLOUD" || $SYSTEM_TYPE == "$VARIANT_SOCIAL" || $SYSTEM_TYPE == "$VARIANT_MEDIA" || $SYSTEM_TYPE == "$VARIANT_CHAT" || $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
+        return
+    fi
 
-	# NOTE: this is annoyingly hacky and going in the opposite
-	# direction of a pure blend, but it's necessary if you want
-	# to run the latest version of gogs
+    # NOTE: this is annoyingly hacky and going in the opposite
+    # direction of a pure blend, but it's necessary if you want
+    # to run the latest version of gogs
 
-	# update to the next commit
-	function_check set_repo_commit
-	set_repo_commit $INSTALL_DIR/gvm "gvm commit" "$GVM_COMMIT" $GVM_REPO
+    # update to the next commit
+    function_check set_repo_commit
+    set_repo_commit $INSTALL_DIR/gvm "gvm commit" "$GVM_COMMIT" $GVM_REPO
 
-	if grep -Fxq "upgrade_golang" $COMPLETION_FILE; then
-		return
-	fi
+    if grep -Fxq "upgrade_golang" $COMPLETION_FILE; then
+        return
+    fi
 
-	export GVM_ROOT=$GVM_HOME
+    export GVM_ROOT=$GVM_HOME
 
-	apt-get -y install curl git mercurial make binutils bison gcc build-essential
-	if [ ! -d $INSTALL_DIR ]; then
-		mkdir $INSTALL_DIR
-	fi
-	cd $INSTALL_DIR
-	function_check git_clone
-	git_clone $GVM_REPO gvm
-	cd $INSTALL_DIR/gvm
-	git checkout $GVM_COMMIT -b $GVM_COMMIT
-	if [ ! -f binscripts/gvm-installer ]; then
-		echo $'gvm installer not found'
-	fi
-	chmod +x binscripts/gvm-installer
+    apt-get -y install build-essential libc6-dev-i386 gcc-multilib g++-multilib
+    apt-get -y install gcc curl git mercurial make binutils bison
+    if [ ! -d $INSTALL_DIR ]; then
+        mkdir $INSTALL_DIR
+    fi
+    cd $INSTALL_DIR
+    function_check git_clone
+    git_clone $GVM_REPO gvm
+    cd $INSTALL_DIR/gvm
+    git checkout $GVM_COMMIT -b $GVM_COMMIT
+    if [ ! -f binscripts/gvm-installer ]; then
+        echo $'gvm installer not found'
+    fi
+    chmod +x binscripts/gvm-installer
 
-	if [ -d /root/.gvm ]; then
-		rm -rf /root/.gvm
-	fi
-	if [ -d $GVM_ROOT ]; then
-		rm -rf $GVM_ROOT
-	fi
-	sed -i "s|export GVM_ROOT=.*|export GVM_ROOT=$GVM_ROOT|g" ~/.bashrc
+    if [ -d /root/.gvm ]; then
+        rm -rf /root/.gvm
+    fi
+    if [ -d $GVM_ROOT ]; then
+        rm -rf $GVM_ROOT
+    fi
+    sed -i "s|export GVM_ROOT=.*|export GVM_ROOT=$GVM_ROOT|g" ~/.bashrc
 
-	if [ ! -d /home/git ]; then
-		# add a gogs user account within which the gvm home directory will exist
-		adduser --disabled-login --gecos 'Gogs' git
-	fi
-	if [ -d /home/git/Maildir ]; then
-		rm -rf /home/git/Maildir
-	fi
+    if [ ! -d /home/git ]; then
+        # add a gogs user account within which the gvm home directory will exist
+        adduser --disabled-login --gecos 'Gogs' git
+    fi
+    if [ -d /home/git/Maildir ]; then
+        rm -rf /home/git/Maildir
+    fi
 
-	# TODO: this script is all over the place
-	# and contains hardcoded github. See if you can do better
-	./binscripts/gvm-installer master /home/git
+    # TODO: this script is all over the place
+    # and contains hardcoded github. See if you can do better
+    ./binscripts/gvm-installer master /home/git
 
-	if [ ! -d $GVM_ROOT ]; then
-		echo $'Unable to install gvm'
-		exit 83537
-	fi
+    if [ ! -d $GVM_ROOT ]; then
+        echo $'Unable to install gvm'
+        exit 83537
+    fi
 
-	[[ -s "$GVM_ROOT/scripts/gvm" ]] && source "$GVM_ROOT/scripts/gvm"
-	if [ ! -f $GVM_ROOT/bin/gvm ]; then
-		echo $'gvm was not installed'
-	fi
-	if ! grep -q "export GVM_ROOT=" ~/.bashrc; then
-		echo "export GVM_ROOT=$GVM_ROOT" >> ~/.bashrc
-	fi
+    [[ -s "$GVM_ROOT/scripts/gvm" ]] && source "$GVM_ROOT/scripts/gvm"
+    if [ ! -f $GVM_ROOT/bin/gvm ]; then
+        echo $'gvm was not installed'
+    fi
+    if ! grep -q "export GVM_ROOT=" ~/.bashrc; then
+        echo "export GVM_ROOT=$GVM_ROOT" >> ~/.bashrc
+    fi
 
-	cd $GVM_ROOT/bin
-	gvm install go1.4
-	gvm use go1.4
-	export GOROOT_BOOTSTRAP=$GOROOT
-	gvm install go${GO_VERSION}
-	if [ ! "$?" = "0" ]; then
-		echo $'Unable to upgrade golang'
-		exit 529252
-	fi
-	gvm use go${GO_VERSION} --default
+    export GOROOT_BOOTSTRAP=$GOROOT
 
-	chown -R git:git $GVM_HOME
+    cd $GVM_ROOT/bin
+    gvm install go${GO_INTERMEDIATE_VERSION}
+    gvm use go${GO_INTERMEDIATE_VERSION}
+    gvm install go${GO_VERSION}
+    if [ ! "$?" = "0" ]; then
+        echo $'Unable to upgrade golang'
+        exit 529252
+    fi
+    gvm use go${GO_VERSION} --default
 
-	if ! grep -q "gvm commit" $COMPLETION_FILE; then
-		echo "gvm commit:$GVM_COMMIT" >> $COMPLETION_FILE
-	else
-		sed -i "s/gvm commit.*/gvm commit:$GVM_COMMIT/g" $COMPLETION_FILE
-	fi
+    chown -R git:git $GVM_HOME
 
-	echo 'upgrade_golang' >> $COMPLETION_FILE
+    if ! grep -q "gvm commit" $COMPLETION_FILE; then
+        echo "gvm commit:$GVM_COMMIT" >> $COMPLETION_FILE
+    else
+        sed -i "s/gvm commit.*/gvm commit:$GVM_COMMIT/g" $COMPLETION_FILE
+    fi
+
+    echo 'upgrade_golang' >> $COMPLETION_FILE
 }
 
 # NOTE: deliberately there is no "exit 0"
