Add mariadb socket

diff --git a/src/freedombone-utils-database b/src/freedombone-utils-database
--- a/src/freedombone-utils-database
+++ b/src/freedombone-utils-database
@@ -162,6 +162,13 @@ function install_mariadb {
         exit 34672
     fi
 
+    if [ ! -f /etc/mysql/conf.d/my.cnf ]; then
+        echo $'/etc/mysql/conf.d/my.cnf not found'
+        exit 6376245
+    fi
+    echo 'socket = /var/run/mysqld/mysqld.sock' >> /etc/mysql/conf.d/my.cnf
+    systemctl restart mysql
+
     mysqladmin -u root password "$MARIADB_PASSWORD"
     mark_completed $FUNCNAME
 }
