Try some additional peertube build dependencies

diff --git a/src/freedombone-app-peertube b/src/freedombone-app-peertube
--- a/src/freedombone-app-peertube
+++ b/src/freedombone-app-peertube
@@ -642,20 +642,30 @@ if [ ! "$?" = "0" ]; then
     echo $'PeerTube Failed to install yarn'
     exit 79353234
 fi
+npm install --arch=$NPM_ARCH bcrypt@1.0.3 --build-from-source
+if [ ! "$?" = "0" ]; then
+    echo $'PeerTube failed to build bcrypt'
+    exit 73563543
+fi
+npm install --arch=$NPM_ARCH fsevents@1.1.3 --build-from-source
+if [ ! "$?" = "0" ]; then
+    echo $'PeerTube failed to build fsevents'
+    exit 2846393
+fi
 yarn add -D webpack --network-concurrency 1
 yarn install
 if [ ! "$?" = "0" ]; then
-    echo $'PeerTube Failed to run yarn install'
+    echo $'PeerTube failed to run yarn install'
     exit 63754235
 fi
 npm install --arch=$NPM_ARCH
 if [ ! "$?" = "0" ]; then
-    echo $'PeerTube Failed to install peertube'
+    echo $'PeerTube failed to install peertube'
     exit 7835243
 fi
 npm run build --arch=$NPM_ARCH
 if [ ! "$?" = "0" ]; then
-    echo $'PeerTube Failed to build peertube'
+    echo $'PeerTube failed to build peertube'
     exit 5293593
 fi
 EOF
