Tidying

diff --git a/src/freedombone-utils-monkeysphere b/src/freedombone-utils-monkeysphere
--- a/src/freedombone-utils-monkeysphere
+++ b/src/freedombone-utils-monkeysphere
@@ -29,38 +29,38 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 function install_monkeysphere {
-	if grep -Fxq "install_monkeysphere" $COMPLETION_FILE; then
-		return
-	fi
-	apt-get -y install monkeysphere msva-perl
-	#su -c "monkeysphere gen-subkey $MY_GPG_PUBLIC_KEY_ID" - $MY_USERNAME
-	mkdir /home/$MY_USERNAME/.monkeysphere
-	chmod 755 /home/$MY_USERNAME/.monkeysphere
-	echo "$MY_NAME <${MY_EMAIL_ADDRESS}>" > /home/$MY_USERNAME/.monkeysphere/authorized_user_ids
-	chmod 644 /home/$MY_USERNAME/.monkeysphere/authorized_user_ids
-	chown -R $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.monkeysphere
-	monkeysphere-authentication update-users
+    if [[ $(is_completed $FUNCNAME) == "1" ]]; then
+        return
+    fi
+    apt-get -y install monkeysphere msva-perl
+    #su -c "monkeysphere gen-subkey $MY_GPG_PUBLIC_KEY_ID" - $MY_USERNAME
+    mkdir /home/$MY_USERNAME/.monkeysphere
+    chmod 755 /home/$MY_USERNAME/.monkeysphere
+    echo "$MY_NAME <${MY_EMAIL_ADDRESS}>" > /home/$MY_USERNAME/.monkeysphere/authorized_user_ids
+    chmod 644 /home/$MY_USERNAME/.monkeysphere/authorized_user_ids
+    chown -R $MY_USERNAME:$MY_USERNAME /home/$MY_USERNAME/.monkeysphere
+    monkeysphere-authentication update-users
 
-	if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
-		echo $'monkeysphere import: ssh host key not found'
-		exit 76295
-	fi
-	monkeysphere-host import-key /etc/ssh/ssh_host_rsa_key ssh://$DEFAULT_DOMAIN_NAME
-	SSH_ONION_HOSTNAME=$(cat ${COMPLETION_FILE} | grep 'ssh onion domain' | awk -F ':' '{print $2}')
-	monkeysphere-host import-key /etc/ssh/ssh_host_rsa_key ssh://$SSH_ONION_HOSTNAME
+    if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
+        echo $'monkeysphere import: ssh host key not found'
+        exit 76295
+    fi
+    monkeysphere-host import-key /etc/ssh/ssh_host_rsa_key ssh://$DEFAULT_DOMAIN_NAME
+    SSH_ONION_HOSTNAME=$(cat ${COMPLETION_FILE} | grep 'ssh onion domain' | awk -F ':' '{print $2}')
+    monkeysphere-host import-key /etc/ssh/ssh_host_rsa_key ssh://$SSH_ONION_HOSTNAME
 
-	if [ ! $MY_GPG_PUBLIC_KEY_ID ]; then
-		MY_GPG_PUBLIC_KEY_ID=$(gpg_pubkey_from_email "$MY_USERNAME" "$MY_USERNAME@$HOSTNAME")
-		if [ ${#MY_GPG_PUBLIC_KEY_ID} -lt 4 ]; then
-			echo $'monkeysphere unable to get GPG key ID for user $MY_USERNAME'
-			exit 52825
-		fi
-	fi
-	# The admin user is the identity certifier
-	fpr=$(gpg --with-colons --fingerprint $MY_GPG_PUBLIC_KEY_ID | grep fpr | head -n 1 | awk -F ':' '{print $10}')
-	monkeysphere-authentication add-identity-certifier $fpr
+    if [ ! $MY_GPG_PUBLIC_KEY_ID ]; then
+        MY_GPG_PUBLIC_KEY_ID=$(gpg_pubkey_from_email "$MY_USERNAME" "$MY_USERNAME@$HOSTNAME")
+        if [ ${#MY_GPG_PUBLIC_KEY_ID} -lt 4 ]; then
+            echo $'monkeysphere unable to get GPG key ID for user $MY_USERNAME'
+            exit 52825
+        fi
+    fi
+    # The admin user is the identity certifier
+    fpr=$(gpg --with-colons --fingerprint $MY_GPG_PUBLIC_KEY_ID | grep fpr | head -n 1 | awk -F ':' '{print $10}')
+    monkeysphere-authentication add-identity-certifier $fpr
 
-	echo 'install_monkeysphere' >> $COMPLETION_FILE
+    mark_completed $FUNCNAME
 }
 
 # NOTE: deliberately no exit 0
