Additional check that onion address gets created

diff --git a/src/freedombone-app-keyserver b/src/freedombone-app-keyserver
--- a/src/freedombone-app-keyserver
+++ b/src/freedombone-app-keyserver
@@ -672,7 +672,14 @@ function install_keyserver {
     fi
     SKS_ONION_HOSTNAME=$(cat /var/lib/tor/hidden_service_sks/hostname)
 
+    # wait again before creating another onion address
+    sleep 3
+
     KEYSERVER_ONION_HOSTNAME=$(add_onion_service keyserver 80 ${KEYSERVER_ONION_PORT})
+    if [ ! -f /var/lib/tor/hidden_service_keyserver/hostname ]; then
+        echo $'keyserver onion site hostname not found'
+        exit 53798573
+    fi
 
     keyserver_nginx_site=/etc/nginx/sites-available/$KEYSERVER_DOMAIN_NAME
     if [[ $ONION_ONLY == "no" ]]; then
