Check muc cert is created

diff --git a/src/freedombone-app-xmpp b/src/freedombone-app-xmpp
--- a/src/freedombone-app-xmpp
+++ b/src/freedombone-app-xmpp
@@ -1162,11 +1162,17 @@ function install_xmpp {
     # obtain a cert for the default domain
     if [[ "$(cert_exists "${DEFAULT_DOMAIN_NAME}" pem)" == "0" ]]; then
         create_site_certificate "${DEFAULT_DOMAIN_NAME}" 'yes'
-        create_site_certificate "chat.${DEFAULT_DOMAIN_NAME}" 'yes'
         if [[ "$ONION_ONLY" == 'no' ]]; then
             if [[ "$(cert_exists "${DEFAULT_DOMAIN_NAME}" pem)" == "0" ]]; then
                 echo $'LetsEncrypt cert could not be obtained for xmpp'
                 exit 72342
+            fi
+        fi
+        create_site_certificate "chat.${DEFAULT_DOMAIN_NAME}" 'yes'
+        if [[ "$ONION_ONLY" == 'no' ]]; then
+            if [[ "$(cert_exists "chat.${DEFAULT_DOMAIN_NAME}" pem)" == "0" ]]; then
+                echo $'LetsEncrypt cert could not be obtained for xmpp muc'
+                exit 56385
             fi
         fi
     fi
