Preparing for international strings

diff --git a/src/freedombone-addcert b/src/freedombone-addcert
--- a/src/freedombone-addcert
+++ b/src/freedombone-addcert
@@ -48,23 +48,23 @@ LETSENCRYPT_SERVER='https://acme-v01.api.letsencrypt.org/directory'
 
 function show_help {
     echo ''
-    echo 'freedombone-addcert -h [hostname] -c [country code] -a [area] -l [location]'
-    echo '                    -o [organisation] -u [unit] --ca "" --nodh ""'
+    echo $'freedombone-addcert -h [hostname] -c [country code] -a [area] -l [location]'
+    echo $'                    -o [organisation] -u [unit] --ca "" --nodh ""'
     echo ''
-    echo 'Creates a self-signed certificate for the given hostname'
+    echo $'Creates a self-signed certificate for the given hostname'
     echo ''
-    echo '     --help                   Show help'
-    echo '  -h --hostname [name]        Hostname'
-    echo '  -e --letsencrypt [hostname] Hostname to use with Lets Encrypt'
-    echo '  -s --server [url]           Lets Encrypt server URL'
-    echo '  -c --country [code]         Optional country code (eg. US, GB, etc)'
-    echo '  -a --area [description]     Optional area description'
-    echo '  -l --location [locn]        Optional location name'
-    echo '  -o --organisation [name]    Optional organisation name'
-    echo '  -u --unit [name]            Optional unit name'
-    echo '     --dhkey [bits]           DH key length in bits'
-    echo '     --nodh ""                Do not calculate DH params'
-    echo '     --ca ""                  Certificate authority cert'
+    echo $'     --help                   Show help'
+    echo $'  -h --hostname [name]        Hostname'
+    echo $'  -e --letsencrypt [hostname] Hostname to use with Lets Encrypt'
+    echo $'  -s --server [url]           Lets Encrypt server URL'
+    echo $'  -c --country [code]         Optional country code (eg. US, GB, etc)'
+    echo $'  -a --area [description]     Optional area description'
+    echo $'  -l --location [locn]        Optional location name'
+    echo $'  -o --organisation [name]    Optional organisation name'
+    echo $'  -u --unit [name]            Optional unit name'
+    echo $'     --dhkey [bits]           DH key length in bits'
+    echo $'     --nodh ""                Do not calculate DH params'
+    echo $'     --ca ""                  Certificate authority cert'
     echo ''
     exit 0
 }
@@ -131,13 +131,13 @@ done
 
 if [ ! $HOSTNAME ]; then
 	if [ ! $LETSENCRYPT_HOSTNAME ]; then
-        echo 'No hostname specified'
+        echo $'No hostname specified'
         exit 5748
 	fi
 fi
 
 if ! which openssl > /dev/null ;then
-    echo "$0: openssl is not installed, exiting" 1>&2
+    echo $"$0: openssl is not installed, exiting" 1>&2
     exit 5689
 fi
 
@@ -169,7 +169,7 @@ if [ $LETSENCRYPT_HOSTNAME ]; then
 	# TODO this requires user interaction - is there a non-interactive mode?
 	./letsencrypt-auto certonly --server $LETSENCRYPT_SERVER --standalone -d $LETSENCRYPT_HOSTNAME
 	if [ ! "$?" = "0" ]; then
-		echo "Failed to install letsencrypt for domain $LETSENCRYPT_HOSTNAME"
+		echo $"Failed to install letsencrypt for domain $LETSENCRYPT_HOSTNAME"
 		exit 63216
 	fi
 
diff --git a/src/freedombone-renew-cert b/src/freedombone-renew-cert
--- a/src/freedombone-renew-cert
+++ b/src/freedombone-renew-cert
@@ -40,32 +40,32 @@ LETSENCRYPT_SERVER='https://acme-v01.api.letsencrypt.org/directory'
 
 function show_help {
     echo ''
-    echo 'freedombone-renew-cert -h [hostname] -p [provider]'
+    echo $'freedombone-renew-cert -h [hostname] -p [provider]'
     echo ''
-    echo 'Makes it easier to renew a ssl/tls certificate for a website'
+    echo $'Makes it easier to renew a ssl/tls certificate for a website'
     echo ''
-    echo '     --help                  Show help'
-    echo '  -h --hostname [name]       Hostname'
-    echo '  -p --provider [name]       eg. startssl/letsencrypt'
+    echo $'     --help                  Show help'
+    echo $'  -h --hostname [name]       Hostname'
+    echo $'  -p --provider [name]       eg. startssl/letsencrypt'
     echo ''
     exit 0
 }
 
 function renew_letsencrypt {
     if [ ! -f /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem ]; then
-        echo "Adding Let's Encrypt certificate"
+        echo $"Adding Let's Encrypt certificate"
         freedombone-addcert -e $HOSTNAME -s $LETSENCRYPT_SERVER --dhkey $DH_KEYLENGTH
         if [ ! "$?" = "0" ]; then
-            echo "Unable to add Let's encrypt certificate"
+            echo $"Unable to add Let's encrypt certificate"
             exit 6328
         fi
     else
-        echo "Renewing Let's Encrypt certificate"
+        echo $"Renewing Let's Encrypt certificate"
         letsencrypt renew \
                     --cert-path /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem \
                     --key-path /etc/letsencrypt/live/${HOSTNAME}/privkey.pem
         if [ ! "$?" = "0" ]; then
-            echo "Unable to renew Let's encrypt certificate"
+            echo $"Unable to renew Let's encrypt certificate"
             exit 2624
         fi
     fi
@@ -76,10 +76,10 @@ function renew_letsencrypt {
 }
 
 function renew_startssl {
-    echo 'Renewing StartSSL certificate'
+    echo $'Renewing StartSSL certificate'
     if [ -s /etc/ssl/certs/$HOSTNAME.new.crt ]; then
         if ! grep -q "-BEGIN CERTIFICATE-" /etc/ssl/certs/$HOSTNAME.new.crt; then
-            echo '/etc/ssl/certs/$HOSTNAME.new.crt does not contain a public key'
+            echo $'/etc/ssl/certs/$HOSTNAME.new.crt does not contain a public key'
             return
         fi
 
@@ -137,18 +137,18 @@ function renew_startssl {
         # update your site to include the bundle
         sed -i "s|$HOSTNAME.crt|$HOSTNAME.bundle.crt|g" /etc/nginx/sites-available/$HOSTNAME
 
-        echo 'Certificate installed'
+        echo $'Certificate installed'
         service nginx restart
         return
     fi
 
     if [ -f /etc/ssl/requests/$HOSTNAME.csr ]; then
-        echo 'Certificate request already created:'
+        echo $'Certificate request already created:'
         echo ''
         cat /etc/ssl/requests/$HOSTNAME.csr
         echo ''
-        echo "Save the requested public key to /etc/ssl/certs/$HOSTNAME.new.crt"
-        echo 'then run this command again.'
+        echo $"Save the requested public key to /etc/ssl/certs/$HOSTNAME.new.crt"
+        echo $'then run this command again.'
         echo ''
         return
     fi
@@ -162,14 +162,14 @@ function renew_startssl {
     echo ''
     cat /etc/ssl/requests/$HOSTNAME.csr
     echo ''
-    echo 'On the StartSSL site select Certificates Wizard then'
-    echo 'Web server SSL/TLS Certificate. You can then click on "skip"'
-    echo 'and then copy and paste the above certificate request into the text'
-    echo 'entry box. You may now need to wait a few hours for a confirmation'
-    echo 'email indicating that the new certificate was created.'
+    echo $'On the StartSSL site select Certificates Wizard then'
+    echo $'Web server SSL/TLS Certificate. You can then click on "skip"'
+    echo $'and then copy and paste the above certificate request into the text'
+    echo $'entry box. You may now need to wait a few hours for a confirmation'
+    echo $'email indicating that the new certificate was created.'
     echo ''
-    echo 'Once you have retrieved the new public certificate paste it to:'
-    echo "/etc/ssl/certs/$HOSTNAME.new.crt then run this command again."
+    echo $'Once you have retrieved the new public certificate paste it to:'
+    echo $"/etc/ssl/certs/$HOSTNAME.new.crt then run this command again."
     echo ''
 }
 
@@ -197,18 +197,18 @@ shift
 done
 
 if [ ! $HOSTNAME ]; then
-    echo 'No hostname specified'
+    echo $'No hostname specified'
     exit 5748
 fi
 
 if ! which openssl > /dev/null ;then
-    echo "$0: openssl is not installed, exiting" 1>&2
+    echo $"$0: openssl is not installed, exiting" 1>&2
     exit 5689
 fi
 
 # check that the web site exists
 if [ ! -f /etc/nginx/sites-available/$HOSTNAME ]; then
-    echo "/etc/nginx/sites-available/$HOSTNAME does not exist"
+    echo $"/etc/nginx/sites-available/$HOSTNAME does not exist"
     exit 7598
 fi
 
@@ -218,7 +218,7 @@ else
     if [[ $PROVIDER == 'letsencrypt' ]]; then
         renew_letsencrypt
     else
-        echo "$PROVIDER is not currently supported"
+        echo $"$PROVIDER is not currently supported"
     fi
 fi
 
