Add web server to mesh images

diff --git a/src/freedombone-image-customise b/src/freedombone-image-customise
--- a/src/freedombone-image-customise
+++ b/src/freedombone-image-customise
@@ -477,6 +477,14 @@ TOX_NODES=
 ZERONET_REPO=
 ZERONET_COMMIT=
 ZERONET_PORT=
+ZERONET_BLOG_REPO=
+ZERONET_BLOG_COMMIT=
+ZERONET_MAIL_REPO=
+ZERONET_MAIL_COMMIT=
+ZERONET_FORUM_REPO=
+ZERONET_FORUM_COMMIT=
+ZERONET_ID_REPO=
+ZERONET_ID_COMMIT=
 
 # Directory where source code is downloaded and compiled
 INSTALL_DIR=$HOME/build
@@ -981,6 +989,96 @@ function mesh_zeronet {
 	chroot "$rootdir" systemctl enable zeronet.service
 }
 
+function mesh_zeronet_blog {
+	if [ -f /usr/local/bin/${PROJECT_NAME} ]; then
+		ZERONET_BLOG_REPO=$(cat /usr/local/bin/${PROJECT_NAME} | grep "ZERONET_BLOG_REPO=" | head -n 1 | awk -F '"' '{print $2}')
+		ZERONET_BLOG_COMMIT=$(cat /usr/local/bin/${PROJECT_NAME} | grep "ZERONET_BLOG_COMMIT=" | head -n 1 | awk -F "'" '{print $2}')
+	else
+		ZERONET_BLOG_REPO=$(cat /usr/bin/${PROJECT_NAME} | grep "ZERONET_BLOG_REPO=" | head -n 1 | awk -F '"' '{print $2}')
+		ZERONET_BLOG_COMMIT=$(cat /usr/bin/${PROJECT_NAME} | grep "ZERONET_BLOG_COMMIT=" | head -n 1 | awk -F "'" '{print $2}')
+	fi
+
+	git clone $ZERONET_BLOG_REPO $rootdir/opt/zeronet/ZeroBlog
+	if [ ! -d $rootdir/opt/zeronet/ZeroBlog ]; then
+		echo $'ZeroBlog repo could not be cloned'
+		exit 6739
+	fi
+	cd $rootdir/opt/zeronet/ZeroBlog
+	git checkout $ZERONET_BLOG_COMMIT -b $ZERONET_BLOG_COMMIT
+	chroot "$rootdir" chown -R zeronet:zeronet /opt/zeronet
+}
+
+function mesh_zeronet_mail {
+	if [ -f /usr/local/bin/${PROJECT_NAME} ]; then
+		ZERONET_MAIL_REPO=$(cat /usr/local/bin/${PROJECT_NAME} | grep "ZERONET_MAIL_REPO=" | head -n 1 | awk -F '"' '{print $2}')
+		ZERONET_MAIL_COMMIT=$(cat /usr/local/bin/${PROJECT_NAME} | grep "ZERONET_MAIL_COMMIT=" | head -n 1 | awk -F "'" '{print $2}')
+	else
+		ZERONET_MAIL_REPO=$(cat /usr/bin/${PROJECT_NAME} | grep "ZERONET_MAIL_REPO=" | head -n 1 | awk -F '"' '{print $2}')
+		ZERONET_MAIL_COMMIT=$(cat /usr/bin/${PROJECT_NAME} | grep "ZERONET_MAIL_COMMIT=" | head -n 1 | awk -F "'" '{print $2}')
+	fi
+
+	git clone $ZERONET_MAIL_REPO $rootdir/opt/zeronet/ZeroMail
+	if [ ! -d $rootdir/opt/zeronet/ZeroMail ]; then
+		echo $'ZeroMail repo could not be cloned'
+		exit 78493
+	fi
+	cd $rootdir/opt/zeronet/ZeroMail
+	git checkout $ZERONET_MAIL_COMMIT -b $ZERONET_MAIL_COMMIT
+	chroot "$rootdir" chown -R zeronet:zeronet /opt/zeronet
+}
+
+function mesh_zeronet_forum {
+	if [ -f /usr/local/bin/${PROJECT_NAME} ]; then
+		ZERONET_FORUM_REPO=$(cat /usr/local/bin/${PROJECT_NAME} | grep "ZERONET_FORUM_REPO=" | head -n 1 | awk -F '"' '{print $2}')
+		ZERONET_FORUM_COMMIT=$(cat /usr/local/bin/${PROJECT_NAME} | grep "ZERONET_FORUM_COMMIT=" | head -n 1 | awk -F "'" '{print $2}')
+	else
+		ZERONET_FORUM_REPO=$(cat /usr/bin/${PROJECT_NAME} | grep "ZERONET_FORUM_REPO=" | head -n 1 | awk -F '"' '{print $2}')
+		ZERONET_FORUM_COMMIT=$(cat /usr/bin/${PROJECT_NAME} | grep "ZERONET_FORUM_COMMIT=" | head -n 1 | awk -F "'" '{print $2}')
+	fi
+
+	git clone $ZERONET_FORUM_REPO $rootdir/opt/zeronet/ZeroTalk
+	if [ ! -d $rootdir/opt/zeronet/ZeroTalk ]; then
+		echo $'ZeroTalk repo could not be cloned'
+		exit 78252
+	fi
+	cd $rootdir/opt/zeronet/ZeroTalk
+	git checkout $ZERONET_FORUM_COMMIT -b $ZERONET_FORUM_COMMIT
+	chroot "$rootdir" chown -R zeronet:zeronet /opt/zeronet
+}
+
+function mesh_zeronet_id {
+	if [ -f /usr/local/bin/${PROJECT_NAME} ]; then
+		ZERONET_ID_REPO=$(cat /usr/local/bin/${PROJECT_NAME} | grep "ZERONET_ID_REPO=" | head -n 1 | awk -F '"' '{print $2}')
+		ZERONET_ID_COMMIT=$(cat /usr/local/bin/${PROJECT_NAME} | grep "ZERONET_ID_COMMIT=" | head -n 1 | awk -F "'" '{print $2}')
+	else
+		ZERONET_ID_REPO=$(cat /usr/bin/${PROJECT_NAME} | grep "ZERONET_ID_REPO=" | head -n 1 | awk -F '"' '{print $2}')
+		ZERONET_ID_COMMIT=$(cat /usr/bin/${PROJECT_NAME} | grep "ZERONET_ID_COMMIT=" | head -n 1 | awk -F "'" '{print $2}')
+	fi
+
+	git clone $ZERONET_ID_REPO $rootdir/opt/zeronet/ZeroID
+	if [ ! -d $rootdir/opt/zeronet/ZeroID ]; then
+		echo $'ZeroID repo could not be cloned'
+		exit 37936
+	fi
+	cd $rootdir/opt/zeronet/ZeroID
+	git checkout $ZERONET_ID_COMMIT -b $ZERONET_ID_COMMIT
+	chroot "$rootdir" chown -R zeronet:zeronet /opt/zeronet
+}
+
+function mesh_web_server {
+	if [ -d /etc/apache2 ]; then
+		chroot "$rootdir" apt-get -y remove --purge apache2
+		chroot "$rootdir" rm -rf /etc/apache2
+	fi
+
+	chroot "$rootdir" apt-get -y install nginx
+
+	if [ ! -d /etc/nginx ]; then
+		echo $'Unable to install web server'
+		exit 346825
+	fi
+}
+
 initialise_mesh() {
 	if [[ $VARIANT != "mesh" && $VARIANT != "meshclient" && $VARIANT != "meshusb" ]]; then
 		return
@@ -1012,7 +1110,11 @@ initialise_mesh() {
 	mesh_tox_node
 	mesh_tox_avahi
 	mesh_tox_client
+	mesh_web_server
 	mesh_zeronet
+	mesh_zeronet_blog
+	mesh_zeronet_mail
+	mesh_zeronet_forum
 
 	MESH_SERVICE='mesh-setup.service'
 	MESH_SETUP_DAEMON=$rootdir/etc/systemd/system/$MESH_SERVICE
