functions to remove babel

diff --git a/src/freedombone-app-babel b/src/freedombone-app-babel
--- a/src/freedombone-app-babel
+++ b/src/freedombone-app-babel
@@ -32,38 +32,57 @@
 ENABLE_BABEL="no"
 BABEL_PORT=6696
 
-function configure_firewall_for_babel {
-	if grep -Fxq "configure_firewall_for_babel" $COMPLETION_FILE; then
-		return
-	fi
-	if [[ $ENABLE_BABEL != "yes" ]]; then
-		return
-	fi
-	iptables -A INPUT -i $WIFI_INTERFACE -p udp --dport $BABEL_PORT -j ACCEPT
-	function_check save_firewall_settings
-	save_firewall_settings
+function remove_babel {
+    if ! grep -Fxq "mesh_babel" $COMPLETION_FILE; then
+        return
+    fi
 
-	OPEN_PORTS+=("Babel    $BABEL_PORT")
-	echo 'configure_firewall_for_babel' >> $COMPLETION_FILE
+    ${PROJECT_NAME}-mesh-install -f babel --remove yes
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to remove babel'
+        exit 83658
+    fi
+
+    iptables -D INPUT -i $WIFI_INTERFACE -p udp --dport $BABEL_PORT -j ACCEPT
+    function_check save_firewall_settings
+    save_firewall_settings
+
+    sed -i '/mesh_babel/d' $COMPLETION_FILE
+    sed -i '/configure_firewall_for_babel/d' $COMPLETION_FILE
+}
+
+function configure_firewall_for_babel {
+    if grep -Fxq "configure_firewall_for_babel" $COMPLETION_FILE; then
+        return
+    fi
+    if [[ $ENABLE_BABEL != "yes" ]]; then
+        return
+    fi
+    iptables -A INPUT -i $WIFI_INTERFACE -p udp --dport $BABEL_PORT -j ACCEPT
+    function_check save_firewall_settings
+    save_firewall_settings
+
+    OPEN_PORTS+=("Babel    $BABEL_PORT")
+    echo 'configure_firewall_for_babel' >> $COMPLETION_FILE
 }
 
 function mesh_babel {
-	if grep -Fxq "mesh_babel" $COMPLETION_FILE; then
-		return
-	fi
-	if [[ $ENABLE_BABEL != "yes" ]]; then
-		return
-	fi
+    if grep -Fxq "mesh_babel" $COMPLETION_FILE; then
+        return
+    fi
+    if [[ $ENABLE_BABEL != "yes" ]]; then
+        return
+    fi
 
-	${PROJECT_NAME}-mesh-install -f babel
-	if [ ! "$?" = "0" ]; then
-		echo $'Failed to install babel'
-		exit 67242
-	fi
+    ${PROJECT_NAME}-mesh-install -f babel
+    if [ ! "$?" = "0" ]; then
+        echo $'Failed to install babel'
+        exit 67242
+    fi
 
-	function_check configure_firewall_for_babel
-	configure_firewall_for_babel
-	echo 'mesh_babel' >> $COMPLETION_FILE
+    function_check configure_firewall_for_babel
+    configure_firewall_for_babel
+    echo 'mesh_babel' >> $COMPLETION_FILE
 }
 
 # NOTE: deliberately there is no "exit 0"
