Check for install success

diff --git a/src/freedombone-app-ghost b/src/freedombone-app-ghost
--- a/src/freedombone-app-ghost
+++ b/src/freedombone-app-ghost
@@ -284,9 +284,6 @@ function install_ghost {
     # for the avatar changing command
     apt-get -yq install unzip wget
 
-    function_check install_nodejs
-    install_nodejs ghost
-
     if [ ! -d /var/www/$GHOST_DOMAIN_NAME/htdocs ]; then
         mkdir -p /var/www/$GHOST_DOMAIN_NAME/htdocs
     fi
@@ -301,7 +298,18 @@ function install_ghost {
         echo $'ghost failed to unzip'
         exit 63835
     fi
+
+    function_check install_nodejs
+    install_nodejs ghost
+
+    ghost_create_config
     npm install --production
+    if [ ! "$?" = "0" ]; then
+        function_check remove_nodejs
+        remove_nodejs ghost
+        echo $'Failed to install ghost'
+        exit 7383563
+    fi
 
     function_check install_mariadb
     install_mariadb
@@ -311,10 +319,9 @@ function install_ghost {
 
     function_check ghost_create_database
     ghost_create_database
-    ghost_create_config
 
-    adduser --system --home=/var/www/$GHOST_DOMAIN_NAME/htdocs/ --group ghost
-    chown -R ghost: /var/www/$GHOST_DOMAIN_NAME/htdocs/
+    adduser --system --home=/var/www/${GHOST_DOMAIN_NAME}/htdocs/ --group ghost
+    chown -R ghost: /var/www/${GHOST_DOMAIN_NAME}/htdocs/
 
     echo '[Unit]' > /etc/systemd/system/ghost.service
     echo 'Description=Ghost Blog' >> /etc/systemd/system/ghost.service
@@ -327,7 +334,7 @@ function install_ghost {
     echo 'User=ghost' >> /etc/systemd/system/ghost.service
     echo 'Group=ghost' >> /etc/systemd/system/ghost.service
     echo "WorkingDirectory=/var/www/${GHOST_DOMAIN_NAME}/htdocs" >> /etc/systemd/system/ghost.service
-    echo "ExecStart=/usr/bin/node /var/www/${GHOST_DOMAIN_NAME}/htdocs/index.js" >> /etc/systemd/system/ghost.service
+    echo "ExecStart=/usr/local/bin/node /var/www/${GHOST_DOMAIN_NAME}/htdocs/index.js" >> /etc/systemd/system/ghost.service
     echo 'Restart=always' >> /etc/systemd/system/ghost.service
     echo 'RestartSec=60' >> /etc/systemd/system/ghost.service
     echo "Environment=NODE_ENV=production PORT=${GHOST_PORT}" >> /etc/systemd/system/ghost.service
