Exit if kernel cannot be flashed

diff --git a/src/freedombone-image-hardware-setup b/src/freedombone-image-hardware-setup
--- a/src/freedombone-image-hardware-setup
+++ b/src/freedombone-image-hardware-setup
@@ -94,7 +94,10 @@ beaglebone_flash() {
     #    that fail in an emulated environment!  We'll have to do it by
     #    hand below anyway...
     export FK_MACHINE="$1"
-    $INSTALL_PACKAGES flash-kernel
+    if ! $INSTALL_PACKAGES flash-kernel; then
+        echo "Unable to flash kernel for $FK_MACHINE"
+        exit 64823562
+    fi
 }
 
 beaglebone_repack_kernel() {
