Check for presence of golang directory

diff --git a/src/freedombone-utils-go b/src/freedombone-utils-go
--- a/src/freedombone-utils-go
+++ b/src/freedombone-utils-go
@@ -209,7 +209,12 @@ function mesh_upgrade_golang {
     echo "export PATH=\$PATH:\$GOPATH" >> "${rootdir}/home/go/.bashrc"
     $prefix chown -R "$MY_USERNAME":"$MY_USERNAME" "/home/$MY_USERNAME"
     $prefix chown -R go:go /home/go
-    cp "${rootdir}/home/go/go${GO_VERSION}/bin/*" "${rootdir}/usr/bin"
+    if [ ! -d "${rootdir}/home/go/go${GO_VERSION}/bin" ]; then
+        echo $"golang binaries directory not found ${rootdir}/home/go/go${GO_VERSION}/bin"
+        exit 356356785
+    fi
+    # shellcheck disable=SC2086
+    cp ${rootdir}/home/go/go${GO_VERSION}/bin/* "${rootdir}/usr/bin"
 }
 
 function upgrade_golang {
