Also autoremove

diff --git a/src/freedombone-utils-i2p b/src/freedombone-utils-i2p
--- a/src/freedombone-utils-i2p
+++ b/src/freedombone-utils-i2p
@@ -64,6 +64,7 @@ function install_i2p {
 
 function remove_i2p {
     apt-get -yq remove i2p i2p-keyring --purge
+    apt-get -yq autoremove
 
     # It's assumed here that ipv6 is only needed for i2p
     # This might not be true in future
@@ -83,6 +84,10 @@ function remove_i2p {
 }
 
 function i2p_enable_sam {
+    if [ ! -f /var/lib/i2p/i2p-config/clients.config ]; then
+        echo $'File not found /var/lib/i2p/i2p-config/clients.config'
+        exit 483648364834
+    fi
     sed -i 's|clientApp.1.startOnLoad=.*|clientApp.1.startOnLoad=true|g' /var/lib/i2p/i2p-config/clients.config
     systemctl restart i2p
 }
