clone failure warning

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -8131,6 +8131,10 @@ function install_gnu_social {
     fi
     if [ ! -d /var/www/$MICROBLOG_DOMAIN_NAME/htdocs ]; then
         git clone $MICROBLOG_REPO /var/www/$MICROBLOG_DOMAIN_NAME/htdocs
+        if [ ! -d /var/www/$MICROBLOG_DOMAIN_NAME/htdocs ]; then
+            echo $'Unable to clone gnusocial repo'
+            exit 87525
+        fi
     fi
 
     cd /var/www/$MICROBLOG_DOMAIN_NAME/htdocs
