Improved handling of Go version

diff --git a/src/freedombone-backup-local b/src/freedombone-backup-local
--- a/src/freedombone-backup-local
+++ b/src/freedombone-backup-local
@@ -42,9 +42,16 @@ USB_MOUNT=/mnt/usb
 # get default USB from config file
 CONFIG_FILE=$HOME/${PROJECT_NAME}.cfg
 if [ -f $CONFIG_FILE ]; then
-    if grep -q "USB_DRIVE=" $CONFIG_FILE; then
-        USB_DRIVE=$(cat $CONFIG_FILE | grep "USB_DRIVE=" | awk -F '=' '{print $2}')
-    fi
+	if grep -q "USB_DRIVE=" $CONFIG_FILE; then
+		USB_DRIVE=$(cat $CONFIG_FILE | grep "USB_DRIVE=" | awk -F '=' '{print $2}')
+	fi
+fi
+
+# get the version of Go being used
+if [ -f /usr/local/bin/${PROJECT_NAME} ]; then
+	GO_VERSION=$(cat /usr/local/bin/${PROJECT_NAME} | grep 'GO_VERSION=' | head -n 1 | awk -F '=' '{print $2}')
+else
+	GO_VERSION=$(cat /usr/bin/${PROJECT_NAME} | grep 'GO_VERSION=' | head -n 1 | awk -F '=' '{print $2}')
 fi
 
 ADMIN_USERNAME=
@@ -56,270 +63,270 @@ SUSPENDED_SITE=
 
 DATABASE_PASSWORD=''
 if [ -f /root/dbpass ]; then
-    DATABASE_PASSWORD=$(cat /root/dbpass)
+	DATABASE_PASSWORD=$(cat /root/dbpass)
 fi
 
 function suspend_site {
-    # suspends a given website
-    if [[ $ENABLE_VERIFICATION != "yes" ]]; then
-        return
-    fi
-    SUSPENDED_SITE="$1"
-    nginx_dissite $SUSPENDED_SITE
-    service nginx reload
+	# suspends a given website
+	if [[ $ENABLE_VERIFICATION != "yes" ]]; then
+		return
+	fi
+	SUSPENDED_SITE="$1"
+	nginx_dissite $SUSPENDED_SITE
+	service nginx reload
 }
 
 function restart_site {
-    # restarts a given website
-    if [ ! $SUSPENDED_SITE ]; then
-        return
-    fi
-    nginx_ensite $SUSPENDED_SITE
-    service nginx reload
-    SUSPENDED_SITE=
+	# restarts a given website
+	if [ ! $SUSPENDED_SITE ]; then
+		return
+	fi
+	nginx_ensite $SUSPENDED_SITE
+	service nginx reload
+	SUSPENDED_SITE=
 }
 
 function update_domains {
-    RSS_READER_DOMAIN_NAME='ttrss'
-    if grep -q "RSS reader domain" $COMPLETION_FILE; then
-        RSS_READER_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Gogs domain" | awk -F ':' '{print $2}')
-    fi
-    GIT_DOMAIN_NAME='gogs'
-    if grep -q "Gogs domain" $COMPLETION_FILE; then
-        GIT_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Gogs domain" | awk -F ':' '{print $2}')
-    fi
-    MICROBLOG_DOMAIN_NAME='microblog'
-    if grep -q "GNU Social domain" $COMPLETION_FILE; then
-        MICROBLOG_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "GNU Social domain" | awk -F ':' '{print $2}')
-    fi
-    HUBZILLA_DOMAIN_NAME='hubzilla'
-    if grep -q "Hubzilla domain" $COMPLETION_FILE; then
-        HUBZILLA_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Hubzilla domain" | awk -F ':' '{print $2}')
-    fi
-    FULLBLOG_DOMAIN_NAME='blog'
-    if grep -q "Blog domain" $COMPLETION_FILE; then
-        FULLBLOG_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Blog domain" | awk -F ':' '{print $2}')
-    fi
-    MEDIAGOBLIN_DOMAIN_NAME='mediagoblin'
-    if grep -q "Mediagoblin domain" $COMPLETION_FILE; then
-        MEDIAGOBLIN_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Mediagoblin domain" | awk -F ':' '{print $2}')
-    fi
+	RSS_READER_DOMAIN_NAME='ttrss'
+	if grep -q "RSS reader domain" $COMPLETION_FILE; then
+		RSS_READER_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Gogs domain" | awk -F ':' '{print $2}')
+	fi
+	GIT_DOMAIN_NAME='gogs'
+	if grep -q "Gogs domain" $COMPLETION_FILE; then
+		GIT_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Gogs domain" | awk -F ':' '{print $2}')
+	fi
+	MICROBLOG_DOMAIN_NAME='microblog'
+	if grep -q "GNU Social domain" $COMPLETION_FILE; then
+		MICROBLOG_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "GNU Social domain" | awk -F ':' '{print $2}')
+	fi
+	HUBZILLA_DOMAIN_NAME='hubzilla'
+	if grep -q "Hubzilla domain" $COMPLETION_FILE; then
+		HUBZILLA_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Hubzilla domain" | awk -F ':' '{print $2}')
+	fi
+	FULLBLOG_DOMAIN_NAME='blog'
+	if grep -q "Blog domain" $COMPLETION_FILE; then
+		FULLBLOG_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Blog domain" | awk -F ':' '{print $2}')
+	fi
+	MEDIAGOBLIN_DOMAIN_NAME='mediagoblin'
+	if grep -q "Mediagoblin domain" $COMPLETION_FILE; then
+		MEDIAGOBLIN_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Mediagoblin domain" | awk -F ':' '{print $2}')
+	fi
 }
 
 function mount_drive {
-    if [ $1 ]; then
-        USB_DRIVE=/dev/${1}1
-    fi
+	if [ $1 ]; then
+		USB_DRIVE=/dev/${1}1
+	fi
 
-    # get the admin user
-    ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
-    if [ $2 ]; then
-        ADMIN_USERNAME=$2
-    fi
-    ADMIN_NAME=$(getent passwd $ADMIN_USERNAME | cut -d: -f5 | cut -d, -f1)
+	# get the admin user
+	ADMIN_USERNAME=$(cat $COMPLETION_FILE | grep "Admin user" | awk -F ':' '{print $2}')
+	if [ $2 ]; then
+		ADMIN_USERNAME=$2
+	fi
+	ADMIN_NAME=$(getent passwd $ADMIN_USERNAME | cut -d: -f5 | cut -d, -f1)
 
-    # check that the backup destination is available
-    if [ ! -b $USB_DRIVE ]; then
-        echo $"Please attach a USB drive"
-        exit 1
-    fi
+	# check that the backup destination is available
+	if [ ! -b $USB_DRIVE ]; then
+		echo $"Please attach a USB drive"
+		exit 1
+	fi
 
-    # unmount if already mounted
-    umount -f $USB_MOUNT
-    if [ ! -d $USB_MOUNT ]; then
-        mkdir $USB_MOUNT
-    fi
-    if [ -f /dev/mapper/encrypted_usb ]; then
-        rm -rf /dev/mapper/encrypted_usb
-    fi
-    cryptsetup luksClose encrypted_usb
+	# unmount if already mounted
+	umount -f $USB_MOUNT
+	if [ ! -d $USB_MOUNT ]; then
+		mkdir $USB_MOUNT
+	fi
+	if [ -f /dev/mapper/encrypted_usb ]; then
+		rm -rf /dev/mapper/encrypted_usb
+	fi
+	cryptsetup luksClose encrypted_usb
 
-    # mount the encrypted backup drive
-    cryptsetup luksOpen $USB_DRIVE encrypted_usb
-    if [ "$?" = "0" ]; then
-        USB_DRIVE=/dev/mapper/encrypted_usb
-    fi
-    mount $USB_DRIVE $USB_MOUNT
-    if [ ! "$?" = "0" ]; then
-        echo $"There was a problem mounting the USB drive to $USB_MOUNT"
-        rm -rf $USB_MOUNT
-        exit 2
-    fi
+	# mount the encrypted backup drive
+	cryptsetup luksOpen $USB_DRIVE encrypted_usb
+	if [ "$?" = "0" ]; then
+		USB_DRIVE=/dev/mapper/encrypted_usb
+	fi
+	mount $USB_DRIVE $USB_MOUNT
+	if [ ! "$?" = "0" ]; then
+		echo $"There was a problem mounting the USB drive to $USB_MOUNT"
+		rm -rf $USB_MOUNT
+		exit 2
+	fi
 }
 
 function unmount_drive {
-    sync
-    umount $USB_MOUNT
-    if [ ! "$?" = "0" ]; then
-        echo $"Unable to unmount the drive. This means that the backup did not work"
-        rm -rf $USB_MOUNT
-        exit 9
-    fi
-    rm -rf $USB_MOUNT
-    if [[ $USB_DRIVE == /dev/mapper/encrypted_usb ]]; then
-        echo $"Unmount encrypted USB"
-        cryptsetup luksClose encrypted_usb
-    fi
-    if [ -f /dev/mapper/encrypted_usb ]; then
-        rm -rf /dev/mapper/encrypted_usb
-    fi
-    echo $"Backup to USB drive is complete. You can now unplug it."
+	sync
+	umount $USB_MOUNT
+	if [ ! "$?" = "0" ]; then
+		echo $"Unable to unmount the drive. This means that the backup did not work"
+		rm -rf $USB_MOUNT
+		exit 9
+	fi
+	rm -rf $USB_MOUNT
+	if [[ $USB_DRIVE == /dev/mapper/encrypted_usb ]]; then
+		echo $"Unmount encrypted USB"
+		cryptsetup luksClose encrypted_usb
+	fi
+	if [ -f /dev/mapper/encrypted_usb ]; then
+		rm -rf /dev/mapper/encrypted_usb
+	fi
+	echo $"Backup to USB drive is complete. You can now unplug it."
 }
 
 function backup_database {
-    if [ ${#DATABASE_PASSWORD} -lt 2 ]; then
-        echo $"No MariaDB password was given"
-        restart_site
-        exit 10
-    fi
-    if [ ! -d $USB_MOUNT/backup/${1} ]; then
-        mkdir -p $USB_MOUNT/backup/${1}
-    fi
-    if [ ! -d $USB_MOUNT/backup/${1}data ]; then
-        mkdir -p $USB_MOUNT/backup/${1}data
-    fi
-    if [ ! -d /root/temp${1}data ]; then
-        mkdir -p /root/temp${1}data
-    fi
-    echo $"Obtaining ${1} database backup"
-    mysqldump --lock-tables --password="$DATABASE_PASSWORD" ${1} > /root/temp${1}data/${1}.sql
-    if [ ! -s /root/temp${1}data/${1}.sql ]; then
-        echo $"${1} database could not be saved"
-        shred -zu /root/temp${1}data/*
-        rm -rf /root/temp${1}data
-        umount $USB_MOUNT
-        rm -rf $USB_MOUNT
-        restart_site
-        exit 5
-    fi
+	if [ ${#DATABASE_PASSWORD} -lt 2 ]; then
+		echo $"No MariaDB password was given"
+		restart_site
+		exit 10
+	fi
+	if [ ! -d $USB_MOUNT/backup/${1} ]; then
+		mkdir -p $USB_MOUNT/backup/${1}
+	fi
+	if [ ! -d $USB_MOUNT/backup/${1}data ]; then
+		mkdir -p $USB_MOUNT/backup/${1}data
+	fi
+	if [ ! -d /root/temp${1}data ]; then
+		mkdir -p /root/temp${1}data
+	fi
+	echo $"Obtaining ${1} database backup"
+	mysqldump --lock-tables --password="$DATABASE_PASSWORD" ${1} > /root/temp${1}data/${1}.sql
+	if [ ! -s /root/temp${1}data/${1}.sql ]; then
+		echo $"${1} database could not be saved"
+		shred -zu /root/temp${1}data/*
+		rm -rf /root/temp${1}data
+		umount $USB_MOUNT
+		rm -rf $USB_MOUNT
+		restart_site
+		exit 5
+	fi
 }
 
 function backup_directory_to_usb {
-    if [ ! -d ${1} ]; then
-        echo $"WARNING: directory does not exist: ${1}"
-    else
-        BACKUP_KEY_EXISTS=$(gpg --list-keys "$ADMIN_NAME (backup key)")
-        if [ ! "$?" = "0" ]; then
-            echo $"Backup key could not be found"
-            restart_site
-            exit 6
-        fi
-        MY_BACKUP_KEY_ID=$(gpg --list-keys "$ADMIN_NAME (backup key)" | grep 'pub ' | awk -F ' ' '{print $2}' | awk -F '/' '{print $2}')
-        if [ ! -d $USB_MOUNT/backup/${2} ]; then
-            mkdir -p $USB_MOUNT/backup/${2}
-        fi
-        obnam force-lock -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
-        obnam backup -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
-        if [[ $ENABLE_VERIFICATION == "yes" ]]; then
-            obnam verify -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
-            if [ ! "$?" = "0" ]; then
-                umount $USB_MOUNT
-                rm -rf $USB_MOUNT
-                if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
-                    shred -zu ${1}/*
-                    rm -rf ${1}
-                fi
-                restart_site
-                exit 71
-            fi
-        fi
-        obnam forget --keep=30d -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID
-        if [ ! "$?" = "0" ]; then
-            umount $USB_MOUNT
-            rm -rf $USB_MOUNT
-            if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
-                shred -zu ${1}/*
-                rm -rf ${1}
-            fi
-            restart_site
-            exit 7
-        fi
-        if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
-            shred -zu ${1}/*
-            rm -rf ${1}
-        fi
-    fi
+	if [ ! -d ${1} ]; then
+		echo $"WARNING: directory does not exist: ${1}"
+	else
+		BACKUP_KEY_EXISTS=$(gpg --list-keys "$ADMIN_NAME (backup key)")
+		if [ ! "$?" = "0" ]; then
+			echo $"Backup key could not be found"
+			restart_site
+			exit 6
+		fi
+		MY_BACKUP_KEY_ID=$(gpg --list-keys "$ADMIN_NAME (backup key)" | grep 'pub ' | awk -F ' ' '{print $2}' | awk -F '/' '{print $2}')
+		if [ ! -d $USB_MOUNT/backup/${2} ]; then
+			mkdir -p $USB_MOUNT/backup/${2}
+		fi
+		obnam force-lock -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+		obnam backup -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+		if [[ $ENABLE_VERIFICATION == "yes" ]]; then
+			obnam verify -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID ${1}
+			if [ ! "$?" = "0" ]; then
+				umount $USB_MOUNT
+				rm -rf $USB_MOUNT
+				if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+					shred -zu ${1}/*
+					rm -rf ${1}
+				fi
+				restart_site
+				exit 71
+			fi
+		fi
+		obnam forget --keep=30d -r $USB_MOUNT/backup/${2} --encrypt-with $MY_BACKUP_KEY_ID
+		if [ ! "$?" = "0" ]; then
+			umount $USB_MOUNT
+			rm -rf $USB_MOUNT
+			if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+				shred -zu ${1}/*
+				rm -rf ${1}
+			fi
+			restart_site
+			exit 7
+		fi
+		if [[ ${1} == "/root/temp"* || ${1} == *"tempbackup" ]]; then
+			shred -zu ${1}/*
+			rm -rf ${1}
+		fi
+	fi
 }
 
 function make_backup_directory {
-    # make a backup directory on the drive
-    if [ ! -d $USB_MOUNT/backup ]; then
-        mkdir $USB_MOUNT/backup
-    fi
-    if [ ! -d $USB_MOUNT/backup ]; then
-        echo $"There was a problem making the directory $USB_MOUNT/backup."
-        umount $USB_MOUNT
-        rm -rf $USB_MOUNT
-        exit 3
-    fi
+	# make a backup directory on the drive
+	if [ ! -d $USB_MOUNT/backup ]; then
+		mkdir $USB_MOUNT/backup
+	fi
+	if [ ! -d $USB_MOUNT/backup ]; then
+		echo $"There was a problem making the directory $USB_MOUNT/backup."
+		umount $USB_MOUNT
+		rm -rf $USB_MOUNT
+		exit 3
+	fi
 }
 
 function check_storage_space_remaining {
-    # Check space remaining on the usb drive
-    used_percent=$(df -k $USB_MOUNT | tail -n 1 | awk -F ' ' '{print $5}' | awk -F '%' '{print $1}')
-    if [ $used_percent -gt 95 ]; then
-        echo $"Less than 5% of space remaining on backup drive"
-        umount $USB_MOUNT
-        rm -rf $USB_MOUNT
-        exit 4
-    fi
+	# Check space remaining on the usb drive
+	used_percent=$(df -k $USB_MOUNT | tail -n 1 | awk -F ' ' '{print $5}' | awk -F '%' '{print $1}')
+	if [ $used_percent -gt 95 ]; then
+		echo $"Less than 5% of space remaining on backup drive"
+		umount $USB_MOUNT
+		rm -rf $USB_MOUNT
+		exit 4
+	fi
 }
 
 function backup_users {
-    # Backup user files
-    for d in /home/*/ ; do
-        USERNAME=$(echo "$d" | awk -F '/' '{print $3}')
-        if [[ $USERNAME != "git" && $USERNAME != "mirrors" && $USERNAME != "sync" ]]; then
+	# Backup user files
+	for d in /home/*/ ; do
+		USERNAME=$(echo "$d" | awk -F '/' '{print $3}')
+		if [[ $USERNAME != "git" && $USERNAME != "mirrors" && $USERNAME != "sync" ]]; then
 
-            # Backup any gpg keys
-            if [ -d /home/$USERNAME/.gnupg ]; then
-                echo $"Backing up gpg keys for $USERNAME"
-                backup_directory_to_usb /home/$USERNAME/.gnupg gnupg/$USERNAME
-            fi
+			# Backup any gpg keys
+			if [ -d /home/$USERNAME/.gnupg ]; then
+				echo $"Backing up gpg keys for $USERNAME"
+				backup_directory_to_usb /home/$USERNAME/.gnupg gnupg/$USERNAME
+			fi
 
-            # Backup any personal settings
-            if [ -d /home/$USERNAME/personal ]; then
-                echo $"Backing up personal settings for $USERNAME"
-                backup_directory_to_usb /home/$USERNAME/personal personal/$USERNAME
-            fi
+			# Backup any personal settings
+			if [ -d /home/$USERNAME/personal ]; then
+				echo $"Backing up personal settings for $USERNAME"
+				backup_directory_to_usb /home/$USERNAME/personal personal/$USERNAME
+			fi
 
-            # Backup ssh keys
-            if [ -d /home/$USERNAME/.ssh ]; then
-                echo $"Backing up ssh keys for $USERNAME"
-                backup_directory_to_usb /home/$USERNAME/.ssh ssh/$USERNAME
-            fi
+			# Backup ssh keys
+			if [ -d /home/$USERNAME/.ssh ]; then
+				echo $"Backing up ssh keys for $USERNAME"
+				backup_directory_to_usb /home/$USERNAME/.ssh ssh/$USERNAME
+			fi
 
-            # Backup fin database if it exists
-            if [ -d /home/$USERNAME/.fin ]; then
-                echo $"Backing up fin files for $USERNAME"
-                backup_directory_to_usb /home/$USERNAME/.fin fin/$USERNAME
-            fi
+			# Backup fin database if it exists
+			if [ -d /home/$USERNAME/.fin ]; then
+				echo $"Backing up fin files for $USERNAME"
+				backup_directory_to_usb /home/$USERNAME/.fin fin/$USERNAME
+			fi
 
-            # Backup syncthing
-            if [ -d /home/$USERNAME/Sync ]; then
-                echo $"Backing up syncthing files for $USERNAME"
-                backup_directory_to_usb /home/$USERNAME/Sync syncthing/$USERNAME
+			# Backup syncthing
+			if [ -d /home/$USERNAME/Sync ]; then
+				echo $"Backing up syncthing files for $USERNAME"
+				backup_directory_to_usb /home/$USERNAME/Sync syncthing/$USERNAME
 				# ensure that device IDs will be backed up as part of user config settings
 				if [ ! -d /home/$USERNAME/.config/syncthing ]; then
 					mkdir -p /home/$USERNAME/.config/syncthing
 					chown -R $USERNAME:$USERNAME /home/$USERNAME/.config
-				fi					
+				fi
 				if [ -f /home/$USERNAME/.syncthing-server-id ]; then
 					cp /home/$USERNAME/.syncthing-server-id /home/$USERNAME/.config/syncthing
 					chown -R $USERNAME:$USERNAME /home/$USERNAME/.config
-				fi				
+				fi
 				if [ -f /home/$USERNAME/.syncthingids ]; then
 					cp /home/$USERNAME/.syncthingids /home/$USERNAME/.config/syncthing
 					chown -R $USERNAME:$USERNAME /home/$USERNAME/.config
-				fi				
+				fi
 			fi
-			
+
 			# Backup user configs
 			if [ -d /home/$USERNAME/.config ]; then
 				echo $"Backing up config files for $USERNAME"
 				backup_directory_to_usb /home/$USERNAME/.config config/$USERNAME
 			fi
-			
+
 			# Backup user local
 			if [ -d /home/$USERNAME/.local ]; then
 				echo $"Backing up local files for $USERNAME"
@@ -370,6 +377,12 @@ function backup_users {
 }
 
 function backup_directories {
+	if [ -d $HOME/.gvm/scripts ]; then
+		cd $HOME/.gvm/scripts
+		gvm use go${GO_VERSION} --default
+		systemctl set-environment GOPATH=$GOPATH
+	fi
+
 	# directories to be backed up (source,dest)
 	backup_dirs=(
 		"none,                               none,       /etc/letsencrypt,                                letsencrypt"
@@ -382,8 +395,8 @@ function backup_directories {
 		"none,                               none,       /etc/nginx/sites-available,                      web"
 		"none,                               none,       /home/$ADMIN_USERNAME/.ipfs,                     ipfs"
 		"none,                               none,       /var/cache/minidlna,                             dlna"
-		"/home/git/go/src/github.com/gogits, gogs,       /root/tempgogsdata,                              gogsdata"
-		"none,                               none,       /home/git/go/src/github.com/gogits/gogs/custom,  gogs"
+		"$GOPATH/src/github.com/gogits, gogs,       /root/tempgogsdata,                              gogsdata"
+		"none,                               none,       $GOPATH/src/github.com/gogits/gogs/custom,  gogs"
 		"none,                               none,       /home/git/gogs-repositories,                     gogsrepos"
 		"none,                               none,       /home/git/.ssh,                                  gogsssh"
 		"none,                               none,       /var/lib/tox-bootstrapd,                         tox"
@@ -451,8 +464,14 @@ function remove_backup_directory {
 }
 
 function prepare_directories {
+	if [ -d $HOME/.gvm/scripts ]; then
+		cd $HOME/.gvm/scripts
+		gvm use go${GO_VERSION} --default
+		systemctl set-environment GOPATH=$GOPATH
+	fi
+
 	# Some miscellaneous preparation for backing up directories
-	if [ -d /home/git/go/src/github.com/gogits ]; then
+	if [ -d $GOPATH/src/github.com/gogits ]; then
 		mv /home/git/gogs-repositories/*.git /home/git/gogs-repositories/$ADMIN_USERNAME
 	fi
 	if [ -d /var/lib/tox-bootstrapd ]; then
