Ensure that clone happens

diff --git a/src/freedombone-app-edith b/src/freedombone-app-edith
--- a/src/freedombone-app-edith
+++ b/src/freedombone-app-edith
@@ -262,25 +262,19 @@ function install_edith {
 
     EDITH_ONION_HOSTNAME=$(add_onion_service edith 80 ${EDITH_ONION_PORT})
 
-    if [ ! -d /var/www/$EDITH_DOMAIN_NAME/htdocs ]; then
-        mkdir -p /var/www/$EDITH_DOMAIN_NAME/htdocs
+    if [ -d /repos/edith ]; then
+        mkdir /var/www/$EDITH_DOMAIN_NAME/htdocs
+        cp -r -p /repos/edith/. /var/www/$EDITH_DOMAIN_NAME/htdocs
+        cd /var/www/$EDITH_DOMAIN_NAME/htdocs
+        git pull
+    else
+        function_check git_clone
+        git_clone $EDITH_REPO /var/www/$EDITH_DOMAIN_NAME/htdocs
     fi
+
     if [ ! -d /var/www/$EDITH_DOMAIN_NAME/htdocs ]; then
-
-        if [ -d /repos/edith ]; then
-            mkdir /var/www/$EDITH_DOMAIN_NAME/htdocs
-            cp -r -p /repos/edith/. /var/www/$EDITH_DOMAIN_NAME/htdocs
-            cd /var/www/$EDITH_DOMAIN_NAME/htdocs
-            git pull
-        else
-            function_check git_clone
-            git_clone $EDITH_REPO /var/www/$EDITH_DOMAIN_NAME/htdocs
-        fi
-
-        if [ ! -d /var/www/$EDITH_DOMAIN_NAME/htdocs ]; then
-            echo $'Unable to clone edith repo'
-            exit 537593569
-        fi
+        echo $'Unable to clone edith repo'
+        exit 537593569
     fi
 
     cd /var/www/$EDITH_DOMAIN_NAME/htdocs
