Try installing webpack without yarn

diff --git a/src/freedombone-app-peertube b/src/freedombone-app-peertube
--- a/src/freedombone-app-peertube
+++ b/src/freedombone-app-peertube
@@ -645,16 +645,21 @@ if [ ! "\$?" = "0" ]; then
     echo $'PeerTube Failed to install yarn'
     exit 79353234
 fi
-yarn add -D webpack
+npm install --arch=$NPM_ARCH webpack --no-optional
 if [ ! "\$?" = "0" ]; then
-    echo $'PeerTube failed to add webpack'
-    exit 67342823
+    echo $'PeerTube failed to install webpack'
+    exit 68386353
 fi
-yarn install --ignore-optional
-if [ ! "\$?" = "0" ]; then
-    echo $'PeerTube failed to run yarn install'
-    exit 63754235
-fi
+#yarn add -D webpack
+#if [ ! "\$?" = "0" ]; then
+#    echo $'PeerTube failed to add webpack'
+#    exit 67342823
+#fi
+#yarn install --ignore-optional
+#if [ ! "\$?" = "0" ]; then
+#    echo $'PeerTube failed to run yarn install'
+#    exit 63754235
+#fi
 npm install --arch=$NPM_ARCH --no-optional
 if [ ! "\$?" = "0" ]; then
     echo $'PeerTube failed to install peertube'
