Move remote blog backup to app script

diff --git a/src/freedombone-app-blog b/src/freedombone-app-blog
--- a/src/freedombone-app-blog
+++ b/src/freedombone-app-blog
@@ -39,7 +39,7 @@ MY_BLOG_TITLE="My Blog"
 MY_BLOG_SUBTITLE="Another ${PROJECT_NAME} Blog"
 
 function reconfigure_blog {
-    echo -n ''
+	echo -n ''
 }
 
 function upgrade_blog {
@@ -121,7 +121,18 @@ function restore_local_blog {
 }
 
 function backup_remote_blog {
-	echo -n ''
+	if grep -q "Blog domain" $COMPLETION_FILE; then
+		FULLBLOG_DOMAIN_NAME=$(cat $COMPLETION_FILE | grep "Blog domain" | awk -F ':' '{print $2}')
+		temp_backup_dir=/var/www/${FULLBLOG_DOMAIN_NAME}/htdocs
+		if [ -d $temp_backup_dir ]; then
+			echo $"Backing up blog"
+			backup_directory_to_friend $temp_backup_dir blog
+			echo $"Backup of blog complete"
+		else
+			echo $"Blog domain specified but not found in $temp_backup_dir"
+			exit 2578
+		fi
+	fi
 }
 
 function restore_remote_blog {
