Include key

diff --git a/src/freedombone-renew-cert b/src/freedombone-renew-cert
--- a/src/freedombone-renew-cert
+++ b/src/freedombone-renew-cert
@@ -46,10 +46,12 @@ function show_help {
 
 function renew_startssl {
     echo "Renewing Let's Encrypt certificate"
-	letsencrypt renew --cert-path /etc/ssl/certs/$HOSTNAME.pem
-	if [ ! "$?" = "0" ]; then
-		echo "Unable to renew Let's encrypt certificate"
-	fi
+    letsencrypt renew \
+                --cert-path /etc/ssl/certs/$HOSTNAME.crt \
+                --key-path /etc/ssl/private/$HOSTNAME.key
+    if [ ! "$?" = "0" ]; then
+        echo "Unable to renew Let's encrypt certificate"
+    fi
 }
 
 function renew_startssl {
@@ -192,11 +194,11 @@ fi
 if [[ $PROVIDER == 'startssl' || $PROVIDER == 'StartSSL' ]]; then
     renew_startssl
 else
-	if [[ $PROVIDER == 'letsencrypt' ]]; then
-		renew_letsencrypt
-	else
-		echo "$PROVIDER is not currently supported"
-	fi
+    if [[ $PROVIDER == 'letsencrypt' ]]; then
+        renew_letsencrypt
+    else
+        echo "$PROVIDER is not currently supported"
+    fi
 fi
 
 exit 0
