Specify npm version

diff --git a/src/freedombone-image-customise b/src/freedombone-image-customise
--- a/src/freedombone-image-customise
+++ b/src/freedombone-image-customise
@@ -572,13 +572,17 @@ install_patchwork() {
         echo $'/usr/bin/node not found'
         exit 7235728
     fi
-    wget https://www.npmjs.com/install.sh -O $rootdir/root/npm_install.sh
-    if [ ! -f $rootdir/root/npm_install.sh ]; then
-        echo $'Unable to download npm installer'
-        exit 8793636
+    if [ -f /usr/share/npm/bin/npm-cli.js ]; then
+        ln -s /usr/share/npm/bin/npm-cli.js /usr/bin/npm
+    else
+        wget https://www.npmjs.com/install.sh -O $rootdir/root/npm_install.sh
+        if [ ! -f $rootdir/root/npm_install.sh ]; then
+            echo $'Unable to download npm installer'
+            exit 8793636
+        fi
     fi
     chroot "$rootdir" chmod +x /root/npm_install.sh
-    chroot "$rootdir" /root/npm_install.sh
+    chroot "$rootdir" /root/npm_install.sh $NPM_VERSION
 
     git clone https://github.com/ssbc/patchwork $rootdir/etc/patchwork
 
