Check that data directory gets created

diff --git a/src/freedombone-app-nextcloud b/src/freedombone-app-nextcloud
--- a/src/freedombone-app-nextcloud
+++ b/src/freedombone-app-nextcloud
@@ -610,6 +610,13 @@ function install_nextcloud_main {
 
     chmod +x occ
     ./occ maintenance:install --database-name nextcloud --admin-user ${MY_USERNAME} --admin-pass "${NEXTCLOUD_ADMIN_PASSWORD}" --database mysql --database-user root --database-pass "${MARIADB_PASSWORD}"
+    if [ ! -d data ]; then
+        echo $'Nextcloud data directory was not found. This probably means that the installation failed.'
+        echo ''
+        echo $'Install command was:'
+        echo "./occ maintenance:install --database-name nextcloud --admin-user ${MY_USERNAME} --admin-pass \"${NEXTCLOUD_ADMIN_PASSWORD}\" --database mysql --database-user root --database-pass \"${MARIADB_PASSWORD}\""
+        exit 83522
+    fi
     chown -R www-data:www-data config
     chown -R www-data:www-data data
     ./occ check
