Sanity check for Owncloud music app

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -6167,6 +6167,10 @@ function install_owncloud_music_app {
   if grep -Fxq "install_owncloud_music_app" $COMPLETION_FILE; then
       return
   fi
+  if ! grep -Fxq "install_owncloud" $COMPLETION_FILE; then
+	  echo 'Tried to install the Owncloud music app, but Owncloud installation was not found'
+      exit 9823
+  fi
 
   cd /usr/share/owncloud/apps
   git clone https://github.com/owncloud/music music
