Mesh install

diff --git a/src/freedombone-image-mesh b/src/freedombone-image-mesh
--- a/src/freedombone-image-mesh
+++ b/src/freedombone-image-mesh
@@ -32,6 +32,7 @@ export TEXTDOMAIN=${PROJECT_NAME}-image-mesh
 export TEXTDOMAINDIR="/usr/share/locale"
 
 MY_USERNAME='fbone'
+PEER_ID=
 
 function change_avahi_name {
     decarray=( 1 2 3 4 5 6 7 8 9 0 )
@@ -53,6 +54,10 @@ function regenerate_ssh_host_keys {
     echo $'ssh small moduli removed'
 }
 
+function configure_zeronet {
+    sed -i "s|replace.local|P${PEER_ID}.local|g" /etc/systemd/system/zeronet.service
+}
+
 function configure_zeronet_blog {
     echo $'Updating ZeroNet Blog'
     ZERONET_DEFAULT_BLOG_TITLE="${MY_USERNAME}'s Blog"
@@ -60,8 +65,8 @@ function configure_zeronet_blog {
     cd /opt/zeronet
     python zeronet.py --batch siteCreate 2> /opt/zeronet/blog.txt
     if [ ! -f /opt/zeronet/blog.txt ]; then
-        echo $'Unable to create blog'
-        exit 479
+        echo $'Unable to create ZeroNet blog'
+        exit 7386
     fi
     blog_address=$(cat blog.txt | grep "Site address" | awk -F ':' '{print $2}')
     blog_private_key=$(cat blog.txt | grep "Site private key" | awk -F ':' '{print $2}')
@@ -132,8 +137,8 @@ function configure_zeronet_mail {
     cd /opt/zeronet
     python zeronet.py --batch siteCreate 2> /opt/zeronet/mail.txt
     if [ ! -f /opt/zeronet/mail.txt ]; then
-        echo 'Unable to create mail'
-        exit 479
+        echo $'Unable to create ZeroNet mail'
+        exit 72574
     fi
     mail_address=$(cat mail.txt | grep "Site address" | awk -F ':' '{print $2}')
     mail_private_key=$(cat mail.txt | grep "Site private key" | awk -F ':' '{print $2}')
@@ -204,8 +209,8 @@ function configure_zeronet_forum {
     cd /opt/zeronet
     python zeronet.py --batch siteCreate 2> /opt/zeronet/forum.txt
     if [ ! -f /opt/zeronet/forum.txt ]; then
-        echo 'Unable to create forum'
-        exit 479
+        echo $'Unable to create ZeroNet forum'
+        exit 47962
     fi
     forum_address=$(cat forum.txt | grep "Site address" | awk -F ':' '{print $2}')
     forum_private_key=$(cat forum.txt | grep "Site private key" | awk -F ':' '{print $2}')
@@ -274,8 +279,8 @@ function configure_tox {
     TOX_BOOTSTRAP_ID_FILE=/var/lib/tox-bootstrapd/pubkey.txt
     TOX_PUBLIC_KEY=$(cat /var/log/syslog | grep tox | grep "Public Key" | awk -F ' ' '{print $8}' | tail -1)
     if [ ${#TOX_PUBLIC_KEY} -lt 30 ]; then
-        echo 'Could not obtain the tox node public key'
-        exit 6529
+        echo $'WARNING: Could not obtain the tox node public key'
+        exit 46362
     fi
 
     # save the public key for later reference
@@ -284,10 +289,10 @@ function configure_tox {
     echo $'Resetting toxic client'
     if [ -d /home/$MY_USERNAME/.config/tox ]; then
         rm -rf /home/$MY_USERNAME/.config/tox
-        su -c 'echo "n
-/nick $MY_USERNAME
+        su -c "echo 'n
+/nick P$PEER_ID
 /exit
-" | /usr/bin/toxic -d' - $MY_USERNAME
+' | /usr/bin/toxic -d" - $MY_USERNAME
     fi
 }
 
@@ -296,12 +301,16 @@ if [ -f /root/.initial_mesh_setup ]; then
         MY_USERNAME=$1
     fi
 
+    # sleep in order to allow other daemons to start up
+    sleep 15
+
+    change_avahi_name
     regenerate_ssh_host_keys
     configure_zeronet_blog
     configure_zeronet_mail
     configure_zeronet_forum
     configure_tox
-    change_avahi_name
+    configure_zeronet
 
     rm /root/.initial_mesh_setup
     systemctl disable mesh-setup.service
