Tidying

diff --git a/src/freedombone-utils-config b/src/freedombone-utils-config
--- a/src/freedombone-utils-config
+++ b/src/freedombone-utils-config
@@ -63,18 +63,11 @@ function write_config_param {
     fi
 }
 
-function read_configuration {
+function read_configuration_values {
     # if not installing on a Beaglebone then use sdb as the USB drive by default
     if [ ! $INSTALLING_ON_BBB ]; then
         if [[ $USB_DRIVE == /dev/sda1 ]]; then
             USB_DRIVE=/dev/sdb1
-        fi
-    fi
-
-    if [[ $INSTALLING_FROM_CONFIGURATION_FILE == "yes"  ]]; then
-        if [ ! -f $CONFIGURATION_FILE ]; then
-            echo $"The configuration file $CONFIGURATION_FILE was not found"
-            exit 8935
         fi
     fi
 
@@ -171,6 +164,17 @@ function read_configuration {
             CHECK_MESSAGE=$"Check your internet connection, /etc/network/interfaces and /etc/resolv.conf, then delete $COMPLETION_FILE, run 'rm -fR /var/lib/apt/lists/* && apt-get update --fix-missing' and run this script again. If hash sum mismatches persist then try setting $DEBIAN_REPO to a different mirror and also change /etc/apt/sources.list."
         fi
     fi
+}
+
+function read_configuration {
+    if [[ $INSTALLING_FROM_CONFIGURATION_FILE == "yes"  ]]; then
+        if [ ! -f $CONFIGURATION_FILE ]; then
+            echo $"The configuration file $CONFIGURATION_FILE was not found"
+            exit 8935
+        fi
+    fi
+
+    read_configuration_values
 }
 
 function check_system_type {
