gpg passphrase

diff --git a/src/freedombone-utils-backup b/src/freedombone-utils-backup
--- a/src/freedombone-utils-backup
+++ b/src/freedombone-utils-backup
@@ -361,7 +361,11 @@ function restore_directory_from_usb_obnam {
 
 function restore_directory_from_usb_duplicity {
     create_backups_temp_directory
-    echo "$BACKUP_DUMMY_PASSWORD" | duplicity restore --gpg-options "$BACKUP_GPG_OPTIONS" --tempdir $BACKUP_TEMP_DIRECTORY --force file://$USB_MOUNT/backup/${2} ${1}
+    PASSPHRASE="$BACKUP_DUMMY_PASSWORD" duplicity restore --gpg-options "$BACKUP_GPG_OPTIONS" --tempdir $BACKUP_TEMP_DIRECTORY --force file://$USB_MOUNT/backup/${2} ${1}
+    if [ ! "$?" = "0" ]; then
+        echo "WARNING: failed to restore $USB_MOUNT/backup/${2} to ${1}"
+    fi
+    PASSPHRASE=
     remove_backups_temp_directory
 }
 
@@ -390,7 +394,8 @@ function restore_directory_from_friend_obnam {
 
 function restore_directory_from_friend_duplicity {
     create_backups_temp_directory
-    echo "$BACKUP_DUMMY_PASSWORD" | duplicity restore --gpg-options "$BACKUP_GPG_OPTIONS" --tempdir $BACKUP_TEMP_DIRECTORY --force file://$SERVER_DIRECTORY/backup/${2} ${1}
+    PASSPHRASE="$BACKUP_DUMMY_PASSWORD" duplicity restore --gpg-options "$BACKUP_GPG_OPTIONS" --tempdir $BACKUP_TEMP_DIRECTORY --force file://$SERVER_DIRECTORY/backup/${2} ${1}
+    PASSPHRASE=
     remove_backups_temp_directory
 }
 
