Tests for failure

diff --git a/src/freedombone-app-pleroma b/src/freedombone-app-pleroma
--- a/src/freedombone-app-pleroma
+++ b/src/freedombone-app-pleroma
@@ -203,8 +203,20 @@ function pleroma_create_database {
 
     cd $PLEROMA_DIR
     mix local.rebar --force
+    if [ ! "$?" = "0" ]; then
+        echo $'mix local.rebar failed'
+        exit 73528562
+    fi
     mix ecto.create --force
+    if [ ! "$?" = "0" ]; then
+        echo $'mix ecto.create failed'
+        exit 83653582
+    fi
     mix ecto.migrate --force
+    if [ ! "$?" = "0" ]; then
+        echo $'mix ecto.migrate failed'
+        exit 73752573
+    fi
 }
 
 function reconfigure_pleroma {
@@ -638,7 +650,15 @@ function install_pleroma {
     # back end
     cd $PLEROMA_DIR
     mix local.hex --force
+    if [ ! "$?" = "0" ]; then
+        echo $'mix local.hex failed'
+        exit 1745673
+    fi
     mix deps.get --force
+    if [ ! "$?" = "0" ]; then
+        echo $'mix deps.get failed'
+        exit 7325733
+    fi
 
     function_check pleroma_create_database
     pleroma_create_database
