Check for config files

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -5641,6 +5641,10 @@ function configure_imap {
   chown root:dovecot /etc/ssl/certs/dovecot.*
   chown root:dovecot /etc/ssl/private/dovecot.*
 
+  if [ ! -f /etc/dovecot/conf.d/10-ssl.conf]; then
+      echo 'Unable to find /etc/dovecot/conf.d/10-ssl.conf'
+      exit 83629
+  fi
   sed -i 's|#ssl =.*|ssl = required|g' /etc/dovecot/conf.d/10-ssl.conf
   sed -i 's|ssl = no|ssl = required|g' /etc/dovecot/conf.d/10-ssl.conf
   sed -i 's|ssl = yes|ssl = required|g' /etc/dovecot/conf.d/10-ssl.conf
@@ -5654,15 +5658,37 @@ function configure_imap {
   sed -i "s|ssl_protocols =.*|ssl_protocols = '$SSL_PROTOCOLS'|g" /etc/dovecot/conf.d/10-ssl.conf
   echo "ssl_cipher_list = '$SSL_CIPHERS'" >> /etc/dovecot/conf.d/10-ssl.conf
 
+  if [ ! -f /etc/dovecot/conf.d/10-master.conf ]; then
+      echo 'Unable to find /etc/dovecot/conf.d/10-master.conf'
+      exit 49259
+  fi
   sed -i 's/#process_limit =.*/process_limit = 5/g' /etc/dovecot/conf.d/10-master.conf
   sed -i 's/#default_client_limit.*/default_client_limit = 5/g' /etc/dovecot/conf.d/10-master.conf
   sed -i 's|#default_process_limit =.*|default_process_limit = 100|g' /etc/dovecot/conf.d/10-master.conf
 
+  if [ ! -f /etc/dovecot/conf.d/10-logging.conf ]; then
+      echo 'Unable to find /etc/dovecot/conf.d/10-logging.conf'
+      exit 48936
+  fi
   sed -i 's/#auth_verbose.*/auth_verbose = yes/g' /etc/dovecot/conf.d/10-logging.conf
 
+  if [ ! -f /etc/dovecot/dovecot.conf ]; then
+      echo 'Unable to find /etc/dovecot/dovecot.conf'
+      exit 43890
+  fi
   sed -i 's/#listen =.*/listen = */g' /etc/dovecot/dovecot.conf
+
+  if [ ! -f /etc/dovecot/conf.d/10-auth.conf ]; then
+      echo 'Unable to find /etc/dovecot/conf.d/10-auth.conf'
+      exit 843256
+  fi
   sed -i 's/#disable_plaintext_auth =.*/disable_plaintext_auth = no/g' /etc/dovecot/conf.d/10-auth.conf
   sed -i 's/auth_mechanisms =.*/auth_mechanisms = plain login/g' /etc/dovecot/conf.d/10-auth.conf
+
+  if [ ! -f /etc/dovecot/conf.d/10-mail.conf ]; then
+      echo 'Unable to find /etc/dovecot/conf.d/10-mail.conf'
+      exit 42036
+  fi
   sed -i 's|mail_location =.*|mail_location = maildir:~/Maildir:LAYOUT=fs|g' /etc/dovecot/conf.d/10-mail.conf
 
   service dovecot restart
