gnusocial sharings plugin theme

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -211,6 +211,8 @@ MICROBLOG_MARKDOWN_COMMIT='03c53942f94b3376f0946e6e1fe566cc21ccf232'
 # Sharings plugin for the microblog
 SHARINGS_REPO="http://git.lasindias.club/bashrc/Sharings"
 SHARINGS_COMMIT='d5c6c7f855d9afff9086c09ea706f38c859bc0d4'
+SHARINGS_THEME_REPO="http://git.lasindias.club/manuel/SharingsTheme"
+SHARINGS_THEME_COMMIT='7106c7ef03'
 
 # Domain name for hubzilla installation
 HUBZILLA_DOMAIN_NAME=
@@ -8773,6 +8775,54 @@ function install_gnu_social_plugin_sharings {
 	echo 'install_gnu_social_plugin_sharings' >> $COMPLETION_FILE
 }
 
+function install_gnu_social_plugin_sharings_theme {
+x   if [[ $SYSTEM_TYPE == "$VARIANT_CLOUD" || $SYSTEM_TYPE == "$VARIANT_MAILBOX" || $SYSTEM_TYPE == "$VARIANT_CHAT" || $SYSTEM_TYPE == "$VARIANT_WRITER" || $SYSTEM_TYPE == "$VARIANT_MEDIA" || $SYSTEM_TYPE == "$VARIANT_DEVELOPER" || $SYSTEM_TYPE == "$VARIANT_MESH" ]]; then
+		return
+	fi
+
+	if [ ! -d /var/www/$MICROBLOG_DOMAIN_NAME/htdocs/local/plugins ]; then
+		echo $'No local/plugins directory found for the microblog'
+		exit 74458
+	fi
+
+	# update to the next commit
+	set_repo_commit /var/www/$MICROBLOG_DOMAIN_NAME/htdocs/local/plugins "GNU Social sharings theme plugin commit" "$SHARINGS_THEME_COMMIT" $SHARINGS_THEME_REPO
+
+	if grep -Fxq "install_gnu_social_plugin_sharings_theme" $COMPLETION_FILE; then
+		return
+	fi
+
+	cd /var/www/$MICROBLOG_DOMAIN_NAME/htdocs/local/plugins
+	git_clone $SHARINGS_THEME_REPO SharingsTheme
+	if [ ! -d /var/www/$MICROBLOG_DOMAIN_NAME/htdocs/local/plugins/SharingsTheme ]; then
+		echo $'Unable to clone microblog sharings plugin theme'
+		exit 639253
+	fi
+
+	cd /var/www/$MICROBLOG_DOMAIN_NAME/htdocs/local/plugins/SharingsTheme
+	git stash
+	git checkout master
+	git branch -D $SHARINGS_THEME_COMMIT
+	git checkout $SHARINGS_THEME_COMMIT -b $SHARINGS_THEME_COMMIT
+
+	# enable the plugin
+	if ! grep -q "addPlugin('SharingsTheme');" /var/www/$MICROBLOG_DOMAIN_NAME/htdocs/config.php; then
+		echo "addPlugin('SharingsTheme');" >> /var/www/$MICROBLOG_DOMAIN_NAME/htdocs/config.php
+	fi
+
+	cd /var/www/$MICROBLOG_DOMAIN_NAME/htdocs
+	php scripts/checkschema.php
+
+	chown -R www-data:www-data /var/www/$MICROBLOG_DOMAIN_NAME/htdocs
+
+	if ! grep -q "GNU Social sharings plugin theme commit" $COMPLETION_FILE; then
+		echo "GNU Social sharings plugin theme commit:$SHARINGS_THEME_COMMIT" >> $COMPLETION_FILE
+	else
+		sed -i "s|GNU Social sharings plugin theme commit.*|GNU Social sharings plugin theme commit:$SHARINGS_THEME_COMMIT|g" $COMPLETION_FILE
+	fi
+	echo 'install_gnu_social_plugin_theme_sharings' >> $COMPLETION_FILE
+}
+
 function expire_gnu_social_posts {
 	# To prevent the database size from growing endlessly this script expires posts
 	# after a number of months
@@ -11029,6 +11079,7 @@ expire_gnu_social_posts
 install_gnu_social_theme
 install_gnu_social_markdown
 install_gnu_social_plugin_sharings
+install_gnu_social_plugin_sharings_theme
 install_rss_reader
 install_rss_reader_gnusocial
 install_rss_mobile_reader
