wifi command

diff --git a/src/freedombone-mesh-batman b/src/freedombone-mesh-batman
--- a/src/freedombone-mesh-batman
+++ b/src/freedombone-mesh-batman
@@ -42,13 +42,13 @@ if [[ $1 == "start" ]]; then
 fi
 
 # Mesh definition
-ESSID=
-if ! grep -q "ESSID:" $COMPLETION_FILE; then
-    ESSID='mesh'
+WIFI_SSID=
+if ! grep -q "WIFI_SSID:" $COMPLETION_FILE; then
+    WIFI_SSID='mesh'
 else
-    ESSID=$(cat $COMPLETION_FILE | grep "ESSID:" | awk -F ':' '{print $2}')
+    WIFI_SSID=$(cat $COMPLETION_FILE | grep "WIFI_SSID:" | awk -F ':' '{print $2}')
 fi
-sed -i "s|ESSID:.*|ESSID:${ESSID}|g" $COMPLETION_FILE
+sed -i "s|WIFI_SSID:.*|WIFI_SSID:${WIFI_SSID}|g" $COMPLETION_FILE
 
 CELLID='any'
 
@@ -93,7 +93,7 @@ start() {
         echo 'error: unable to find wifi interface, not enabling batman-adv mesh'
         return
     fi
-    echo 'info: enabling batman-adv mesh network $ESSID on $IFACE'
+    echo 'info: enabling batman-adv mesh network $WIFI_SSID on $IFACE'
 
     systemctl stop network-manager
     sleep 5
@@ -109,7 +109,7 @@ start() {
     ifconfig $IFACE down
     ifconfig $IFACE mtu 1532
     iwconfig $IFACE enc off
-    iwconfig $IFACE mode ad-hoc essid $ESSID channel $CHANNEL
+    iwconfig $IFACE mode ad-hoc essid $WIFI_SSID channel $CHANNEL
     sleep 1
     iwconfig $IFACE ap $CELLID
 
@@ -214,9 +214,9 @@ case "$1" in
         avahi-browse -atl
         ;;
     *)
-    echo "error: invalid parameter $1"
-    echo 'usage: $0 {start|stop|restart|status|ping|ls|list}'
-    exit 2
-    ;;
+		echo "error: invalid parameter $1"
+		echo 'usage: $0 {start|stop|restart|status|ping|ls|list}'
+		exit 2
+		;;
 esac
 exit 0
