Check that repo clone happens

diff --git a/src/freedombone-app-batman b/src/freedombone-app-batman
--- a/src/freedombone-app-batman
+++ b/src/freedombone-app-batman
@@ -143,6 +143,10 @@ function install_mesh_tunnel {
     chroot "$rootdir" apt-get -yq install iproute bridge-utils libnetfilter-conntrack3 python-dev libevent-dev ebtables python-pip git
 
     git clone https://github.com/wlanslovenija/tunneldigger $rootdir/opt/tunneldigger
+    if [ ! -d $rootdir/opt/tunneldigger/client ]; then
+        echo $'Unable to clone tunneldigger repo'
+        exit 1987453
+    fi
     cd $rootdir/opt/tunneldigger/client
     chroot "$rootdir" make
     if [ ! -f $rootdir/opt/tunneldigger/client/l2tp_client ]; then
