babybuddy packages

diff --git a/src/freedombone-app-babybuddy b/src/freedombone-app-babybuddy
--- a/src/freedombone-app-babybuddy
+++ b/src/freedombone-app-babybuddy
@@ -296,7 +296,8 @@ function install_babybuddy {
     git checkout "$BABYBUDDY_COMMIT" -b "$BABYBUDDY_COMMIT"
     set_completion_param "babybuddy commit" "$BABYBUDDY_COMMIT"
 
-    pip3 install --user pipenv gunicorn
+    export PYTHONPATH=/usr/lib/python3.5/dist-packages:/usr/local/lib/python3.5/dist-packages
+    pip3 install pipenv gunicorn easy_thumbnails dotenv django
 
     if ! npm install -g gulp-cli; then
         exit 3468365
@@ -323,7 +324,9 @@ function install_babybuddy {
     sed -i "s|ALLOWED_HOSTS.*|ALLOWED_HOSTS = ['$BABYBUDDY_DOMAIN_NAME', '$BABYBUDDY_ONION_HOSTNAME']|g" babybuddy/settings/production.py
 
     export DJANGO_SETTINGS_MODULE=babybuddy.settings.production
-    gulp collectstatic
+    if ! gulp collectstatic; then
+        echo $'gulp collectstatic failed'
+    fi
     gulp migrate
 
     if [ ! -f "/var/www/$BABYBUDDY_DOMAIN_NAME/data/db.sqlite3" ]; then
