Check for server file

diff --git a/src/freedombone-app-tahoelafs b/src/freedombone-app-tahoelafs
--- a/src/freedombone-app-tahoelafs
+++ b/src/freedombone-app-tahoelafs
@@ -622,6 +622,10 @@ function install_tahoelafs {
         echo $'Unable to create tahoelafs server'
         exit 738752
     fi
+    if [ ! -f ${tahoelafs_storage_file} ]; then
+        echo $'tahoelafs server file missing'
+        exit 529362
+    fi
 
     # start the storage node
     su -c '/home/tahoelafs/tahoelafs/venv/bin/python2 /home/tahoelafs/tahoelafs/venv/bin/tahoe start /home/tahoelafs/storage' - tahoelafs
