Function to remove tox node

diff --git a/src/freedombone-app-tox b/src/freedombone-app-tox
--- a/src/freedombone-app-tox
+++ b/src/freedombone-app-tox
@@ -44,6 +44,26 @@ TOXIC_REPO="https://github.com/Tox/toxic"
 TOXIC_COMMIT='cf16849b374e484a33a4dffa3dfb937b59d537f2'
 TOXIC_FILE=/usr/local/bin/toxic
 
+function remove_tox_node {
+	if ! grep -Fxq "install_tox_node" $COMPLETION_FILE; then
+		return
+	fi
+
+	iptables -D INPUT -p tcp --dport $TOX_PORT -j ACCEPT
+	function_check save_firewall_settings
+	save_firewall_settings
+
+	function_check remove_onion_service
+	remove_onion_service tox ${TOX_PORT}
+
+	${PROJECT_NAME}-mesh-install -f tox_node --remove yes
+	if [ ! "$?" = "0" ]; then
+		echo $'Failed to remove tox node'
+		exit 763836
+	fi
+	sed -i '/install_tox_node/d' $COMPLETION_FILE
+}
+
 function configure_firewall_for_tox {
 	if grep -Fxq "configure_firewall_for_tox" $COMPLETION_FILE; then
 		return
