Make installer into a state machine

diff --git a/src/freedombone-installer b/src/freedombone-installer
--- a/src/freedombone-installer
+++ b/src/freedombone-installer
@@ -32,6 +32,15 @@ PROJECT_NAME='freedombone'
 export TEXTDOMAIN=${PROJECT_NAME}-installer
 export TEXTDOMAINDIR="/usr/share/locale"
 
+
+INSTALL_STATE_FIRST_BOOT=0
+INSTALL_STATE_WEBADMIN_PASSWORD_CTEATED=1
+INSTALL_STATE_RUNNING_COMMAND=2
+INSTALL_STATE_COMMAND_FAIL=3
+INSTALL_STATE_COMMAND_SUCCESS=4
+
+install_state=$INSTALL_STATE_FIRST_BOOT
+
 CONFIGURATION_FILE="/root/${PROJECT_NAME}.cfg"
 COMPLETION_FILE="/root/${PROJECT_NAME}-completed.txt"
 
@@ -42,6 +51,7 @@ setup_file="$webadmin_install_dir/setup.txt"
 domain_file="$webadmin_install_dir/.temp_domain.txt"
 pending_removes="$webadmin_install_dir/pending_removes.txt"
 pending_installs="$webadmin_install_dir/pending_installs.txt"
+install_state_file="/root/.install_state.txt"
 INSTALL_DIR=/root/build
 webadmin_user='admin'
 webadmin_temp_password_file=/root/.temp_webadmin_password
@@ -82,6 +92,10 @@ function web_admin_create_user {
 }
 
 function web_admin_setup_login {
+    if [ $install_state -ne $INSTALL_STATE_FIRST_BOOT ]; then
+        return
+    fi
+
     # if an nginx password file has not been created for web admin
     if [ -f /etc/nginx/.webadminpasswd ]; then
         return
@@ -131,6 +145,9 @@ function web_admin_setup_login {
     if ! grep -q 'install_final' "$COMPLETION_FILE"; then
         echo -n "$webadmin_password" > /root/login.txt
     fi
+
+    echo -n "$INSTALL_STATE_WEBADMIN_PASSWORD_CTEATED" > "$install_state_file"
+    install_state=$INSTALL_STATE_WEBADMIN_PASSWORD_CTEATED
 }
 
 function enable_webadmin_login {
@@ -182,20 +199,12 @@ function remove_temporary_setup_files {
     if [ -f "$domain_file" ]; then
         rm "$domain_file"
     fi
-
-    # if the file indicating that the freedombone command is running
-    # is still present then remove it
-    if [ -f /root/.running_install_command ]; then
-        rm /root/.running_install_command
-    fi
 }
 
 function restore_webadmin_files {
     # restore files which were removed for the initial setup
     if [ -d "$INSTALL_DIR/tempwebadmin" ]; then
-        if [ ! -f /root/.finished_install_command ]; then
-            mv "$INSTALL_DIR/tempwebadmin"/* "$webadmin_install_dir"
-        fi
+        mv "$INSTALL_DIR/tempwebadmin"/* "$webadmin_install_dir"
         rm -rf "$INSTALL_DIR/tempwebadmin"
     fi
 }
@@ -206,6 +215,10 @@ function set_webadmin_permissions {
 }
 
 function run_setup_command {
+    if [ $install_state -ne $INSTALL_STATE_WEBADMIN_PASSWORD_CTEATED ]; then
+        return
+    fi
+
     { echo '#!/bin/bash';
       echo '';
       echo '# ensure that any other running installs are killed';
@@ -219,46 +232,63 @@ function run_setup_command {
       echo '    fi';
       echo 'fi';
       echo '';
-      echo 'if [ -f /root/.finished_install_command ]; then';
-      echo '    rm /root/.finished_install_command';
-      echo 'fi';
-      echo '';
-      echo 'if [ -f /root/.running_install_command ]; then';
-      echo '    touch /root/.running_install_command';
-      echo 'fi';
-      echo '';
       echo "echo \"Beginning install $(date)\" > $webadmin_install_dir/log.txt";
       echo "chown www-data:www-data $webadmin_install_dir/log.txt";
       echo '';
       echo "/usr/local/bin/freedombone -c \"$CONFIGURATION_FILE\" > $webadmin_install_dir/log.txt;";
 
       echo "if ! grep -q 'install_final' \"$COMPLETION_FILE\"; then";
-      echo '    rm /root/.running_install_command';
       echo "    chown www-data:www-data $webadmin_install_dir/log.txt";
-      echo "    if [ -f $setup_file ]; then";
-      echo "        rm $setup_file";
-      echo '    fi';
-      echo '    if [ -f /etc/nginx/.webadminpasswd ]; then';
-      echo '        rm /etc/nginx/.webadminpasswd';
-      echo '    fi';
+      echo "    echo '$INSTALL_STATE_COMMAND_FAIL' > $install_state_file";
       echo '    exit 364873';
       echo 'fi';
       echo '';
       echo "chown www-data:www-data $webadmin_install_dir/log.txt";
       echo '';
-      echo 'if [ -f /root/.running_install_command ]; then';
-      echo '    rm /root/.running_install_command';
-      echo 'fi';
-      echo '';
-      echo 'if [ ! -f /root/.finished_install_command ]; then';
-      echo '    exit 79623';
-      echo 'fi';
-      echo '';
       echo "exit 0"; } > $installer_script
     chmod +x $installer_script
 
+    echo -n "$INSTALL_STATE_RUNNING_COMMAND" > "$install_state_file"
+    install_state=$INSTALL_STATE_RUNNING_COMMAND
+
     # run in a separate process
     ./$installer_script &
+}
+
+function check_install_command_state {
+    if [ $install_state -ne $INSTALL_STATE_RUNNING_COMMAND ]; then
+        return
+    fi
+    reset_install_state=
+    if [ ! -f "$install_state_file" ]; then
+        reset_install_state=1
+    else
+        curr_state=$(cat "$install_state_file")
+        # shellcheck disable=SC2086
+        if [ $curr_state -eq $INSTALL_STATE_COMMAND_FAIL ]; then
+            reset_install_state=1
+        fi
+        # shellcheck disable=SC2086
+        if [ $curr_state -eq $INSTALL_STATE_COMMAND_SUCCESS ]; then
+            echo -n "$INSTALL_STATE_COMMAND_SUCCESS" > "$install_state_file"
+            install_state=$INSTALL_STATE_COMMAND_SUCCESS
+            restore_webadmin_files
+        fi
+    fi
+
+    if [ $reset_install_state ]; then
+        chown www-data:www-data "$webadmin_install_dir/log.txt"
+        # remove the setup file containing login details
+        if [ -f "$setup_file" ]; then
+            rm "$setup_file"
+        fi
+        # remove the webadmin password file
+        if [ -f /etc/nginx/.webadminpasswd ]; then
+            rm /etc/nginx/.webadminpasswd
+        fi
+        echo -n "$INSTALL_STATE_FIRST_BOOT" > "$install_state_file"
+        install_state=$INSTALL_STATE_FIRST_BOOT
+    fi
 }
 
 function web_admin_get_language_subdir {
@@ -274,11 +304,11 @@ function web_admin_get_language_subdir {
 }
 
 function before_setup_runs {
-    if [ ! -f /etc/nginx/.webadminpasswd ]; then
+    if [ $install_state -ne $INSTALL_STATE_WEBADMIN_PASSWORD_CTEATED ]; then
         return
     fi
 
-    if [ -f /root/.running_install_command ]; then
+    if [ ! -f /etc/nginx/.webadminpasswd ]; then
         return
     fi
 
@@ -361,7 +391,7 @@ function before_setup_runs {
 }
 
 function after_setup_has_finished {
-    if ! grep -q 'install_final' "$COMPLETION_FILE"; then
+    if [ $install_state -ne $INSTALL_STATE_COMMAND_SUCCESS ]; then
         return
     fi
     if [ -f /root/.initial_setup ]; then
@@ -371,7 +401,7 @@ function after_setup_has_finished {
     remove_initial_setup_page
     set_webadmin_permissions
     remove_temporary_setup_files
-    restore_webadmin_files
+
     if [ -f $webadmin_temp_password_file ]; then
         rm $webadmin_temp_password_file
     fi
@@ -379,9 +409,11 @@ function after_setup_has_finished {
     if [ -f $installer_script ]; then
         rm $installer_script
     fi
-    if [ -f /root/.finished_install_command ]; then
-        systemctl reboot -i
-    fi
+
+    echo -n "$INSTALL_STATE_COMPLETED" > "$install_state_file"
+    install_state=$INSTALL_STATE_COMPLETED
+
+    systemctl reboot -i
 }
 
 function install_apps_from_webadmin {
@@ -453,11 +485,12 @@ function remove_apps_from_webadmin {
 }
 
 function update_progress_bar {
-    if [ ! -f /root/.running_install_command ]; then
+    # shellcheck disable=SC2086
+    if [ $install_state -ne $INSTALL_STATE_RUNNING_COMMAND ]; then
         return
     fi
     if [ ! -f /root/.install_counter ]; then
-        return
+        echo -n '1' > /root/.install_counter
     fi
     max_counter=50
     installing_page="$webadmin_install_dir/setup_installing.html"
@@ -466,18 +499,12 @@ function update_progress_bar {
     if [ $progress_percent -gt 100 ]; then
         progress_percent=100
     fi
-    sed -i "s|<div class=\"w3-container|<div class=\"w3-container w3-round w3-blue\" style=\"width:$progress_percent%\">$progress_percent%</div>|g" "$installing_page"
-    if grep -q 'w3-container w3-round w3-blue' "$webadmin_install_dir/index.html"; then
-        sed -i "s|<div class=\"w3-container|<div class=\"w3-container w3-round w3-blue\" style=\"width:$progress_percent%\">$progress_percent%</div>|g" "$webadmin_install_dir/index.html"
+    sed -i "s|<div class=\"w3-container.*|<div class=\"w3-container w3-round w3-blue\" style=\"width:$progress_percent%\">$progress_percent%</div>|g" "$installing_page"
+    if ! grep -q 'w3-container w3-round w3-blue' "$webadmin_install_dir/index.html"; then
+        cp "$webadmin_install_dir/setup_installing.html" "$webadmin_install_dir/index.html"
     fi
+    sed -i "s|<div class=\"w3-container.*|<div class=\"w3-container w3-round w3-blue\" style=\"width:$progress_percent%\">$progress_percent%</div>|g" "$webadmin_install_dir/index.html"
 }
-
-if [ -f /root/.finished_install_command ]; then
-    rm /root/.finished_install_command
-fi
-if [ -f /root/.running_install_command ]; then
-    rm /root/.running_install_command
-fi
 
 # If the freedombone command is already running then kill its process
 #shellcheck disable=SC2009
@@ -491,6 +518,14 @@ if [ "$install_process" ]; then
     fi
 fi
 
+# get the current install state
+if [ -f "$install_state_file" ]; then
+    install_state=$(cat "$install_state_file")
+else
+    echo -n "$INSTALL_STATE_FIRST_BOOT" > "$install_state_file"
+    install_state=$INSTALL_STATE_FIRST_BOOT
+fi
+
 while true
 do
     if [ -f /tmp/.upgrading ]; then
@@ -501,10 +536,11 @@ do
             if [ -f "$setup_file" ]; then
                 update_progress_bar
                 before_setup_runs
+                check_install_command_state
                 after_setup_has_finished
                 sleep 1
             else
-                if [ ! -f "$webadmin_install_dir/setup.prev" ]; then
+                if [ $install_state -eq $INSTALL_STATE_COMMAND_SUCCESS ]; then
                     install_apps_from_webadmin
                     sleep 1
                     remove_apps_from_webadmin
