Don't create directory

diff --git a/src/freedombone b/src/freedombone
--- a/src/freedombone
+++ b/src/freedombone
@@ -6377,14 +6377,14 @@ function upgrade_golang {
 		adduser --disabled-login --gecos 'Gogs' git
 	fi
 
-	if [ ! -d $GVM_ROOT ]; then
-		mkdir -p $GVM_ROOT
-	fi
-
 	# TODO: this script is all over the place
 	# and contains hardcoded github. See if you can do better
 	./binscripts/gvm-installer master /home/git
 
+	if [ ! -d $GVM_ROOT ]; then
+		echo $'Unable to install gvm'
+		exit 83537
+	fi
 
 	[[ -s "$GVM_ROOT/scripts/gvm" ]] && source "$GVM_ROOT/scripts/gvm"
 	if [ ! -f $GVM_ROOT/bin/gvm ]; then
